### PR TITLE
Simplify transition `func` retrieval for `finish` case

### PR DESCRIPTION
**Pull request by jakirkham**
The transition `func` that was being grabbed depended on whether `key` was found in the recommendations from the last transition. If `key` was found, one function based on `v` was called. If not, `finish` was used in place of `v`. To make this a bit more explicit, simple, and efficient, assign `finish` to `v` if `key` is not found. This way `v` can be used in all cases with one call to retrieve the `func`.

- [ ] Closes #xxxx
- [ ] Tests added / passed
- [x] Passes `black distributed` / `flake8 distributed` / `isort distributed`

### CODE REVIEW

**Comment by jakirkham** [comment]
`test_dashboard` is failing, but is also known to be flaky ( https://github.com/dask/distributed/issues/4697 ). So probably not related

**Comment by jakirkham** [comment]
Planning on merging tomorrow if no comments

**Review by jrbourbeau — APPROVED** [review]
Thanks @jakirkham!

**Comment by jakirkham** [comment]
Thanks James! 😄

**Pull request merged**
