### PR TITLE
Retry get_data_from_worker when worker is busy in gather_from_workers

### LINKED ISSUE #4698: Client/Scheduler gather not robust to busy worker
When I run a lot of tasks on the CNES HPC with a big Dask cluster (512 threads/128 workers), I sometimes have communication errors between the scheduler and the workers. The error is thrown by the module "distributed/utils_comm.py," because the code tries to read the key 'data' which does not exist in the dictionary.

```python
    /home/ad/briolf/anaconda3/lib/python3.8/site-packages/distributed/utils_comm.py in retry_operation
          383         dask.config.get("distributed.comm.retry.delay.max"), default="s"
          384     )
    ----> 385     return await retry(
          386         partial(coro, *args, **kwargs),
          387         count=retry_count,
    
    /home/ad/briolf/anaconda3/lib/python3.8/site-packages/distributed/utils_comm.py in retry
          368                 delay *= 1 + random.random() * jitter_fraction
          369             await asyncio.sleep(delay)
    ----> 370     return await coro()
          371 
          372 
    
    /home/ad/briolf/anaconda3/lib/python3.8/site-packages/distributed/core.py in send_recv_from_rpc
          860             name, comm.name = comm.name, "ConnectionPool." + key
          861             try:
    ----> 862                 result = await send_recv(comm=comm, op=key, **kwargs)
          863             finally:
          864                 self.pool.reuse(self.addr, comm)
    
    /home/ad/briolf/anaconda3/lib/python3.8/site-packages/distributed/core.py in send_recv
          659         if comm.deserialize:
          660             typ, exc, tb = clean_exception(**response)
    ----> 661             raise exc.with_traceback(tb)
          662         else:
          663             raise Exception(response["text"])
    
    /home/ad/briolf/anaconda3/lib/python3.8/site-packages/distributed/core.py in handle_comm
          499                             result = asyncio.ensure_future(result)
          500                             self._ongoing_coroutines.add(result)
    ----> 501                             result = await result
          502                     except (CommClosedError, CancelledError) as e:
          503                         if self.status == Status.running:
    
    /home/ad/briolf/anaconda3/lib/python3.8/site-packages/distributed/scheduler.py in gather
          5052                 who_has[key] = []
          5053 
    ----> 5054         data, missing_keys, missing_workers = await gather_from_workers(
          5055             who_has, rpc=self.rpc, close=False, serializers=serializers
          5056         )
    
    /home/ad/briolf/anaconda3/lib/python3.8/site-packages/distributed/utils_comm.py in gather_from_workers
          86                     missing_workers.add(worker)
          87                 else:
    ----> 88                     response.update(r["data"])
          89         finally:
          90             for r in rpcs.values():
    
    KeyError: 'data'
```
I modified the module code, to display the content of this dictionary when this error is thrown. I saw that in this context, the dictionary just contains the following data: ```dict(status='busy')```.

I cannot put reproducible code because the software used is not public and I did not discover simple lines of code to reproduce this problem. I can eventually do other tests to give you further information.

**Environment**:

- Dask version: 2021.4.0
- Python version: 3.8.8
- Operating System: CentOS Linux release 7.6.1810
- Install method (conda, pip, source): conda, channel conda-forge

### PR DESCRIPTION
**Pull request by aiudirog**
- [X] Closes #4698
- [X] Tests added / passed
- [X] Passes `pre-commit run --all-files`
    - Note: only checked the modified file

This is an alternative solution to #5546 which applies the standard retry logic when a worker returns `status: busy` inside `utils_comm.gather_from_workers()` instead of attempting to force a retry inside of `utils_comm.get_data_from_worker()`. It passes the tests that the other PR fails by not raising an error in the other usages of `get_data_from_worker()` where `status: busy` is already handled properly.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Review by fjetter — COMMENTED** [review]
Thanks for your PR @aiudirog 

I would prefer us not mixing the connection retry mechanism with busy handling. Busy is perfectly fine and can basically happen an unlimited amount of time. It is also not an error case so it doesn't feel right that it is coupled to the retry counter which is off by default, see https://github.com/dask/distributed/blob/4e2c1b36a9cfb7df092f47ca604511319cbeab52/distributed/distributed.yaml#L178-L182

Instead, I would suggest to modify the line with `response.update(r["data"])` to check for business instead of simply using the key `data`. All busy keys can be rescheduled after a short delay (maybe by recursion?)

would you be interested in looking into this?

**Comment by aiudirog** [comment]
That's fair, I'll look into it. Is there a stop case for a perpetually busy worker?

**Comment by fjetter** [comment]
> Is there a stop case for a perpetually busy worker?

Not directly but the `busy` response is only accounting for the number of incoming `get_data` requests. See https://github.com/dask/distributed/blob/9a66b719d53303b51034b339a97a9131105e5451/distributed/worker.py#L1718-L1731

This will eventually free up once the cluster reaches equilibrium.

In the other place we're handling this, we are using an exponential backoff to manage this, see https://github.com/dask/distributed/blob/9a66b719d53303b51034b339a97a9131105e5451/distributed/worker.py#L3085-L3092

**Comment by aiudirog** [comment]
Thanks for the info, I'll see about implementing that and also maybe abstracting it into it's own retry function.

**Comment by aiudirog** [comment]
Thanks for the info, I'll open a new PR when I have a better solution.

**Pull request closed without merging**
