### PR TITLE
Pass --bokeh-prefix keyword through to bokeh 

### PR DESCRIPTION
**Pull request by mrocklin**
cc @quasiben 

Also note that I'm renaming `--prefix` to `--bokeh-prefix`

### CODE REVIEW

**Comment by quasiben** [comment]
Noted

**Comment by quasiben** [comment]
I believe this is erroring simply because of linting

**Comment by mrocklin** [comment]
Apologies for the delay

**Comment by quasiben** [comment]
no problem!

**Comment by mrocklin** [comment]
@quasiben this is in.

**Pull request merged**
