### PR TITLE
Use `tmp_path` fixture instead of  outdated `tmpdir` fixture

### PR DESCRIPTION
**Pull request by ypogorelova**
Closes https://github.com/dask/distributed/issues/6799

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by fjetter** [comment]
https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html#the-tmpdir-and-tmpdir-factory-fixtures suggests to set `no:legacypath` in the config file which would raise if the older fixtures are used. This would protect us from accidentally reintroducing it again.
@ypogorelova can you try out if we can add this to our addopts, here https://github.com/dask/distributed/blob/8d239e91f6b61bd2b0048d373b20879ac88d2584/setup.cfg#L57-L66 ?

**Comment by ypogorelova** [comment]
Sure. Added

**Review by jrbourbeau — COMMENTED** [review]
Thanks @ypogorelova! Would you mind merging `main` into this branch when you get a chance? There are a bunch of CI failures (totally unrelated to the change in this PR) that have been fixed in `main`

**Comment by ypogorelova** [comment]
Sure, just merged it

**Review by jrbourbeau — APPROVED** [review]
Thanks @ypogorelova -- this is in 

Also, I noticed this is your first code contribution to this repository. Welcome!

**Pull request merged**
