### PR TITLE
Add base_url parameter to Bokeh handling

### PR DESCRIPTION
**Pull request by mrocklin**
This adds a `base_url` to all links within the Bokeh dashboard.  So that instead of serving at `/foo` we now serve at `/some_base_url/foo` .  Most links within our application seem to propagate fine, however we seem to have lost the actual Bokeh plots themselves.  The template renders but the plots don't.  

cc @bryevdv if you have thoughts on this I would welcome help here.

### CODE REVIEW

**Comment by mrocklin** [comment]
Ah, this seems to work well if I also pass along the `prefix=` keyword to Bokeh.  I guess I'm confused about the relationship between these parameters.

**Comment by mrocklin** [comment]
Perhaps I am mistaken and the prefix and base_url arguments should be merged.  I wonder what Jupyter does here.

**Comment by bryevdv** [comment]
`--base-url` is not part of Bokeh. It seems to be duplicated of `--prefix` which does this:
```
The Bokeh server can also add an optional prefix to all URL paths.
This can often be useful in conjunction with "reverse proxy" setups.

.. code-block:: sh

    bokeh serve app_script.py --prefix foobar

Then the application will be served under the following URL:

.. code-block:: none

    http://localhost:{DEFAULT_PORT}/foobar/app_script
```

**Comment by mrocklin** [comment]
OK, thanks for the comment @bryevdv .  Replaced with `prefix` everywhere.

**Pull request merged**
