### PR TITLE
Fix the resource key representation before sending graphs (#2716)

### PR DESCRIPTION
**Pull request by Spiegel0**
Convert resource key tuples to a string representation before they are submitted to the scheduler.

The commit is intended demonstrate a quick-fix of #2716. I'm not sure whether it breaks something else because I wasn't able to successfully run all test-cases, yet.

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks for the PR @Spiegel0 !  It would be good to include a test in this PR that would have failed before this fix.  There is some information here: http://distributed.dask.org/en/latest/develop.html#writing-tests

Perhaps something like the following, with the example that you shared in the original issue filled in.

```python
@gen_cluster(client=True)
def test_resources_str(c, s, a, b):
    a.set_resources({"MyRes": 1000})
    df = ...
    df.persist(resouces=...)
    yield wait(df)

    ts = s.tasks[tokey(df.__dask_keys__()[0])]
    assert ts.resources == 
```

**Comment by Spiegel0** [comment]
You are right, a test case would be very beneficial. Thank you for providing me the code snippet! I currently don't have access to my development environment but I'll try to implement the test case on Monday or Tuesday. (I guess its a good opportunity to get started with the Dask distributed internals.) I'll let you know as soon as I have the test case ready.

**Comment by jakirkham** [comment]
Would you have another chance to take a look, @mrocklin? Looks like there is now a test case. Travis CI is passing (with the exception of Python 2.7, which we may not care about here). AppVeyor is failing, but it is unclear (at least to me) if the failures are related.

**Comment by mrocklin** [comment]
Looks good.  Merging.  Thanks @Spiegel0 !

**Comment by Spiegel0** [comment]
Thank you very much for the assistance and for merging the PR @mrocklin, @jakirkham and @TomAugspurger!

**Pull request merged**
