### PR TITLE
Reduce memory footprint of culling P2P rechunking

### PR DESCRIPTION
**Pull request by hendrikmakait**
Previously, culling appeared to have an exponentially-growing memory footprint, this PR fixes that.

- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks @hendrikmakait, I can confirm this drastically reduces the memory required to kick off some of the large ERA5 rechunking jobs I've been running lately. (@dcherian you may also find this one interesting)

**Comment by dcherian** [comment]
you guys are killing it :)

**Comment by hendrikmakait** [comment]
Benchmarking on Coiled showed no impact on performance (https://github.com/coiled/benchmarks/actions/runs/10628454825). Note that we do not measure client-side memory.

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thanks!

**Pull request merged**
