### PR TITLE
Add tiny test for ToPickle

### PR DESCRIPTION
**Pull request by mrocklin**
- [ ] Closes #xxxx
- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by madsbk — COMMENTED** [review]
LGTM but I suggest that the test is moved to [`test_to_pickle.py`](https://github.com/dask/distributed/blob/main/distributed/protocol/tests/test_to_pickle.py).

**Comment by mrocklin** [comment]
Also, it looks like ToPickle fails with inproc comms.

**Comment by mrocklin** [comment]
Maybe we need this?

```diff
diff --git a/distributed/protocol/serialize.py b/distributed/protocol/serialize.py
index b4daf5bd..48091cc5 100644
--- a/distributed/protocol/serialize.py
+++ b/distributed/protocol/serialize.py
@@ -611,8 +611,12 @@ def nested_deserialize(x):
                     x[k] = replace_inner(v)
                 elif typ is Serialize:
                     x[k] = v.data
+                elif typ is ToPickle:
+                    x[k] = v.data
                 elif typ is Serialized:
                     x[k] = deserialize(v.header, v.frames)
+                elif typ is Pickled:
+                    x[k] = pickle.loads(v.header, buffers=v.frames)
 
         elif type(x) is list:
             x = list(x)
@@ -622,8 +626,12 @@ def nested_deserialize(x):
                     x[k] = replace_inner(v)
                 elif typ is Serialize:
                     x[k] = v.data
+                elif typ is ToPickle:
+                    x[k] = v.data
                 elif typ is Serialized:
                     x[k] = deserialize(v.header, v.frames)
+                elif typ is Pickled:
+                    x[k] = pickle.loads(v.header, buffers=v.frames)
 
         return x
 
```

**Comment by madsbk** [comment]
https://github.com/dask/distributed/pull/6044 should fix the `nproc` issue.

**Pull request merged**
