### PR TITLE
Send buffers in chunks <2GB

### PR DESCRIPTION
**Pull request by jakirkham**
Works around the OpenSSL 1.0.2 bug demonstrated in issue ( https://github.com/dask/distributed/issues/4538 ), except unlike PR ( https://github.com/dask/distributed/pull/5115 ) which did this for reading, this does the same thing for writing. The error may be less likely to show up in the write path (as frames may simply be smaller than this limit). Still it seems like a good idea to protect against `OverflowError`s from OpenSSL.

- [ ] Closes #xxxx
- [ ] Tests added / passed
- [ ] Passes `black distributed` / `flake8 distributed` / `isort distributed`

### CODE REVIEW

**Comment by mrocklin** [comment]
I suspect that this could be handled by the current max shard size functionality.  We recently did this for websockets in other to keep the frame size below 8MB.

**Comment by mrocklin** [comment]
Relevant PR: https://github.com/dask/distributed/pull/5070 (I was on my phone last message)

**Comment by jakirkham** [comment]
Would suggest merging so that both sides of the OpenSSL issue are fixed. Especially in the upcoming release ( https://github.com/dask/community/issues/173 ).

If someone wants to come along and improve on this work, that would be great, but cannot personally promise to do that (particularly not in the near future).

**Comment by mrocklin** [comment]
I'm thinking of the following: https://github.com/dask/distributed/pull/5141

**Comment by jakirkham** [comment]
Great, feel free to close this then :)

**Comment by jrbourbeau** [comment]
Closing in favor of https://github.com/dask/distributed/pull/5141

**Pull request closed without merging**
