### PR TITLE
fix/worker-bokeh-page

### PR DESCRIPTION
**Pull request by quasiben**
PR is a small fix to worker url path.  Path is now at `/status` instead of `/main`

### CODE REVIEW

**Comment by mrocklin** [comment]
Would it be possible to add a redirect to help existing users that use this page?

My guess is that this would be added to the normal Tornado routes in `distributed/bokeh/worker_html.py`

**Comment by mrocklin** [comment]
> Would it be possible to add a redirect to help existing users that use this page?

Poke @quasiben

**Comment by quasiben** [comment]
coming back to this now

**Comment by mrocklin** [comment]
Thanks @quasiben

**Comment by quasiben** [comment]
Thanks for those last commits!

**Pull request merged**
