### PR TITLE
[WIP] Move _download_module into Preload constructor

### PR DESCRIPTION
**Pull request by marcosmoyano**
Turn _download_module into a sync function

- [ ] Closes #xxxx
- [ ] Tests added / passed
- [ ] Passes `black distributed` / `flake8 distributed` / `isort distributed`

### CODE REVIEW

**Comment by mrocklin** [comment]
In principle this seems good to me.  I suspect that the test fails because the webserver is on the same event loop as the Nanny, which is doing a blocking call with urllib3, so the server isn't able to respond to the request.

To resolve this we may have to use a separate thread?

**Comment by marcosmoyano** [comment]
> To resolve this we may have to use a separate thread?

@mrocklin I couldn't make it work without leaking threads 😞 but it was pretty straight fwd to use a different process. Happy to keep looking if using multiprocessing is a no-no.

**Comment by mrocklin** [comment]
In principle this looks fine to me.  The test is unhappy on CI though :/

**Comment by mrocklin** [comment]
Well, I don't know why tests are failing on CI here.  As I'm sure you've observed as well everything seems to pass locally.  I just added a different implementation with `loop_in_thread` which is maybe lighter weight?  I'll see if CI likes it or not.

**Comment by mrocklin** [comment]
So while testing locally I found that it actually *did* fail, but very rarely.  Looking at the test I realized that the web server wasn't guaranteed to come up before the Scheduler/Nanny did, which explained the "max retries" error message.  I started running the test in a bash for loop

    for i in {1..100}; do py.test distributed/tests/test_preload.py::test_web_preload; done

And found that it failed around 10% of the time.  I added a threading.Event and that seemed to fix things locally.  Pushed up to see what CI thinks.

**Comment by marcosmoyano** [comment]
@mrocklin awesome! Thanks for taking the time to look into this. I was coming to the same conclusion and my next test was going to wait in the fixture until the webserver is up. 
We'll see what CI thinks 🤞

**Comment by mrocklin** [comment]
I took another look at this.  I created the test environment (in continuous_integration/environment-3.9.yaml) and indeed it fails locally.  I suspect a different version of pytest or pytest-asyncio.  I see two approaches here:

1.  Understand how my environment (where things work) differs from the CI environment and update the CI environment
2.  Go back to processes, as @marcosmoyano was doing before

**Comment by mrocklin** [comment]
I probably won't make presonal progress on this over the next couple of days.  @marcosmoyano this is back to you :)

**Comment by jrbourbeau** [comment]
Closing this in favor of https://github.com/dask/distributed/pull/5194. Feel free to re-open is needed @marcosmoyano

**Pull request closed without merging**
