### PR TITLE
add kwargs to progressbars

### PR DESCRIPTION
**Pull request by manugarri**
This PR allows the user to use the `progress` function passing progressbar specific arguments, such as `interval` for TextProgressBars.

Im not sure I have followed all the contributing guidelines. I read the contributing docs and run the tests, but got some tests failing from master.

### CODE REVIEW

**Comment by quasiben** [comment]
@manugarri thanks for the PR.   It looks like `interval` is already a valid argument for `TextProgressBars`

https://github.com/dask/distributed/blob/8af282651d701569acda55e742f2db741700de9a/distributed/diagnostics/progressbar.py#L111-L120

Are there other kwargs you wish to pass ?  If so, perhaps add a test to https://github.com/dask/distributed/blob/master/distributed/diagnostics/tests/test_progressbar.py ?

**Comment by manugarri** [comment]
@quasiben  I know, and this PR basically allows you to pass the argument interval to the general function `progress`. This way you can add the interval when you are running a cli script.

If not the only alternative to reduce the interval (which produces a long log file on Yarn EMR) is to do something like this (which works, but its not as concise).

```
from distributed.diagnostics.progressbar import TextProgressBar
from distributed.client import futures_of
output =output.persist()
TextProgressBar(futures_of(output), interval="10s")
output.compute()
```

Regarding the tests, I can add them but i am not sure it makes sense (since Im not altering the ProgressBar class at all, only allowing it to process kwargs).

**Comment by quasiben** [comment]
Ah, apologies.  I misunderstood.  

I think if you want to use `progress` with arbitrary kwargs you will need to change the assertion in the function definition.

https://github.com/dask/distributed/blob/2d431399ee32aef85f4ccd386623d599fa1ca50c/distributed/diagnostics/progressbar.py#L422-L428

@mrocklin do you recall why this assertion is made ?

**Comment by mrocklin** [comment]
> @mrocklin do you recall why this assertion is made ?

Unfortunately not

**Comment by manugarri** [comment]
@quasiben  yup that makes sense, it is easy to  assign the remaining bar specific args to a variable and pop them off the kwargs so the assertion wont fail (even though it would be good to know why that assert is there)

**Comment by mrocklin** [comment]
Checking in, what's the status here?

**Comment by quasiben** [comment]
@manugarri are you planning on removing the assertion and adding a test ?

**Comment by manugarri** [comment]
@quasiben  I am, my son was just born 2 days ago and we just left the hospital. Will do a PR as soon as I can :D

**Comment by quasiben** [comment]
@manugarri congratulations!!!  be with family --  this can wait

**Comment by manugarri** [comment]
@quasiben  I removed the assertion, let me know if its ok :)

**Comment by quasiben** [comment]
@manugarri apologies for dropping this.  There are still some linting issues -- if you run `black distributed` this should correct everything for you.  Also, I would recommend adding the following test to test_progressbar.py

```python
def test_progress_function_w_kwargs(client, capsys):
    f = client.submit(lambda: 1)
    g = client.submit(lambda: 2)

    progress(f, interval="20ms")
    check_bar_completed(capsys)
```

**Comment by mrocklin** [comment]
Merging this in.  Thanks @manugarri !

Also, I notice that this is your first code contribution to this repository.  Welcome!

**Comment by quasiben** [comment]
Yes, thank you @manugarri !

Thanks for merging @mrocklin

**Comment by manugarri** [comment]
thanks guys!, i apologize for not adding the test, im a bit behind these days :)

**Comment by manugarri** [comment]
thanks guys!, i apologize for not adding the test, im a bit behind these days :)

**Comment by jakirkham** [comment]
It seems we forgot to merge. Sorry about that. Have gone ahead and merged. Thanks all! 😄

**Pull request merged**
