### PR TITLE
Add total row to workers plot in dashboard

### PR DESCRIPTION
**Pull request by jsignell**
Closes https://github.com/dask/dask/issues/5275

image

Note that the `Total` is also included in the circle plots above the table. I added the worker name to the hover to make it clear which one is which:

Screenshot from 2020-02-10 13-40-10

But I would like some input on whether to take it out of those, or make it another color.

### CODE REVIEW

**Comment by mrocklin** [comment]
I feel like we should visually promote the total value a bit more.  Having it at the bottom of the list makes it seem unimportant, particularly if there are more workers than there are visible rows.  We could put it at the top, or if we wanted to, maybe even separate it into its own standalone table just above the current workers table?

**Comment by jsignell** [comment]
Yeah I'd almost like to bold it or something. Here it is at the top. See what you think of that:

image

**Comment by mrocklin** [comment]
At the top definitely seems nicer to me.

**Comment by jsignell** [comment]
And do you have an opinion about including the total in the circles plots at the top?

**Comment by mrocklin** [comment]
I'm personally less excited about that.  In my experience when people hover over or select those they're looking to highlight a pathological worker, and at that point don't care strongly about how many workers there are.

No strong feelings though.  I'm happy to defer to your judgment.

**Comment by jsignell** [comment]
Well, it'd be more work to exclude the totals from the circles then to just leave it in, so if people tend to use those plots via hover I'll just leave it in, since it shouldn't t upset them to have the total in there.

**Comment by mrocklin** [comment]
This looks good to me.  It looks like the only CI failure is linting.  You might want to install the git commit hooks with pre-commit.  https://docs.dask.org/en/latest/develop.html#code-formatting

**Comment by jsignell** [comment]
Oh I only did the pip install, not the second step. Sorry about that.

**Comment by mrocklin** [comment]
Looks good to me.  Thanks @jsignell !

**Pull request merged**
