### PR TITLE
Add failing test for h5py serialization

### PR DESCRIPTION
**Pull request by mrocklin**
See https://github.com/dask/distributed/issues/860

### CODE REVIEW

**Comment by mrocklin** [comment]
Oddly it looks like we're getting lists from BatchedSend in `handle_comm`.  I'm not sure why this would occur.

**Comment by mrocklin** [comment]
@martindurant this may now be resolved.  Was a tricky case to find.  Thank you for reporting the issue.

**Comment by martindurant** [comment]
Thank you. Seems pretty subtle.

**Comment by mrocklin** [comment]
L[-0] .  Not the first time that has bitten me.

**Pull request merged**
