### PR TITLE
Canavandl/collapse navbar

### PR DESCRIPTION
**Pull request by canavandl**
This PR:
* Adds necessary JS/CSS to have navbar collapse into clickable hamburger menu on small screen sizes (<650px)
* Adds a Bokeh theme to make the plot backgrounds transparent (there was some weirdness about the whites not quite matching)
* Moves the "active page" logic to highlight the current page on the navbar entirely to JS
* General CSS/JS/HTML involving moving some styles into standalone CSS files that are loaded as stylesheets

Here's proof that the cleanup didn't break anything
screen shot 2018-08-29 at 9 09 25 pm

Here's the collapsed navbar (note the cleanup didn't break anything at small screen sizes)
screen shot 2018-08-29 at 9 09 31 pm

Here's the open navbar
screen shot 2018-08-29 at 9 09 35 pm

### CODE REVIEW

**Comment by mrocklin** [comment]
This looks pretty good to me!

**Comment by mrocklin** [comment]
Thanks @canavandl !

**Comment by h4nyu** [comment]
When I use --bokeh-prefix option,  href in the navbar is unreachable.

https://github.com/dask/distributed/blob/cdbbc5d606ceb8b957696d5effc52d5091ccbaa4/distributed/bokeh/templates/base.html#L29

-> 
```html
 <a href="../{{ page }}">{{ page|title }}</a>
```
Will  this solve the problem?

**Comment by mrocklin** [comment]
Thanks for reporting this. I've changed this to a relative link here:
https://github.com/dask/distributed/pull/2242

**Pull request merged**
