### PR TITLE
Import joblib classes from public module

### PR DESCRIPTION
**Pull request by lesteve**
for ParallelBackendBase and AutoBatchingMixin.

Both classes have been exposed in joblib.parallel in joblib/joblib@1eb46ca which is in joblib 0.10.2.

### CODE REVIEW

**Comment by mrocklin** [comment]
In that same file a bit higher up we check the version number of joblib and eventually raise an error if the version number is too low.  We should probably bump that version to 0.10.2.

**Comment by mrocklin** [comment]
We should do the same for the `sklearn` version number.

**Comment by lesteve** [comment]
Good point I missed that !

**Comment by lesteve** [comment]
Done, the scikit-learn version is still correct, since joblib 0.10.2 will be bundled with scikit-learn 0.18.

**Comment by mrocklin** [comment]
Great.  Merging on passed tests

**Pull request merged**
