### PR TITLE
Robustly close LocalCluster in tests

### PR DESCRIPTION
**Pull request by mrocklin**
See #1620 

cc @pitrou @detrout

Maybe this helps?

### CODE REVIEW

**Comment by mrocklin** [comment]
Although in all cases we were already closing the cluster.

**Comment by detrout** [comment]
I tried the commit against 1.20.2 and it didn't work for me.

```
=============================== warnings summary ===============================
usr/lib/python3/dist-packages/distributed/tests/test_collections.py::test_rolling_sync
  /usr/lib/python3/dist-packages/dask/dataframe/rolling.py:152: UserWarning: DeprecationWarning: dd.rolling_mean is deprecated and will be removed in a future version, replace with df.rolling(...).mean(...)
    "df.rolling(...).{0}(...)").format(method_name))

-- Docs: http://doc.pytest.org/en/latest/warnings.html
============================== 4 tests deselected ==============================
 987 passed, 82 skipped, 4 deselected, 9 xfailed, 1 xpassed, 1 warnings in 357.13 seconds 
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/distributed/deploy/local.py", line 237, in close
    self.loop.add_callback(self._stop_worker, w)
  File "/usr/lib/python3/dist-packages/tornado/platform/asyncio.py", line 149, in add_callback
    functools.partial(stack_context.wrap(callback), *args, **kwargs))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 620, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
autopkgtest [20:16:41]: test command1: -----------------------]
autopkgtest [20:16:42]: test command1:  - - - - - - - - - - results - - - - - - - - - -
command1             FAIL stderr: Error in atexit._run_exitfuncs:
autopkgtest [20:16:42]: test command1:  - - - - - - - - - - stderr - - - - - - - - - -
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/distributed/deploy/local.py", line 237, in close
    self.loop.add_callback(self._stop_worker, w)
  File "/usr/lib/python3/dist-packages/tornado/platform/asyncio.py", line 149, in add_callback
    functools.partial(stack_context.wrap(callback), *args, **kwargs))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 620, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by mrocklin** [comment]
Ah, now I see that there are asyncio bits in that traceback. That led me to the right tests.  I think that this is now resolved.

**Comment by mrocklin** [comment]
Merging this.  Please let me know if this does not resolve the problem @detrout

**Comment by detrout** [comment]
Ok apparently on my first test I forgot to rebuild the source package with second patch.

But with both commits applied 1.20.2's test run correctly. Final summary:
```
=============================== warnings summary ===============================
usr/lib/python3/dist-packages/distributed/tests/test_collections.py::test_rolling_sync
  /usr/lib/python3/dist-packages/dask/dataframe/rolling.py:152: UserWarning: DeprecationWarning: dd.rolling_mean is deprecated and will be removed in a future version, replace with df.rolling(...).mean(...)
    "df.rolling(...).{0}(...)").format(method_name))

-- Docs: http://doc.pytest.org/en/latest/warnings.html
============================== 4 tests deselected ==============================
 987 passed, 82 skipped, 4 deselected, 8 xfailed, 2 xpassed, 1 warnings in 344.22 seconds 
```

I did have to make some minor changes to the changes to test_asyncio_variable, as git master refers to s.tasks and 1.20.2 s.task_state

**Comment by detrout** [comment]
Thank you for your help.

**Comment by mrocklin** [comment]
Thank you for reporting this and for working with us to resolve it.

**Pull request merged**
