### PR TITLE
Mark `test_worker_reconnects_mid_compute*` tests as flaky

### PR DESCRIPTION
**Pull request by jrbourbeau**
xref https://github.com/dask/distributed/issues/5377

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]
Thanks James! 😄

**Comment by jakirkham** [comment]
Seeing `test_stress_creation_and_deletion` fail on CI [here]( https://github.com/dask/distributed/pull/5378/checks?check_run_id=3762507464 ) and [here]( https://github.com/dask/distributed/pull/5378/checks?check_run_id=3762507418 ), which is already noted as a flaky test in issue ( https://github.com/dask/distributed/issues/5172 ).

Also seeing `test_client_timeout ` fail on CI [here]( https://github.com/dask/distributed/pull/5378/checks?check_run_id=3762507634 ). Not seeing any open issues about it.

**Comment by crusaderky** [comment]
The same should also be applied to test_worker_reconnects_mid_compute

**Comment by crusaderky** [comment]
According to my latest stress test, test_client_timeout fails exclusively on MacOS.

**Comment by jrbourbeau** [comment]
Just pushed a commit to mark `test_worker_reconnects_mid_compute` as flaky too.

@jakirkham for reference, @crusaderky is running a bunch of stress tests on the `distributed` test suite to see what tests fail, how often, etc. Let's leave `test_client_timeout` for after we have the results of those stress tests. Right now I'm mostly concerned about `test_worker_reconnects_mid_compute*` and `test_stress_creation_and_deletion` as they are failing at a high rate.

**Review by crusaderky — APPROVED** [review]

**Comment by jakirkham** [comment]
Sure am mostly just trying to get a sense of what flaky test failures we are dealing with since there appear to be several

**Review by jakirkham — APPROVED** [review]

**Pull request merged**
