### PR TITLE
Change default multiprocessing behavior to spawn

### LINKED ISSUE #3374: Can't start worker on MacOS
On current master `distributed-2.9.1+13.g7d2ed43c` (and `tornado==6.0.3`), I get the following error on MacOS but not in Docker:
```
# already running dask scheduler
(.venv) ➜  model git:(nyc) ✗ PYTHONPATH=. dask-worker 'localhost:8786' --nthreads 1 --memory-limit 6GB --local-directory /tmp/ --nprocs 1
distributed.nanny - INFO -         Start Nanny at: 'tcp://127.0.0.1:55985'
objc[39479]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called.
objc[39479]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
distributed.nanny - INFO - Worker process 39479 was killed by signal 6
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x118220490>>, <Task finished coro=<Nanny._on_exit() done, defined at /Users/brett/model/.venv/lib/python3.7/site-packages/distributed/nanny.py:396> exception=TypeError('addresses should be strings or tuples, got None')>)
Traceback (most recent call last):
  File "/Users/brett/model/.venv/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/Users/brett/model/.venv/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/Users/brett/model/.venv/lib/python3.7/site-packages/distributed/nanny.py", line 399, in _on_exit
    await self.scheduler.unregister(address=self.worker_address)
  File "/Users/brett/model/.venv/lib/python3.7/site-packages/distributed/core.py", line 757, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/Users/brett/model/.venv/lib/python3.7/site-packages/distributed/core.py", line 556, in send_recv
    raise exc.with_traceback(tb)
  File "/Users/brett/model/.venv/lib/python3.7/site-packages/distributed/core.py", line 408, in handle_comm
    result = handler(comm, **msg)
  File "/Users/brett/model/.venv/lib/python3.7/site-packages/distributed/scheduler.py", line 2122, in remove_worker
    address = self.coerce_address(address)
  File "/Users/brett/model/.venv/lib/python3.7/site-packages/distributed/scheduler.py", line 4831, in coerce_address
    raise TypeError("addresses should be strings or tuples, got %r" % (addr,))
TypeError: addresses should be strings or tuples, got None
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:55985'
distributed.dask_worker - INFO - End worker
```
No issues in the latest release (2.9.1). Possibly related to #3356 but I didn't see any similar error messages so I figured I'd keep it separate for now.

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes #3374

### CODE REVIEW

**Comment by mrocklin** [comment]
I genuinely don't understand why the asyncio.sleep avoids the broken pipe error messages, but it does.

**Comment by jakirkham** [comment]
Thanks Matt! This seems like a good change to me. 😄

Should we make [an analogous change to Dask]( https://github.com/dask/dask/blob/4ddcc9374533e7765f341f86edfedf5c8d82df8c/dask/multiprocessing.py#L152-L153 )?

**Comment by mrocklin** [comment]
> Should we make an analogous change to Dask?

I'm just doing this in response to user issues.  I don't currently have any thoughts on what to do with dask proper. My understanding is that it isn't currently a problem, so I plan to ignore it for now.

**Comment by mrocklin** [comment]
Saw this test failure

```python-traceback
___________________________ test_tcp_connect_timeout ___________________________
    @pytest.mark.asyncio
    async def test_tcp_connect_timeout():
>       await check_connect_timeout("tcp://127.0.0.1:44444")
distributed/comm/tests/test_comms.py:841: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
addr = 'tcp://127.0.0.1:44444'
    async def check_connect_timeout(addr):
        t1 = time()
        with pytest.raises(IOError):
>           await connect(addr, timeout=0.15)
E           Failed: DID NOT RAISE <class 'OSError'>
distributed/comm/tests/test_comms.py:834: Failed
```

**Comment by mrocklin** [comment]
OK, I'm going to go ahead and merge this for now.  I suspect that we'll get a couple of new intermittent test failures for a bit due to the increased testing time, but it seems nicer than the alternative.  cc @bnaul

**Pull request merged**
