### PR TITLE
TST: clean up flaky test

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/dask/distributed/issues/3232

Not sure why yet, just some cleanup for now. Will rerun this a bunch to see if it appears on Travis.

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks for working on this @TomAugspurger .  Fixing intermittent tests is rarely satisfying.

**Comment by TomAugspurger** [comment]
2 successes so far.

**Comment by TomAugspurger** [comment]
Hmm, a failure in `test_profile_server` on 3.7.

```pytb
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

c = <Client: not connected>

s = <Scheduler: "tcp://127.0.0.1:34054" processes: 0 cores: 0>

a = <Worker: tcp://127.0.0.1:43311, closed, stored: 0, running: 0/1, ready: 0, comm: 0, waiting: 0>

b = <Worker: tcp://127.0.0.1:41623, closed, stored: 0, running: 0/2, ready: 0, comm: 0, waiting: 0>

    @gen_cluster(client=True, worker_kwargs={"profile_cycle_interval": "10ms"})

    async def test_profile_server(c, s, a, b):

        x = c.map(slowinc, range(10), delay=0.01, workers=a.address)

        await wait(x)

    

        await asyncio.gather(

            c.run(slowinc, 1, delay=0.5), c.run_on_scheduler(slowdec, 1, delay=0.5)

        )

    

        p = await c.profile(server=True)  #  All worker servers

        assert "slowinc" in str(p)

    

        p = await c.profile(scheduler=True)  #  Scheduler

>       assert "slowdec" in str(p)

E       assert 'slowdec' in "{'description': {'filename': '', 'name': '', 'line_number': 0, 'line': ''}, 'children': {'<module>;/home/travis/minic...entifier': '<module>;/home/travis/miniconda/envs/test-environment/bin/py.test;4'}}, 'count': 89, 'identifier': 'root'}"

E        +  where "{'description': {'filename': '', 'name': '', 'line_number': 0, 'line': ''}, 'children': {'<module>;/home/travis/minic...entifier': '<module>;/home/travis/miniconda/envs/test-environment/bin/py.test;4'}}, 'count': 89, 'identifier': 'root'}" = str({'children': {'<module>;/home/travis/miniconda/envs/test-environment/bin/py.test;4': {'children': {'main;/home/travis/...est;4'}}, 'count': 89, 'description': {'filename': '', 'line': '', 'line_number': 0, 'name': ''}, 'identifier': 'root'})

distributed/tests/test_client.py:5704: AssertionError
```


and `test_nprocs_requires_nanny` on 3.6

```pytb
__________________________ test_nprocs_requires_nanny __________________________

loop = <tornado.platform.asyncio.AsyncIOLoop object at 0x7feaeceec7f0>

    def test_nprocs_requires_nanny(loop):

        with popen(["dask-scheduler", "--no-dashboard"]) as sched:

            with popen(

                ["dask-worker", "127.0.0.1:8786", "--nprocs=2", "--no-nanny"]

            ) as worker:

>               assert any(

                    b"Failed to launch worker" in worker.stderr.readline()

                    for i in range(15)

                )

distributed/cli/tests/test_dask_worker.py:175: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

../../../miniconda/envs/test-environment/lib/python3.6/contextlib.py:88: in __exit__

    next(self.gen)

distributed/utils_test.py:1024: in popen

    terminate_process(proc)

distributed/utils_test.py:988: in terminate_process

    proc.wait(10)

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <subprocess.Popen object at 0x7feaeceecc18>, timeout = 10

endtime = 208.237043138

    def wait(self, timeout=None, endtime=None):

        """Wait for child process to terminate.  Returns returncode

        attribute."""

        if self.returncode is not None:

            return self.returncode[0m

    

        if endtime is not None:

            warnings.warn(

                "'endtime' argument is deprecated; use 'timeout'.",

                DeprecationWarning,

                stacklevel=2)

        if endtime is not None or timeout is not None:

            if endtime is None:

                endtime = _time() + timeout

            elif timeout is None:

                timeout = self._remaining_time(endtime)

    

        if endtime is not None:

            # Enter a busy loop if we have a timeout.  This busy loop was

            # cribbed from Lib/threading.py in Thread.wait() at r71065.

            delay = 0.0005 # 500 us -> initial delay of 1 ms

            while True:

                if self._waitpid_lock.acquire(False):

                    try:

                        if self.returncode is not None:

                            break  # Another thread waited.

                        (pid, sts) = self._try_wait(os.WNOHANG)

                        assert pid == self.pid or pid == 0

                        if pid == self.pid:

                            self._handle_exitstatus(sts)

                            break

                    finally:

                        self._waitpid_lock.release()

                remaining = self._remaining_time(endtime)

                if remaining <= 0:

>                   raise TimeoutExpired(self.args, timeout)

E                   subprocess.TimeoutExpired: Command '['/home/travis/miniconda/envs/test-environment/bin/dask-scheduler', '--no-dashboard']' timed out after 10 seconds
```

**Comment by TomAugspurger** [comment]
Well there's a failure on run 7 :/

**Comment by mrocklin** [comment]
@TomAugspurger is there anything I can do to help here?

**Comment by TomAugspurger** [comment]
Nothing comes to mind, unless you have an educated guess about where things are going wrong. I think things look OK in the implementation, but there may be cases I'm not considering (I don't think the one worker should be stealing these tasks, since I'm using `workers=` to restrict the tasks).

I just pushed a change to wait for all the futures in the final result, rather than just the first. I'm not if it'll make a difference.

**Comment by TomAugspurger** [comment]
https://travis-ci.org/dask/distributed/jobs/621645958?utm_medium=notification&utm_source=github_status failed on `test_nanny_throttle`.

**Comment by mrocklin** [comment]
What should we do on this?

**Comment by mrocklin** [comment]
Or rather, if it's ok with you @TomAugspurger I'd like to leave this issue with you.  If you think that this should be merged in, then please merge.  If you think that there is still work to do then please keep it open.

I think I've cleaned up most of the other intermittent failures (though not all) but this probably accounts for 70% or so of them.

**Comment by mrocklin** [comment]
I would also be happy with just removing the functionality or changing around the test somewhat.

**Comment by TomAugspurger** [comment]
I've rewritten the test to be a bit more direct, though less "realistic", since it's using `get_data` directly. It's passed for me locally 100 times, but the old way never failed for me either so it's hard to say.

**Comment by TomAugspurger** [comment]
This new test seems more reliable. It's succeeded through 7 attempts so far. I'd recommend merging this, and if we have more failures we can remove the test or the feature.

**Comment by mrocklin** [comment]
Thank you for prioritizing this @TomAugspurger .  Merged.

**Pull request merged**
