### PR TITLE
let nannied processes inherit stdin

### LINKED ISSUE #1505: Possibility to use IPythom.embed() on workers
Follow-up on our discussion with @mrocklin: It would be nice to use `IPython.embed()` directly in a worker for debugging purposes (in a cluster running locally). Example usage:

```python
from distributed import Client

def logic_to_run_on_worker():
    # ... imagine complex logic here ...
    # local embed for debugging
    import IPython
    IPython.embed()

client = Client("tcp://10.128.4.209:8786")
client.run(logic_to_run_on_worker)
```

This currently fails with

```
Traceback (most recent call last):
  File "dask_test.py", line 9, in <module>
    client.run(logic_to_run_on_worker)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/distributed/client.py", line 1819, in run
    return self.sync(self._run, function, *args, **kwargs)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/distributed/client.py", line 559, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/distributed/utils.py", line 248, in sync
    six.reraise(*error[0])
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/distributed/utils.py", line 236, in f
    result[0] = yield make_coro()
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/distributed/client.py", line 1773, in _run
    six.reraise(*clean_exception(**resp))
  File "dask_test.py", line 6, in logic_to_run_on_worker
    IPython.embed()
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/IPython/terminal/embed.py", line 383, in embed
    frame.f_code.co_filename, frame.f_lineno), **kwargs)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/IPython/terminal/embed.py", line 158, in __init__
    super(InteractiveShellEmbed,self).__init__(**kw)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 439, in __init__
    self.init_prompt_toolkit_cli()
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 274, in init_prompt_toolkit_cli
    output=create_output(true_color=self.true_color))
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 81, in __init__
    self.input = input or StdinInput(sys.stdin)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/prompt_toolkit/input.py", line 67, in __init__
    assert self.stdin.isatty()
AssertionError
```

Maybe only a minor change is necessary to make this work and it could be optionally enabled via the Dask config.

### PR DESCRIPTION
**Pull request by minrk**
enables things like `IPython.embed()` in workers to access the terminal.

Adds `inherit_stdin` arg to AsyncProcess. Default is False to preserve default behavior, but nannies specify inherit_stdin=True.

If no fileno for sys.stdin can be found (e.g. sys.stdin is None, which can happen, or sys.stdin has already been redirected and is not the original FD), inheriting stdin is disabled.

closes #1505

### CODE REVIEW

**Comment by minrk** [comment]
I'm not sure if this works on Windows. If it doesn't, it ought to fallback on the previous behavior where stdin is lost, rather than throwing an error.

**Comment by mrocklin** [comment]
cc @bluenote10

**Comment by mrocklin** [comment]
Also cc @pitrou for review

**Comment by pitrou** [comment]
I'm unsure this actually works:
* on Python 2, this shouldn't be needed if I understand #1505 correctly
* on Python 3, the worker's stdin could very well have had a different fd number than the nanny's stdin, since the intermediate forkserver process is spawned

I think the proper solution would to not pass an fd but instead restore `sys.stdin` from the original `sys.__stdin__`, see https://docs.python.org/3/library/sys.html#sys.__stdin__

**Comment by mrocklin** [comment]
This PR has gone stale.  Closing for now.

**Pull request closed without merging**
