### PR TITLE
Fix #1158: stress socket backlog

### LINKED ISSUE #1158: Add a configuration entry for TCP socket backlog
This may help write tests which would stress saturating the connection accept queue.

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
Unfortunately the test fails quite consistently.

**Comment by mrocklin** [comment]
Any thoughts here on how/if we should make Dask robust to tasks like this?

**Comment by pitrou** [comment]
One easy thing would be to make the connect-timeout configurable, which would help our users with large clusters. Generally there is a tension between retrying a certain number of times and returning early when an error is detected. Making it configurable will let users choose whichever is best of them.

**Comment by pitrou** [comment]
As for the situation in the test, it's quite unusual so I'm not sure whether we should do something against it (what?).

**Comment by mrocklin** [comment]
This PR has gone stale.  Closing for now.

**Pull request closed without merging**
