### PR TITLE
Improve check_active_rpc() to avoid calling gc.collect()

### PR DESCRIPTION
**Pull request by pitrou**
This seems to make the test suite a bit faster (issue #1519)

### CODE REVIEW

**Comment by mrocklin** [comment]
That's a nice speedup :)

**Comment by mrocklin** [comment]
+1 from me

**Comment by pitrou** [comment]
There have been weird sporadic failures on test_AllProgress. Have you already encountered them?

**Comment by mrocklin** [comment]
> There have been weird sporadic failures on test_AllProgress. Have you already encountered them?

This doesn't sound familiar to me.  Is there anything interesting from the traceback?

**Comment by pitrou** [comment]
IIRC it was a `CancelledError` in line 184 of `test_progress.py`. Unfortunately I committed the mistake of restarting the Travis job :-/

**Comment by pitrou** [comment]
More generally it seems this PR makes 2.7 more flaky:
https://travis-ci.org/dask/distributed/jobs/302558952

Perhaps because with os.fork() it's better to make sure everything is cleaned up before running a new cluster.

**Pull request merged**
