### PR TITLE
Add UCX support for RDMACM

### PR DESCRIPTION
**Pull request by pentschev**
This PR adds a new UCX configuration that allows enabling RDMACM for use with InfiniBand.

### CODE REVIEW

**Comment by pentschev** [comment]
cc @quasiben

**Comment by quasiben** [comment]
This looks really great @pentschev and thanks for doing this.  For others, `RDMACM` is command used for InfiniBand devices.  While `SOCKCM` (sockets) will work, we have seen performance improvements when using `RDMACM` exclusively.

**Comment by quasiben** [comment]
Thanks again @pentschev   Also happy to see the recently merged schema test working!  Happy to merge in tomorrow in the later morning or afternoon -- want to give others a chance to comment.

**Comment by quasiben** [comment]
Thanks again Peter!

**Pull request merged**
