### PR TITLE
Update dashboard logo

### PR DESCRIPTION
**Pull request by jacobtomlinson**
We have a new logo 🎉 Replacing the old one on the dashboard.

image

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Nice! Thanks @jacobtomlinson 

Does this also update the favicon used? I seem to recall us having separate logic for that

**Comment by jacobtomlinson** [comment]
Good catch thanks! One sec.

**Comment by jrbourbeau** [comment]
Thanks for getting the favicon too @jacobtomlinson. I'm curious if we have a non-white background version we could use?

Screen Shot 2022-06-06 at 11 33 48 AM

Though to be clear, this is a nice improvement already as it's using the new logo

**Comment by jacobtomlinson** [comment]
Oh interesting, the conversion tool I used must've added it. Sorry for the premature merge. Let me try converting it with something else.

**Pull request merged**
