### PR TITLE
Update for black

### PR DESCRIPTION
**Pull request by TomAugspurger**
CI is failing on the linting step. Apparently a change to black's formatting.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
https://github.com/dask/dask/pull/6568 is passing.

**Comment by TomAugspurger** [comment]
Oh whoops that was for Dask :) I'll try to get this passing.

**Comment by TomAugspurger** [comment]
I believe that the CI failure is unrelated though I haven't looked closely.

**Comment by jrbourbeau** [comment]
I suspect it's unrelated too. I've restarted CI and will merge if it passes

**Pull request merged**
