### PR TITLE
Ensure distributed can be imported in thread

### LINKED ISSUE #4521: IOLoop instantiated on import of distributed breaks tornado forking
I've noticed that importing distributed seems to create an `IOLoop` which can break further code that tries to fork multiple processes, assuming the main process does not have an `IOLoop`. The workaround is to move around the imports, but that can get messy, and I don't think an import should be instantiating this to begin with.

**Sample code run on Linux:**
```python
from tornado.ioloop import IOLoop
from tornado.netutil import bind_sockets
from tornado.process import fork_processes
from tornado.tcpserver import TCPServer

print(f"IOLoop before import: {IOLoop.current(instance=False)}")
import distributed
print(f"IOLoop after import: {IOLoop.current(instance=False)}")

sockets = bind_sockets(8888)
fork_processes(2, max_restarts=1)
server = TCPServer()
server.add_sockets(sockets)
IOLoop.current().start()
```

**Error message:**
```
IOLoop before import: None
IOLoop after import: <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fffef352490>
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/distributed_test/lib/python3.8/asyncio/selector_events.py", line 259, in _add_reader
    key = self._selector.get_key(fd)
  File "/home/user/miniconda3/envs/distributed_test/lib/python3.8/selectors.py", line 192, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '11 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "distributed_test.py", line 13, in <module>
    server.add_sockets(sockets)
  File "/home/user/miniconda3/envs/distributed_test/lib/python3.8/site-packages/tornado/tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "/home/user/miniconda3/envs/distributed_test/lib/python3.8/site-packages/tornado/netutil.py", line 282, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "/home/user/miniconda3/envs/distributed_test/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 150, in add_handler
    self.selector_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "/home/user/miniconda3/envs/distributed_test/lib/python3.8/asyncio/selector_events.py", line 332, in add_reader
    return self._add_reader(fd, callback, *args)
  File "/home/user/miniconda3/envs/distributed_test/lib/python3.8/asyncio/selector_events.py", line 261, in _add_reader
    self._selector.register(fd, selectors.EVENT_READ,
  File "/home/user/miniconda3/envs/distributed_test/lib/python3.8/selectors.py", line 359, in register
    self._selector.register(key.fd, poller_events)
FileExistsError: [Errno 17] File exists
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/distributed_test/lib/python3.8/asyncio/selector_events.py", line 259, in _add_reader
    key = self._selector.get_key(fd)
  File "/home/user/miniconda3/envs/distributed_test/lib/python3.8/selectors.py", line 192, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '11 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "distributed_test.py", line 13, in <module>
    server.add_sockets(sockets)
  File "/home/user/miniconda3/envs/distributed_test/lib/python3.8/site-packages/tornado/tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "/home/user/miniconda3/envs/distributed_test/lib/python3.8/site-packages/tornado/netutil.py", line 282, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "/home/user/miniconda3/envs/distributed_test/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 150, in add_handler
    self.selector_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "/home/user/miniconda3/envs/distributed_test/lib/python3.8/asyncio/selector_events.py", line 332, in add_reader
    return self._add_reader(fd, callback, *args)
  File "/home/user/miniconda3/envs/distributed_test/lib/python3.8/asyncio/selector_events.py", line 261, in _add_reader
    self._selector.register(fd, selectors.EVENT_READ,
  File "/home/user/miniconda3/envs/distributed_test/lib/python3.8/selectors.py", line 359, in register
    self._selector.register(key.fd, poller_events)
FileExistsError: [Errno 17] File exists
Traceback (most recent call last):
  File "distributed_test.py", line 11, in <module>
    fork_processes(2, max_restarts=1)
  File "/home/user/miniconda3/envs/distributed_test/lib/python3.8/site-packages/tornado/process.py", line 167, in fork_processes
    raise RuntimeError("Too many child restarts, giving up")
RuntimeError: Too many child restarts, giving up
```

Debugging through the import, I came across the below where the `ExecutorResolver` attached to the `BaseTCPConnector` class implicitly creates an `IOLoop` on initialization.
https://github.com/dask/distributed/blob/cbb88bd43288a7e25a03e11f17e1c9a2f5e6f31d/distributed/comm/tcp.py#L351-L353

**Tornado code:**
https://github.com/tornadoweb/tornado/blob/b4e39e52cd27d6b3b324a399dff046f71545c4a5/tornado/netutil.py#L422

### LINKED ISSUE #5587: distributed cannot be first imported by a non-main thread
```python
from threading import Thread
import traceback
def import_dask_distributed():
    try:
        import dask.distributed
    except Exception as e:
        traceback.print_exc()
x = Thread(target=import_dask_distributed)
x.start()
```

**What happened**:
Running the above code results in the following output:
```
Traceback (most recent call last):
  File "/tmp/ipykernel_76351/1031499154.py", line 5, in import_dask_distributed
    import dask.distributed
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/site-packages/dask/distributed.py", line 11, in <module>
    from distributed import *
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/site-packages/distributed/__init__.py", line 7, in <module>
    from .actor import Actor, ActorFuture
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/site-packages/distributed/actor.py", line 5, in <module>
    from .client import Future
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/site-packages/distributed/client.py", line 59, in <module>
    from .batched import BatchedSend
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/site-packages/distributed/batched.py", line 10, in <module>
    from .core import CommClosedError
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/site-packages/distributed/core.py", line 28, in <module>
    from .comm import (
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/site-packages/distributed/comm/__init__.py", line 25, in <module>
    _register_transports()
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/site-packages/distributed/comm/__init__.py", line 17, in _register_transports
    from . import inproc, tcp, ws
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/site-packages/distributed/comm/tcp.py", line 387, in <module>
    class BaseTCPConnector(Connector, RequireEncryptionMixin):
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/site-packages/distributed/comm/tcp.py", line 389, in BaseTCPConnector
    _resolver = netutil.ExecutorResolver(close_executor=False, executor=_executor)
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/site-packages/tornado/util.py", line 288, in __new__
    instance.initialize(*args, **init_kwargs)
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/site-packages/tornado/netutil.py", line 427, in initialize
    self.io_loop = IOLoop.current()
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/site-packages/tornado/ioloop.py", line 263, in current
    loop = asyncio.get_event_loop()
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-10'.
```

**What you expected to happen**:

It not to crash 😄 

**Anything else we need to know?**:

I think it is related to the recent change in:
https://github.com/dask/distributed/pull/5531

**Environment**:

- Dask version: `'2021.12.0'`
- Python version: `'3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) \n[GCC 9.4.0]'`
- Operating System: Ubuntu 21.10
- Install method (conda, pip, source): conda (conda-forge)

### PR DESCRIPTION
**Pull request by jcrist**
Fixes a bug introduced where `distributed` could not be first imported
in a background thread, since `tornado` would attempt to create an
`IOLoop` on import, and no event loop exists in a background thread by
default. We now delay creating a tornado `TCPClient` until use.

Fixes #5587.
Fixes https://github.com/dask/dask/issues/8466.
Fixes #4521
Supersedes #4672

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks for fixing @jcrist! 

When I run `distributed/comm/tests/test_comms.py::test_comm_failure_threading` locally I my Mac, it fails consistently with 

```python
____________________________________________________________ test_comm_failure_threading[tornado] ____________________________________________________________

tcp = <module 'distributed.comm.tcp' from '/Users/james/projects/dask/distributed/distributed/comm/tcp.py'>

    @pytest.mark.asyncio
    async def test_comm_failure_threading(tcp):
        """
        When we fail to connect, make sure we don't make a lot
        of threads.

        We only assert for PY3, because the thread limit only is
        set for python 3.  See github PR #2403 discussion for info.
        """
        if tcp is asyncio_tcp:
            pytest.skip("not applicable for asyncio")

        async def sleep_for_60ms():
            max_thread_count = 0
            for x in range(60):
                await asyncio.sleep(0.001)
                thread_count = threading.active_count()
                if thread_count > max_thread_count:
                    max_thread_count = thread_count
            return max_thread_count

        original_thread_count = threading.active_count()

        # tcp.TCPConnector()
        sleep_future = sleep_for_60ms()
        with pytest.raises(IOError):
            await connect("tcp://localhost:28400", 0.052)
        max_thread_count = await sleep_future
        # 2 is the number set by BaseTCPConnector.executor (ThreadPoolExecutor)
        assert max_thread_count <= 2 + original_thread_count

        # tcp.TLSConnector()
        sleep_future = sleep_for_60ms()
        with pytest.raises(IOError):
            await connect(
                "tls://localhost:28400", 0.052, ssl_context=get_client_ssl_context()
            )
        max_thread_count = await sleep_future
>       assert max_thread_count <= 2 + original_thread_count
E       assert 7 <= (2 + 3)

distributed/comm/tests/test_comms.py:366: AssertionError
```

Though interestingly this doesn't happen on the linux CI builds here. 

Also, for reference this seems similar to https://github.com/dask/distributed/pull/4672

**Comment by jcrist** [comment]
Weird, that doesn't fail on my linux laptop, but I see the issue here. Fixed. And yeah, this should supersede #4672.

**Review by jrbourbeau — COMMENTED** [review]
Thanks @jcrist!

Other than delaying `TCPClient` creation until use (which we want) the only main difference I see with our current behavior is we now create a `TCPClient` (and maybe a resolver?) for each class which inherits from `BaseTCPConnector`. This means that `TCPConnector` and `TLSConnector` will now have separate clients instead of sharing one like they do now. Do you see any issue with that? FWIW I know there used to be some issues around creating many tcp clients, but I believe these were resolved in https://github.com/dask/distributed/pull/2403 where `test_comm_failure_threading` was added and this test still passes with the changes here

Also @martindurant brought up a concern about multiple threads trying to get the cached client at the same time over in https://github.com/dask/distributed/pull/4672 (xref https://github.com/dask/distributed/pull/4672#pullrequestreview-627416576) which, I think, also applies to this PR

**Comment by martindurant** [comment]
This PR does indeed make one client (per class) rather than one per instance, so that's good. However, it could easily be a race point - I don't know if accidentally creating a couple would be any sort of problem.

**Comment by jcrist** [comment]
No, there should be no issue - the `TCPClient` and `Resolver` are lightweight enough that creating multiple of them should have no real performance impact (it's the thread pool that matters). And there's no persistent state, so even in the presence of a race condition having a temporary client that eventually gets collected is fine. We could even create a new client & resolver on every connection, but it feels nicer (IMO) to only create one once.

**Comment by martindurant** [comment]
^ I am satisfied by that

**Pull request merged**
