### PR TITLE
Replace loop.call_later and loop.add_callback with background tasks added to Server. 

### LINKED ISSUE #6359: Replace `loop.call_later` and `loop.add_callback` with background tasks
At the moment, we use `loop.call_later` and `loop.call_later` in several places to fire-and-forget schedule background tasks. Since we do not keep track of them, they are never cleaned up until they are done.  See the snippet for an example:
https://github.com/dask/distributed/blob/50d29110a430fe8457f73163082716844e1f11a6/distributed/scheduler.py#L4287-L4295

One issue this causes is the prevention of garbage collection in tests (see #6353). To ensure that we clean up all scheduled tasks, we to implement functionality for managing background tasks and ensure proper cleanup on pending tasks. This should be implemented on the `Server` to make it available to all subclasses.

To advance our efforts to get rid of `tornado`, we want to implement this functionality using `asyncio` and remove the calls to `loop.call_later` and `loop.add_callback`.

Sketch of a possible implementation in `Server`:
```python3
class Server(...):
    ...    
    def __init__(...):
        ...
        self._background_tasks: set[asyncio.Task]
        ...

    def add_background_task(self, coro):
        task = create_task(coro())
        self._background_tasks.add(task)
        task.add_done_callback(lambda _: self._background_tasks.remove(task))
        ...

    async def close(self, ...):
        for ts in self._background_tasks:
            ts.cancel()
        await asyncio.gather(*self._background_tasks)
```

cc @fjetter, @graingert

### PR DESCRIPTION
**Pull request by graingert**
Closes #6359
https://github.com/dask/distributed/pull/6478 with conflicts fixed and a few suggestions applied

This PR introduces a `TaskGroup` class that encapsulates scheduling behavior behind `call_soon` and `call_later` methods and allows gracefully shutting down all its tasks at once with a `timeout`.

Outside of scope:

    * Replacing `loop.add_callback` and `loop.call_later` if the call is performed to another loop or the loop is not running.

    * Avoiding multiple concurrent calls to `Server.close()`, the fastest one wins as before, now it just cancels the others.

    * [x]  Tests added / passed (failing tests are [test_stress_scatter_death #6305](https://github.com/dask/distributed/issues/6305), [flaky test diagnostics/tests/test_progress.py::test_group_timing #6452](https://github.com/dask/distributed/issues/6452))

    * [x]  Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by graingert** [comment]
seemed to fail with https://github.com/dask/distributed/issues/4498 last time

**Comment by graingert** [comment]
Tests / test (ubuntu-latest, 3.8, not ci1) : https://github.com/dask/distributed/issues/6045

**Comment by graingert** [comment]
I think this PR should be squash merged

**Review by fjetter — APPROVED** [review]

**Comment by fjetter** [comment]
Thank you @graingert and @hendrikmakait ! Really looking forward to having this 🎉

**Comment by crusaderky** [comment]
This PR has caused a major performance degradation in CI: #6632

**Pull request merged**
