### PR TITLE
change thread name to be machine unique (#2084)

### PR DESCRIPTION
**Pull request by Dror-LightCyber**

### CODE REVIEW

**Comment by mrocklin** [comment]
I've removed the extra commits, rebased on master, and force pushed.  Hope you don't mind.

I also tried this out and found that the thread names didn't seem to be incrementing.  

```python
In [1]: from distributed.threadpoolexecutor import ThreadPoolExecutor

In [2]: e = ThreadPoolExecutor(4)

In [3]: list(e.map(lambda x: x + 1, range(10)))
Out[3]: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]: e._threads
Out[4]: 
{<Thread(ThreadPoolExecutor-19787-0, started daemon 140119312451328)>,
 <Thread(ThreadPoolExecutor-19787-0, started daemon 140119320844032)>,
 <Thread(ThreadPoolExecutor-19787-0, started daemon 140119329236736)>,
 <Thread(ThreadPoolExecutor-19787-0, started daemon 140119593821952)>}
```

I recommend adding a test to `distributed/tests/test_threadpoolexecutor.py` and then diving into what is going on here.

**Comment by Dror-LightCyber** [comment]
Thanks, man.

I fixed it using another approach. I hope it is ok.
However, one of the other tests fails apparently randomly and unrelated.
https://travis-ci.org/dask/distributed/builds/406623554?utm_source=github_status&utm_medium=notification

How do you suggest I proceed?

**Comment by mrocklin** [comment]
> However, one of the other tests fails apparently randomly and unrelated

I agree that that's likely unrelated.  I've restarted the test.  My apologies for the CI issues.  These have been happening over the last few weeks and I haven't yet had an opportunity to clean them all up.

The solution here looks good to me.  I'll take a look in the morning after CI has passed and merge in.  Thanks @Dror-LightCyber !

**Comment by mrocklin** [comment]
This is in.  Thanks @Dror-LightCyber !

**Pull request merged**
