### PR TITLE
add timeout to as_completed

### PR DESCRIPTION
**Pull request by CJ-Wright**
Closes #3133

### CODE REVIEW

**Comment by mrocklin** [comment]
@CJ-Wright are you still working on this?  No pressure, just checking in.

**Comment by CJ-Wright** [comment]
Sadly not, I'm a bit oversubscribed at the moment.

**Comment by john-jam** [comment]
@mrocklin @CJ-Wright Sorry for commenting on an old PR but I would like to use this feature.
Is there any alternative currently to use a `timeout` with `as_completed`?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by hendrikmakait** [comment]
Closed as superseded by #7811.

**Pull request closed without merging**
