### PR TITLE
Don't send closing messages on closed comm

### PR DESCRIPTION
**Pull request by mrocklin**
When client closes it sends out a bunch of final messages to the scheduler
cleaning up its various resources.  However if the scheduler connection is
already dead then this generates annoying error messages.  This was a common
occurrence when closing a LocalCluster.

Reported in https://github.com/dask/distributed/issues/1294

### CODE REVIEW

**Comment by mrocklin** [comment]
@ogrisel

**Comment by ogrisel** [comment]
I confirm that fixes my issue. Cannot you find an easy way to add a non-regression test for this?

**Comment by ogrisel** [comment]
The travis failures are real apparenty.

**Comment by mrocklin** [comment]
Yeah, I've been tracking down a failure today that snuck in recently.

Regarding tests the clearest way to test this would probably be to look at logs.  I've had issues testing logging in the past.  Do you have any recommendations or examples where you've seen this done well?

**Comment by mrocklin** [comment]
Ah, no.  These failures are genuine

**Comment by ogrisel** [comment]
Besides registering a specific logger in a test fixture and grepping the byte buffer...

**Comment by mrocklin** [comment]
> Besides registering a specific logger in a test fixture and grepping the byte buffer...

If you had a pointer to someplace that had done this well I would be happy to learn from such an example.  My attempts to do this in the past have either not worked or felt like a hack.

**Comment by ogrisel** [comment]
I assume it's possible to do a test fixture that does:

```python
import logging
import io

CAPTURED_LOGS = io.BytesIO()
logging.basicConfig(level=logging.DEBUG, stream=CAPTURED_LOGS)
```

(I have not tested it).

**Comment by ogrisel** [comment]
LGTM.

**Pull request merged**
