### PR TITLE
Replace all occurrences of sys.is_finalizing

### PR DESCRIPTION
**Pull request by fjetter**
We stumbled again over some noisiness during interpreter shutdown inside of the Futures `__del__`. For this we implemented the `is_python_shutting_down` utility which has slightly different semantics than the actual python `sys.is_finalizing`. I have to admit that I don't fully understand the differences but from what I can tell our toggle is set a little bit earlier. Reviewing all of our usage of `sys.is_finalizing` I think it is safe to use the utility everywhere for simplicity.

### CODE REVIEW

**Comment by hendrikmakait** [comment]
It looks like `test_quiet_close_process` isn't happy with these changes.

**Comment by fjetter** [comment]
if tests keep failing, let's just change the one in `Future` and keep it at that. No point in wasting our time hunting this down

**Comment by hendrikmakait** [comment]
> if tests keep failing, let's just change the one in `Future` and keep it at that. No point in wasting our time hunting this down

Looks like I'm playing ping-pong with test failures. I'll reactivate my PR.

**Comment by hendrikmakait** [comment]
> Looks like I'm playing ping-pong with test failures. I'll reactivate my PR.

I may have figured it out.

**Pull request merged**
