### PR TITLE
Add `locket` as a dependency instead of vendoring

### LINKED ISSUE #2486: Resource Warnings with LocalCluster
Hi Everyone, 

After starting a local cluster on my machine as shown here:

```  cluster = LocalCluster()

    print(cluster)

    client = Client()

    print(client)

    cluster.close()
```

I got so many Resource Warnings as shown below. 

```/usr/local/lib/python3.6/dist-packages/distributed/diskutils.py:161:

 ResourceWarning:

unclosed file <_io.BufferedWriter name='/home/amal/PycharmProjects/dynamicparcels/dynpar/dask-worker-space/worker-4t43rjqe.dirlock'>

/usr/local/lib/python3.6/dist-packages/distributed/diskutils.py:161: ResourceWarning:

unclosed file <_io.BufferedWriter name='/home/amal/PycharmProjects/dynamicparcels/dynpar/dask-worker-space/worker-4fyxnn5d.dirlock'>

<Client: scheduler='tcp://127.0.0.1:43123' processes=8 cores=8>
distributed.scheduler - INFO - Clear task state
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:37009'
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:41811'
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:38581'
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:42381'
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:41167'
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:39899'
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:43027'
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:34385'
distributed.scheduler - INFO - Remove worker tcp://127.0.0.1:39323
distributed.core - INFO - Removing comms to tcp://127.0.0.1:39323
distributed.scheduler - INFO - Remove worker tcp://127.0.0.1:46047
distributed.core - INFO - Removing comms to tcp://127.0.0.1:46047
distributed.scheduler - INFO - Remove worker tcp://127.0.0.1:45833
distributed.core - INFO - Removing comms to tcp://127.0.0.1:45833
distributed.scheduler - INFO - Remove worker tcp://127.0.0.1:36641
distributed.core - INFO - Removing comms to tcp://127.0.0.1:36641
distributed.scheduler - INFO - Remove worker tcp://127.0.0.1:42175
distributed.core - INFO - Removing comms to tcp://127.0.0.1:42175
distributed.scheduler - INFO - Remove worker tcp://127.0.0.1:33033
distributed.core - INFO - Removing comms to tcp://127.0.0.1:33033
distributed.scheduler - INFO - Remove worker tcp://127.0.0.1:46337
distributed.core - INFO - Removing comms to tcp://127.0.0.1:46337
distributed.scheduler - INFO - Remove worker tcp://127.0.0.1:37449
distributed.core - INFO - Removing comms to tcp://127.0.0.1:37449
distributed.scheduler - INFO - Lost all workers
distributed.scheduler - INFO - Scheduler closing...
distributed.scheduler - INFO - Scheduler closing all comms
/usr/lib/python3.6/asyncio/base_events.py:511: ResourceWarning:

unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
```

Do anyone have an idea how can I fix that please ?

### PR DESCRIPTION
**Pull request by madkinsz**
This was vendored to get an unmerged improvement to Windows handling of file locks that has now been merged. It is not yet released, so this pull request may not pass CI until a new locket release is made. The maintainer is active and a new release will likely be made soon after a dangling file descriptor fix discussed in https://github.com/mwilliamson/locket.py/issues/14 is confirmed to be working as intended.

See https://github.com/mwilliamson/locket.py/pull/8#issuecomment-1098402859 for discussion about vendoring.
Replaces https://github.com/dask/distributed/pull/6122

- [x] Closes #2486 
- [ ] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by madkinsz** [comment]
I do not think these test failures are related to locket. I've confirmed that the resource warnings reported in #2486 are no longer raised in the Prefect test suite so I believe https://github.com/mwilliamson/locket.py/issues/14 is resolved.

@mwilliamson may want to wait for confirmation from @mrocklin but it seems safe to cut a release with the windows/resource fixes, I can update this pull request to require it afterwards. Thanks!

**Comment by mrocklin** [comment]
yeah, the test failure that I'm seeing here is unrelated.  I've seen this a bit recently.  cc'ing @fjetter who may be able to handle it separately

```
    @gen_cluster(client=True)
    async def test_flight_cancelled_error(c, s, a, b):
        """One worker with one thread. We provoke an flight->cancelled transition
        and let the task err."""
        lock = asyncio.Lock()
        await lock.acquire()
    
        async def wait_and_raise(*args, **kwargs):
            async with lock:
                raise RuntimeError()
    
        with mock.patch.object(
            distributed.worker,
            "get_data_from_worker",
            side_effect=wait_and_raise,
        ):
            fut1 = c.submit(inc, 1, workers=[a.address], allow_other_workers=True)
            fut2 = c.submit(inc, fut1, workers=[b.address])
    
            await wait_for_state(fut1.key, "flight", b)
            fut2.release()
            fut1.release()
            await wait_for_state(fut1.key, "cancelled", b)
    
        lock.release()
        # At this point we do not fetch the result of the future since the future
        # itself would raise a cancelled exception. At this point we're concerned
        # about the worker. The task should transition over error to be eventually
        # forgotten since we no longer hold a ref.
        while fut1.key in b.tasks:
            await asyncio.sleep(0.01)
    
        # Everything should still be executing as usual after this
>       assert await c.submit(sum, c.map(inc, range(10))) == sum(map(inc, range(10)))

distributed\tests\test_cancelled_state.py:247: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
distributed\client.py:294: in _result
    raise exc.with_traceback(tb)
C:\Miniconda3\envs\dask-distributed\lib\unittest\mock.py:2164: in _execute_mock_call
    result = await effect(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   raise RuntimeError()
E   RuntimeError
```

**Comment by mrocklin** [comment]
> so I believe https://github.com/mwilliamson/locket.py/issues/14 is resolved

Woo!

> @mwilliamson may want to wait for confirmation from @mrocklin but it seems safe to cut a release with the windows/resource fixes, I can update this pull request to require it afterwards. Thanks

This is all good to go from my end.

**Comment by mrocklin** [comment]
It looks like CI is sad because locket isn't yet up.  Once it's up I'm happy to press the green button.  Let me know if I should rerun CI.

**Comment by mrocklin** [comment]
I'm guessing that you're also aware of errors like these, and that they'll be resolved when the new version comes out?

https://github.com/dask/distributed/runs/6104354678?check_suite_focus=true

**Comment by madkinsz** [comment]
Locket looks up https://pypi.org/project/locket/ but CI isn't detecting it? I'm presuming I've added the package incorrectly. Are there contributing guides for adding a dependency or another pull request I could refer to? There are a lot of files listing dependencies haha.

**Comment by mrocklin** [comment]
It looks like the conda build CI test failure is mostly saying "this isn't up on conda yet, and so I'm hesitant to let you merge".  

it looks like the bots are maybe handling this though: https://github.com/conda-forge/locket-feedstock/pull/9

**Comment by mrocklin** [comment]
Hrm, looks like the recipe there needs to be updated a bit.  Do you want to take this on @madkinsz , or bug the locket maintainers?  If not I can ask someone on our end to poke things there.  Learning about conda-forge is a good activity though, if you haven't engaged already.

**Comment by mrocklin** [comment]
Cool.  Thanks Michael.

**Comment by madkinsz** [comment]
@mrocklin should be available now, perhaps a rerun?

**Comment by mrocklin** [comment]
Running

**Comment by mrocklin** [comment]
This is in. Thanks @madkinsz !  

@jrbourbeau @jsignell whoever handles the next release should probably add `locket>=1.0` to the distributed requirements in the conda package.  https://github.com/conda-forge/distributed-feedstock/issues/204

**Pull request merged**
