### PR TITLE
Get worker resources from client

### PR DESCRIPTION
**Pull request by aa1371**
- [x] Closes https://github.com/apache/airflow/pull/16829#discussion_r673227899
- [x] Tests added / passed
- [ ] Passes `black distributed` / `flake8 distributed` / `isort distributed`

This PR adds a client.get_worker_reosurces method. This was suggested by @fjetter in the following DaskExecutor PR on Airflow (https://github.com/apache/airflow/pull/16829), as an alternative to using client.run_on_scheduler.

### CODE REVIEW

**Comment by mrocklin** [comment]
I suspect that this information is already visible in `client.scheduler_info()`.  This returns a dictionary with a "workers" key that points to another dictionary with a bunch of information about each worker.  I believe that resources is one of the things that is in that dictionary.

I slightly prefer to rely on that general purpose method rather than making a new method for every worker attribute, which could cause mild API bloat. 

If for some reason using scheduler_info doesn't work though then yes, let's do something like what is proposed here.

Also +1 on the implementation.  This looks clean to me.

**Comment by aa1371** [comment]
Yup you're right, it's there. Glad to see it. Agreed on avoiding the bloat. Closing the issue. Thanks.

@mrocklin @fjetter do you foresee any issues using client.scheduler_info in the DaskExecutor in airflow?

**Comment by mrocklin** [comment]
It's pretty stable API and is standard and secure to use.

Unrelated, but please let me know if there is anything I can do to help
Airflow/Dask support.

**Comment by aa1371** [comment]
Absolutely. If possible just taking a look at the airflow PR for implementing Airflow task queues, based on the worker resources, would be great. While I think the current suggestion of using the worker resources seems pretty solid, I'd be happy to see any holes you could poke in it, or any better alternatives.
https://github.com/apache/airflow/pull/16829 (updated to use your suggestion)

Gonna close this issue now. Thanks again.

**Pull request closed without merging**
