### PR TITLE
DO NOT Merge: Trigger CI

### PR DESCRIPTION
**Pull request by pentschev**
Triggering CI here to check gpuCI status, since it didn't seem to run/complete in https://github.com/dask/distributed/pull/5556 .

cc @jrbourbeau @quasiben

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Thanks for opening this up -- looks like `TypeError: catching classes that do not inherit from BaseException is not allowed
` is the root issue

**Comment by pentschev** [comment]
@jrbourbeau yes, you're right. The problem is UCX-Py packages haven't been built for 9 days, the fix is merged and I pinged our ops team to build new packages. Please hold on for a few more minutes while this is fixed.

**Comment by jrbourbeau** [comment]
Thanks for handling this @pentschev. Thoughts on adding a minimum version requirement to `test_ucx_unreachable` so it's skipped if an older version is used?

**Comment by pentschev** [comment]
> Thanks for handling this @pentschev. Thoughts on adding a minimum version requirement to `test_ucx_unreachable` so it's skipped if an older version is used?

This is why we have https://github.com/dask/distributed/blob/824c0abdecc96f1f8997757bacb86d48ba9157a5/distributed/comm/ucx.py#L423 , if the exception doesn't exist (old UCX-Py versions) it should just be ignored, but it seems the condition is incorrect. I'll check that.

**Comment by pentschev** [comment]
> > Thanks for handling this @pentschev. Thoughts on adding a minimum version requirement to `test_ucx_unreachable` so it's skipped if an older version is used?
> 
> This is why we have
> 
> https://github.com/dask/distributed/blob/824c0abdecc96f1f8997757bacb86d48ba9157a5/distributed/comm/ucx.py#L423
> 
> , if the exception doesn't exist (old UCX-Py versions) it should just be ignored, but it seems the condition is incorrect. I'll check that.

Nevermind, you meant to skip the test if `UCXUnreachable` is not available. I opened https://github.com/dask/distributed/pull/5560 to do that. Sorry for the misunderstanding.

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
New packages just landed, I'll just check that `test_ucx_unreachable` runs with it, but we can close this then as https://github.com/dask/distributed/pull/5560 was merged too.

**Comment by pentschev** [comment]
rerun tests

**Comment by jrbourbeau** [comment]
Looks like `test_ucx_unreachable` passes with the new images -- thanks again for the quick fix @pentschev

**Comment by pentschev** [comment]
It was actually being skipped because we needed to rebuild the Docker gpuCI container to pick up the latest UCX-Py package. Anyway it should be good, I'll take a look at some new PR when there's one just to confirm later.

**Pull request closed without merging**
