### PR TITLE
Use tuples in msgpack

### PR DESCRIPTION
**Pull request by mrocklin**
This makes msgpack decode arrays as tuples rather than lists, allowing them to be used within containers like set and dict that expect hashable elements.

cc @mariusvniekerk 

I took a quick look at this but then got side tracked by other things.  I thought I'd push it up here in case you were interested in carrying on.

### CODE REVIEW

**Comment by rbubley** [comment]
It seems that the unit tests in msgpack-python use a different approach to the issue of types.

See, e.g. https://github.com/lbolla/msgpack-python/commit/c8042ea99c3fa6641628e054d9a6ad6e4162b24a

**Comment by mariusvniekerk** [comment]
I like the approach in that and we can implement set, tuple, frozenset which is probably good enough for now?

**Comment by mrocklin** [comment]
Because I'm somewhat occupied this week the best solution might be to
submit  a PR of your own to the master branch, possibly including my
commits or not, as you like.  You could also submit a PR to my PR's branch.

**Comment by mrocklin** [comment]
OK, hypothetically this passes tests.  There are some things that concern me though:

1.  We are inconsistent about our use of tuples and lists.  We use tuples everywhere *except* if the tuple contained a Serilized object, in that case we use a list
2.  We actually *have* to do this, because we only traverse through lists to find serialized objects.

I would not be surprised if this came back to bite us later.

**Comment by mrocklin** [comment]
Well, lets see what happens.  Merging.

**Pull request merged**
