### PR TITLE
Make multi-progress bars in notebooks indicate failure. 

### PR DESCRIPTION
**Pull request by nfaggian**
Picked up on the TODO that was listed in the multiprogress bar,  #280.

I suspect this could give a false impression of the entire computation not being completed, which is not true if you use the "delayed" method for forming a list of tasks to execute and only one fails.

### CODE REVIEW

**Comment by mrocklin** [comment]
Thoughts on how we can add a test for this?

**Comment by nfaggian** [comment]
I used a notebook but is it possible to setup a mock display loop somehow?

**Comment by mrocklin** [comment]
While it's probably hard to test the display you *can* test the attributes of the widgets themselves.  Perhaps see `test_progressbar.py` to see if there are tests there that you could copy?

**Comment by nfaggian** [comment]
Yep - I will have a go at doing exactly that. What are your thoughts on having a "warn" level, which simply states that some component of the calculation failed?

**Comment by mrocklin** [comment]
Seems reasonable

**Comment by nfaggian** [comment]
Apologies for slow progress here.. I will tackle this tomorrow.

**Comment by nfaggian** [comment]
@mrocklin - possibly silly question but is just running py.test in the src directory supposed to work? or is it best to use travis?

**Comment by mrocklin** [comment]
I usually run the following from the main repository directory (one up from the source directory)

    py.test distributed --verbose

If you want the cli tests to pass you'll also have to install the library ahead of time

**Comment by nfaggian** [comment]
@mrocklin thanks -- trying to figure out how to create a "delayed" graph for the tests. Any examples?

**Comment by mrocklin** [comment]
The bulk of the tests are in https://github.com/dask/distributed/blob/master/distributed/tests/test_executor.py .  Searching in that file will probably yield some nice examples.

**Comment by mrocklin** [comment]
Closing as stale

**Pull request closed without merging**
