### PR TITLE
Add OS X Travis builder

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
Looks like the OS X builder is too slow for `test_open_close_many_workers[Worker-100-5] `, or it genuinely hangs on that test... Perhaps someone can test on their local OS X machine?

**Comment by mrocklin** [comment]
This test takes around 7-8 seconds on my local OS X machine

**Comment by mrocklin** [comment]
And passes

**Comment by pitrou** [comment]
Ah. Perhaps we need to disable slow tests on Travis OS X?

**Comment by pitrou** [comment]
Ok, it seems there are a lot of failures on the OS X builder. Some of them are timeouts, some of them are other errors. I also see "Too many open files" in some of the printed out log excerpts.

**Comment by pitrou** [comment]
I can't push this any further as I don't have an OS X machine to diagnose these errors. Someone else may take over.

**Comment by pitrou** [comment]
Things seem much better now. We're down to one failing test on OS X, and hopefully zero soon.

**Comment by mrocklin** [comment]
This looks fine to me.  Looks like it has conflicts with master

**Comment by pitrou** [comment]
Weird, I don't see any conflicts here. Is a Github glitch?

**Comment by mrocklin** [comment]
Either way it sounds like you should press the green button.  Either it will work or it won't.

**Pull request merged**
