### PR TITLE
Add python 3.11 to GPU CI matrix

### PR DESCRIPTION
**Pull request by charlesbluca**
With https://github.com/rapidsai/build-planning/issues/3, we're now publishing RAPIDS packages for 3.11 - we should test against those packages here (and in dask/dask, but probably once https://github.com/dask/dask/pull/11010 is in).

### CODE REVIEW

**Comment by mrocklin** [comment]
Quick question, I don't think we often see people engaging with the GPU CI on Dask PRs.  Is that correct?  Are you all actiely tracking each PR that fails GPU CI?  

If not, I propose that we stop running GPU CI on these PRs and that instead you all run a nightly test or something.  Thoughts?

It probably doesn't make sense to keep running GPU CI on every PR if no one is looking at the results.

**Comment by rjzamora** [comment]
@mrocklin - Before the query-planning switch we were absolutely engaging on gpuCI in dask. It was a great way for us to stay on top of breaking changes.

For the past few weeks we have been working to get dask-expr working with rapids (many small things are still broken, but we are getting much closer). I was nervous that you would propose removing it, because it has been quite valuable to us over the past year.

During the maintainers sync, I have mentioned a few times that rapids is trying not to slow down the legacy->dask-expr transition, and so it is temporarily okay for gpuCI to be broken.

**Comment by mrocklin** [comment]
Ah ok, I just misunderstood the situation.  I was seeing GPUCI broken for much of the last couple of years without NVIDIA folks responding on PRs when things were off.  Maybe you all are actually aware of what is going on though and just operating in the background?  Or maybe I'm just not as attentive as I could be here and missed stuff.  My apologies.

**Comment by rjzamora** [comment]
>Maybe you all are actually aware of what is going on though and just operating in the background?

I think it's fair that you think we are ignoring things. We do often work in the background, but I can/should develop a more visible process on our end. I appreciate the nudge.

**Comment by pentschev** [comment]
> I think it's fair that you think we are ignoring things. We do often work in the background, but I can/should develop a more visible process on our end. I appreciate the nudge.

I don't think it's fair we are "ignoring" things as normally folks like Florian and James are nice enough to nudge us when gpuCI is broken for some reason and then we act to fix it. It is true though that we don't watch every PR which "in a perfect world" is precisely what we hope for, ideally it is always green but we should catch things that break GPU usage when a change occurs either on Dask/Distributed's end or by some other dependency in the context of Dask/Distributed.

**Review by jrbourbeau — APPROVED** [review]
Thanks @charlesbluca! 

Just noting the failures here are unrelated and possibly already fixed (xref https://github.com/dask/distributed/issues/8591). I'm testing over in https://github.com/dask/distributed/pull/8599 to see if `main` is broken or not.

**Pull request merged**
