### PR TITLE
Msgpack 1.0 compatibility

### LINKED ISSUE #3491: distributed breaks with msgpack 1.0.0rc1
Just for information, distributed breaks with the 1.0.0 release candidate of msgpack. To reproduce:

1) `pip install distributed 'msgpack==1.0.0rc1'`
2) start a local dask cluster
3) connect client and call `Client.run(some_function)`

```
In [2]: Client("tcp://...:8786")                                     
Out[2]: <Client: 'tcp://...:8786' processes=1 threads=8, memory=16.46 GB>

In [3]: c = Client("tcp://...:8786")                                 

In [4]: c.run(lambda: "meh")                                                    
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-5ff942d48f6b> in <module>
----> 1 c.run(lambda: "meh")

~/.virtualenvs/ddtest/lib/python3.7/site-packages/distributed/client.py in run(self, function, *args, **kwargs)
   2384         >>> c.run(print_state, wait=False)  # doctest: +SKIP
   2385         """
-> 2386         return self.sync(self._run, function, *args, **kwargs)
   2387 
   2388     def run_coroutine(self, function, *args, **kwargs):

~/.virtualenvs/ddtest/lib/python3.7/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    765         else:
    766             return sync(
--> 767                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    768             )
    769 

~/.virtualenvs/ddtest/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    343     if error[0]:
    344         typ, exc, tb = error[0]
--> 345         raise exc.with_traceback(tb)
    346     else:
    347         return result[0]

~/.virtualenvs/ddtest/lib/python3.7/site-packages/distributed/utils.py in f()
    327             if callback_timeout is not None:
    328                 future = asyncio.wait_for(future, callback_timeout)
--> 329             result[0] = yield future
    330         except Exception as exc:
    331             error[0] = sys.exc_info()

~/.virtualenvs/ddtest/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/.virtualenvs/ddtest/lib/python3.7/site-packages/distributed/client.py in _run(self, function, nanny, workers, wait, *args, **kwargs)
   2313             ),
   2314             workers=workers,
-> 2315             nanny=nanny,
   2316         )
   2317         results = {}

~/.virtualenvs/ddtest/lib/python3.7/site-packages/distributed/core.py in send_recv_from_rpc(**kwargs)
    755             name, comm.name = comm.name, "ConnectionPool." + key
    756             try:
--> 757                 result = await send_recv(comm=comm, op=key, **kwargs)
    758             finally:
    759                 self.pool.reuse(self.addr, comm)

~/.virtualenvs/ddtest/lib/python3.7/site-packages/distributed/core.py in send_recv(comm, reply, serializers, deserializers, **kwargs)
    538         await comm.write(msg, serializers=serializers, on_error="raise")
    539         if reply:
--> 540             response = await comm.read(deserializers=deserializers)
    541         else:
    542             response = None

~/.virtualenvs/ddtest/lib/python3.7/site-packages/distributed/comm/tcp.py in read(self, deserializers)
    210             try:
    211                 msg = await from_frames(
--> 212                     frames, deserialize=self.deserialize, deserializers=deserializers
    213                 )
    214             except EOFError:

~/.virtualenvs/ddtest/lib/python3.7/site-packages/distributed/comm/utils.py in from_frames(frames, deserialize, deserializers)
     67         res = await offload(_from_frames)
     68     else:
---> 69         res = _from_frames()
     70 
     71     return res

~/.virtualenvs/ddtest/lib/python3.7/site-packages/distributed/comm/utils.py in _from_frames()
     53         try:
     54             return protocol.loads(
---> 55                 frames, deserialize=deserialize, deserializers=deserializers
     56             )
     57         except EOFError:

~/.virtualenvs/ddtest/lib/python3.7/site-packages/distributed/protocol/core.py in loads(frames, deserialize, deserializers)
    104 
    105         header = frames.pop()
--> 106         header = msgpack.loads(header, use_list=False, **msgpack_opts)
    107         keys = header["keys"]
    108         headers = header["headers"]

msgpack/_unpacker.pyx in msgpack._cmsgpack.unpackb()

ValueError: tuple is not allowed for map key

distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/home/alex/.virtualenvs/ddtest/lib/python3.7/site-packages/distributed/protocol/core.py", line 106, in loads
    header = msgpack.loads(header, use_list=False, **msgpack_opts)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: tuple is not allowed for map key

```

cc @Brow71189

### PR DESCRIPTION
**Pull request by jrbourbeau**
In msgpack 1.0 the default value for `strict_map_key` was changed from `False` to `True` (see https://github.com/msgpack/msgpack-python#major-breaking-changes-in-msgpack-10). This causes failures for us as we use map keys which are not `bytes` or `str`. This PR updates our use of `msgpack.loads` to include `strict_map_key=False`

Closes #3491

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks for handling this @jrbourbeau

**Comment by jrbourbeau** [comment]
CI has passed against both msgpack 1.0 and a pre-1.0 release to check for backwards compatibility

I've also set `0.6.0` as the minimum supported msgpack version (released in Nov 2018) because that's when the `strict_map_key` option was added. This seems reasonable to me, but if there's reason to think this `0.6.0` restriction is too aggressive we can add some additional logic surrounding the msgpack version to support older versions too

**Comment by TomAugspurger** [comment]
Requiring>=0.6 sounds fine.

**Comment by jrbourbeau** [comment]
Great, I just set the minimum version for our CI environments and will merge this PR when the current set of CI builds pass

**Comment by jrbourbeau** [comment]
The test failure seems unrelated and I've raised a separate issue for it (xref https://github.com/dask/distributed/issues/3498)

**Comment by Carreau** [comment]
May I suggest a new build/build number on conda-forge that update the metadata info to pin msgpack to `<1.0.0` ? I've [read recently](https://twitter.com/ocefpaf/status/1227292336662597632) that there should be a simpler way to do that via repodata patch, but I haven't used that before.

**Comment by mrocklin** [comment]
cc @jakirkham

**Comment by jakirkham** [comment]
A PR to the conda-forge feedstock to do that would be welcome 🙂

**Comment by Carreau** [comment]
> A PR to the conda-forge feedstock to do that would be welcome 🙂

Do you know how to patch the repodata, or do I just bump the build number ?

**Comment by Carreau** [comment]
See https://github.com/conda-forge/distributed-feedstock/pull/114

**Comment by jakirkham** [comment]
Thanks for doing that. Merged! 😄

**Comment by jakirkham** [comment]
> Do you know how to patch the repodata, or do I just bump the build number ?

Ah sorry missed this bit.

The [patches live here]( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/928f79eb1a70432e6e7fb99839329252462f3983/recipe/gen_patch_json.py ). Though bumping the build number works also and may be a bit more straightforward.

**Comment by jrbourbeau** [comment]
Thanks for updating the conda-forge recipe @Carreau!

**Comment by Carreau** [comment]
Jakirkham, I'm more thinking that all previous version of distributed (or at least a few of those) should get msgpack<1;
Bumping the build only affect latest one. It's something that I think will come up more and more often to update dependencies compat after the releases. Hence why I was thinking about repodata patch.

**Comment by jakirkham** [comment]
Yeah hot-fixing would still be appropriate Matthias 🙂

**Pull request merged**
