### PR TITLE
Pin openssl to 1.1.1d for Travis

### PR DESCRIPTION
**Pull request by jacobtomlinson**
See #3588

### CODE REVIEW

**Comment by jrbourbeau** [comment]
It looks like installing `libunwind` was causing `openssl` to be upgraded from `1.1.1d` to `1.1.1e` (see https://travis-ci.org/github/dask/distributed/jobs/665056582#L630-L657). I've moved the `openssl=1.1.1d` pinning to the end of our installation steps to make sure we're definitely pinning `openssl`

**Comment by jrbourbeau** [comment]
[Huzzah](https://travis-ci.org/github/dask/distributed/builds/665056580) 🎉

**Comment by mrocklin** [comment]
Oooh, nice green check marks :)

**Comment by mrocklin** [comment]
I'm going to go ahead and merge this short term.

Does this issue signal something larger that we need to be concerned with long term?

**Comment by jacobtomlinson** [comment]
Ah thanks for spotting this @jrbourbeau!

@mrocklin yes this doesn't seem like a great solution, but perhaps we should wait for `openssl` `1.1.1f` and see if the problem persists before being too concerned.

**Pull request merged**
