### PR TITLE
Ignore warning for unclose SSHCluster in tests

### PR DESCRIPTION
**Pull request by fjetter**
I don't think this is worth raising.

Closes https://github.com/dask/distributed/issues/6771
Closes https://github.com/dask/distributed/issues/6653

### CODE REVIEW

**Comment by gjoseph92** [comment]
@graingert you've looked at this SSHCluster a bit?

**Comment by fjetter** [comment]
There are a couple of tests that are not necessarily closing SSHCluster properly. Some are instantiating the object but not awaiting or closing it. Both can leave a cluster dangling.

While this _may_ be worth fixing, I don't think it's worth it right now and would prefer just ignoring this warning unless there is concern that this would indeed negatively impact other tests

**Comment by graingert** [comment]
I think this is only happening due to xfailed tests that should be skipped

**Review by graingert — CHANGES_REQUESTED** [review]
I think better to skip the xfailed Macos tests?

**Review by graingert — APPROVED** [review]

**Pull request merged**
