### PR TITLE
Fix System page on dashboard

### PR DESCRIPTION
**Pull request by prasunanand**
* Fixes https://github.com/dask/distributed/issues/2710
* Modified the flex property of `#system-fluid` and `.system-item`

Attached screenshot
Screenshot from 2020-05-04 19-18-22

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @dsludwig in case he has time

**Comment by mrocklin** [comment]
Or @jsignell perhaps?  This should be a quick review if you're around and are comfortable with CSS (I am not unfortunately)

**Comment by jsignell** [comment]
Thanks for the ping; I will take a look.

**Comment by jsignell** [comment]
An alternate approach that is more similar to the proposal in the original issue is at #3781.

**Comment by prasunanand** [comment]
Thanks @jsignell . Made the changes.

**Comment by jsignell** [comment]
Thank you for making the changes @prasunanand. Since you have brought up this fix I went back to the original issue and I think an even better solution is to use bokeh layouts and not write our own css for this view at all. I implemented that in #3781.

**Pull request closed without merging**
