### PR TITLE
BUG: allows logging config under distributed key

### PR DESCRIPTION
**Pull request by deniederhut**
The logging documentation specifies a configuration path to
logging info like config['distributed']['logging'], but the
config module looks in config['logging']. This commit allows
both by looking first in config['distributed'], then falling
back to config.

Closes https://github.com/dask/distributed/issues/2937

### CODE REVIEW

**Comment by jakirkham** [comment]
@mrocklin, would you be able to review this?

**Comment by mrocklin** [comment]
I don't think anyone knows much about the logging code here (it may have been Antoine's).  @jcrist might be the best person to think about how we can improve the logging/config situation.  Perhaps we can ask him?

**Comment by mrocklin** [comment]
poke @jcrist , if you have a minute

(sorry for letting this linger @deniederhut )

**Comment by deniederhut** [comment]
No worries - thanks for circling back to it!

**Comment by deniederhut** [comment]
Okay, test in place. Should I open an issue for deprecating the older logging config placement? Or just open a second PR that addresses this?

**Comment by mrocklin** [comment]
cc @quasiben for review

**Comment by mrocklin** [comment]
@jcrist would you be willing to review/manage this PR?

**Comment by mrocklin** [comment]
Ping @jcrist , who we recently realized wasn't getting github notifications.  

@jcrist no pressure (I know I just pinged you on other things as well), but if you have time it would be great to have someone take a long look at how we do logging configuration.

**Comment by mrocklin** [comment]
@jcrist are you planning to look at this?  If no, that's fine, but it'd be good to get a response if you're able.

**Comment by deniederhut** [comment]
Hey @mrocklin, have we found someone to review this PR?

**Comment by mrocklin** [comment]
I personally haven't done anything here, no.  Is that what you were asking?

**Comment by deniederhut** [comment]
No worries! Things have been quiet for a while so I just wanted to check in

**Comment by quasiben** [comment]
@deniederhut thanks again for this PR.  I merged with master and I hope to get this in today.  I think I only have a few questions.  Currently, when setting logging config from the CLI the user does something like the following:

> DASK_LOGGING__DISTRIBUTED=debug python -c "import dask, distributed; print(dask.config.get('logging'))"

I was expecting with this PR to be able to be able to use `DASK__DISTRIBUTED_LOGGING=debug ` but this does not seem to work:

>  DASK__DISTRIBUTED_LOGGING=debug python -c "import dask, distributed; print(dask.config.get('distributed.logging'))"

**Comment by jcrist** [comment]
@quasiben, I think you meant:

```shell
$ DASK_DISTRIBUTED__LOGGING=debug python -c "import dask, distributed; print(dask.config.get('distributed.logging'))"
debug
```

which works fine (no `__` after `DASK` is needed, but `__` from then on indicate `.` in the key).

**Comment by jcrist** [comment]
Apologies for letting this sit so long. I've kicked off a new build (travis ci only, just to check that things haven't broken while idle). Will merge on tests pass.

**Comment by quasiben** [comment]
@jcrist thanks for the correction

**Comment by TomAugspurger** [comment]
All green, merging.

Thanks for sticking with this @deniederhut. Sorry for the delay!

**Pull request merged**
