### PR TITLE
Deprecate --bokeh/--no-bokeh CLI

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/dask/distributed/issues/2799

### CODE REVIEW

**Comment by mrocklin** [comment]
Looks great.  Thanks @TomAugspurger

**Comment by mrocklin** [comment]
Hrm, the tests here seem to be unhappy

**Comment by TomAugspurger** [comment]
Whoops, I was running the worker one twice.

I don't really see an easy way to do the test for the scheduler.

**Comment by mrocklin** [comment]
> I don't really see an easy way to do the test for the scheduler.

I don't understand.  What is the concern here?

**Comment by TomAugspurger** [comment]
The click-based version I was using seemed to just be waiting in the dask-scheduler command, waiting for workers to connect. I didn’t see a way to background the call, so that we could interrupt / end it.

I didn’t have luck using the style of tests in that file already. I don’t recall the issue I ran into.

**Pull request merged**
