### PR TITLE
Add support for packing namedtuple and add test for future resolution in submit

### PR DESCRIPTION
**Pull request by ahuang11**
Follow up on https://github.com/dask/distributed/pull/7282.

I apologize for the noise; the initial PR did not accomplish what we needed entirely. This one adds support for packing  namedtuple (previously unpacking), and builds on top of https://github.com/dask/distributed/pull/7291. We also tested on our use-case with expected results.

Thanks!

cc: @madkinsz 

- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by ahuang11** [comment]
I think the tests are flaky
```

                children = wait_active_children(timeout=check_timeout)
>               assert not children, f"Test leaked subprocesses: {children}"
E               AssertionError: Test leaked subprocesses: [<SpawnProcess name='Dask Worker process (from Nanny)' pid=35959 parent=4068 started daemon>]
E               assert not [<SpawnProcess name='Dask Worker process (from Nanny)' pid=35959 parent=4068 started daemon>]
```

**Comment by madkinsz** [comment]
@mrocklin this is blocking some work on our end; is there anything we can do to help move this forward?

**Comment by mrocklin** [comment]
Thanks for the ping @madkinsz 

@fjetter this is important for Prefect.  Is this something I can ask your team to own and get in before the next release?

**Comment by antonymayi** [comment]
Please note this implementation (together with #7282) is making an incorrect assumption on the constructor signature of any `namedtuple` subtypes. In the first place, this is conceptually wrong, but more painfully it is effectively a backward incompatible change that is breaking the processing of a number of legitimate implementations.

I am proposing to fix it using per #7465 which also provides more detail on the issue.

Please consider holding back from releasing this patch until fixed.

**Pull request merged**
