### PR TITLE
Use upstream dask.widgets

### PR DESCRIPTION
**Pull request by jacobtomlinson**
This PR is a companion to dask/dask#8019 which moves the new jinja2 widgets tooling up into `dask`.

### Changes

- Remove `distributed.widgets.utils` as they are now upstream
- Update `distributed.widgets.__init__` to configure the distributed templates directory and custom filters with `dask.widgets`
- Update `distributed.utils.typename` to import `dask.utils.typename`
- Fix a couple of bugs in the `Client` and `Computation` templates

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Since we're tightly pinning dask and distributed releases, I don't think it will matter if this is merged before or after the next release

**Comment by jacobtomlinson** [comment]
My worry is that #5188 added some things which have been removed again in this PR, so it would be good to get them both merged in the same release cycle.

As @jrbourbeau says `dask` and `distributed` are tightly coupled.

**Comment by mrocklin** [comment]
OK, grand

**Comment by jacobtomlinson** [comment]
Looks like some bug fixes were made in `typename` that needed to be upstreamed to `dask` (dask/dask#8060). Tests _should_ pass here once that is merged.

**Comment by jacobtomlinson** [comment]
Test failures now appear flaky and unrelated. I intend to merge this tomorrow if there are no further comments.

**Review by jrbourbeau — APPROVED** [review]
Thanks @jacobtomlinson! 

I pushed a couple of commits to deprecate the `typename` utility in `distributed`, hope that's okay.

**Comment by jacobtomlinson** [comment]
Of course! Many thanks @jrbourbeau.

**Pull request merged**
