### PR TITLE
Replaced `distributed.utils.key_split` with `dask.utils.key_split`

### LINKED ISSUE #6313: Replace `distributed.utils.key_split` with `dask.utils.key_split`
The `key_split` function is defined in both [`dask.utils`]( https://github.com/dask/dask/blob/8e596ce74a0993164e93095e51639884d18c3382/dask/utils.py#L1728 ) and [`distributed.utils`]( https://github.com/dask/distributed/blob/fb1f7d1b8158e882644bda1a18eeb9d24f24abc4/distributed/utils.py#L610 ). Given this, it would make sense to drop the Distributed implementation (copying over any needed bits to Dask) and then use the Dask implementation in Distributed.

### PR DESCRIPTION
**Pull request by lukeconibear**
- [x] Closes #6313 
  - Companion PR from `dask` is [Added `distributed.utils.key_split` functionality to `dask.utils.key_split` #9464](https://github.com/dask/dask/pull/9464)
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by lukeconibear** [comment]
These 3 tests pass locally, but not on CI. I don't think they were impacted by this PR.
Is there an issue?

```bash
distributed/tests/test_steal.py::test_steal_reschedule_reset_in_flight_occupancy
distributed/tests/test_nanny.py::test_nanny_death_timeout
distributed/diagnostics/tests/test_task_stream.py::test_get_task_stream_save
```

**Comment by ncclementi** [comment]
add to allowlist

**Review by fjetter — APPROVED** [review]
> Is there an issue?

Our CI is not the most reliable and we have a couple of flaky tests. See https://github.com/dask/distributed/issues/6999

Haven't seen `test_nanny_death_timeout` and `test_get_task_stream_save` fail before. I suspect they are unrelated

**Comment by fjetter** [comment]
Thanks @lukeconibear

**Comment by fjetter** [comment]
Thank you @lukeconibear

**Comment by lukeconibear** [comment]
Great, thank you very much!

**Pull request merged**
