### PR TITLE
WorkerProcess blocks on kill if still starting

### PR DESCRIPTION
**Pull request by mrocklin**
See #6311 

This is a commit that @fjetter already wrote, but didn't get put into main.  I'm just putting it up here to see if it fixes problems.  It seems to do so.

### CODE REVIEW

**Comment by mrocklin** [comment]
Anecdotally this seems to be a very good commit to have.  CI is decently happy and I've been seeing this failure occur frequently.   @crusaderky do you have time to review tomorrow?

**Comment by mrocklin** [comment]
CI is fully green.  (one yellow, but it appears to have actually gone through everything correctly and happily when you investigate)

**Comment by mrocklin** [comment]
xref https://github.com/dask/distributed/pull/7323 where I suspect this commit originally came from

**Comment by mrocklin** [comment]
Two failures in test_semaphore

One failure in dashboard test_simple (maybe already fixed in #7426 )

**Comment by mrocklin** [comment]
Merging later today if there are no further comments

**Review by crusaderky — APPROVED** [review]

**Comment by mrocklin** [comment]
🎉

**Pull request merged**
