### PR TITLE
Keep old dependencies on run_spec collision

### PR DESCRIPTION
**Pull request by crusaderky**
- Closes https://github.com/dask/dask/issues/10905
- Buids on top of https://github.com/dask/distributed/pull/8185
- Works around https://github.com/dask/dask/issues/9888

While developing https://github.com/dask/distributed/pull/8185, @fjetter and I discussed the option to simply retain the old run_spec in case of key collision. During that conversation, the prevailing opinion was that a hard crash was preferable.
Since then, we realised that a hard crash cannot be implemented as it would break many other use cases impacted by https://github.com/dask/dask/issues/9888, where the run_spec changes and the dependencies are either the same or become a subset of the previous ones. The use cases where https://github.com/dask/dask/issues/9888 causes the cluster crash is when there are _added_ dependencies. So we fell back to just a warning in the scheduler log.

This one-liner PR ensures that, in case of run_spec collision, both run_spec and dependencies remain the same as in the old version (while still printing a warning). This should effectively sweep dask/dask#9888 under the carpet, i.e. whenever two task with different run_spec and possibly different dependencies produce the same output, and just leave the problem of manually crafted keys.

### CODE REVIEW

**Comment by fjetter** [comment]
I'm a little concerned about the case where the tasks are not producing the same output. With this change there is a (very unlikely) chance to produce wrong results, isn't there?

**Comment by crusaderky** [comment]
> I'm a little concerned about the case where the tasks are not producing the same output. With this change there is a (very unlikely) chance to produce wrong results, isn't there?

More or less like it was before.

### Legend
:heavy_check_mark: produces correct output
:name_badge: cluster crashes or hangs on AssertionError
:confused: task completes successfully, but output is wrong
:warning: emits warning in the scheduler log

| Task output | Deps | Old status | 2024.2.0 | main | this PR | Use case of dask/dask#9888? | 
| --- | --- | --- | --- | --- | --- | --- |
| same | same | pending | :heavy_check_mark: | :warning: :heavy_check_mark: | :warning: :heavy_check_mark:  | yes |
| same | new has less | pending |  :heavy_check_mark: | :warning: :heavy_check_mark: | :warning: :heavy_check_mark:  | yes |
| same | new has more | pending | :name_badge: | :warning: :name_badge: | :warning: :heavy_check_mark: | yes |
| same | * | memory | :heavy_check_mark: | :warning: :heavy_check_mark: | :warning: :heavy_check_mark:  | yes |
| same | * | released | :heavy_check_mark: |:heavy_check_mark: | :heavy_check_mark:  | yes |
| differs | same | pending | :confused: | :warning: :confused: | :warning: :confused: | no |
| differs | new has less | pending | :confused: | :warning: :confused: | :warning: :confused: | no |
| differs | new has more | pending | :name_badge: | :warning: :name_badge: | :warning: :confused: | no |
| differs | * | memory | :confused: | :warning: :confused: | :warning: :confused: | no |
| differs | * | released | :confused: | :confused: | :confused: | no |

**Comment by crusaderky** [comment]
Out of scope for this PR: I'm unsure why a task that's already in memory only emits a warning when there are less dependecies than before.

**Review by fjetter — APPROVED** [review]
I guess this is the lesser evil 🙈

**Pull request merged**
