### PR TITLE
Avoid use of external resources in bokeh server

### PR DESCRIPTION
**Pull request by mrocklin**
This removes a reference to google fonts
and also includes the Dask logo as a static local resource.

Fixes https://github.com/dask/distributed/issues/1920

### CODE REVIEW

**Comment by guillaumeeb** [comment]
I've tried your branch, no timeout, but I've only the menu bar at the top of the UI... No logo, and more importantly no content/graphs/data...

I've not had a lot of time to try, so maybe I've done something wrong...

**Comment by guillaumeeb** [comment]
Going back to the master branch, I can see the content of the pages (once the timeout induced by the network configuration of my infrastructure is over).

**Comment by guillaumeeb** [comment]
Just for checking, here is the command I used to install this branch:
`pip install git+https://github.com/mrocklin/distributed@bokeh-without-internet`

which gives me:
```
Installing collected packages: distributed
  Found existing installation: distributed 1.21.6+12.g650118a
    Uninstalling distributed-1.21.6+12.g650118a:
      Successfully uninstalled distributed-1.21.6+12.g650118a
  Running setup.py install for distributed ... done
Successfully installed distributed-1.18.1+324.ge4950b9
```

Find it weird to install distributed 1.18 in place of 1.21. Did I do something wrong?

**Comment by mrocklin** [comment]
> Find it weird to install distributed 1.18 in place of 1.21. Did I do something wrong?

I just haven't pushed the tags to my fork.  It shouldn't matter.

> I've tried your branch, no timeout, but I've only the menu bar at the top of the UI... No logo, and more importantly no content/graphs/data...

That's odd.  Do any errors show up either locally in your scheduler process or in the web browser in the web console when you refresh the page?

**Comment by guillaumeeb** [comment]
Scheduler log, nothing weird:

```
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:   tcp://10.xxx:8786
distributed.scheduler - INFO -       bokeh at:         10.1xxx:8787
distributed.scheduler - INFO - Local Directory: /tmp/pbs.4364071.admin01/scheduler-k1q9mlqn
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Register tcp://10.xxx:39959
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.xxx.42:39959
distributed.scheduler - INFO - Register tcp://10.xxx:54602
distributed.scheduler - INFO - Register tcp://10.xxx.41:35833
distributed.scheduler - INFO - Register tcp://10.xxx.41:44175
distributed.scheduler - INFO - Register tcp://10.xxx.41:50082
distributed.scheduler - INFO - Register tcp://10.xxx.41:45432
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.xxx.41:44175
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.xxx.41:45432
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.xxx.41:50082
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.xxx.41:54602
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.xxx.41:35833
distributed.scheduler - INFO - Register tcp://10.xxx.40:36941
distributed.scheduler - INFO - Register tcp://10.xxx40:36743
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.xxx.40:36941
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.xxx.40:36743
distributed.scheduler - INFO - End scheduler at 'tcp://10.xxx.37:8786'
```
Problem shows up in firefox with a lot of 404 errors:
daskworkeruibranch

**Comment by guillaumeeb** [comment]
Some examples of requested URLs in firefox:
```
http://10.XXX.37:8787/static/css/bokeh.min.css?...
http://10.XXX.37:8787/static/dask_horizontal.svg
```

**Comment by guillaumeeb** [comment]
Solved for bokeh data content, still the 404 error with the svg file:
`http://10.135.36.39:8787/statics/dask_horizontal.svg`

**Comment by mrocklin** [comment]
Can you check the following:

```python
>>> os.listdir(os.path.join(os.path.dirname(distributed.__file__), 'bokeh', 'static'))
['dask_horizontal.svg']
```

I suspect that this is now a packaging issue, perhaps I need to include something in the setup.py file?

**Comment by guillaumeeb** [comment]
```
>>> os.listdir(os.path.join(os.path.dirname(distributed.__file__), 'bokeh', 'static'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/work/ADM/hpc/eynardbg/Outils/miniconda3/envs/dask_dev/lib/python3.5/site-packages/distributed/bokeh/static'
```
Files here:
```
$ ls /work/ADM/hpc/eynardbg/Outils/miniconda3/envs/dask_dev/lib/python3.5/site-packages/distributed/bokeh/
components.py       export_tool.js  __pycache__        task_stream.py  tests
core.py             export_tool.py  scheduler_html.py  template.html   utils.py
export_tool.coffee  __init__.py     scheduler.py       templates       worker.py
```

**Comment by mrocklin** [comment]
@jakirkham if you're around can I ask for your help on this?  What should I
be doing here to ensure that this svg file is properly bundled with the
source?  (or is that the wrong question to ask?)

**Comment by jakirkham** [comment]
So I think `dask_horizontal.svg` is [coming from Dask]( https://github.com/dask/dask/blob/0.17.2/docs/source/images/dask_horizontal.svg ). If we want it bundled, we either need to start bundling it in Dask packages or we need to move/copy that file over here and start bundling it here. To cutdown on moving parts, would suggest including it here for now while we try to figure things out at least. Long term we can figure out what we want to do after we are sure this is working reasonably well.

Also `MANIFEST.in` is fine for adding things to the `sdist` (e.g. `README`s, docs, and such). Mainly stuff that we want to show up on PyPI. Though it's not great for handling stuff that we expect to land in `site-packages` or somewhere else in the installation tree. Admittedly there are options like [`include_package_data`]( http://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files ), which requires `setuptools`, but this pulls everything from `MANIFEST.in` into `site-packages`, which is not typically what one wants. For situations like this one, using [`package_data`]( https://packaging.python.org/tutorials/distributing-packages/#package-data ) or [`data_files`]( https://packaging.python.org/tutorials/distributing-packages/#data_files ) is preferable as these allow more precise inclusion and allow the structure to be specified as needed.

**Comment by jakirkham** [comment]
Looks like [we do use `include_package_data`]( https://github.com/dask/distributed/blob/1.21.6/setup.py#L32 ). So that should be fine now that the file is here.

**Comment by mrocklin** [comment]
Do I need to include the svg file in the package_data parameter there as is
done with some of the html files?

**Comment by mrocklin** [comment]
Merging this tomorrow if there are no further comments.  

Things seem to work well when I pip install from source from a clean environment.

**Comment by jakirkham** [comment]
Also tested it and it looks good. If you have a chance to retest @guillaumeeb, that would be appreciated.

> Do I need to include the svg file in the package_data parameter there as is done with some of the html files?

Could do that, but shouldn't be needed. `include_package_data` solves this problem for us.

**Comment by mrocklin** [comment]
Can we delete those lines in setup.py or are they still needed for the html
files?

**Comment by guillaumeeb** [comment]
It's working for me two, thanks!

**Comment by jakirkham** [comment]
> Can we delete those lines in setup.py or are they still needed for the html files?

Which lines are you thinking about? Maybe a link or code snippet to the relevant ones?

**Comment by mrocklin** [comment]
I was thinking of these: 

https://github.com/dask/distributed/blob/58c1babb28dc6a4cc418c40c08c252a83fc3e79d/setup.py#L30

**Pull request merged**
