### PR TITLE
Fix pyright error when importing from distributed

### LINKED ISSUE #6903: Importing from distributed shows pyright error
**What happened**:
When type-checking a program that imports from distributed with pyright, an error is accused:

```python
# foo.py
from distributed import Client
print(Client)
```

```
pyright foo.py
...
  /tmp/test-area/foo.py:1:25 - error: "Client" is not exported from module "distributed"
    Import from "distributed.client" instead (reportPrivateImportUsage)
1 error, 0 warnings, 0 informations
```

**What you expected to happen**:
I expect the package to be correctly typed, following PEP 484

**Anything else we need to know?**:

PEP 484 states that

> Modules and variables imported into the stub are not considered exported from the stub unless the import uses the `import ... as ... form` or the equivalent `from ... import ... as ... form`

and Pyright follows this guideline, although mypy doesn't.

**Environment**:

- Dask version: 2022.8.0
- Python version: 3.10.5
- Operating System: Arch linux
- Install method (conda, pip, source): pip inside an environment

### PR DESCRIPTION
**Pull request by ianliu**
Consider the following snippet of code:

```python
from distributed import Client
```

When type-checking with pyright, this gives an error stating that _"Client" is not exported from module "distributed"_. This is because pyright is following PEP 484, where I extracted the following excerpt:

> Modules and variables imported into the stub are not considered exported from the stub unless the import uses the `import ... as ... form` or the equivalent `from ... import ... as ... form`

Although `distributed` is not a stub, this rule is being applied because of the `py.typed` file.

Closes #6903

- [ ] Tests added / passed

Where are the tests? The CONTRIBUTING.md tells me to run `py.test`, but I couldn't find how.

- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by crusaderky** [comment]
The paragraph you mention from PEP 484 was written before `py.typed` existed, and it specifically refers to stub files. PEP 561, which introduces `py.typed`, does not clarify, so it's up to interpretation.

My personal interpretation is that this is extremely unreadable, and I don't think that treating .py files as stubs just because of `py.typed` is a good policy. IMHO you should open an upstream issue in pyright.

**Comment by ianliu** [comment]
> My personal interpretation is that this is extremely unreadable

I think this is unreadable as well, so I will consider opening an issue on pyright.

I was also searching for another perspective, and pyright errors go away if the symbols are put in the `__all__` list as well. Do you think that defining `__all__` makes sense for this case?

**Comment by crusaderky** [comment]
Yes, `__all__` would be a bit verbose but definitely cleaner.

**Comment by crusaderky** [comment]
Opened upstream ticket: https://github.com/python/peps/issues/2768
Could you open a ticket on pyright and link it on the python/peps ticket above?

**Comment by gjoseph92** [comment]
I also have found this annoying. I'd prefer `__all__`; it seems a bit more readable to me as well.

**Comment by ianliu** [comment]
Sorry for the delay. I've opened this issue https://github.com/microsoft/pyright/issues/3843 on pyright, and Eric responded with this link: https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface

I will change the patch to include an `__all__` constant.

**Comment by ianliu** [comment]
@crusaderky I was searching the typing-sig mailing list and found this thread: https://mail.python.org/archives/list/typing-sig@python.org/thread/YLJPWECBNPD2K4TRIBRIPISNUZJCRREY/#C2ZZKEM3EESWMDUF3PYZB4ZG2L42XUZT

The thread was started by Eric Traut himself, the author of Pyright, and his concern is exactly how to determine public symbols in `py.typed` packages. I think the [documentation](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface) I've linked above is the result of the discussion on the thread.

**Review by crusaderky — APPROVED** [review]

**Comment by crusaderky** [comment]
Thank you

**Pull request merged**
