### PR TITLE
Santize get_dataset trace

### PR DESCRIPTION
**Pull request by jakirkham**
Closes https://github.com/dask/distributed/pull/1887

Bump up where `KeyError` is raised in the `get_dataset` stack to cutdown on noise in the logs while preserving the expected behavior in the user facing API.

cc @martindurant

### CODE REVIEW

**Comment by martindurant** [comment]
I'm OK with it.
Could use a little test.
@mrocklin , `raise` is enough in a coroutine, does not need some `gen` ?

**Comment by jakirkham** [comment]
What would you suggest testing? FWIW there are tests for `get_dataset` when the dataset does and does not exist already.

Always wonder the same thing with Tornado. Seems [just raising is fine]( https://stackoverflow.com/a/43942549 ).

**Comment by martindurant** [comment]
Ah, so indeed you replaces the complex exception with the cleaner one, and so of course the tests are happy :) In that case, all good with me.

**Comment by jakirkham** [comment]
Great. FWIW would be ok check the log too, but would need advice on how to approach it.

**Comment by jakirkham** [comment]
Hmm...so this is still a bit noisier than I'd like. Will see about moving the exception to `get_dataset` instead.

**Comment by jakirkham** [comment]
Seems that is not possible as `_get_dataset` returns a `Future`. Suggestions?

For context, this is the red text that shows up any time we check for a named dataset that doesn't exist. This happens regardless of whether we catch the `KeyError` thrown outside the Tornado `IOLoop`.

```python
distributed.utils - ERROR - "Dataset 'raw' not found"
Traceback (most recent call last):
  File "/opt/conda3/lib/python3.6/site-packages/distributed/utils.py", line 238, in f
    result[0] = yield make_coro()
  File "/opt/conda3/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/opt/conda3/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/opt/conda3/lib/python3.6/site-packages/distributed/client.py", line 1833, in _get_dataset
    raise KeyError("Dataset '%s' not found" % name)
KeyError: "Dataset 'raw' not found"
```

**Comment by mrocklin** [comment]
You want to control line 240 in utils.py.  We don't necessarily want to log every error that occurs with sync.  I'm actually inclined to just remove this line entirely and see what happens.  We always raise the exception anyway, so it doesn't seem necessary to log it as well.

**Comment by jakirkham** [comment]
That feels a little heavy-handed to me. Wouldn't be surprised if someone came and gripped about that change after the fact. Is there any way for us to fix this issue locally?

**Comment by mrocklin** [comment]
https://github.com/dask/distributed/pull/1894

**Comment by jakirkham** [comment]
Think this is good to go.

**Pull request merged**
