### PR TITLE
Persist worker keyword

### PR DESCRIPTION
**Pull request by martindurant**
Beginning of thoughts on #285

### CODE REVIEW

**Comment by mrocklin** [comment]
In principle this looks fine to me.  Some thoughts:

1.  We should add support for compute
2.  We should verify that both `a.ip` and `a.address` and `[a.ip]` all work
3.  I'm a bit curious what the behavior is if we call persist on the same collection twice with different `workers=` .  I would hope that `restrictions` would merge on the scheduler but I doubt that this is current behavior.
4.  It's not entirely clear if actual use cases want this or if they want the ability to restrict certain parts of the computation to different worker sets.

**Comment by mrocklin** [comment]
But, we should probably nail down point 4 above before spending much effort on points 1-3

**Comment by martindurant** [comment]
Agreed we need to make a plan on number 4).
From the code (not tested), I think in the case for 3), the most recent wins. This kind of thing would be important, since (once it's implemented) one can call compute() on something persisted/submitted, and pass different restrictions too.

**Comment by mrocklin** [comment]
This is stalled.  Closing for now.

**Pull request closed without merging**
