### PR TITLE
Add nanny logs

### PR DESCRIPTION
**Pull request by TomAugspurger**
I had a need to collate logs from the cluster, and would like to include logs from the Nanny. This adds a method to get logs from the nanny as well. 

This isn't quite ready.

1. The keys in the returned dict are the address of the workers, not the nannies. Do we have a convention here? I assume we want the address of the nannies.
2. I may be adding the handler to the `distribted.nanny.logger` multiple times, resulting in duplicate logs. Need to verify what's going on.

### CODE REVIEW

**Comment by mrocklin** [comment]
> Do we have a convention here? 

Other functions like `run` and broadcast take a `nanny=` keyword argument.  That might be appropriate here as well.

**Comment by mrocklin** [comment]
So `client.get_worker_logs(nanny=True)`

In fact, I suspect that on the scheduler you could just pass through the `nanny=nanny` keyword to `Scheduler.broadcast` and everything would work out.

**Comment by TomAugspurger** [comment]
Thanks @mrocklin that works out quite nicely.

I found similar behavior for Client.run. I updated the docstring there to specify that `workers` should still be the *worker* addresses when you specify `nanny=True`, not the nanny address.

**Comment by TomAugspurger** [comment]
As an aside, having timestamps in logs is quite helpful for collation across the cluster (assuming the clocks synced well enough). What's our backwards compatibility story for configuration things like that?

**Comment by TomAugspurger** [comment]
Actually, this may not be ready. I thought I had sorted out the duplicate logging, but apparently not.

**Comment by mrocklin** [comment]
Other than the possible duplicate handler issue the implementation here looks great to me.

**Comment by mrocklin** [comment]
> As an aside, having timestamps in logs is quite helpful for collation across the cluster (assuming the clocks synced well enough). What's our backwards compatibility story for configuration things like that?

I don't have any particular thoughts here.  

You may want to take a look here though:

-  https://github.com/dask/distributed/issues/2660
-  https://github.com/dask/distributed/issues/2659

**Comment by mrocklin** [comment]
> Actually, this may not be ready. I thought I had sorted out the duplicate handler, but apparently not.

Can you explain this a bit more?  This seems to be the same behavior as before.  Is this correct?

**Comment by TomAugspurger** [comment]
I'm not too sure what's going on.

```python
In [1]: from distributed import Client
   ...: import logging
   ...:
   ...:
   ...: client = Client(n_workers=2, threads_per_worker=1)
   ...:
   ...: logger = logging.getLogger('distributed.nanny')
   ...: logger.handlers

Out[1]:
[<StreamHandler <stderr> (WARNING)>,
 <DequeHandler (NOTSET)>,
 <DequeHandler (NOTSET)>]
```

So if I get the `distributed.nanny` logger from my main processes, I see one handler per Nanny.

Oh... but I just realized this is the same behavior as `distributed.worker` with `processes=False`.

```python
   ...: client = Client(n_workers=2, threads_per_worker=1, processes=False)
   ...:
   ...: logger = logging.getLogger('distributed.worker')
   ...: logger.handlers
Out[2]: [<DequeHandler (NOTSET)>, <DequeHandler (NOTSET)>]
```

so perhaps we're OK?

**Comment by mrocklin** [comment]
Looks good to me.   Merging.

**Pull request merged**
