### PR TITLE
Fix regression in task stealing for already released keys

### PR DESCRIPTION
**Pull request by fjetter**
This fixes a regression introduced in #4107 

I believe this scenario can only be encountered in some race condition scenarios which is why I had a hard time constructing a test case which is less close to the implementation.

### CODE REVIEW

**Comment by gforsyth** [comment]
This fix looks correct to me -- I hadn't hit this particular edge case while working on #4107 but the `key in self.tasks` check is prevalent throughout.  The Travis failure is spurious -- if someone can restart the windows 3.6 build, I'm curious to see if that is a legitimate failure or just a bit of flakiness.

**Comment by jrbourbeau** [comment]
> if someone can restart the windows 3.6 build, I'm curious to see if that is a legitimate failure or just a bit of flakiness

I pushed an empty commit so we can still see the initial CI failure (hope that's okay @fjetter)

**Review by gforsyth — APPROVED** [review]
Great.  Looks like the windows failure was a fluke -- once this passes on Travis should be good to go in.

**Comment by fjetter** [comment]
Builds still fail and run into connection timeout errors. I'm wondering if this connects to https://github.com/dask/distributed/pull/4176 :/

**Comment by mrocklin** [comment]
Thank you for identifying and fixing this @fjetter 

> Builds still fail and run into connection timeout errors. I'm wondering if this connects to #4176 :/

In situations like these I recommend submitting a fresh PR to test CI and see if the issue repeats there.  If so, we should raise an issue, but can go ahead and merge this in.

**Comment by jrbourbeau** [comment]
There's already an issue for `test_broken_worker_during_computation` (xref https://github.com/dask/distributed/issues/4173), so I'll go ahead and merge this PR in

**Pull request merged**
