### PR TITLE
Add code coverage

### PR DESCRIPTION
**Pull request by jrbourbeau**
As title. xref https://github.com/dask/community/issues/146

### CODE REVIEW

**Review by hristog — COMMENTED** [review]
Perhaps, this could benefit from a Coverage badge, as the one in the [dask repo](https://github.com/dask/dask/blame/main/README.rst#L18-L20).

**Comment by jrbourbeau** [comment]
Yep, agreed we should add a badge in the README. There seem to be some issues with the Windows CI, so I'm going to focus on those first.

**Comment by jakirkham** [comment]
It should be possible to [collect coverage of Cython code]( https://cython.readthedocs.io/en/latest/src/tutorial/profiling_tutorial.html#enabling-coverage-analysis ). Have not had a lot of luck with it personally. So am not sure it is worth doing initially, but wanted to note this in case we are wanting to exploring that option

**Comment by jrbourbeau** [comment]
That's a fair point -- good to know. I agree it's probably okay to ignore for now and add in later in a follow-up PR if needed. I think this PR should be good to go. If you or @fjetter get a chance to review, that would be welcome : )

**Review by fjetter — APPROVED** [review]
Thanks for looking into this again. Last time I checked the tests got severely slowed down by coverage report.

This is something we should keep in mind going forward but for now I think coverage is important enough to suffer performance hits. If this becomes a problem we might want to consider to not do it for osx builds

**Review by jacobtomlinson — APPROVED** [review]
I agree this is really nice to have.

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks James! 😄 Let's get this in :shipit:

**Pull request merged**
