### PR TITLE
Attempt to fix test_preload_remote_module on windows

### PR DESCRIPTION
**Pull request by jrbourbeau**

### CODE REVIEW

**Comment by mrocklin** [comment]
Thank you for working to resolve this @jrbourbeau .  I appreciate it.

**Comment by mrocklin** [comment]
Hrm, I tried pushing the following commit to your branch but wasn't able to.  Odd.

```diff
diff --git a/distributed/cli/tests/test_dask_scheduler.py b/distributed/cli/tests/test_dask_scheduler.py
index d5c0d9c7..fc7469ec 100644
--- a/distributed/cli/tests/test_dask_scheduler.py
+++ b/distributed/cli/tests/test_dask_scheduler.py
@@ -305,6 +305,11 @@ def test_preload_remote_module(loop, tmp_path):
         f.write(PRELOAD_TEXT)
 
     with popen([sys.executable, "-m", "http.server", "9382"], cwd=tmp_path):
+        import requests
+
+        data = requests.get("http://localhost:9382/scheduler_info.py").content
+        assert b"scheduler.foo" in data
+
         with popen(
             [
                 "dask-scheduler",
```

**Comment by jrbourbeau** [comment]
GitHub appears to have updated the default setting that allows maintainers to push to other's PRs

Screen Shot 2020-05-05 at 8 32 06 PM

I've applied the diff you posted and checked the box so you should be able to push to this branch now

**Comment by mrocklin** [comment]
OK, I broke open the Windows partition.  The issue was this https://github.com/dask/distributed/issues/3777

Client.run was running before the preload had a chance to finish.  I've resolved the test short term with https://github.com/jrbourbeau/distributed/pull/1

**Comment by mrocklin** [comment]
There is a nicer solution in there now

**Comment by jrbourbeau** [comment]
Thanks for fixing this @mrocklin!

**Comment by galipremsagar** [comment]
Could this PR be merged? - Asking for other PR's which are blocked by CI failures

**Comment by galipremsagar** [comment]
Thanks @mrocklin !! 🎉

**Comment by mrocklin** [comment]
Thanks for the poke :)

**Pull request merged**
