### PR TITLE
Fix NumPy writeable serialization bug

### LINKED ISSUE #3252: cannot set WRITEABLE flag to True of this array
My colleague is seeing the following error on distirbuted 2.8.0. It looks related to #3180 and this set of lines

https://github.com/dask/distributed/blob/35551998d7350cd5ae6a5c24970d8437fd8d521d/distributed/protocol/numpy.py#L110-L114

```
distributed.worker - INFO - Start worker at: tcp://10.12.205.19:34307

distributed.worker - INFO - Listening to: tcp://10.12.205.19:34307

distributed.worker - INFO - dashboard at: 10.12.205.19:34094

distributed.worker - INFO - Waiting to connect to: tcp://128.117.181.211:37309

distributed.worker - INFO - -------------------------------------------------

distributed.worker - INFO - Threads: 1

distributed.worker - INFO - Memory: 25.00 GB

distributed.worker - INFO - Local Directory: /glade/scratch/deppenme/dask-tmp/worker-k05sxxku

distributed.worker - INFO - -------------------------------------------------

distributed.worker - INFO - Registered to: tcp://128.117.181.211:37309

distributed.worker - INFO - -------------------------------------------------

distributed.worker - ERROR - cannot set WRITEABLE flag to True of this array 

Traceback (most recent call last): File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/worker.py", line 894, in handle_scheduler comm, every_cycle=[self.ensure_communicating, self.ensure_computing] File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/core.py", line 447, in handle_stream msgs = await comm.read() File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/comm/tcp.py", line 208, in read frames, deserialize=self.deserialize, deserializers=deserializers 
File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/comm/utils.py", line 63, in from_frames res = await offload(_from_frames) File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/utils.py", line 1371, in offload return await loop.run_in_executor(_offload_executor, fn, *args, **kwargs) File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) 
File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/comm/utils.py", line 51, in _from_frames frames, deserialize=deserialize, deserializers=deserializers File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/protocol/core.py", line 124, in loads value = _deserialize(head, fs, deserializers=deserializers) 
File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 268, in deserialize return loads(header, frames) 
File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 54, in dask_loads return loads(header, frames) 
File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/protocol/numpy.py",
 line 113, in deserialize_numpy_ndarray x.setflags(write=writeable) ValueError: cannot set WRITEABLE flag to True of this array
```

This is coming out of a complicated analysis pipeline with xarray, zarr and dask so we don't have a minimal example yet. We could work to find one if you have some pointers on what to look for.

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR is intended to close #3252. Currently just adds a failing test.

### CODE REVIEW

**Comment by jrbourbeau** [comment]
@dcherian is it possible for you to try out these changes? (no problem if not)

**Comment by dcherian** [comment]
I can try tomorrow.

**Comment by dcherian** [comment]
@jrbourbeau I apologize. I won't have time to check this today unfortunately.

**Comment by jrbourbeau** [comment]
Not a problem @dcherian! I suspect we'll want these changes anyways as it fixes the example in https://github.com/dask/distributed/issues/3252#issuecomment-556434977 which worked prior to #3180, but no longer does. 

I'll plan to merge this PR later today unless there are other comments.

**Comment by TomAugspurger** [comment]
Thanks James!

**Pull request merged**
