### PR TITLE
Have worker data transfer wait until recipient acknowledges

### PR DESCRIPTION
**Pull request by mrocklin**
Previously when a worker sent data it would think it was finished as soon as the data was dumped to the socket.  Now we wait until we hear an acknowledgement from the recipient that the transfer is complete.  This helps with our diagnostics a bit *may* help avoid backing up a bunch of memory on the OS level, and also assists in future GPU work, where the sending side wants to wait until deserialization on the recipient side has finished.

### CODE REVIEW

**Comment by seibert** [comment]
This could also be useful for shared memory data exchange on the CPU (i.e. via Plasma or other mechanisms) in scenarios where having multiple worker processes on the CPU is necessary.  That's still pretty hypothetical, but the GPU use case is really a special case of shared memory communication more broadly.

**Comment by sklam** [comment]
@mrocklin, it's not clear to me how to use this with custom serialization.  My GPU dataframe serialization would send the data as a IPC handle and would need to wait for the deserializer to finish using the IPC handle.

**Comment by mrocklin** [comment]
> My GPU dataframe serialization would send the data as a IPC handle and would need to wait for the deserializer to finish using the IPC handle.

Right, all this PR does is guarantee to you that the data will stay in scope on the sender's side for as long as your deserialization code has not returned.

**Comment by mrocklin** [comment]
`human`

**Comment by mrocklin** [comment]
Is this enough for your needs @sklam ?

**Comment by sklam** [comment]
I thk so.  I will be integrating this in a branch of dask_gdf in the next few days.  The dask_gdf data transfer is my current top priority task.

**Comment by sklam** [comment]
I have success with this patch in dask_gdf.

**Pull request merged**
