### PR TITLE
Fix flaky `test_rebalance`

### LINKED ISSUE #5688: Regression: P2P shuffle skeleton (#5520) causes test flakiness
Since #5520 was merged earlier today, several tests that I never observed failing before became very flaky:

FAILED distributed/shuffle/tests/test_shuffle_extension.py::test_get_partition
FAILED distributed/shuffle/tests/test_shuffle_extension.py::test_get_partition
FAILED distributed/shuffle/tests/test_shuffle_extension.py::test_get_partition
FAILED distributed/tests/test_client.py::test_rebalance - assert 0 == 10
FAILED distributed/tests/test_client.py::test_rebalance - assert 0 == 10
FAILED distributed/tests/test_scheduler.py::test_rebalance - AssertionError: ...
FAILED distributed/tests/test_scheduler.py::test_rebalance - AssertionError: ...
FAILED distributed/tests/test_tls_functional.py::test_rebalance - assert 0 == 10

logs:
https://github.com/dask/distributed/actions/runs/1739731969
https://github.com/dask/distributed/actions/runs/1740153471
https://github.com/dask/distributed/actions/runs/1740658508

CC @gjoseph92

### PR DESCRIPTION
**Pull request by gjoseph92**
Reduce memory spikes during data transfer with `test_rebalance`, by using NumPy arrays (zero-copy) and more, smaller keys.

- [x] Closes #5688
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by gjoseph92** [comment]
@crusaderky this still failed once: https://github.com/dask/distributed/runs/4927021521?check_suite_focus=true#step:12:1626
```
>       assert 30 <= ndata[a] <= 70
E       assert 80 <= 70
```

But in stderr for that test, there's no longer anything about unmanaged memory use being high, or the worker pausing or restarting. So is it possible that the `rebalance` heuristics are just different for 100 small keys vs 10 bigger ones, and the 30-70 numbers should change? I just multiplied your original 3-7 by 10, no idea if those targets still make sense.

**Comment by gjoseph92** [comment]
Note that with https://github.com/dask/distributed/pull/5695, this may not be necessary. However, the fact that it was so sensitive to a 10mb change in worker memory means it probably should be made less sensitive anyway.

**Comment by crusaderky** [comment]
> Note that with #5695, this may not be necessary. However, the fact that it was so sensitive to a 10mb change in worker memory means it probably should be made less sensitive anyway.

Indeed. I think the whole suite requires a more intensive facelift. See #5697.

**Comment by crusaderky** [comment]
Superseded by #5697

**Pull request closed without merging**
