### PR TITLE
Support `asynchronous` option in `get_client()`

### LINKED ISSUE #6723: Support creating an asynchronous client with get_client
We would like to use `get_client()` to manage a single Client attached to a cluster. However, there doesn't seem to be a way to create a asynchronous Client during the first call to `get_client()`.

### PR DESCRIPTION
**Pull request by cjao**
Closes #6723 .

- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by cjao** [comment]
Thanks, I've added a test for the new flag.

**Comment by gjoseph92** [comment]
The fact that you could pass `get_client(..., asynchronous=True)` and still get back a synchronous client (if there's already a global client) is concerning. That's not the fault of your PR, but an inherent flaw in even the idea of global clients—as well as how asynchronous clients are implemented.

The mechanisms for getting a current client are generally a mess:
* https://github.com/dask/distributed/issues/5466
* https://github.com/dask/distributed/issues/3827
* https://github.com/dask/distributed/pull/5467#issuecomment-969611828
* https://github.com/dask/distributed/issues/5485

I appreciate this PR, and I'm curious in what situations you'd like to use it, but I guess I'm concerned about adding another option (which won't work consistently) to something that's already so fraught.

In https://github.com/dask/distributed/issues/6723 it sounds like you just want to be able to create a global asynchronous client to be shared by your code. You don't need this for getting a client within a (possibly async) task on a worker, or other complex use cases. Honestly, unless you feel like refactoring all of the `get_client` vs `default_client` vs `_current_client` logic and coming up with something consistent, I'd recommend just writing your own function to create and manage your own async global client using a ContextVar—it's very simple.

**Comment by cjao** [comment]
Thanks @gjoseph92 , I'll look into your suggestion using a ContextVar.

**Pull request closed without merging**
