### PR TITLE
Generate Cython HTML annotations

### PR DESCRIPTION
**Pull request by crusaderky**
Offer developers a simple way to generate distributed/scheduler.html

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks @crusaderky! cc @jakirkham

**Comment by jakirkham** [comment]
Makes sense to me. Should we update the Python 3.7 build to cover both of these options (since we are already doing Cython testing there)?

**Comment by crusaderky** [comment]
I don't think so? Both flags are for development only; the CI build should test what is being packaged.

**Comment by jakirkham** [comment]
For clarity, am wondering if we should add one or both of these flags here

https://github.com/dask/distributed/blob/3f86e58f729c315905d51acedd9229a1db240cf4/.github/workflows/tests.yaml#L75

**Comment by crusaderky** [comment]
All test failures are unrelated.
Is there anything outstanding here?

**Comment by jakirkham** [comment]
Any thoughts on the question above?

**Comment by crusaderky** [comment]
Both flags are exclusively for the benefit of developers. I think that the CI build should test what is being packaged, not debug/profile variants.

**Comment by crusaderky** [comment]
@jakirkham did I answer your question? Or did you want to suggest something different?

**Comment by crusaderky** [comment]
Merging - feel free to submit further PRs if you wish to refine this

**Pull request merged**
