### PR TITLE
Minor fixes to worker Prometheus endpoint

### PR DESCRIPTION
**Pull request by ntabris**
For counts (monotonically increasing), the `counter` metric type helps the consumer of metric know how to use the number.

~Also fixes what looks like copy-paste typo that meant `transfer_incoming_count` was reporting wrong value.~ (already fixed by @crusaderky in https://github.com/dask/distributed/pull/7112)

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks @ntabris. It looks like the `distributed/http/worker/tests/test_worker_http.py::test_prometheus` test failure is genuine. It looks like the expected metric names are hardcoded -- updating there should fix things. 

cc @fjetter

**Comment by fjetter** [comment]
I'm OK with the changes but there are merge conflicts and CI complains

**Comment by ntabris** [comment]
> It looks like the expected metric names are hardcoded -- updating there should fix things.

Turns out that by changing metric from gauge to count the metrics got classified under a different family.

I've changed the test so it checks against sample names rather than family names, since I think we still want to make sure that the `dask_worker_transfer_incoming_count_total` and `dask_worker_transfer_outgoing_count_total` metrics are exposed.

**Comment by ntabris** [comment]
@fjetter checks are now green, though note I've modified one of the tests (I think for the better).

**Review by hendrikmakait — APPROVED** [review]
LGTM, thanks @ntabris!

**Review by crusaderky — APPROVED** [review]

**Pull request merged**
