### PR TITLE
Expand ~ in SSL certificate paths.

### PR DESCRIPTION
**Pull request by marberi**
Expand "~" in the SSL certificate paths. This simplifies a multi-user configuration where each user have SSL certificates generated in their respective home directory.

- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by marberi** [comment]
We are using dask-labextension and can therefore not use the temporary in-memory security mechanism.

**Review by jrbourbeau — COMMENTED** [review]
Thanks @marberi. This seems sensible to me. Could you please add a test to `distributed/tests/test_security.py`? for this behavior.

**Comment by marberi** [comment]
@jrbourbeau Made a fix and added a tests. The place I originally changed only affected the output in the representation.  And then there were some other issues. By now the github is not showing the logs, so I will continue with this tomorrow.

ps. Did you overlap with Gonzalo Merino in Madison? He was in Icecube before moving to BCN

**Comment by marberi** [comment]
By now I have fixed the code and added a test. The failure seen does not seem to be directly related to this pull request and changes each time when rerunning. All the commits in this pull request should be merged into one. How do you normally handle that? I create a new commit and force an update in this branch or its handled automatically? Please let me know if I should do something more to get this change accepted.

**Comment by marberi** [comment]
Looking at [https://github.com/dask/distributed/pull/7533](url), I realized the more general form is using substitution with environment variables. Would this be preferred?

**Comment by marberi** [comment]
Implemented the Python string formatting instead of only replacing "~" in another pull request. Closing this one.

**Pull request closed without merging**
