### PR TITLE
Add nprocs auto option to dask-worker CLI

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Partly solves #4373

I've moved `nprocesses_nthreads` from `distributed.deploy.local` into `distributed.deploy.utils` and then am making use of it in `distributed.cli.dask_worker`.

Setting `nprocs` to `auto` when starting a worker will now have the same behaviour as `LocalCluster` in terms of the number of processes and threads created.

```
dask-worker tcp://localhost:8786 --nprocs=auto
```

### CODE REVIEW

**Comment by quasiben** [comment]
Kicked CI

**Comment by jacobtomlinson** [comment]
Thanks @quasiben. Looks like it was my fault, new test filename wasn't unique.

**Review by jrbourbeau — COMMENTED** [review]
Just merged the main branch to resolve some unrelated CI failures

**Review by jrbourbeau — COMMENTED** [review]
Thanks @jacobtomlinson! This is a nice addition. Could you add a test that checks when using `--nprocs auto` the expected number of workers with the expected number of threads are created? Something similar to `distributed/cli/tests/test_dask_worker.py::test_nprocs_negative` should work here too

**Comment by jacobtomlinson** [comment]
Thanks for the feedback @jrbourbeau. Added a test.

**Review by jrbourbeau — APPROVED** [review]
Thanks @jacobtomlinson! This LGTM, will merge after CI finishes

**Pull request merged**
