### PR TITLE
Add pytest marker for GPU tests

### LINKED ISSUE #5015: Add pytest marker for GPU tests
It came up in the monthly community meeting that we should add a `gpu` pytest marker to certain test modules / individual tests which run on GPUs. This will allow us to select only GPU-related tests when running the test suite on machines with GPUs in CI (xref https://github.com/dask/distributed/pull/5011) 

cc @charlesbluca @quasiben @aktech

### PR DESCRIPTION
**Pull request by charlesbluca**
In preparation for #5011, adds `pytest` marker `gpu` to mark the subset of the testing suite we would like running on GPUs.

- [ ] Closes #5015
- [ ] Tests added / passed
- [ ] Passes `black distributed` / `flake8 distributed` / `isort distributed`

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Nice! Thanks @charlesbluca

cc'ing @quasiben @pentschev for thoughts on other tests / modules which should be marked with `gpu`

**Comment by pentschev** [comment]
We can mark `test_nanny.py` as discussed in https://github.com/dask/distributed/issues/5015#issuecomment-873084154 , and not technically a GPU test but it would be great to have UCX tested, although this could be left for a future iteration as it would require also installing UCX.

Finally, we should do the same on the Dask main repo and test CuPy and cuDF tests there. IMO those are even more important to be tested.

**Comment by charlesbluca** [comment]
Good point - I'll open up a PR for Dask main too.

**Comment by aktech** [comment]
Here is the run of GPU tests based on the tags added in this PR so far (all green): https://github.com/aktech/distributed/runs/2999891454?check_suite_focus=true

**Comment by charlesbluca** [comment]
Thanks @aktech! Also opened a corresponding PR in mainline dask/dask#7876

**Comment by aktech** [comment]
> Thanks @aktech! Also opened a corresponding PR in mainline dask/dask#7876

Awesome! Is this one good to come out of draft?

**Review by jrbourbeau — APPROVED** [review]
Thanks @charlesbluca! Will merge after CI finishes up

**Pull request merged**
