### PR TITLE
Make sphinx autosummary and autoclass consistent (#3693)

### PR DESCRIPTION
**Pull request by caseyclements**
It turns out there's a solution floating about. This updates conf.py and api.rst.

See https://www.programcreek.com/python/example/122651/sphinx.ext.autosummary.get_documenter
and https://stackoverflow.com/questions/20569011/python-sphinx-autosummary-automated-listing-of-member-functions

### CODE REVIEW

**Comment by caseyclements** [comment]
Hi. Two checks failing. 

The pre-commit checks are formatting and string preferences. The output suggests changes. I'm not familiar with this functionality yet. Does it create a branch or local copy with which one can commit the suggestions?

The travis builds appear to be unrelated to docs. Timeout failures.

**Comment by gforsyth** [comment]
Hey @caseyclements, thanks for putting this in! You can run the formatting checks locally by installing `pre-commit` and then running `pre-commit install --install-hooks` inside your local clone of `distributed`.

You can run `pre-commit run --all-files` to see what it's complaining about (in this case, it looks like `black` needs to be run to autoformat, and there's an unused import of `re` and a bare `except`)

I agree that the travis failures are unrelated.

**Comment by gforsyth** [comment]
Thanks for pushing up those fixes @caseyclements !  The test failures look to be upstream issues with `dask`, unrelated to your doc fixes here.

**Comment by caseyclements** [comment]
Thanks, @gforsyth. Have we met? Hudson Valley? I was with Continuum, living in NYC until this time two years ago.

What's the next step with this PR? Do we need to wait for a clean build? I imagine. I'm just keen to get it done by EOW as there's a prize involved. :)

**Comment by caseyclements** [comment]
Were you one of a bunch of the people that I dragged down for a slice of Joe's pizza near West 4th one night after a conference?

**Comment by gforsyth** [comment]
> Thanks, @gforsyth. Have we met? Hudson Valley? I was with Continuum, living in NYC until this time two years ago.

We might've just missed each other -- I moved back to the NY area from DC this time two years ago :grin:

So the failures are due to unrelated upstream issues, so I think this is good to go in.  Thanks for putting it together!

Also, I see that this is your first contribution to `distributed`.  Welcome!

**Review by gforsyth — APPROVED** [review]
This is good to go in @dask/maintenance (test failures are due to the BlockwiseIO serialization stuff).

I've built the docs locally off this branch and they look good.

**Comment by caseyclements** [comment]
Thanks for the engagement, @gforsyth! Once it gets merged, who marks the issue as closed?
Next time I'm upstate, I'll let you know.

**Comment by caseyclements** [comment]
Hi @gforsyth . Just checking in on this.

**Comment by gforsyth** [comment]
Hey @caseyclements -- sorry this got lost at YE.  Can you merge from master to update CI?

**Comment by caseyclements** [comment]
@gforsyth Good to go

**Review by gforsyth — APPROVED** [review]
Thanks again for putting this in @caseyclements !

@dask/maintenance this is good to go in.

**Pull request merged**
