### PR TITLE
Add to FAQ section about how to get workers to import right

### PR DESCRIPTION
**Pull request by martindurant**
Fixes https://github.com/dask/dask/issues/6702

This section may now be too long to fit int he FAQ.

### CODE REVIEW

**Comment by martindurant** [comment]
By the way, does [skip ci] still work for docs-only PRs?

**Comment by quasiben** [comment]
Do you think we should also mention the [PipInstall plugin](https://github.com/dask/distributed/pull/3216/) as a temporary solution ?

**Comment by martindurant** [comment]
> we should also mention the PipInstall plugin

Probably - I had missed that. I did *not* want to say "do `client.run(subprocess.call())`. Nice to see considerations of restarts. However, the plugin isn't mentioned in any docs (yet).

**Comment by mrocklin** [comment]
distributed.dask.org gets far less traffic than docs.dask.org 

I wonder if this would be better suited as a new deployment best practices page on docs.dask.org

**Comment by martindurant** [comment]
@mrocklin , that being the case, we should consider more information that might be more visible if moved; but not in this PR...

**Comment by mrocklin** [comment]
Yeah, I don't have strong thoughts on what goes into this FAQ file.  My preference in the future is to remove it.  (I think that FAQs should be fairly comprehensive or else not exist).  If your goal is to solve an education problem then I don't think that editing docs here will do a ton of good.  I think that starting a best practices doc in dask/dask would have high value but yes, I agree that this isn't necessary.

**Comment by mrocklin** [comment]
Should we still consider merging this, or are we relying on the dask/dask PR?

**Comment by martindurant** [comment]
I think the one on dask/dask is better, and is marked as closing this one. But I'll close this now anyway.

**Comment by mrocklin** [comment]
Thanks for both Martin!

**Pull request closed without merging**
