### PR TITLE
Include total number of tasks in the performance report

### LINKED ISSUE #3753: [FEA] Include total number of tasks in the performance report summary
Dask performance reports can be invaluable when profiling complex workloads. When evaluating multiple workloads at once, it can be difficult to remember the size of the task graphs in each workload. Including the total number of tasks in the Summary tab of the performance report would be a nice addition, perhaps under the Duration section.

### PR DESCRIPTION
**Pull request by abduhbm**
This PR tries to close #3753
Still not sure if this is a correct approach, please let me know if more work is needed. 

Screen Shot 2020-05-22 at 4 24 51 AM

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @beckernick

**Comment by quasiben** [comment]
I think this resolves the stated issue but I am wondering if this useful generally ? Perhaps instead we want a summary breakdown of how tasks spent their time.  Similar to https://github.com/dask/distributed/issues/3745 you could print out timings of various tasks actions: compute, transfer, disk-read, serialization, etc.

**Comment by abduhbm** [comment]
Thanks @quasiben for your comment. 
Timings of tasks actions and total number of tasks are now printed out in the performance report under Tasks Information header. 

Screen Shot 2020-05-22 at 8 59 18 PM

**Comment by quasiben** [comment]
Sorry for the delay here @abduhbm .  Thanks for doing this!  Merging in

**Pull request merged**
