### PR TITLE
Drop support for zict 2.1.0

### PR DESCRIPTION
**Pull request by crusaderky**

### CODE REVIEW

**Review by hendrikmakait — COMMENTED** [review]
The code looks good to me, I'm mildy concerned by the number of failing tests on the CI, though I don't see how they'd be related. I've re-triggered CI without caches to see if the errors persist.

**Review by hendrikmakait — APPROVED** [review]
Thanks @crusaderky!

**Review by jrbourbeau — COMMENTED** [review]
Thanks @crusaderky. Why was this change made? It looks like this PR was opened up without a description or referencing a issue / discussions somewhere. To be clear, I don't object to the actual changes here, but having some sense for what's motivating them is useful

**Comment by crusaderky** [comment]
Discussion here: https://github.com/dask/distributed/issues/4424#issuecomment-1490236795

**Pull request merged**
