### PR TITLE
fixed publist_delete : publish_delete typo in client.py

### PR DESCRIPTION
**Pull request by bschreck**
Fixes typo #782 that prevents using Client.unpublish_dataset()

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks for the correction @bschreck .

It's a bit concerning that this didn't come up during tests.  I guess we only tested the asynchronous versions of these functions.  Do you have any interest in also submitting a small test that exercises this fix to make sure that something like this doesn't occur in the future?

**Comment by bschreck** [comment]
Sure I'll put 1 or 2 in now. By the way, it looks like there are several testing dependencies not in requirements.txt. Would it make sense to have a dev-requirements.txt with Mock, pandas, joblib, etc?

**Comment by mrocklin** [comment]
Adding dev-requirements sounds sensible to me

**Comment by mrocklin** [comment]
This looks great to me.  Thank you for your work.

Looks like there was an unrelated testing failure.  I've restarted the test and will investigate separately.

**Pull request merged**
