### PR TITLE
NO MRG: Test serializing/deserializing dask arrays

### PR DESCRIPTION
**Pull request by jakirkham**
This is here simply to test serializing/deserializing of dask arrays. Hopefully should be helpful debugging issue ( https://github.com/dask/dask/issues/1777 ). Possibly the tests can be merged in the future to protect against similar problems.

cc @mrocklin

### CODE REVIEW

**Comment by mrocklin** [comment]
Serialize/deserialize are not intended to be used in this way.  If you'd like to produce a failure I recommend limiting yourself to the Client public API.

**Comment by jakirkham** [comment]
Perhaps so. Doing this seems to reproduce this [failure]( https://github.com/dask/dask/issues/1777#issuecomment-260376331 ) identically, which suggest that serialization/deserialization is proceeding this way under the hood..

**Comment by jakirkham** [comment]
Perhaps so. However, doing this seems to reproduce this [failure]( https://github.com/dask/dask/issues/1777#issuecomment-260376331 ) identically, which suggest that serialization/deserialization is proceeding this way under the hood.

**Comment by jakirkham** [comment]
So I can see the error locally, but it is being suppressed by the test suite somehow. Note multiple tracebacks showing the error seen before.

```python
distributed/protocol/tests/test_h5py.py::test_serialize_deserialize_dask <- distributed/utils_test.py distributed.scheduler - INFO -   Scheduler at:            127.0.0.1:45062
distributed.worker - INFO -       Start worker at:            127.0.0.1:45295
distributed.worker - INFO - Waiting to connect to:            127.0.0.1:45062
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    5.02 GB
distributed.worker - INFO -       Local Directory:         /tmp/worker-wQ_Zwb
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Start worker at:            127.0.0.1:40946
distributed.worker - INFO - Waiting to connect to:            127.0.0.1:45062
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          2
distributed.worker - INFO -                Memory:                    5.02 GB
distributed.worker - INFO -       Local Directory:         /tmp/worker-GSh7r6
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Connection from 127.0.0.1:60104 to Scheduler
distributed.core - INFO - Connection from 127.0.0.1:60106 to Scheduler
distributed.scheduler - INFO - Register 127.0.0.1:45295
distributed.scheduler - INFO - Register 127.0.0.1:40946
distributed.core - INFO - Connection from 127.0.0.1:40814 to Worker
distributed.core - INFO - Connection from 127.0.0.1:55802 to Worker
distributed.worker - INFO -         Registered to:            127.0.0.1:45062
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:            127.0.0.1:45062
distributed.worker - INFO - -------------------------------------------------
distributed.scheduler - INFO - Starting worker compute stream, 127.0.0.1:45295
distributed.scheduler - INFO - Starting worker compute stream, 127.0.0.1:40946
distributed.core - INFO - Connection from 127.0.0.1:60112 to Scheduler
distributed.core - INFO - Connection from 127.0.0.1:60114 to Scheduler
distributed.scheduler - INFO - Receive client connection: 4b89a6f8-aaad-11e6-a2b4-179361712552
Exception KeyError: KeyError(139776199108512,) in 'h5py._objects.ObjectID.__dealloc__' ignored
CRITICAL:/distributed/distributed/protocol/core.pyc:Failed to deerialize
Traceback (most recent call last):
  File "/distributed/distributed/protocol/core.py", line 112, in loads
    value = _deserialize(head, fs)
  File "/distributed/distributed/protocol/serialize.py", line 125, in deserialize
    return f(header, frames)
  File "/distributed/distributed/protocol/serialize.py", line 12, in <lambda>
    deserializers = {None: lambda header, frames: pickle.loads(b''.join(frames))}
  File "/distributed/distributed/protocol/pickle.py", line 51, in loads
    return pickle.loads(x)
  File "/opt/conda/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/opt/conda/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/opt/conda/lib/python2.7/pickle.py", line 1089, in load_newobj
    obj = cls.__new__(cls, *args)
  File "h5py/_objects.pyx", line 178, in h5py._objects.ObjectID.__cinit__ (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:4203)
TypeError: __cinit__() takes exactly 1 positional argument (0 given)
distributed.utils - ERROR - __cinit__() takes exactly 1 positional argument (0 given)
Traceback (most recent call last):
  File "/distributed/distributed/utils.py", line 228, in log_errors
    yield
  File "/distributed/distributed/worker.py", line 471, in compute_stream
    msgs = yield read(stream)
  File "/opt/conda/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/opt/conda/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/opt/conda/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/distributed/distributed/core.py", line 217, in read
    msg = protocol.loads(frames, deserialize=deserialize)
  File "/distributed/distributed/protocol/core.py", line 112, in loads
    value = _deserialize(head, fs)
  File "/distributed/distributed/protocol/serialize.py", line 125, in deserialize
    return f(header, frames)
  File "/distributed/distributed/protocol/serialize.py", line 12, in <lambda>
    deserializers = {None: lambda header, frames: pickle.loads(b''.join(frames))}
  File "/distributed/distributed/protocol/pickle.py", line 51, in loads
    return pickle.loads(x)
  File "/opt/conda/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/opt/conda/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/opt/conda/lib/python2.7/pickle.py", line 1089, in load_newobj
    obj = cls.__new__(cls, *args)
  File "h5py/_objects.pyx", line 178, in h5py._objects.ObjectID.__cinit__ (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:4203)
TypeError: __cinit__() takes exactly 1 positional argument (0 given)
distributed.core - ERROR - __cinit__() takes exactly 1 positional argument (0 given)
Traceback (most recent call last):
  File "/distributed/distributed/core.py", line 172, in handle_stream
    result = yield gen.maybe_future(handler(stream, **msg))
  File "/opt/conda/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/opt/conda/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/opt/conda/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/distributed/distributed/worker.py", line 471, in compute_stream
    msgs = yield read(stream)
  File "/opt/conda/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/opt/conda/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/opt/conda/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/distributed/distributed/core.py", line 217, in read
    msg = protocol.loads(frames, deserialize=deserialize)
  File "/distributed/distributed/protocol/core.py", line 112, in loads
    value = _deserialize(head, fs)
  File "/distributed/distributed/protocol/serialize.py", line 125, in deserialize
    return f(header, frames)
  File "/distributed/distributed/protocol/serialize.py", line 12, in <lambda>
    deserializers = {None: lambda header, frames: pickle.loads(b''.join(frames))}
  File "/distributed/distributed/protocol/pickle.py", line 51, in loads
    return pickle.loads(x)
  File "/opt/conda/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/opt/conda/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/opt/conda/lib/python2.7/pickle.py", line 1089, in load_newobj
    obj = cls.__new__(cls, *args)
  File "h5py/_objects.pyx", line 178, in h5py._objects.ObjectID.__cinit__ (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:4203)
TypeError: __cinit__() takes exactly 1 positional argument (0 given)
distributed.scheduler - INFO - Remove client 4b89a6f8-aaad-11e6-a2b4-179361712552
distributed.scheduler - ERROR - 'key'
Traceback (most recent call last):
  File "/distributed/distributed/scheduler.py", line 1114, in worker_stream
    key = msg['key']
KeyError: 'key'
distributed.scheduler - INFO - Remove worker 127.0.0.1:45295
distributed.scheduler - INFO - Close client connection: 4b89a6f8-aaad-11e6-a2b4-179361712552
distributed.core - INFO - Lost connection: ('127.0.0.1', 60112)
distributed.core - INFO - Close connection from 127.0.0.1:60112 to Scheduler
distributed.core - INFO - Lost connection: ('127.0.0.1', 40814)
distributed.core - INFO - Close connection from 127.0.0.1:40814 to Worker
distributed.core - INFO - Lost connection: ('127.0.0.1', 60114)
distributed.core - INFO - Close connection from 127.0.0.1:60114 to Scheduler
distributed.scheduler - INFO - Remove client None
distributed.scheduler - INFO - Worker failed from closed stream: 127.0.0.1:40946
distributed.scheduler - INFO - Remove worker 127.0.0.1:40946
distributed.scheduler - INFO - Lost all workers
distributed.core - INFO - Lost connection: ('127.0.0.1', 60104)
distributed.core - INFO - Close connection from 127.0.0.1:60104 to Scheduler
distributed.core - INFO - Lost connection: ('127.0.0.1', 60106)
distributed.core - INFO - Close connection from 127.0.0.1:60106 to Scheduler
distributed.worker - INFO - Close compute stream
distributed.core - INFO - Lost connection: ('127.0.0.1', 55802)
distributed.core - INFO - Close connection from 127.0.0.1:55802 to Worker
PASSED
```

**Comment by mrocklin** [comment]
Yeah so h5py objects aren't serializable by pickle.  Ideally they should never read a call to pickle.dumps.  I'm not sure why they're getting there.  This would happen if they were part of a complex task rather than just a bare value in a task graph.

Unfortunately I don't have a huge amount of time to devote to this at the moment.  I suspect that you'll have a better time if you let this sit for a week.

**Comment by jakirkham** [comment]
> Yeah so h5py objects aren't serializable by pickle.

Right.

> Ideally they should never read a call to pickle.dumps. I'm not sure why they're getting there.

Me neither. FWICT everything looks ok, but obviously something is not ok. Just can't see it yet.

> This would happen if they were part of a complex task rather than just a bare value in a task graph.

Right, trying to see if all of these cases in issue ( https://github.com/dask/dask/issues/1777 ) are related somehow.

> Unfortunately I don't have a huge amount of time to devote to this at the moment.

That's fine.

> I suspect that you'll have a better time if you let this sit for a week.

Yeah, I was feeling a bit ambitious and wanted to push on this functionality a bit. Am not too surprised that there would be a few kinks to work out. Was hoping to leave a couple reproducers as tests, but that appears to be a bit tricky right now.

In any event, have some other things I need to do near term. So will come back to this later.

**Comment by mrocklin** [comment]
Reproducible tests are, as you're well aware, the best thing since sliced bread.  It's tricky to know how the internal API works at the moment though because there isn't any developer documentation about it.  The most productive kind of test you can write is something that uses the `gen_cluster` testing harness as you're doing now, and strictly uses the client API.

**Comment by jakirkham** [comment]
Tried in the last commit. Not sure why the `TypeError` is getting suppressed instead of being converted to an error or failure for the test. In any event, this does seem to demonstrate the problem.

**Comment by mrocklin** [comment]
Closing as stale.

**Comment by jakirkham** [comment]
So the main point of this was to demonstrate issue ( https://github.com/dask/dask/issues/1777 ), which it does. Not entirely sure why it is being closed then. 😕

**Comment by mrocklin** [comment]
I was closing PRs that seem to be lingering for a long time without change.  Not sure where to put things like this.  I guess we'll keep it open for now.

**Comment by mrocklin** [comment]
This PR has gone stale.  Closing for now.

**Pull request closed without merging**
