### PR TITLE
Copyediting typos + `codespell` `pre-commit` hook for docs

### PR DESCRIPTION
**Pull request by mplough-kobold**
This is a more thorough follow-up of #7281.

I used [codespell](https://github.com/codespell-project/codespell) to look for typos and manually reviewed what it found, with a bias towards leaving things alone.  I was very careful to let stand existing UK/US English spelling variations as well as common spelling variations (e.g. "unparseable" / "unparsable").  

Pretty much all of the changes lie in documentation files, docstrings, comments, or message strings.  The only change directly affecting executable code lies in `distributed/deploy/tests/test_adaptive.py`.  A keyword argument was misspelled.  I don't believe this will affect test coverage or execution as the asserts are not related to the spelling of the kwarg.
```
-        first = cluster.adapt(maxmimum=1)
-        second = cluster.adapt(maxmimum=2)
+        first = cluster.adapt(maximum=1)
+        second = cluster.adapt(maximum=2)
```

After discussion with @jrbourbeau I also configured codespell to run on docs, similar to how it's set up in `dask/dask`.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Review by jrbourbeau — COMMENTED** [review]
Thanks @mplough-kobold! Over in `dask/dask` we [use `codespell` as a pre-commit hook on `.md` and `.rst` files](https://github.com/dask/dask/blob/bfe07f63967494a5cfcfafbb2a6b5271a6714dcc/.pre-commit-config.yaml#L40-L45) -- would doing the same here turn up a bunch of errors? If not, it would be a good way to catch typos in our docs moving forward

**Comment by mplough-kobold** [comment]
I was reluctant to submit a pre-commit hook PR as I wasn't sure what the appetite would be for using automated tools for spell checking.  It's great to hear that the precedent is there over in `dask/dask`.  I'll take a look at how the hook is set up over there and how ignores are configured.  Shouldn't me take too long to get it set up here.

**Comment by jrbourbeau** [comment]
That makes sense. I personally (and I suspect other too) would be in favor of something lightweight like `codespell`. FWIW I do think it's worth restricting to docs only as I recall `codespell` not liking what it thoughts were misspellings in Python variable names. Also, this PR looks good to go, if you'd prefer I'm happy to merge this in and `pre-commit`-related things can be handled in a follow-up PR

**Comment by mplough-kobold** [comment]
Wow, codespell setup was easy.  Codespell does find some errors in rst docs right now.  Prior to this PR, codespell says:

```
codespell................................................................Failed
- hook id: codespell
- exit code: 65

docs/source/scheduling-state.rst:324: happend ==> happened, happens, happen
docs/source/resources.rst:62: specifed ==> specified
docs/source/actors.rst:127: curently ==> currently
docs/source/scheduling-policies.rst:101: bandwith ==> bandwidth
```

This PR fixes all the errors and sets up codespell as it's configured in `dask/dask`.

I do agree that now is not a good time to set up codespell on Python code itself.  It can end up spitting out a lot of annoying false positives.

**Review by jrbourbeau — APPROVED** [review]
Thanks @mplough-kobold! This looks great 

@fjetter @crusaderky I'm going to move ahead with add `codespell` as a pre-commit hook because I view it as not-so-controversial. Let me know if you have reservations and we can iterate as needed.

**Pull request merged**
