### PR TITLE
Add bokeh `mode` parameter to performance reports

### PR DESCRIPTION
**Pull request by jrbourbeau**
- [ ] Closes https://github.com/dask/distributed/issues/4999
- [ ] Tests added / passed
- [ ] Passes `black distributed` / `flake8 distributed` / `isort distributed`

cc @jsignell @max-sixty

### CODE REVIEW

**Comment by max-sixty** [comment]
Thanks a lot @jrbourbeau !

**Comment by mrocklin** [comment]
What is the resulting size increase here?  In the issue I think you mentioned 1MB.  If so, maybe we should consider what default to use here?

**Comment by jrbourbeau** [comment]
Just pushed a commit which let's the user choose which value for `mode` they would like to use. By default we will use `mode=None`, which is the current default on `main`

**Review by jsignell — APPROVED** [review]
This looks great! I assume the test failures are unrelated?

**Comment by jrbourbeau** [comment]
Yeah, the CI failures here are unrelated. Thanks for reviewing all!

**Pull request merged**
