### PR TITLE
Add a pytest plugin to test for resource leaks

### PR DESCRIPTION
**Pull request by pitrou**
This adds an option to `py.test` to test for resource leaks after each test. For example `py.test --leaks=all` (or `py.test -L all` in short). There's also a `pytest.mark.leaking` decorator to control which tests are known as leaking which resources.

This should supersede PR #1485 (edit: not entirely, as the `wait` flag changes are still relevant).

### CODE REVIEW

**Comment by pitrou** [comment]
Example output:
```
$ py.test --leaks=all --tb=native distributed/tests/test_core.py 
========================= test session starts ==========================
platform linux -- Python 3.6.3, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: /home/antoine/distributed, inifile:
plugins: xdist-1.20.1, timeout-1.2.0, repeat-0.4.1, forked-0.2, faulthandler-1.3.1
collected 26 items                                                      

distributed/tests/test_core.py .L.............s...........

============================ RESOURCE LEAKS ============================
distributed/tests/test_core.py::test_server leaked 10 MB of RSS memory
============ 25 passed, 1 skipped, 1 leaked in 3.95 seconds ============
```

**Comment by pitrou** [comment]
@mrocklin

**Comment by pitrou** [comment]
Update: I added support for retries. When a test leaks, it is retried a number of times (default 1) to try to weed out warmup issues. Effect:
```
$ py.test -v --leaks=all distributed/tests/test_utils.py::test_is_kernel
============================ test session starts =============================
platform linux -- Python 3.6.3, pytest-3.2.3, py-1.4.34, pluggy-0.4.0 -- /home/antoine/miniconda3/envs/dask36/bin/python
cachedir: .cache
rootdir: /home/antoine/distributed, inifile:
plugins: xdist-1.20.1, timeout-1.2.0, repeat-0.4.1, forked-0.2, faulthandler-1.3.1
collected 1 item                                                              

distributed/tests/test_utils.py::test_is_kernel PASSED

========================== 1 passed in 1.05 seconds ==========================
```

If disabled:
```
$ py.test -v --leaks=all --leak-retries=0 distributed/tests/test_utils.py::test_is_kernel
============================ test session starts =============================
platform linux -- Python 3.6.3, pytest-3.2.3, py-1.4.34, pluggy-0.4.0 -- /home/antoine/miniconda3/envs/dask36/bin/python
cachedir: .cache
rootdir: /home/antoine/distributed, inifile:
plugins: xdist-1.20.1, timeout-1.2.0, repeat-0.4.1, forked-0.2, faulthandler-1.3.1
collected 1 item                                                              

distributed/tests/test_utils.py::test_is_kernel PASSED
distributed/tests/test_utils.py::test_is_kernel LEAKED

=============================== RESOURCE LEAKS ===============================
distributed/tests/test_utils.py::test_is_kernel leaked 1 file descriptor(s)
distributed/tests/test_utils.py::test_is_kernel leaked 19 MB of RSS memory
===================== 1 passed, 1 leaked in 1.05 seconds =====================
```

**Comment by pitrou** [comment]
It seems some of our tests hang when restarted...

**Comment by pitrou** [comment]
I think I managed to solve the fixture bug now.

**Comment by mrocklin** [comment]
In general this seems very nice and much cleaner than our previous solution.  It seems like it does a good job reducing the costs of the tests as well.  I probably won't have an opportunity to investigate the implementation in detail.  If you feel confident in the solution then I suggest that you merge.  Otherwise I should hopefully have some time to review on Friday.

**Comment by pitrou** [comment]
I think the implementation is ok now. Since you have to pass a flag to enable leak checking, this isn't enabled by default on our CI.

**Pull request merged**
