### PR TITLE
fix typo in comment

### PR DESCRIPTION
**Pull request by ibebrett**
Noticed a typo when reading the worker code, thought it was a good way to start contributing.

### CODE REVIEW

**Comment by ibebrett** [comment]
The build is failing, but due to something completely unrelated (this is only a comment). What is the best next steps here? Wait for master to be green? Or merge anyway?

**Comment by mrocklin** [comment]
The errors are, indeed, unrelated.  I'll take a look at them.  Thanks for the typo fix @ibebrett !

**Comment by jakirkham** [comment]
Is there already an issue tracking these errors somewhere?

**Comment by mrocklin** [comment]
Nominally https://github.com/dask/distributed/issues/966 , though I'll admit that I don't update it all the time.

**Pull request merged**
