### PR TITLE
Executor clean context close

### PR DESCRIPTION
**Pull request by mrocklin**
Clean up Executor's handling of the IOLoop and thread

cc @sklam

### CODE REVIEW

**Comment by sklam** [comment]
This fixed the issue in my scripts

**Comment by mrocklin** [comment]
Excellent.  Merging on passed tests.

**Comment by sklam** [comment]
With this script and the post-merged master (a9c73fb0ded7578e4498ff087a9e8f25a48d63e2):

```python
import time
import random
from functools import reduce
from distributed import Executor
from dask.imperative import value, do


def load(x):
    print('load', x)
    time.sleep(1)
    return x

with Executor('10.10.10.209:8786') as e:
    # e = Executor('10.10.10.209:8786')
    loaded = e.compute(list(map(do(load), range(5))))
    print(loaded)
    for i in range(5):
        print('round', i)
        computed = map(do(int), loaded)
        result = reduce(do(lambda x, y: x + y), computed)
        print('result', e.compute(result).result())
        random.shuffle(loaded)
    print("Point A")
print("Point B")
```

I am now occasionally and randomly seeing the one of the following error between "Point A" and "Point B" in different runs:

Error 1
```
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/Users/sklam/dev/gtc2016/.conda.workspace/devel34/lib/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/Users/sklam/dev/gtc2016/.conda.workspace/devel34/lib/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sklam/dev/gtc2016/.conda.workspace/devel34/lib/python3.4/site-packages/tornado/ioloop.py", line 826, in start
    for callback in callbacks:
TypeError: 'NoneType' object is not iterable
```

Error 2
```
distributed.executor - INFO - Stream closed to scheduler
Traceback (most recent call last):
  File "/Users/sklam/dev/gtc2016/.conda.workspace/devel34/lib/python3.4/site-packages/distributed-1.8.1-py3.4.egg/distributed/executor.py", line 376, in _handle_report
    msg = yield next_message()
  File "/Users/sklam/dev/gtc2016/.conda.workspace/devel34/lib/python3.4/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/sklam/dev/gtc2016/.conda.workspace/devel34/lib/python3.4/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/sklam/dev/gtc2016/.conda.workspace/devel34/lib/python3.4/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/sklam/dev/gtc2016/.conda.workspace/devel34/lib/python3.4/site-packages/distributed-1.8.1-py3.4.egg/distributed/core.py", line 204, in read
    msg = yield stream.read_until(sentinel)
  File "/Users/sklam/dev/gtc2016/.conda.workspace/devel34/lib/python3.4/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/sklam/dev/gtc2016/.conda.workspace/devel34/lib/python3.4/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
tornado.iostream.StreamClosedError: Stream is closed
```

Nothing appeared in the dworker and dscheduler.  The error message seems to be ignored and does not interfere with the execution.

**Comment by mrocklin** [comment]
OK, it looks like we're not closing things down in a thread-safe manner.  I'll take a look at this in a bit.

**Comment by mrocklin** [comment]
@sklam this may have been resolved in https://github.com/dask/distributed/commit/bbda807a18c2e24dbc76f4902ce1c43f656e0093

**Comment by sklam** [comment]
Fix confirmed. Thanks!

**Pull request merged**
