### PR TITLE
Fix inconsistent hashing for Nanny-spawned workers

### PR DESCRIPTION
**Pull request by cisaacstern**
Towards #4141

- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

This PR implements @mrocklin's suggestion in https://github.com/dask/distributed/issues/4141#issuecomment-702808530 to replicate https://github.com/dask/dask/pull/6660, but for Nanny-spawned workers. As noted there, this is not a complete solution for #4141, as the Nanny is not required for spawning workers, but nonetheless should unblock a large percentage of uses cases currently blocked by #4141.

First commit is just a failing test, will push the fix momentarily.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by fjetter** [comment]
There is one related test failure in `distributed/tests/test_nanny.py::test_environment_variable_pre_post_spawn` which h ard codes what variables we set in the pre spawn config

You're also affected by https://github.com/dask/distributed/issues/8397

Otherwise this LGTM. If you can adjust the failing test we can merge

**Comment by cisaacstern** [comment]
Thanks so much for the prompt review @fjetter! The last commit fixes the broken test.

**Review by jacobtomlinson — APPROVED** [review]
Thanks for fixing up the tests @cisaacstern. Failures we see now look unrelated tot his change.

**Comment by cisaacstern** [comment]
Thanks @jacobtomlinson and @fjetter !

**Pull request merged**
