### PR TITLE
Issue #1477: Use IOStream.read_into() when available

### PR DESCRIPTION
**Pull request by pitrou**
The API is proposed in https://github.com/tornadoweb/tornado/pull/2193 and allows zero-copy reads of distributed protocol frames.

### CODE REVIEW

**Comment by pitrou** [comment]
@mrocklin, this may interest you if you are into benchmarking :-)

**Comment by mrocklin** [comment]
Just as a reference this PR brings us up to about 2x the bandwidth when compared to 4.5.2 (as recorded in https://github.com/pangeo-data/pangeo/issues/6)

**Comment by pitrou** [comment]
Note this PR is WIP because the required Tornado patch hasn't been merged upstream.

**Comment by pitrou** [comment]
The Tornado API addition was merged in https://github.com/tornadoweb/tornado/pull/2251

**Comment by mrocklin** [comment]
Merging.  Thanks @pitrou !

**Pull request merged**
