### PR TITLE
Downgrade exception to warning when reusing port

### PR DESCRIPTION
**Pull request by mrocklin**
cc @stsievert can you give this PR a try and see if it works for you?

### CODE REVIEW

**Comment by stsievert** [comment]
Things have always worked okay. I updated the image to show dask.distributed’s path, but I think the image before also had the dashboard link.

**Comment by lesteve** [comment]
I stumbled on this in master and I have to admit I find the warning slightly on the noisy side. It feels like if no `diagnostics_port` argument is passed into `Client`, the user does not care too much about which port the dashboard uses and there should be no warning. IMHO the warning should also say that another port has been chosen for the dashboard and other than this everything is completely fine.

I suspect people are rather likely to have multiple clusters on the same machine (multiple notebooks running, different clusters defined in multiple cells in the same notebook, or rerunning the same cell that creates a cluster) and may find it slightly annoying that they have to pass `diagnostics_port` to silence it. In dask-jobqueue I am not 100% sure there is a straightforward way to override `diagnostics_port` of the underlying `LocalCluster`.

I may well be missing something about adding a warning for this "port is already in use" case so I would be more than happy to hear about the reason behind it ...

**Comment by mrocklin** [comment]
I made the change originally after sitting with novice users a few times and noticing the same behavior.  They would work in a notebook, re-run the cell that creates a local `Client()` then they would run some code and be confused why the dashboard wasn't changing. 

Anyone with some experience of using dask in a notebook is pretty used to avoiding the cell that creates the client or are accustomed to restarting the notebook every time (this is what I do).  I think that this no longer bothers us but is a very common stumbling block when setting up new users.

My hope was that this warning would give them a hint about what was going on.

I suspect that there is a way to make everyone happy though.  Does anyone have any suggestions that could both help the situation I describe above while also not being too noisy?

**Comment by mrocklin** [comment]
@lesteve how is this?

```python
In [1]: from dask.distributed import Client

In [2]: client = Client(processes=False)

In [3]: client = Client(processes=False)
/home/mrocklin/workspace/distributed/distributed/bokeh/core.py:53: UserWarning: 
Port 8787 is already in use. 
Perhaps you already have a cluster running?
Hosting the diagnostics dashboard on a random port instead.
  warnings.warn('\n' + msg)
```

**Comment by lesteve** [comment]
> @lesteve how is this?

Looks like I did not hit Enter of my comment but tl;dr looks good to me!

For completeness, here it is:
I see I guess the novice use case kind of makes sense. I don't really have a good suggestion off the top of my head to make everyone happy. A config option would work but seems a bit overkill for this IMO.

I would say merge this one and see if someone else than me complains ;-).

**Pull request merged**
