### PR TITLE
absolufy-imports - No relative - PEP8

### PR DESCRIPTION
**Pull request by fjetter**
Closes https://github.com/dask/distributed/issues/5889

Alternative to https://github.com/dask/distributed/pull/5917

### CODE REVIEW

**Review by jsignell — APPROVED** [review]
I'm happy with this approach and happy that we don't really need to justify it since it aligns with  pep8.

**Review by crusaderky — APPROVED** [review]

**Comment by crusaderky** [comment]
This looks good. Thank you!

**Comment by martindurant** [comment]
Is there a tool to do this kind of refactor?

**Comment by MarcoGorelli** [comment]
Yes, the one just added to `.pre-commit-config.yaml`:
```
  -   repo: https://github.com/MarcoGorelli/absolufy-imports
      rev: v0.3.1
      hooks:
      - id: absolufy-imports
        name: absolufy-imports
```

**Comment by martindurant** [comment]
Got it, thank you.

**Pull request merged**
