### PR TITLE
Drop runtime dependency to setuptools

### PR DESCRIPTION
**Pull request by crusaderky**
setuptools now remains exclusively in setup.py and conda meta.yaml.
It is also optionally used by versioneer, with a transparent fallback to distutils if it's not already loaded.

twin of
- https://github.com/dask/dask/pull/8855

xrefs
- #5963 
- #5923
- dask/dask#8509

### CODE REVIEW

**Comment by crusaderky** [comment]
I can see a wealth of differences between 

- dask/continuous_integration/recipe/meta.yaml 
and 
- distributed/continuous_integration/recipes/dask/meta.yaml

I expect one of the two files to be unused?

CC @jsignell

**Comment by crusaderky** [comment]
All failures unrelated.
linting failure: https://github.com/dask/distributed/pull/6019

**Review by fjetter — APPROVED** [review]

**Comment by jsignell** [comment]
My understanding is that there recipes are exclusively used for nightly builds. @charlesbluca @jakirkham

**Comment by charlesbluca** [comment]
> My understanding is that there recipes are exclusively used for nightly builds

Correct, both are used in [this workflow](https://github.com/dask/distributed/blob/main/.github/workflows/conda.yml) to build / publish nightlies on every commit.

> I expect one of the two files to be unused?

Both are being used, with `dask/continuous_integration/recipe/meta.yaml` generating `dask-core` nightlies and `distributed/continuous_integration/recipes/dask/meta.yaml` generating `dask` metapackage nightlies

**Pull request merged**
