### PR TITLE
Fix leak in `test_localcluster_get_client`

### LINKED ISSUE #6794: Flaky `distributed.deploy.tests.test_spec_cluster::test_adaptive_killed_worker`
```
_________________________ test_adaptive_killed_worker __________________________

args = (), kwds = {}

    @wraps(func)
    def inner(*args, **kwds):
>       with self._recreate_cm():

../../../miniconda3/envs/dask-distributed/lib/python3.10/contextlib.py:78: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../miniconda3/envs/dask-distributed/lib/python3.10/contextlib.py:142: in __exit__
    next(self.gen)
distributed/utils_test.py:1904: in clean
    with check_thread_leak() if threads else nullcontext():
../../../miniconda3/envs/dask-distributed/lib/python3.10/contextlib.py:142: in __exit__
    next(self.gen)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @contextmanager
    def check_thread_leak():
        """Context manager to ensure we haven't leaked any threads"""
        active_threads_start = threading.enumerate()
    
        yield
    
        start = time()
        while True:
            bad_threads = [
                thread
                for thread in threading.enumerate()
                if thread not in active_threads_start
                # FIXME this looks like a genuine leak that needs fixing
                and "watch message queue" not in thread.name
            ]
            if not bad_threads:
                break
            else:
                sleep(0.01)
            if time() > start + 5:
                # Raise an error with information about leaked threads
                from distributed import profile
    
                bad_thread = bad_threads[0]
                call_stacks = profile.call_stack(sys._current_frames()[bad_thread.ident])
>               assert False, (bad_thread, call_stacks)
E               AssertionError: (<Thread(asyncio_3, started daemon 123145605582848)>, ['  File "/Users/runner/miniconda3/envs/dask-distributed/lib/pyt...ibuted/lib/python3.10/concurrent/futures/thread.py", line 81, in _worker
E                 \twork_item = work_queue.get(block=True)
E                 '])
E               assert False

distributed/utils_test.py:1755: AssertionError
----------------------------- Captured stderr call -----------------------------
2022-07-26 14:46:57,289 - distributed.worker - INFO -       Start worker at:    tcp://10.79.11.16:54792
2022-07-26 14:46:57,289 - distributed.worker - INFO -          Listening to:    tcp://10.79.11.16:54792
2022-07-26 14:46:57,289 - distributed.worker - INFO -          dashboard at:          10.79.11.16:54793
2022-07-26 14:46:57,289 - distributed.worker - INFO - Waiting to connect to:    tcp://10.79.11.16:54755
2022-07-26 14:46:57,289 - distributed.worker - INFO - -------------------------------------------------
2022-07-26 14:46:57,289 - distributed.worker - INFO -               Threads:                          1
2022-07-26 14:46:57,289 - distributed.worker - INFO -                Memory:                   4.67 GiB
2022-07-26 14:46:57,290 - distributed.worker - INFO -       Local Directory: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/dask-worker-space/worker-p3uk5khp
2022-07-26 14:46:57,290 - distributed.worker - INFO - -------------------------------------------------
2022-07-26 14:46:58,033 - distributed.worker - INFO -         Registered to:    tcp://10.79.11.16:54755
2022-07-26 14:46:58,034 - distributed.worker - INFO - -------------------------------------------------
2022-07-26 14:46:58,035 - distributed.core - INFO - Starting established connection
2022-07-26 14:46:58,174 - distributed.worker - INFO - Stopping worker at tcp://10.79.11.16:54792
2022-07-26 14:46:58,177 - distributed.worker - INFO - Connection to scheduler broken. Closing without reporting. ID: Worker-ea338bf0-1457-492a-b791-3dc97bd58bfd Address tcp://10.79.11.16:54792 Status: Status.closing
2022-07-26 14:47:00,481 - distributed.worker - INFO -       Start worker at:    tcp://10.79.11.16:54845
2022-07-26 14:47:00,482 - distributed.worker - INFO -          Listening to:    tcp://10.79.11.16:54845
2022-07-26 14:47:00,482 - distributed.worker - INFO -          dashboard at:          10.79.11.16:54846
2022-07-26 14:47:00,482 - distributed.worker - INFO - Waiting to connect to:    tcp://10.79.11.16:54755
2022-07-26 14:47:00,482 - distributed.worker - INFO - -------------------------------------------------
2022-07-26 14:47:00,482 - distributed.worker - INFO -               Threads:                          1
2022-07-26 14:47:00,482 - distributed.worker - INFO -                Memory:                   4.67 GiB
2022-07-26 14:47:00,482 - distributed.worker - INFO -       Local Directory: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/dask-worker-space/worker-bwpenfrc
2022-07-26 14:47:00,482 - distributed.worker - INFO - -------------------------------------------------
2022-07-26 14:47:01,331 - distributed.worker - INFO -         Registered to:    tcp://10.79.11.16:54755
2022-07-26 14:47:01,332 - distributed.worker - INFO - -------------------------------------------------
2022-07-26 14:47:01,333 - distributed.core - INFO - Starting established connection
2022-07-26 14:47:01,471 - distributed.worker - INFO - Stopping worker at tcp://10.79.11.16:54845
2022-07-26 14:47:01,475 - distributed.worker - INFO - Connection to scheduler broken. Closing without reporting. ID: Worker-d17dea54-fc9a-405c-b029-58f458f5c865 Address tcp://10.79.11.16:54845 Status: Status.closing
```
https://github.com/dask/distributed/runs/7522388304?check_suite_focus=true#step:11:2209

### PR DESCRIPTION
**Pull request by hendrikmakait**
Fixes issue mentioned in https://github.com/dask/distributed/pull/6745#issuecomment-1195676661.
Likely fixes:
* #6794
* #6795 
* #6796 

which started occurring once #6745 was merged.

- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by hendrikmakait** [comment]
Note: We may want to add an `autouse` fixture that checks _all_ tests for leaks (#6498).

**Review by gjoseph92 — APPROVED** [review]
This looks like a good change to me. But I'm not sure how it would affect other tests besides `test_localcluster_get_client`? Are you saying it would address the `RuntimeError: cannot schedule new futures after shutdown` issue from https://github.com/dask/distributed/pull/6745#issuecomment-1195676661? Because I'm not sure how it would affect https://github.com/dask/distributed/issues/6796 (but I may be missing something).

**Comment by gjoseph92** [comment]
Going to merge this now regardless since `test_localcluster_get_client` is causing failures.

**Comment by hendrikmakait** [comment]
> But I'm not sure how it would affect other tests besides test_localcluster_get_client?

To be honest, my assumption was based on correlation rather than an understanding of causality. What I observed was an oddly behaving test that kept the test suite busy for a while after passing and then returned a pretty long error output as well as a sudden uptick in CI failures once this test was merged into `main`. Once I had fixed this test, those failures seemed to have disappeared on my branch. Should this really fix the linked CI issues, this might warrant a more thorough investigation of what was going on that this test affected seemingly unrelated ones.

**Pull request merged**
