### PR TITLE
Adaptive Deployments

### PR DESCRIPTION
**Pull request by mrocklin**
This adds an interface to adaptively deploy dask workers based on scheduler load.  

Full doc page is here: https://github.com/mrocklin/distributed/blob/worker-nbytes/docs/source/adaptive.rst

### CODE REVIEW

**Comment by mrocklin** [comment]
@hussainsultan @kszucs this could use your feedback.  In particular the docpage linked to from the top and the example Marathon implementation included at the bottom of that docpage

**Comment by kszucs** [comment]
It looks good to me. Health-checks and port definitions would be nice though. 

Is there any advantage if using --nprocs option for colocated workers?

```py
if 'cpus' in kwargs:
    args.extend(['--nprocs', str(int(kwargs['cpus']))])
```

**Comment by mrocklin** [comment]
@kszucs how would you recommend integrating docker containers into this solution?

Submitting the scheduler is tricky.  We use information on the scheduler to determine how many workers to create.  It's convenient to have it locally.

Looking into health checks and ports now

**Comment by kszucs** [comment]
The interface of marathon client is pretty ugly, so:

```python
MarathonApp(
    cmd='...', 
    container=MarathonContainer(
        docker=MarathonDockerContainer(
            image='dask/distributed', 
            force_pull_image=True)))
```

It translates to https://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-apps

You need to enable docker containerizer in mesos_slaves like You [did](https://github.com/mrocklin/dask-marathon/blob/master/docker-compose.yml#L69) :)

**Pull request merged**
