### PR TITLE
ignore oserror exception when scaling down (dask#4591)

### PR DESCRIPTION
**Pull request by gerald732**
Adaptive stop() is called if workers are preempted. From the discussion #4591 with @jacobtomlinson , it's reasonable to ignore the exception and carry on with adaptive when scaling down

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Looks reasonable to me. I've restarted the CI to see if the failure was a flaky test.

**Comment by gerald732** [comment]
Seems like it. Earlier, the test against the mac os platform failed. Now we’re seeing 7 other failures.

**Comment by jrbourbeau** [comment]
I just merged the `main` branch into this PR (hope that's okay @gerald732). This will _hopefully_ resolve some of the unrelated CI failures

**Comment by gerald732** [comment]
> 
> 
> I just merged the `main` branch into this PR (hope that's okay @gerald732). This will _hopefully_ resolve some of the unrelated CI failures

sure thanks!

**Comment by gerald732** [comment]
Looks like all the checks have passed.

**Comment by jacobtomlinson** [comment]
Thanks @gerald732

**Pull request merged**
