### PR TITLE
insert newline by default after TextProgressBar

### PR DESCRIPTION
**Pull request by ptooley**
PR to add functionality requested in issue #1487.

New option to progress() allows the old behaviour to be reproduced but default to adding a newline as that seems to be more likely what most people will want.

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks for doing this @ptooley !

Three (or two, depending) small comments:

1.  Can we test this functionality?  Hopefully some of the tests in distributed/diagnostics/tests/test_progressbar.py can be adapted here
2.  Do we want to preserve the old functionality?
3.  If we do then can we rename the keyword to `newline=True` to avoid the double-negative

**Comment by ptooley** [comment]
Agree, double-negatives bad, fixed.

I don't see a reason not to keep the old functionality around, someone may well be using it and it introduces minimal additional code.

As far as testing goes, the newline breaks the current tests because of the way the output is captured.  `check_bar_completed` should grab the second-last line now rather than the last.  I am inclined to fix the current tests for the new default case and add a single extra test of the `newline=False` case.  Does that sound logical to you?

**Comment by mrocklin** [comment]
That sounds fine to me.  

> I don't see a reason not to keep the old functionality around, someone may well be using it and it introduces minimal additional code.

One reason not to keep it around is an accrual of functionality and increased maintenance costs.  If you think that this is likely to be preferred then I'm inclined to remove the old functionality until someone arrives who needed the older functionality.

**Comment by mrocklin** [comment]
Looks like some failing tests here, in particular I just tried this locally and got the following:

```python
~/workspace/distributed/distributed/diagnostics/progressbar.py in listen(self)
     75             if response['status'] in ('error', 'finished'):
     76                 yield self.comm.close()
---> 77                 self._draw_stop(**response)
     78                 break
     79 

TypeError: _draw_stop() got an unexpected keyword argument 'all'
```

**Comment by ptooley** [comment]
Yeah, sorry, missed the **kwargs in the signature.  Unfortunately I haven't out how to run the tests locally. Pytest just throws a bunch of errors.

**Comment by mrocklin** [comment]
> Pytest throws an AttributeError trying to access dask.config.config

Testing dask/distributed master requires dask/dask master.  You might want to install from github

    pip install git+https://github.com/dask/dask.git --upgrade --no-deps

**Comment by mrocklin** [comment]
It looks like there are still some failing tests:

```
distributed/diagnostics/tests/test_progressbar.py:71: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/tornado/ioloop.py:581: in run_sync
    return future_cell[0].result()
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/tornado/gen.py:1113: in run
    yielded = self.gen.send(value)
distributed/diagnostics/tests/test_progressbar.py:65: in f
    check_bar_completed(capsys)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
capsys = <_pytest.capture.CaptureFixture object at 0x7fafc64730f0>, width = 40
    def check_bar_completed(capsys, width=40):
        out, err = capsys.readouterr()
        # trailing newline so grab next to last line for final state of bar
>       bar, percent, time = [i.strip() for i in out.split('\r')[-2].split('|')]
E       ValueError: not enough values to unpack (expected 3, got 1)
```

You can also see these by clicking on the `details` link next to the travis-ci check and then following down to one of the four builds.

**Comment by mrocklin** [comment]
Hi @ptooley , any luck with this?  If you need help running tests locally let me know.  I'd be happy to help.

**Comment by jakirkham** [comment]
Maybe it's not worth adding a test for something so simple. Will likely take significantly more effort than the fix itself.

**Comment by ptooley** [comment]
Sorry for the radio silence, real life got in the way of productive coding...

I got the tests running in a conda env and the breakage was just a typo from me in the end.  I have rebased my changes on latest master and hopefully they come up good on the CI.

**Comment by ptooley** [comment]
So digging into the remaining test failure locally getting sporadic failures (~5% of runs) on the current master as well as my branch.  Additionally the offending test doesn't touch my changes.

**Comment by mrocklin** [comment]
Indeed.  That's related to a recent PR.  I'll push up a fix shortly.

**Comment by mrocklin** [comment]
The intermittently failing test is resolved in https://github.com/dask/distributed/pull/2112

Merging this.  Thank you for following through @ptooley !

**Comment by jakirkham** [comment]
Thanks @ptooley :)

**Pull request merged**
