### PR TITLE
ENH: Close Adaptive during Cluster shutdown

### LINKED ISSUE #1898: Option to shutdown adaptive cluster
During shutdown of a cluster, sometimes the adaptive portion springs back to life and requests workers. To workaround that, have started calling `cluster._adaptive.stop()` as a hack as that appears to close out the existing adaptive instance. However it would be nice if there was a more standard way to handle this as part of cluster shutdown. Thoughts on how this should be done?

### PR DESCRIPTION
**Pull request by salomondush**
- Closes #1898

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Thanks for raising this @salomondush.

Most of the cluster managers which use adaptive are based on `SpecCluster` which already handles this on close.

https://github.com/dask/distributed/blob/main/distributed/deploy/spec.py#L413-L414

Are you experiencing a specific problem here?

**Comment by jakirkham** [comment]
ok to test

**Comment by jakirkham** [comment]
@jacobtomlinson do you have thoughts on Genevieve's question? Admittedly when I observed this issue it preceded `SpecCluster`

**Comment by jacobtomlinson** [comment]
@jakirkham yeah that's my understanding.

Given the lack of response from @salomondush I'm going to close this out. But feel free to continue the discussion here if it's still relevant and we can reopen.

**Comment by jakirkham** [comment]
For context this was trying to address this issue ( https://github.com/dask/distributed/issues/1898 ), but I think PR ( https://github.com/dask/distributed/pull/4720 ) did that earlier last year.

**Pull request closed without merging**
