### PR TITLE
AMM: redesign start/stop methods

### PR DESCRIPTION
**Pull request by crusaderky**
This is a redesign pass over ``client.scheduler.amm_start()`` &co.
The accessors had a few problems:

- They're asynchronous when you have a synchronous client
- typing ``await client.scheduler.amm_start()`` in a Jupyter Notebook while the client is synchronous will result in a deadlock due to event loop mismatch
- poor naming - it's much nicer to have a singular amm namespace
- they were polluting the scheduler attributes
- missing access to current running status

IMHO no deprecation cycle needed as the whole system is still considered experimental.

### CODE REVIEW

**Comment by crusaderky** [comment]
Reimplemented using handlers

**Comment by crusaderky** [comment]
> You might simply want to implement a scheduler comm handler like
> ```python
> self.handlers = {
>     ... 
>     "op_extension": self.handle_op_extension,
>     ...
> }
>
> def handle_op_extension(self, comm, extension, action, **kwargs):
>     getattr(self.extensions[exctention], action)(**kwargs)
> 
> ```
This would be a major security flaw as it would allow running any arbitrary method on any extension.

**Comment by crusaderky** [comment]
all test failures are unrelated

**Comment by crusaderky** [comment]
@fjetter gentle ping

**Review by fjetter — APPROVED** [review]

**Pull request merged**
