### PR TITLE
`ipywidgets` 8 compatibility

### PR DESCRIPTION
**Pull request by jrbourbeau**
This seems to work for me locally, but I'll admit I don't have much context around `ipywidgets`. cc @ian-r-rose @jacobtomlinson who may have thoughts 

Note: I've not yet checked how backwards compatible these changes are 

Closes https://github.com/dask/distributed/issues/6909

### CODE REVIEW

**Review by jacobtomlinson — COMMENTED** [review]
Oh interesting I didn't know this was changing. I expect we use `_ipython_display_` in other places in Dask outside of distributed.

@ian-r-rose could you advise on the right way to handle this?

**Comment by crusaderky** [comment]
Please merge from main and revert #6910

**Comment by ian-r-rose** [comment]
> Oh interesting I didn't know this was changing. I expect we use `_ipython_display_` in other places in Dask outside of distributed.
> 
> @ian-r-rose could you advise on the right way to handle this?

The tricky thing is supporting both `ipywidgets~=7` and `ipywidgets~=8` here. Generally speaking, we should prefer `_repr_mimebundle_` to `_ipython_display_`, which is why `ipywidgets` made the change. The difference is that `_repr_mimebundle_` is supposed to just return a dictionary keyed by mimetype, and the frontend can decide which repr it wants to/is able to display. `_ipython_display_`, on the other hand, is supposed to display *as a side effect*.

Since we probably don't want to go ipywidgets==8 exclusively, I don't think we can fully commit to using `_repr_mimebundle_` everywhere. I've pushed a commit with what I think is the best way forward: we stick with `_ipython_display_` for now but use `_repr_mimebundle_` when available.

**Review by jacobtomlinson — APPROVED** [review]
Thanks for this @ian-r-rose.

**Comment by jacobtomlinson** [comment]
Test failure is unrelated.

```
FAILED distributed/tests/test_client.py::test_reconnect - asyncio.exceptions....
```

Merging.

**Pull request merged**
