### PR TITLE
Support using other serializers with `register_generic`

### PR DESCRIPTION
**Pull request by jakirkham**
This changes `register_generic` (and surrounding machinery) to support using other protocols when traversing through an object's `__dict__`. This can be handy if another serialization protocol (like `"cuda"` 😉) is need for an object that contains content that can already be serialized using this protocol. A couple examples of this are other CuPy objects (like sparse matrices) and cuML models ( https://github.com/rapidsai/cuml/issues/1732 ).

cc @cjnolet @dantegd

### CODE REVIEW

**Comment by quasiben** [comment]
Please correct me if wrong, @jakirkham .  This will allow dask to use other serializers (should they be present) for mixed typed dictionary.   Something like:

> {msgpack, pickle, dask, cuda, cuda}

with this PR, as dask is iterating over the dictionary, dask will call out to the cuda serialization for cuda objects.   Where as before, it would have used pickle, correct ?

**Comment by jakirkham** [comment]
Not quite.

Before this PR one could call `register_generic` on an object and that would allow it to go through `"dask"` serialization. After this PR one can call `register_generic` with another serialization protocol (like `"cuda"` serialization) and benefit from the same recursive serialization of the object, but with a different protocol.

Does that make more sense?

**Comment by jakirkham** [comment]
As to usage, it should look something like this

```python
register_generic(MyClass, "cuda", cuda_serialize, cuda_deserialize)
```

**Comment by quasiben** [comment]
Great!   Thanks for that explanation!  Would it make sense to add a test for this as well?  We could run any cuda tests in the ucx-py CI for now.  If not, let's merge

**Comment by jakirkham** [comment]
Of course 😊

It might make sense. I didn't seen existing tests for it though. 😟 Maybe I'm missing something?

Am planning on adding a subsequent PR that supports a few different sparse matrix types (both SciPy and CuPy), which would be tested and leverage this functionality.

**Comment by quasiben** [comment]
Thanks John.  A follow up PR with tests would be welcome

**Comment by jakirkham** [comment]
Added PR ( https://github.com/dask/distributed/pull/3545 ), which includes sparse array serialization using this functionality.

**Pull request merged**
