### PR TITLE
`str`/`bytes` compatibility for PyNVML device name

### PR DESCRIPTION
**Pull request by jrbourbeau**

### CODE REVIEW

**Comment by jrbourbeau** [comment]
We've started seeing the following test failures in gpuCI (for example, see [this build](https://gpuci.gpuopenanalytics.com/job/dask/job/distributed/job/prb/job/distributed-prb/5862/CUDA_VER=11.5,LINUX_VER=ubuntu18.04,PYTHON_VER=3.8,RAPIDS_VER=23.04/console))

```
14:55:11 FAILED distributed/diagnostics/tests/test_nvml.py::test_gpu_metrics - AttributeError: 'str' object has no attribute 'decode'
14:55:11 FAILED distributed/diagnostics/tests/test_nvml.py::test_gpu_monitoring_recent - AttributeError: 'str' object has no attribute 'decode'
```

Related to https://github.com/dask/distributed/pull/7544

cc @pentschev @jacobtomlinson @wence-

**Comment by quasiben** [comment]
The error might be due to a recent update in PyNVML.  xref: https://github.com/rapidsai/dask-cuda/pull/1118/

@wence- @charlesbluca do you have opinions here ?

**Review by wence- — APPROVED** [review]
Thanks @jrbourbeau, and sorry for missing this. This looks right since it now just asks the nvml diagnostics module to decode the name (which handles the str/bytes distinction).

**Comment by jrbourbeau** [comment]
No worries @wence-! Thanks for reviewing

**Pull request merged**
