### PR TITLE
Dask config item for always showing GPU in scheduler dashboard menu

### PR DESCRIPTION
**Pull request by ntabris**
Currently the scheduler dashboard only shows GPU in menu if there's
a GPU on the scheduler, regardless of whether workers have GPUs.
For deployments where we know in advance that we'll have GPUs we want
to monitor on workers, it would be nice to have a way to force the
scheduler dashboard to show this menu item.

Easy to test locally by running `DASK_DISTRIBUTED__DASHBOARD__ALWAYS_SHOW_GPU=1 dask-scheduler`

- [ ] Tests added / passed (**I think there's no existing test coverage for dashboard menu—should there be?**)
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Review by jacobtomlinson — COMMENTED** [review]
This is really interesting, I expect this would come up a bunch given that many folks do not configure a GPU for the scheduler (despite it being recommended practice).

Perhaps instead of showing this menu option with the scheduler has GPUs we should be detecting if the workers have GPUs and showing it in that case. The scheduler should already have all of this information.

cc @dask/gpu

**Review by jrbourbeau — COMMENTED** [review]
Thanks @ntabris!

> Perhaps instead of showing this menu option with the scheduler has GPUs we should be detecting if the workers have GPUs and showing it in that case. The scheduler should already have all of this information.

If we can automatically show this menu option, I agree that would be a good path forward

**Comment by ntabris** [comment]
> Perhaps instead of showing this menu option with the scheduler has GPUs we should be detecting if the workers have GPUs and showing it in that case. The scheduler should already have all of this information.

Automatically showing the menu option would be great! But currently I think the menu doesn't dynamically update (correct me if I'm wrong) and when the scheduler starts it doesn't know whether there will be workers with GPU... so this would be a less trivial change (I think).

**Comment by ntabris** [comment]
> GPU for the scheduler (despite it being recommended practice)

@jacobtomlinson Is there a doc somewhere that says this? If so, I'm not finding it.

**Comment by jacobtomlinson** [comment]
> currently I think the menu doesn't dynamically update 

This is correctly, but we could always fix this.

> Is there a doc somewhere that says this? If so, I'm not finding it.

@quasiben @rjzamora we talked before about the scheduler needing a GPU in case of deserialization. Rick I think there was something related to the use of `pickle` that also required this. Do we have this documented anywhere?

**Comment by pentschev** [comment]
> @quasiben @rjzamora we talked before about the scheduler needing a GPU in case of deserialization. Rick I think there was something related to the use of `pickle` that also required this. Do we have this documented anywhere?

The only documentation I'm aware of is the following sentence taken from the [UCX Integration docs in Dask-CUDA](https://docs.rapids.ai/api/dask-cuda/nightly/ucx.html):

> A memory pool also prevents the Dask scheduler from deserializing CUDA data, which will cause a crash.

Reading now I believe this isn't entirely correct, as it doesn't prevent the scheduler from deserializing data, but prevents the scheduler from crashing while deserializing data. I remember @quasiben once showed me some examples of why we Dask may need to deserialize data on the scheduler, but I don't quite remember details of it, maybe he could provide some details here.

**Comment by quasiben** [comment]
My recollection is that there are cases where object can find their way into a task graphs which will get deserialized by the scheduler.  Those can be arbitrary  things: NumPy, CuPy, cuDF, etc.  I'm having trouble recalling when this happen -- probably something like: `client.submit(add, a, b)` where a/b can be anything or `client.map(inc,  [...])`

FWIW, I don't think these not common patterns for many RAPIDS users but they easily _could_ happen

**Comment by jacobtomlinson** [comment]
> FWIW, I don't think these not common patterns for many RAPIDS users but they easily could happen

Should we document this somewhere so we can points folks to it at times like these? Given that it's a messy subject is it even worth a blog post?

**Comment by quasiben** [comment]
> Should we document this somewhere so we can points folks to it at times like these? Given that it's a messy subject is it even worth a blog post?

Yes, we should document this.  I found an old issue here: https://github.com/dask/distributed/issues/3507

and some related thoughts on objects in graphs:
- https://stackoverflow.com/questions/52997229/is-there-an-advantage-to-pre-scattering-data-objects-in-dask/52997326#52997326
- https://docs.dask.org/en/stable/phases-of-computation.html#graph-serialization

For the PR, why not default to True ?  I suppose we currently run into issues when navigating the GPU page when gpus aren't present (I can't recall what happens)

**Comment by jacobtomlinson** [comment]
I'm generally 👎 on adding config options as a workaround. We have enough config options as it is.

> that doesn't sound like a clear and strong recommendation for scheduler having GPU

Personally, I strongly advise you to give the scheduler a GPU if any of your workers have GPUs. It's common for the scheduler to share a GPU with a worker to try and save overall resources, `LocalCUDACluster` does this. But not all deployment methods support this.

Running a scheduler without a GPU is equivalent to running a different version of the scheduler. It *might* work, but you'll have a better time if you do it properly.

_I take your point that we should write this down somewhere more official though._

I would also push that correctly configuring the scheduler with a GPU nullifies this bug.

**Comment by ntabris** [comment]
> I'm generally 👎 on adding config options as a workaround

Totally understand, closing the issue.

> It's common for the scheduler to share a GPU with a worker to try and save overall resources, LocalCUDACluster does this. But not all deployment methods support this.

Interesting. My understanding was that for workers you didn't want GPU sharing (and `dask-cuda` exposes a single GPU for each Nanny/Worker) but I guess that's fine for scheduler + worker since scheduler would have very little gpu util.

I'm going to open a new issue (https://github.com/dask/distributed/issues/6924) requesting some documentation about scheduler GPU, hope nobody minds.

**Comment by jacobtomlinson** [comment]
> My understanding was that for workers you didn't want GPU sharing 

Yeah this is true. The main problem is that there are cases where the scheduler needs to deserialize an object from a GPU accelerated library. Those objects may be empty but they still need to be created. In theory the library shouldn't use any GPU memory for that object, it shouldn't make any CUDA calls at all. But we just can't confidently guarantee that or expect all libraries to do that. So the scheduler needs a GPU so that it can allocate 0 bytes of memory on it, which won't impact the worker at all.

**Pull request closed without merging**
