### PR TITLE
Discover HTTP endpoints

### PR DESCRIPTION
**Pull request by martindurant**
Fixes https://github.com/dask/distributed/issues/3677

### CODE REVIEW

**Comment by martindurant** [comment]
@mrocklin , I have made a list here, but I'm not sure where it should go. This could be documentation, a live page, a JSON endpoint... 

Also, I'm sure I don't have them all yet. Although I'm not done, I have no idea what pew-pew is.

**Comment by TomAugspurger** [comment]
>  I have no idea what pew-pew is.

That's the Official Name for the "Cluster map" dashboard added in https://github.com/dask/distributed/pull/3361

**Comment by mrocklin** [comment]
Two thoughts:

1.  The different routes can change for a few reasons:
    - People can turn off different pieces of functionality in config
    - Hardware like GPUs can show up, which enables others
    - People can add in their own with config
2.  We should probably have links from the directory

For point 1, I wonder if there is some way that we can discover pages (maybe see distributed.http.utils.get_handlers plus whatever bokeh does) and grab descriptions of them from docstrings?

**Comment by martindurant** [comment]
Something dynamic might be nice, but take a little working out - it means having a list somewhere of the places to look.

I also think that a static list like this, for the docs, is very useful, though

**Comment by mrocklin** [comment]
> Something dynamic might be nice, but take a little working out - it means having a list somewhere of the places to look.

Yes, see `distributed.http.utils.get_handlers`

> I also think that a static list like this, for the docs, is very useful, though

No objection, but I suspect that less than 10% of our users will check that doc page, while I think that very many of them may check something like a collapsable sidebar on the dashboard.

**Comment by martindurant** [comment]
Interestingly, bokeh endpoints come out like:
```
"/individual-graph/?$",
"/individual-graph/autoload.js$",
"/individual-graph/metadata$",
"/individual-graph/ws$",
```
It may be worthwhile to consolidate these (i.e., treat the bokeh application object as special), since it is "/individual-graph" that we expect people to navigate to. 
Also, it may look nicer to remove the "$"s, although they appear always to be part of the regex.

**Comment by martindurant** [comment]
OK did that - I'll make a few tests before finishing up here.

**Comment by martindurant** [comment]
Still didn't link the doc page to anywhere - happy to hear suggestions. @jrbourbeau , you mentioned somewhere it would fit?

**Comment by martindurant** [comment]
Failures:
- test_preload_remote_module in github tests
- test_pid_file on travis

no idea why...

**Comment by jrbourbeau** [comment]
I thought there was a list of some of the endpoints in the distributed docs, but I can't seem to find it now...

Re: failues.`test_preload_remote_module` has been fixed (sorry that's my fault) and `test_pid_file` is a [known flaky test](https://github.com/dask/distributed/issues/3734).

**Comment by martindurant** [comment]
@jrbourbeau , any thought?

**Comment by martindurant** [comment]
Ping here - any further requests?

**Comment by jakirkham** [comment]
cc @jacobtomlinson (in case this is of interest 😉)

**Comment by jsignell** [comment]
I wonder if there'd be a way to list what's included in statics ("/statics/individual-cluster-map.html" for example).  

Also, I think a top-level index would be very nice. Ideally, it'd have thumbnails, but that is more involved. I am happy for that to be follow on work though. I think this is a big step in the right direction for discoverability of these plots.

**Comment by martindurant** [comment]
@jsignell , are you saying you'd like to see that change in this PR? I'm not sure how to go about listing statics, except really a file-list (which is easy and doable)

**Comment by jsignell** [comment]
Yeah I'd like to see this in this PR.

**Comment by martindurant** [comment]
@jsignell : done. This method may be specific to standard configuration of the tornado static handler, but works fine for the dashboard servers as they are right now.

**Comment by martindurant** [comment]
@jsignell : finally :)

**Pull request merged**
