### PR TITLE
remove deprecated old_ssh

### LINKED ISSUE #5869: test suite intermittently closes with no further output from pytest
I was debugging the test run on tmate and noticed the test suite sometimes just aborted with no pytest teardown at all, traced it down to an `os._exit(1)` call here

https://github.com/dask/distributed/blob/a0f2af66aaccd1c88958372c076d2a53e52a1701/distributed/deploy/old_ssh.py#L94-L95

### PR DESCRIPTION
**Pull request by graingert**
- [x] Closes #5869
- [ ] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
cc @jacobtomlinson

**Review by jacobtomlinson — APPROVED** [review]
Do it! 🔥

This is still a draft, let me know when it's ready for review.

**Review by jacobtomlinson — APPROVED** [review]

**Comment by mrocklin** [comment]
Sorry, quick question, will the `dask-ssh` CLI utility still work?

SSH is cited as the most commonly used technology for setting up Dask in the survey (this surprises me).  The old SSH system was still used for the CLI I think.

**Comment by graingert** [comment]
Yes this removes the dask-ssh console script https://github.com/dask/distributed/pull/5874/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L65

**Comment by mrocklin** [comment]
We may want to keep this around until we have a suitable replacement.  

dask-ssh is as popular as dask-gateway or dask-cloudprovider: https://blog.dask.org/2021/09/15/user-survey

**Comment by jacobtomlinson** [comment]
> dask-ssh is as popular as dask-gateway or dask-cloudprovider

I've not really encountered folks using the CLI option, we have CLI options in `dask-cloudprovider` too that nobody seems to use. My reading of the survey was that we are talking about the `SSHCluster` class. 

@mrocklin do you have a perspective on whether folks are using the CLI utility?

**Comment by mrocklin** [comment]
I rarely meet people who use SSH to set up clusters, so I don't have much
experience here.  I have no reason to believe that they're mostly using the
Python class though.

What is the benefit of removing this code?  Does it come up often in
maintenance issues?  (I haven't seen it be much of a nuisance personally)

**Pull request closed without merging**
