### PR TITLE
Make local directory if it does not exist

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes https://stackoverflow.com/questions/62603609/create-local-directory-for-dask-jobqueue

### CODE REVIEW

**Comment by lsterzinger** [comment]
Hi @mrocklin, I'm the author of the SO question you linked. Looks like this small fix resolved my issue, thanks!

**Comment by mrocklin** [comment]
Thank you for the well phrased question @lsterzinger and for taking the time to try this out and report success.

**Comment by mrocklin** [comment]
Also, cc @lesteve who might have thoughts on if this policy change is good or bad.

**Comment by quasiben** [comment]
I've probably bit but this in the past and unconsciously created the directory and moved on. +1 for merging in though I have limited dask-jq experience

**Pull request merged**
