### PR TITLE
Set sizing mode on `Tabs` to avoid layout collapse

### PR DESCRIPTION
**Pull request by mattpap**
Fixes part of issue #7173.

- [ ] Tests added / passed
- [x] Passes `pre-commit run --all-files`

image

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by mattpap** [comment]
The other part of #7173 (layouts collapsed in jupyter-lab) is fixed in https://github.com/bokeh/bokeh/pull/12656, which will be released as part of bokeh 3.0.3 in a few days

**Review by jrbourbeau — COMMENTED** [review]
Thanks @mattpap! I tried this out locally with `bokeh=3.0.2` and can confirm the sizing issue for this plot is resolved (also checked `bokeh<3` and saw that things continue to look correct). 

We have a couple other `Tabs` objects -- should we add similar changes there too? FWIW I applied the same change to the http://127.0.0.1:8787/individual-compute-time-per-key plot:

```diff
diff --git a/distributed/dashboard/components/scheduler.py b/distributed/dashboard/components/scheduler.py
index 01154812..6a2818c2 100644
--- a/distributed/dashboard/components/scheduler.py
+++ b/distributed/dashboard/components/scheduler.py
@@ -1501,7 +1501,7 @@ class ComputePerKey(DashboardComponent):
         self.wedge_fig = fig2
         tab2 = TabPanel(child=fig2, title="Pie Chart")

-        self.root = Tabs(tabs=[tab1, tab2])
+        self.root = Tabs(tabs=[tab1, tab2], sizing_mode="stretch_both")

     @without_property_validation
     @log_errors
```

but am still seeing vertical sizing issues 

Screen Shot 2022-12-01 at 7 42 07 PM

Maybe https://github.com/bokeh/bokeh/pull/12656 will fix that?

**Comment by mattpap** [comment]
> Maybe https://github.com/bokeh/bokeh/pull/12656 will fix that?

Yes, I verified that setting the sizing mode with that PR fixes the problem, and I updated this PR accordingly. This will require bokeh 3.0.3, which will be released possibly later today.

**Comment by bryevdv** [comment]
@jrbourbeau I also verified that this PR with 3.0.3rc1 fixes things. I will be releasing 3.0.3 tomorrow morning. 
Screenshot 2022-12-08 at 20 49 49
Screenshot 2022-12-08 at 20 51 22
Screenshot 2022-12-08 at 20 51 28

**Comment by bryevdv** [comment]
@jrbourbeau FYI Bokeh 3.0.3 is released, I am not sure is dask needs any updates for compatible Bokeh versions or not

**Pull request merged**
