### PR TITLE
Add dashboard component for size of open data transfers

### PR DESCRIPTION
**Pull request by hendrikmakait**
Follow-up to #6936

**Blocked by #6975**

* adds a plot the size of incoming/outgoing data transfers per worker
* adds that plot to the tabs on the status page

transferbytes

- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by fjetter** [comment]
pic/gif?

**Comment by crusaderky** [comment]
Some design observations:
- I don't think that hardcoding the x scale to memory_limit is very useful.
A more reasonable scale would be ``max(memory_limit * transfer, current)``, or however you called the new 10% threshold you're implementing in #6208.
Check WorkerMemory for how the dynamic x scale is implemented (it's tricky to avoid flickering).
- I struggle reading the two bars side by side for each worker. The red one instinctively feels more important than the blue one. Maybe putting the origin in the center and having two bars come out for each worker (grow to the left for incoming; grow to the right for outgoing) would look more readable?
- the tooltip for each worker should show both incoming and outgoing
- it would be nice to dynamically change the title to show the grand total cluster-wide (outgoing and incoming should roughly be the same, minus race conditions, so just pick an arbitrary one)

**Comment by hendrikmakait** [comment]
> I don't think that setting the x scale to memory_limit is very useful.
> A more reasonable scale would be max(memory_limit * transfer, current), or however you called the new 10% threshold you're implementing in https://github.com/dask/distributed/issues/6208.
> Check WorkerMemory for how the dynamic x scale is implemented (it's tricky to avoid flickering).

Agreed, this should be updated once #6208 is merged. For now, this seems better than adding some superfluous calculations myself.

> I struggle reading the two bars side by side for each worker. The red one instinctively feels more important than the blue one. Maybe putting the origin in the center and having two bars come out for each worker (grow to the left for incoming; grow to the right for outgoing) would look more readable?

I stole this pattern from the bandwidth plots (e.g. disk bandwidth). I'd leave it as is for now and create a follow-up issue for design improvements. These might apply to more than this one plot.

**Comment by fjetter** [comment]
> > I don't think that setting the x scale to memory_limit is very useful.
> > A more reasonable scale would be max(memory_limit * transfer, current), or however you called the new 10% threshold you're implementing in https://github.com/dask/distributed/issues/6208.
Check WorkerMemory for how the dynamic x scale is implemented (it's tricky to avoid flickering).

> Agreed, this should be updated once https://github.com/dask/distributed/issues/6208 is merged. For now, this seems better than adding some superfluous calculations myself.


I suggest to merge the other PR first then.

**Comment by fjetter** [comment]
FWIW I think a great visualization would be an overlay with the bytes stored but I think that's not straight forward with bokeh

(Pardon the pic quality; It shows "reserved bytes" overlaying the unmanaged memory section)

Screenshot 2022-09-02 at 15 20 45

**Comment by crusaderky** [comment]
> FWIW I think a great visualization would be an overlay with the bytes stored but I think that's not straight forward with bokeh

I thought about that; the problem is that we don't have the information about how much of the transfer_incoming_bytes already contribute to unmanaged_memory and how much they are on top of it instead (as they haven't landed yet). We could figure out a way to measure it but I suspect we would need to probe quite deep in the networking stack, as you want to catch it literally as soon as it's copied from the network card's buffer.

**Comment by fjetter** [comment]
> I thought about that; the problem is that we don't have the information about how much of the transfer_incoming_bytes already contribute to unmanaged_memory and how much they are on top of it instead (as they haven't landed yet). We could figure out a way to measure it but I suspect we would need to probe quite deep in the networking stack, as you want to catch it literally as soon as it's copied from the network card's buffer.

true. Since it's not straight forward to do anyhow, let's forget I brought it up :)

**Comment by hendrikmakait** [comment]
> true. Since it's not straight forward to do anyhow, let's forget I brought it up :)

FWIW that's why I added it as an additional tab to the status page panel. This way, you can at least observe them at the same time and we can spend some time thinking hard about making a _good_ combined plot.

**Pull request merged**
