### PR TITLE
Some light dashboard cleanup

### PR DESCRIPTION
**Pull request by bryevdv**
I thought it was time I familiarized myself with Dask's use of Bokeh. Cleaning up code is one way I approach learning new codebase, so here are some light suggested changes. The commits are pretty cleanly split up, so I am happy to :

* drop any commits you don't want
* split this up into smaller PRs instead

All tests pass and a light manual testing looks OK but certainly it would be good for others to put things though paces. 

Summary:

#### Bokeh specific 
  * Make Bokeh 1.0 the minimum supported version. This is truly the lowest reasonable Bokeh version anyone should even *consider* supporting. I will plan to make the case that Dask should set even higher, but I will do that in a separate issue when I can collect some downloads and/or CDN data to present
  * Removes the Bokeh logo once via the theme, instead of individually in many places with code
  * Deletes obsolete coffeescript cruft
  * Streamline doc creation with a decorator to avoid repeated boilerplate
#### General
  * removes some unused imports, functions
  * drop unnecessary calls to `list`
  * fixes cases of "if-return-else" 

I'd like to see about offloading more explicit styling code into the theme, add additional tests, and make more minor improvements but will save those for another PR.

### CODE REVIEW

**Comment by bryevdv** [comment]
Oh, BTW I noticed the tentative numpy imports trying to make numpy an optional dependency, but please be aware there are unconditioned usages e.g. of `np.historgram`. So AFAICT, currently numpy is a *required* dependency. Would you like a new separate issue regarding this?

**Comment by bryevdv** [comment]
@jrbourbeau any idea about the OSX failure? AFAICT that is outside/unrelated to the dashboard code

**Review by jrbourbeau — COMMENTED** [review]
Yeah, I agree those look unrelated. We're currently working to remedy a few flaky tests. I'll re-run CI to see if that helps

**Comment by mrocklin** [comment]
> I thought it was time I familiarized myself with Dask's use of Bokeh. 

Thank you for doing this Bryan.  If you ever want to debrief or have a conversation about it I'm happy to chat any time. 

> Make Bokeh 1.0 the minimum supported version

What version would you recommend?

> but I will do that in a separate issue when I can collect some downloads and/or CDN data to present

You could do that, or you could just tell us what you think is best and we would probably just do it.

> I'd like to see about offloading more explicit styling code into the theme

I'm generally enthusiastic about theming.  I would also welcome your thoughts on what we might change to improve the style of the dashboard.  I don't really know what theming options are available.

**Comment by mrocklin** [comment]
I took this for a spin.  Things look good to me.  Merging.

**Comment by mrocklin** [comment]
Also I notice that this is your first direct code contribution to this repository.  Welcome!

**Comment by bryevdv** [comment]
> If you ever want to debrief or have a conversation about it I'm happy to chat any time.

Sure my calendar is generally open (probably more than yours!) so just send me an invite. 

> What version would you recommend?

If I had my druthers I would suggest >= 2.1  But >=1.4 would at least allow for cleaning up most of the last of the version-conditional code.

>  I don't really know what theming options are available.

More or less any property value can be themed. Currently that is limited per-type but hopefully someday theming may be able to discriminate e.g. by a configured `name` on a specific instance. FWIW I am also interested in helping to develop a distinctive "Dask Dashboard look and feel"

**Comment by mrocklin** [comment]
> FWIW I am also interested in helping to develop a distinctive "Dask Dashboard look and feel"

I wonder if you and @jacobtomlinson would have fun collaborating on this.

**Comment by jacobtomlinson** [comment]
Absolutely! We've discussed this a bit in dask/community#140. It would be great to have @bryevdv involved in that effort!

**Pull request merged**
