### PR TITLE
account for nthreads in adaptive_target

### PR DESCRIPTION
**Pull request by dchudz**
how about something like this? (no test yet, but I could add one if this seems reasonable...)

- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by mrocklin** [comment]
Thanks for raising.  I'm screwing around now.

**Comment by mrocklin** [comment]
See https://github.com/dask/distributed/pull/8041

**Comment by dchudz** [comment]
thanks

**Pull request closed without merging**
