### PR TITLE
Add Dashboard Themes

### LINKED ISSUE #2305: Alternate themes for the dashboard
People may prefer different themes for the dashboard.  This both allows individual style to come out, and also exposes a nice laboritory for others to explore and create better visual style than we can.  (which we can then steal as defaults).

There are a few places where we currently specify colors and styling:

1.  In the bokeh [theme.yaml](https://github.com/dask/distributed/blob/master/distributed/bokeh/theme.yaml) .  This determines the style of the bokeh figures, except what we specify in code
2.  In the code, where we specify colors explicitly (for example we currently have hard-coded values for "blue", "red" and "Viridis11" within our codecase.  See https://github.com/dask/distributed/blob/a78109e3605756562dc7caed4608db5e99b8dbd0/distributed/bokeh/scheduler.py#L441-L444
3.  In [static/css/base.css](https://github.com/dask/distributed/blob/master/distributed/bokeh/static/css/base.css) where we specify background color, and color for the navbar

Currently if you want to build a new theme you'll need to touch all of these.  Once you've built that theme it's not easy to switch back and forth.  

What is the right way to represent styling so that people can easily experiment with it and switch back and forth without having to repackage things?

cc @canavandl

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Closes #2305.

Add support for alternative themes for the distributed dashboard. You can configure your theme with the `dashboard.yaml` config file. It ships with a light and dark mode in the package and users can add their own via the config. I've included a couple more examples here.

### Light
screencap7

### Dark
screencap12

### Solarized Light
screencap13

<details>
<summary>Config</summary>
<p>

```yaml
solarized_light:
  page_theme:
    background: "#fdf6e3"
    navbar:
      text: "#eee8d5"
      background: "#073642"
    navbar_active:
      text: "#eee8d5"
      background: "#586e75"
    navbar_hover:
      text: "#eee8d5"
      background: "#657b83"
  colors:
    task_stream_palette:
      - "#d33682"
      - "#9F53A3"
      - "#6c71c4"
      - "#497ECB"
      - "#268bd2"
      - "#2896B5"
      - "#2aa198"
      - "#579D4C"
      - "#859900"
      - "#9D9100"
      - "#b58900"
    good: "#268bd2"
    alternative_good: "#2aa198"
    notice: "#cb4b16"
    stressed: "#dc322f"
    critical: "#002b36"
    text: "#073642"
  bokeh_theme:
    attrs:
      Figure:
        background_fill_color: null
        border_fill_color: null
        outline_line_color: "#002b36"
        outline_line_alpha: 0.25
      Grid:
        grid_line_dash: [6, 4]
        grid_line_color: "#002b36"
        grid_line_alpha: 0.25
      Axis:
        major_tick_line_alpha: 0
        major_tick_line_color: "#002b36"
        minor_tick_line_alpha: 0
        minor_tick_line_color: "#002b36"
        axis_line_alpha: 0
        axis_line_color: "#002b36"
        major_label_text_color: "#002b36"
        major_label_text_font: Helvetica
        major_label_text_font_size: 1.025em
        axis_label_standoff: 10
        axis_label_text_color: "#002b36"
        axis_label_text_font: Helvetica
        axis_label_text_font_size: 1.25em
        axis_label_text_font_style: normal
      Legend:
        spacing: 8
        glyph_width: 15
        label_standoff: 8
        label_text_color: "#002b36"
        label_text_font: Helvetica
        label_text_font_size: 1.025em
        border_line_alpha: 0
        background_fill_alpha: 0.25
        background_fill_color: "#20262B"
      ColorBar:
        title_text_color: "#002b36"
        title_text_font: Helvetica
        title_text_font_size: 1.025em
        title_text_font_style: normal
        major_label_text_color: "#002b36"
        major_label_text_font: Helvetica
        major_label_text_font_size: 1.025em
        background_fill_color: "#15191C"
        major_tick_line_alpha: 0
        bar_line_alpha: 0
      Title:
        text_color: "#002b36"
        text_font: Helvetica
        text_font_size: 1.15em
      Plot:
        background_fill_color: null
        border_fill_color: null
```

</p>
</details>

### Solarized Dark
screencap14

<details>
<summary>Config</summary>
<p>

```yaml
solarized_dark:
  page_theme:
    background: "#002b36"
    navbar:
      text: "#fdf6e3"
      background: "#073642"
    navbar_active:
      text: "#fdf6e3"
      background: "#586e75"
    navbar_hover:
      text: "#fdf6e3"
      background: "#657b83"
  colors:
    task_stream_palette:
      - "#d33682"
      - "#9F53A3"
      - "#6c71c4"
      - "#497ECB"
      - "#268bd2"
      - "#2896B5"
      - "#2aa198"
      - "#579D4C"
      - "#859900"
      - "#9D9100"
      - "#b58900"
    good: "#268bd2"
    alternative_good: "#2aa198"
    notice: "#cb4b16"
    stressed: "#dc322f"
    critical: "#eee8d5"
    text: "#fdf6e3"
  bokeh_theme:
    attrs:
      Figure:
        background_fill_color: null
        border_fill_color: null
        outline_line_color: "#eee8d5"
        outline_line_alpha: 0.25
      Grid:
        grid_line_dash: [6, 4]
        grid_line_color: "#eee8d5"
        grid_line_alpha: 0.25
      Axis:
        major_tick_line_alpha: 0
        major_tick_line_color: "#eee8d5"
        minor_tick_line_alpha: 0
        minor_tick_line_color: "#eee8d5"
        axis_line_alpha: 0
        axis_line_color: "#eee8d5"
        major_label_text_color: "#eee8d5"
        major_label_text_font: Helvetica
        major_label_text_font_size: 1.025em
        axis_label_standoff: 10
        axis_label_text_color: "#eee8d5"
        axis_label_text_font: Helvetica
        axis_label_text_font_size: 1.25em
        axis_label_text_font_style: normal
      Legend:
        spacing: 8
        glyph_width: 15
        label_standoff: 8
        label_text_color: "#eee8d5"
        label_text_font: Helvetica
        label_text_font_size: 1.025em
        border_line_alpha: 0
        background_fill_alpha: 0.25
        background_fill_color: "#20262B"
      ColorBar:
        title_text_color: "#eee8d5"
        title_text_font: Helvetica
        title_text_font_size: 1.025em
        title_text_font_style: normal
        major_label_text_color: "#eee8d5"
        major_label_text_font: Helvetica
        major_label_text_font_size: 1.025em
        background_fill_color: "#15191C"
        major_tick_line_alpha: 0
        bar_line_alpha: 0
      Title:
        text_color: "#eee8d5"
        text_font: Helvetica
        text_font_size: 1.15em
      Plot:
        background_fill_color: null
        border_fill_color: null
```

</p>
</details>

### Jupyter Lab Dark
screencap15

<details>
<summary>Config</summary>
<p>

```yaml
jupyterlab_dark:
  page_theme:
    background: "#111111"
    navbar:
      text: "#E0E0E0"
      background: "#111111"
    navbar_active:
      text: "#E0E0E0"
      background: "#111111"
    navbar_hover:
      text: "#E0E0E0"
      background: "#111111"
  colors:
    task_stream_palette: Viridis8
    good: "#2196F3"
    alternative_good: "#338242"
    notice: "#EF6C00"
    stressed: "#8C2121"
    critical: "white"
    text: "white"
  bokeh_theme:
    attrs:
      Figure:
        background_fill_color: null
        border_fill_color: null
        outline_line_color: "#E0E0E0"
        outline_line_alpha: 0.25
      Grid:
        grid_line_dash: [6, 4]
        grid_line_color: "#E0E0E0"
        grid_line_alpha: 0.25
      Axis:
        major_tick_line_alpha: 0
        major_tick_line_color: "#E0E0E0"
        minor_tick_line_alpha: 0
        minor_tick_line_color: "#E0E0E0"
        axis_line_alpha: 0
        axis_line_color: "#E0E0E0"
        major_label_text_color: "#E0E0E0"
        major_label_text_font: Helvetica
        major_label_text_font_size: 1.025em
        axis_label_standoff: 10
        axis_label_text_color: "#E0E0E0"
        axis_label_text_font: Helvetica
        axis_label_text_font_size: 1.25em
        axis_label_text_font_style: normal
      Legend:
        spacing: 8
        glyph_width: 15
        label_standoff: 8
        label_text_color: "#E0E0E0"
        label_text_font: Helvetica
        label_text_font_size: 1.025em
        border_line_alpha: 0
        background_fill_alpha: 0.25
        background_fill_color: "#20262B"
      ColorBar:
        title_text_color: "#E0E0E0"
        title_text_font: Helvetica
        title_text_font_size: 1.025em
        title_text_font_style: normal
        major_label_text_color: "#E0E0E0"
        major_label_text_font: Helvetica
        major_label_text_font_size: 1.025em
        background_fill_color: "#15191C"
        major_tick_line_alpha: 0
        bar_line_alpha: 0
      Title:
        text_color: "#E0E0E0"
        text_font: Helvetica
        text_font_size: 1.15em
      Plot:
        background_fill_color: null
        border_fill_color: null
```

</p>
</details>

This is the culmination of a Friday afternoon indulgence in a fun issue plus a trip on a plane. Therefore it may be a little rushed and would be keen to get some feedback on best ways to get the theme config.

### CODE REVIEW

**Comment by mrocklin** [comment]
That sounds like a fun airplane ride :)

**Comment by mrocklin** [comment]
cc @birdsarah in case she has time to pass judgement on style

cc @bryevdv just in case he's looking for an example of folks using Bokeh themes

**Comment by jacobtomlinson** [comment]
Also cc @meganfitzsimons for any design input.

**Comment by mrocklin** [comment]
Something odd is going on with the config system and tests.  I spent a bit of time trying to track it down but couldn't find anything yet.

**Comment by mrocklin** [comment]
Tests are still failing, but now at least I think that it's your fault :)

**Comment by birdsarah** [comment]
LGTM

**Pull request closed without merging**
