### PR TITLE
Drop asyncio TCP backend

### PR DESCRIPTION
**Pull request by fjetter**
I propose to drop support for the `asyncio_tcp` backend. Since it's implementation nobody ever touched it and there are plenty of xfailed tests because the implementation is failing on different combinations of OSes or python versions.

Right now, another flaky test `test_share_buffer_with_header` is connected to the asyncio backend on python 3.12

I propose to drop this implementation for good since I do not think it's worth maintaining at the moment and it does actually cause problems. I'm not aware of a single user so I'm fine doing this without a deprecation cycle.

In this PR I deleted all relevant code but kept the test parametrization in case we want to give this a shot later on again.

### CODE REVIEW

**Comment by fjetter** [comment]
cc @jacobtomlinson @quasiben in case you are aware of any users

**Comment by mrocklin** [comment]
+1 generally to dropping things

**Comment by quasiben** [comment]
+1 -- I'm unaware of anyone using

**Comment by jacobtomlinson** [comment]
+1 on dropping things that nobody is using.

**Pull request merged**
