### PR TITLE
[NO MRG] Test CI

### PR DESCRIPTION
**Pull request by jakirkham**
- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by jakirkham** [comment]
Am seeing the test `distributed/tests/test_client.py::test_futures_of_class` failing [on CI]( https://github.com/dask/distributed/runs/6329377750?check_suite_focus=true ). This started happening recently. The error is a bit peculiar

```
elif dask.is_dask_collection(x):
[1314](https://github.com/dask/distributed/runs/6329112229?check_suite_focus=true#step:11:1314)
>               stack.extend(x.__dask_graph__().values())
[1315](https://github.com/dask/distributed/runs/6329112229?check_suite_focus=true#step:11:1315)
E               TypeError: Array.__dask_graph__() missing 1 required positional argument: 'self'
```

Not sure, but maybe this is related to PR ( https://github.com/dask/dask/pull/8674 )

cc @douglasdavis @dask/maintenance (in case anyone has ideas 🙂)

**Comment by douglasdavis** [comment]
Yea I think it's related to changing `is_dask_collection` in https://github.com/dask/dask/pull/8674.

In the test `futures_of` is getting one element list where the element is the class `da.Array`, not an instance. In `is_dask_collection` we now check for the attribute `__dask_graph__` and see if it's callable. Perhaps we should also check to make sure that the thing (`x`) that has a callable `__dask_graph__` is an _instance_ and not a class.

**Comment by douglasdavis** [comment]
With https://github.com/dask/dask/pull/9054 the test passes

**Comment by jakirkham** [comment]
Looks like things are working again with the Dask fix. Thanks Doug! 🙏

**Pull request closed without merging**
