### PR TITLE
Remove duplicated teardown logic in Server.close, Nanny.close and Server.stop

### PR DESCRIPTION
**Pull request by thedeg123**
Closes https://github.com/dask/distributed/issues/8077

- [ ] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### Overview
The PR moves duplicated logic to stop listeners into a new private method called `_stop_listeners`.

The only logical change here is that the warning "Support for asynchronous `Listener.stop` will be removed in a future version" is now raised by `Server.stop` and `Nanny.close` rather than just `Server.close`.

This PR also adds type hinting to the method signature of `Server.close`.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Review by hendrikmakait — APPROVED** [review]
@thedeg123: Thanks for your contribution! The PR is still in draft mode, is there anything you'd like to change?

**Comment by thedeg123** [comment]
@hendrikmakait I was considering adding testing coverage for `_stop_listeners` but maybe this is not necessary considering the public facing APIs calling this code already have coverage? Please let me know your thoughts.

**Comment by hendrikmakait** [comment]
> @hendrikmakait I was considering adding testing coverage for `_stop_listeners` but maybe this is not necessary considering the public facing APIs calling this code already have coverage? Please let me know your thoughts.

I think there's no need to add tests for this given that everything we care about has coverage. The only line lacking it deals with async listeners and nobody should be using those in the first place.

**Comment by thedeg123** [comment]
Sounds good, thanks for your feedback! Feel free to merge this PR.

**Comment by hendrikmakait** [comment]
Just for additional context: You're only refactoring existing functionality, so I assume that everything we care about is already properly tested and coverage does not hint toward the contrary.

**Pull request merged**
