### PR TITLE
Fix flaky test_wall_clock

### PR DESCRIPTION
**Pull request by crusaderky**
https://github.com/dask/distributed/runs/7788208025?check_suite_focus=true

```
>           assert max(deltas) <= 0.001, deltas
E           AssertionError: [0.0012852999998358428, 3.499999820633093e-06, 1.7000002117129043e-06, 1.500000053056283e-06, 1.99999976757681e-06, 1.5999999050109182e-06, ...]
E           assert 0.0012852999998358428 <= 0.001
E            +  where 0.0012852999998358428 = max([0.0012852999998358428, 3.499999820633093e-06, 1.7000002117129043e-06, 1.500000053056283e-06, 1.99999976757681e-06, 1.5999999050109182e-06, ...])
```

### CODE REVIEW

**Review by hendrikmakait — APPROVED** [review]
Fix generally LGTM, is there any potential issue with the sampling taking more than 1 ms in other tests on CI that we should deal with? My guess is that there's not.

**Comment by crusaderky** [comment]
> Fix generally LGTM, is there any potential issue with the sampling taking more than 1 ms in other tests on CI that we should deal with? My guess is that there's not.

It *shouldn't*. I don't think what we're seeing here is a problem in the tested function per se. I think it's just that the process or the whole VM was not given any breathing space for 2ms.

**Comment by hendrikmakait** [comment]
> I don't think what we're seeing here is a problem in the tested function per se. I think it's just that the process or the whole VM was not given any breathing space for 2ms.

That's what I meant; sorry for the unclear phrasing. I was thinking about any scenarios where we could run into trouble because one "iteration" of sampling (i.e., sampling + break in-between) takes up too much wall time. From what I recall, we don't tend to rely on sampling on a 1 ms frequency though.

> It _shouldn't_.

Thanks for clearing this up!

**Comment by crusaderky** [comment]
Any test that relied on a `sleep(0.001)` to take less than 2ms would be *extremely flaky on CI. So I think we would have already noticed 🤞

**Pull request merged**
