### PR TITLE
Add client.profile(filename='myfile.html') option

### PR DESCRIPTION
**Pull request by mrocklin**
This allows users to save profile results directly to a sharable file

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @TomAugspurger I don't have this for the profilers running on the event loops yet, but can probably get there soonish.  (which might be helpful for UCX profiling)

**Comment by TomAugspurger** [comment]
Thanks. A sentence in the docs under http://distributed.dask.org/en/latest/diagnosing-performance.html#statistical-profiling would be helpful.

**Comment by mrocklin** [comment]
Done

**Comment by martindurant** [comment]
I thought there was also an intent here to use the same code to profile any process, either where the client is running or anything else, for general usefulness. Did I misunderstand, or did that end up elsewhere?

**Pull request merged**
