### PR TITLE
add occupancy as individual plot

### LINKED ISSUE #4870: Add bar chart for worker occupancy
We currently have bar charts for worker memory and the number of tasks processing.  A similar chart to number of tasks processing would be worker occupancy, which records the sum of the amount of compute time of all tasks currently residing on the worker.  This would be exactly like the number of tasks processing chart, but use `ws.occupancy` rather than `len(ws.processing)`

I would have used this today when trying to diagnose work stealing issues.  

The relevant code for the number of processing tasks is here.  It's made slightly complex because the code for this chart is currently merged with the memory chart.  It might make sense to break these apart.

https://github.com/dask/distributed/blob/9d4f0bf2fc804f955a869febd3b51423c4382908/distributed/dashboard/components/scheduler.py#L1017-L1139

### PR DESCRIPTION
**Pull request by ncclementi**
- [x] Closes #4870
- [x] Tests added / passed
- [x] Passes `black distributed` / `flake8 distributed` / `isort distributed`

Adding occupancy chart as an individual plot.

### CODE REVIEW

**Comment by ncclementi** [comment]
Currently this plot can be accessible only in applications (jupyter lab). Do we want to also have it available as a separate `occupancy_doc` and been able to do something like: `http://127.0.0.1:8787/occupancy`. This might be a bit redundant since we have this plot on `/stealing`

**Review by jrbourbeau — COMMENTED** [review]
Thanks @ncclementi! Could you add an entry for this to the [http endpoint docs](https://github.com/dask/distributed/blob/2e446ae70f3bfc23853c2a61915f5bd0625ce7d0/docs/source/http_services.rst)?

> Do we want to also have it available as a separate occupancy_doc and been able to do something like: http://127.0.0.1:8787/occupancy

I think the `/individual-occupancy` endpoint you've added here is good for now

**Comment by ncclementi** [comment]
@jrbourbeau I think this one is ready. Although, I'm seeing couple of tests failing and I'm not sure if all of those are flaky or not.

**Review by jrbourbeau — COMMENTED** [review]
Thanks @ncclementi! Those failures are almost certainly unrelated. I've pushed an empty commit to trigger CI again to see if those failures occur again

**Review by jrbourbeau — APPROVED** [review]
Thanks @ncclementi! This is in

**Pull request merged**
