### PR TITLE
Fix dask-ssh after removing local-directory from dask_scheduler cli

### LINKED ISSUE #3683: dask-ssh fails after removing local-directory keyword from dask_scheduler
PR #3620 removed local-directory keyword from `dask_scheduler` cli. Now, `dask-ssh` cannot be launched with this keyword. 

```
$ python -m distributed.cli.dask_ssh localhost --local-directory /tmp

---------------------------------------------------------------
Worker nodes:
  0: localhost

scheduler node: localhost:8786
---------------------------------------------------------------

[ scheduler localhost:8786 ] : /Users/abduh/workplaces/dask-env/bin/python -m distributed.cli.dask_scheduler --port 8786 --local-directory /tmp
[ worker localhost ] : /Users/abduh/workplaces/dask-env/bin/python -m distributed.cli.dask_worker localhost:8786 --nthreads 0 --host localhost --memory-limit auto --local-directory /tmp
[ scheduler localhost:8786 ] : Usage: dask_scheduler.py [OPTIONS] [PRELOAD_ARGV]...
[ scheduler localhost:8786 ] : 
[ scheduler localhost:8786 ] : Error: no such option: --local-directory
[ scheduler localhost:8786 ] : remote process exited with exit status 2
[ scheduler localhost:8786 ] : remote process exited with exit status 2
```
I will work on a fix.

### PR DESCRIPTION
**Pull request by abduhbm**
Fixes #3683

### CODE REVIEW

**Comment by martindurant** [comment]
This looks OK to me. 
@mrocklin , you'd be the one to sign off on dask-ssh?

**Comment by mrocklin** [comment]
> @mrocklin , you'd be the one to sign off on dask-ssh?

For old-ssh there isn't really anyone.  You're as qualified as anyone who is still active in the project.

For the newer ssh.py file yeah, maybe me, but it's also really just a thin wrapper around SpecCluster, for which I probably can't answer all of the questions.  I would encourage you to use this as an opportunity to learn how SpecCluster works, which is probably worth the time (there's no way I can personally handle all deployment questions for all time).

**Comment by martindurant** [comment]
Looks good, thank you. 
Would you mind including a test to dask-ssh with the directory parameter, to show that it doesn't error? (see distributed/deploy/tests/test_ssh.py)

**Comment by abduhbm** [comment]
@martindurant should I mark it with `avoid_travis` too?

**Comment by martindurant** [comment]
I would copy the most similar-looking test, so probably yes.

**Comment by abduhbm** [comment]
@martindurant should I re-check?

**Comment by martindurant** [comment]
Rerunning timed-out test

**Comment by martindurant** [comment]
Thanks, @abduhbm !

**Pull request merged**
