### PR TITLE
Install PyTorch on CI

### PR DESCRIPTION
**Pull request by jakirkham**
In order to run PyTorch tests on CI, make sure that it gets installed.

### CODE REVIEW

**Comment by jakirkham** [comment]
Any thoughts on this?

cc @mrocklin @jrbourbeau @quasiben

**Comment by jrbourbeau** [comment]
Thanks for the PR @jakirkham! I'm +0.5 on adding `pytorch` to CI. It'd be great to run `pytorch`-related tests. However it looks like `conda install pytorch` adds a little over 2 minutes to our Travis builds. That's probably not prohibitive given that builds take ~40 minutes today, but small additions do add up over time. Do you know if there have been issues recently where having `pytorch` in CI would have helped?

**Comment by jakirkham** [comment]
We saw some issues where the PyTorch serializers were not being used. So wanted to make sure they are working and tests pass. Additionally we are interested in extending these to handle more efficiently GPU serialization. So it would help to have a sanity check to make sure we don't break what already works in the process.

Would it be better if we only install PyTorch on one job as opposed to all of them?

**Comment by jakirkham** [comment]
Should add I think part of the issue is PyTorch pulls in MKL, which is quite large and takes some time to install.

**Comment by jrbourbeau** [comment]
> Would it be better if we only install PyTorch on one job as opposed to all of them?

Yeah, I think that would make the situation better. 

I'll plan to merge at the end of the day if there are no objections

**Comment by jakirkham** [comment]
Thanks James! Moved to the Python 3.8 job. Though happy to move to a different job if there is a preference.

**Comment by jakirkham** [comment]
Thanks James! 😄

**Pull request merged**
