### PR TITLE
Client._gather will now reraise original Attribute and Key Errors

### PR DESCRIPTION
**Pull request by bschreck**
Before, if a task had an AttributeError or KeyError, the except block in reraise would catch these-- that except block is only meant for the FutureState object not having exception or traceback attribute, or the key no longer being inside self.futures.

### CODE REVIEW

**Comment by mrocklin** [comment]
That looks like a good change to me.  Sorry for the Python 3 failures in CI.  Those are unrelated and will be cleaned up shortly.  

Are you able to set up a small test to ensure that this change doesn't revert by accident in the future?

**Comment by mrocklin** [comment]
@bschreck any interest in adding a small test to this PR?

**Comment by bschreck** [comment]
Yes I will- sorry for the delay, been busy this week

**Comment by mrocklin** [comment]
I can't very well fault you if you're working for free :)

**Comment by bschreck** [comment]
How does that test look?

**Comment by mrocklin** [comment]
This looks good to me.  Thanks for following up @bschreck

**Pull request merged**
