### PR TITLE
Only call `frame_split_size` when there are frames

### PR DESCRIPTION
**Pull request by jakirkham**
This just becomes a no-op if an empty list is given (returning an empty list). However there is no need to do this work if we don't need it. So simply restrict calling `frame_split_size` to the case where frames are present and compression will occur.

### CODE REVIEW

**Comment by quasiben** [comment]
Ive been seeing the `test_bandwidth` in a few other PRs.  Would you mind merging with master and resubmitting ?

**Comment by jakirkham** [comment]
Unfortunately this is already based on the latest commit in `dask/master`.

**Comment by quasiben** [comment]
I restarted CI to see if that fixes things

**Comment by jakirkham** [comment]
Yeah `test_bandwidth` also fails on `master`. Submitted PR ( https://github.com/dask/distributed/pull/3999 ) in an attempt to fix this.

**Comment by quasiben** [comment]
Looks good.  Thanks @jakirkham

**Comment by jakirkham** [comment]
Thanks Ben 🙂

**Pull request merged**
