### PR TITLE
Add a dashboard component that displays RMM memory

### PR DESCRIPTION
**Pull request by shwina**
- [ ] Closes #xxxx
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

This PR adds a visualization that provides a bit more information than the current GPU memory utilization plot. It also shows the amount of GPU memory being managed by RMM, and in the case of a RMM pool, the amount of pool memory actually used:

Screen Shot 2022-01-31 at 3 46 54 PM

The purple region of the bar represents the total amount of memory managed by RMM. Dark purple shows the amount of memory actively being utilized (this is relevant when a memory pool is used). The green region represents GPU memory used outside of RMM.

### CODE REVIEW

**Comment by quasiben** [comment]
Thanks @shwina this will be very useful when trying to understand memory consumption with RAPIDS workloads. 

cc @charlesbluca & @rjzamora

**Comment by VibhuJawa** [comment]
CC: @ayushdg ,  This will be useful when deciding on the choice of 32GB vs 40 GB vs 80 GB for a workflow.

**Review by jacobtomlinson — COMMENTED** [review]
This looks great!

I noticed that `RMM` doesn't get capitalised correctly in the UI. I think we special case CPU and GPU so we should update that list.

image

I'm also not super confident on the colours. Purple for RMM makes sense, but it vibrates a bit with the green. I wonder if we would either reduce the opacity of the green or switch to a different purple.

**Comment by jacobtomlinson** [comment]
Just wanted to bump this @shwina .

What do you think about my comment on the colours?

> I'm also not super confident on the colours. Purple for RMM makes sense, but it vibrates a bit with the green. I wonder if we would either reduce the opacity of the green or switch to a different purple. In the worker memory plot we use three opacities of the same blue. It would be good to try and stay consistent.

**Comment by jacobtomlinson** [comment]
Closing as superseded by #7718. Thanks for getting this started @shwina.

**Pull request closed without merging**
