### PR TITLE
Worker diagnostics

### PR DESCRIPTION
**Pull request by mrocklin**
This adds back a simplified version of the worker table to the web diagnostics.  It also adds a simple plot showing memory percentage use of all workers and a Paragraph element that we might eventually populate with further information.

### CODE REVIEW

**Comment by mrocklin** [comment]
Relates to #437 cc @caseyjlaw care to give this a spin and recommend changes?

image

**Comment by caseyjlaw** [comment]
I have not built distributed before, but it seems to work with a 'python setup.py install'. Starting scheduler and workers up reports no errors.
Loading web ui at localhost:8787/status looks new, but loading the workers view gives me a 404 error.

**Comment by mrocklin** [comment]
Hrm, that's surprising.  You can also install from a git branch with 

    pip install git+https://github.com/mrocklin/distributed.git@worker-diagnostic --upgrade

Perhaps give that a try?

**Comment by caseyjlaw** [comment]
Closer. With that build, the workers page loads, but I only see an empty table during and after a computation. The tasks and status pages look fine.

screen shot 2016-08-19 at 2 40 39 pm

**Comment by mrocklin** [comment]
Hrm, I ran into this as well on my machine but was hoping that it was an environment problem (several other similar issues ended up being the result of stale versions lying around.)  It's nice to have the issue confirmed. I'll have a closer look.

It may end up working for you if you tear down and bring back up the scheduler a few times.  Seems to be caused by a race condition somewhere.

**Comment by caseyjlaw** [comment]
The workers page never worked for showed info, even after several restarts
of workers and scheduler. My default conda Python is 2, fwiw.

**Comment by mrocklin** [comment]
OK.  Good to know.  Thanks for giving it a shot

**Comment by mrocklin** [comment]
@caseyjlaw I believe that the no-show plot issue has been resolved

**Comment by caseyjlaw** [comment]
It works! 
Very nice and I am already learning that a memory limit is not causing one of my issues...

**Comment by mrocklin** [comment]
Hooray for visual diagnostics!

**Pull request merged**
