### PR TITLE
Test Pandas `Series` is writeable

### PR DESCRIPTION
**Pull request by jakirkham**
Follow-up to PR ( https://github.com/dask/distributed/pull/3967 ) and issue ( https://github.com/dask/distributed/issues/3943 )

Includes a test to ensure a Pandas `Series` is writeable after round-trip serialization.

### CODE REVIEW

**Comment by quasiben** [comment]
Looks like this is failing on the test submitted in the PR:
https://travis-ci.org/github/dask/distributed/jobs/712415247#L1560

**Comment by jakirkham** [comment]
Yeah I saw that last night. This is weird as it passed locally. Will look into it.

**Comment by mrocklin** [comment]
Checking in.  Do we know what happened here?  I ran into `buffer source array is read-only` errors on 2.21.0 recently and I'm curious if our latest release is broken.

**Comment by jakirkham** [comment]
The fix got merged after the last release unfortunately ( https://github.com/dask/distributed/pull/3967 ). I suppose we could push out a patch release with that fix. Though we are planning to release tomorrow ( https://github.com/dask/community/issues/77 )

A separate question is why this test doesn't work. Though people have already confirmed that PR does.

**Comment by mrocklin** [comment]
Ah ok, so we just need to release.  Grand.  Thanks @jakirkham !

**Comment by jakirkham** [comment]
This test was included as part of PR ( https://github.com/dask/distributed/pull/4004 ).

**Pull request closed without merging**
