### PR TITLE
feat: MambaInstall plugin

### PR DESCRIPTION
**Pull request by wietzesuijker**
Enables the use of both Mamba and Micromamba for package installation, offering flexibility depending on user preference or environment constraints.
Mamba accelerates package installation and dependency resolution compared to Conda.

### CODE REVIEW

**Comment by wietzesuijker** [comment]
ok to test from my perspective. Nit: sorry I initially missed [the section on code formatting](https://github.com/dask/distributed/blob/b03efeeda5f17c48d020f4820ff89a752beeaf89/docs/source/develop.rst#code-formatting)

**Comment by wietzesuijker** [comment]
Just realised that the `channels` arg could be squashed into the `options`. However, I'd rather have it explicit (if we go ahead with that, this would also need a small change in the CondaInstall class)

**Review by jacobtomlinson — COMMENTED** [review]
Thank you for taking the time to raise this.

Given that [`libmamba` is now the default conda solver](https://conda.org/blog/2023-11-06-conda-23-10-0-release/) it sort of feels like `mamba` will gradually disappear. Especially given the `mamba` devs are now focused on [`pixi`](https://prefix.dev/).

What benefit does this plugin give over the existing `CondaInstall` with modern versions of `conda`?

**Comment by wietzesuijker** [comment]
Thanks I didn't fully appreciate those changes. I quickly tested CondaInstall and MambaInstall, and they perform quite similarly indeed! The only use case would be for setups that do have `(micro)mamba`, but not `conda` installed. Fine to close though!

**Pull request closed without merging**
