### PR TITLE
Create new Zstd (De)Compressor for each compression call

### LINKED ISSUE #7403: Zstandard compression is not thread safe
**Describe the issue**:

In `compression.py` we create a singleton `ZstdCompressor` and `ZstdDecompressor` object. The docs for the Zstandard library [state](https://github.com/indygreg/python-zstandard/blob/main/zstandard/backend_cffi.py#L1764):

> Unless specified otherwise, assume that no two methods of ``ZstdCompressor`` instances can be called from multiple Python threads simultaneously. In other words, assume instances are not thread safe unless stated otherwise.

**Minimal Complete Verifiable Example**:
This can trivially be reproduced by introducing threading to the `test_maybe_compress` test in `test_protocol.py`

Some errors that I've reproduced range from compression/decompression failure, to seg faults. Examples for searchability:

```
Fatal Python error: Segmentation fault

Thread 0x000000030df25000 (most recent call first):
  File "/Users/dwragge/code/distributed/distributed/protocol/compression.py", line 92 in zstd_compress
  File "/Users/dwragge/code/distributed/distributed/protocol/compression.py", line 186 in maybe_compress
  File "/Users/dwragge/code/distributed/distributed/protocol/tests/test_protocol.py", line 148 in test_compress_decompress
  File "/Users/dwragge/miniconda/envs/dask-distributed/lib/python3.8/threading.py", line 870 in run
  File "/Users/dwragge/miniconda/envs/dask-distributed/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/Users/dwragge/miniconda/envs/dask-distributed/lib/python3.8/threading.py", line 890 in _bootstrap
```

-  `zstd.ZstdError: cannot compress: Src size is incorrect`
- `zstd.ZstdError: cannot compress: Operation not authorized at current processing stage`
- `zstd.ZstdError: decompression error: Corrupted block detected`
- `zstd.ZstdError: error determining content size from frame header`
- `zstd.ZstdError: decompression error: Unknown frame descriptor`
- `zstd.ZstdError: decompression error: Destination buffer is too small`

This manifests in production as errors such as:

- `distributed.core - ERROR - Exception while handling op get_data`
- `distributed.worker - ERROR - failed during get data with tcp://a.b.c.d:39195 -> tcp://d.e.f.g:43787`
- `distributed.protocol.core - CRITICAL - Failed to deserialize`

Amongst others, including clear lost workers, and `CommClosedError`s.

**Anything else we need to know?**:

The fix is trivial (instantiate a new Zstd(De)Compressor instance for each compression. I will raise a PR to fix plus tests.

### PR DESCRIPTION
**Pull request by dwragge**
The ZstdCompressor and ZstdDecompressor objects are not thread safe to reuse. This commit re-instantiates a new object for each call to compress/decompress and adds a test to ensure this is the case.

The tests run the compress/decompress round trip 100 times, 10 times, and take about 500ms for each compression algo. In my testing this was enough to reproduce issues 90% of the time, while ensuring tests didn't take too long.

Closes #7403.

- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by jakirkham** [comment]
ok to test

**Comment by mrocklin** [comment]
In principle this seems fine to me.  The cost to make compressors seems to be very cheap

```python
In [1]: import zstandard

In [2]: zstandard.ZstdCompressor()
Out[2]: <zstd.ZstdCompressor at 0x106e5f9f0>

In [3]: %timeit zstandard.ZstdCompressor()
209 ns ± 2.58 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [4]: %timeit zstandard.ZstdDecompressor()
101 ns ± 0.326 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```

The test here was wonky, the internal test function was expecting an `fn` argument that it wasn't getting.  I hope you don't mind but I've pushed a commit resolving this.

I'll merge after tests pass.

**Comment by mrocklin** [comment]
My apologies also for the delay in review

**Comment by mrocklin** [comment]
CI failure is unrelated.  Fixing in https://github.com/dask/distributed/pull/7423

**Comment by mrocklin** [comment]
Thank you @dwragge .  This is in.

Also, I notice that this is your first code contribution to this repository.  Welcome!

**Pull request merged**
