### PR TITLE
Resilient Scheduler state 

### PR DESCRIPTION
**Pull request by Dracio**
This is a first rev at address #1072 . The scheduler state is saved to disk every 1 second, if a file is provided. The logic in add_worker returns if a task is still "executing". The logic for picking up when the result is in memory breaks test "test_worker_breaks_and_returns". 

I have created 1 test for the scheduler task state file.

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks for giving this a shot @Dracio .  I'm curious, have you used it in practice?  If so, how does it perform?

**Comment by Dracio** [comment]
> 1. What happens when the events that occur in the 1s lag between saving state are important?  For example a worker may have finished or deleted work, but restarted scheduler doesn't know about it.  Does it wait forever or is there some mechanism for the worker to update the scheduler with this new information?

This occurs in the add_worker function. I added logic to have the worker send the current state of each task it has a record of. This logic still needs to be fleshed out to make sure all the attributes from taskstate and workerstate are correlated correctly. 

> 2. How slow is this when we have millions of tasks?

I will try and setup a good stress test. It will depend on the size of self.tasks.

**Comment by inc0** [comment]
Quickly looking at this change, did you consider using external service (optionally) like Redis? Problem with using file as mechanism for state sync will be shared filesystem requirement for clustered schedulers. In cloud world it's not very trivial thing to setup shared fs that's reliable and safe. Having support for simple but fast protocol that Redis offers we can depend on it's replication model (which isn't ideal, but it's not horrible as well).

**Comment by Dracio** [comment]
> Quickly looking at this change, did you consider using external service (optionally) like Redis? 

> More resilient option would be ETCD, but number of active tasks would be something to consider (it should scale to millions of keys).

These maybe opinions. This was only my first pass at addressing this problem.

> Problem with using file as mechanism for state sync will be shared filesystem requirement for clustered schedulers. In cloud world it's not very trivial thing to setup shared fs that's reliable and safe. Having support for simple but fast protocol that Redis offers we can depend on it's replication model (which isn't ideal, but it's not horrible as well). 

I don't understand this comment. I don't see any documentation on more than one scheduler for a cluster. The task state on the scheduler is the only one that is saved to disk.

**Comment by inc0** [comment]
> I don't understand this comment. I don't see any documentation on more than one scheduler for a cluster. The task state on the scheduler is the only one that is saved to disk.

I'm looking at it from cloud perspective. To allow autohealing of scheduler in cloud, you won't have guarantee that it will restart on same node (especially if said node blows up). If we want to address autohealing of even single scheduler on different node with file-based dumps we'd need to either reconnect network attached storage if it's single writer of have it connected via multi-write. There are huge problems with ensuring that single writer is properly unattached from original node, so only real viable option is distributed, multi-write fs.

On the other hand, if we use k-v store like etcd or redis, this problem is solved (very well) on k-v storage layer. It is also quite a bit more performant than writing to disk (especially if we'd want to dump whole thing always) so we might not need to have intervals like that, or have them very short and add logic to only update statuses that changed.

**Comment by mrocklin** [comment]
I like seeing the conversation on this topic, but generally speaking I don't think that persisting the scheduler state is the way to go.  It changes too rapidly for anything but in-memory on-node storage.  Instead I think that the following are the only pragmatic ways to achieve high availability with a Dask deployment:

1.  Don't, and ask people to resubmit computations should the single point of failure go down (spark style)
2.  Have workers and clients reconnect to the scheduler and share their view of the world.  Have the scheduler re-assemble what it can from these views.

Currently we do option 1.  Option 2 is feasible with effort.

I'm pessimistic on persisting state because it changes too rapidly, and because I think it will be difficult to handle small mismatches in understanding between schedulers and workes.

**Comment by inc0** [comment]
> Have workers and clients reconnect to the scheduler and share their view of the world. Have the scheduler re-assemble what it can from these views.

Will workers have context of what remains to be scheduled?

**Comment by Dracio** [comment]
> Combined with the clients, yes, I think that that's feasible. #594

When the client is disconnected, then you lose that information. If a machine reboots in the middle of the night, then it has no clue what tasks need to be scheduled.

**Comment by mrocklin** [comment]
Correct.  However if a client disconnects then that user probably won't be expecting the result back.  This isn't always correct (for example with `fire_and_forget` computations) but is usully the case.

**Comment by inc0** [comment]
> Correct. However if a client disconnects then that user probably won't be expecting the result back. 

Unless last scheduled task would be to dump data to .csv, then it still should work correct?

**Comment by mrocklin** [comment]
I'm going to close this.  Work here has stalled, and I'm not sure that this direction is likely to be the long term solution.

**Pull request closed without merging**
