### PR TITLE
Add keep-alive message between worker and scheduler

### LINKED ISSUE #2524: Keep alive for inactive worker/scheduler connection
I noticed that the connection between workers and schedulers (and effectively all `Server` subclasses using [`handle_stream`](https://github.com/dask/distributed/blob/357bca686b47293062584e12543f2ce22bd8f16f/distributed/core.py#L378)) are kept open to continuously listen to incoming requests. This connection is solely used to listen to `stream_handler` requests while, for instance the `heartbeat`, uses a different connection from the connection pool. This means that for a longer time of cluster inactivity, the _primary_ connection is inactive. The issue about inactive connections is that some external tools are inclined to kill inactive connections (for instance, we're using [haproxy](http://www.haproxy.org) and we kill inactive connections after 1h) which requires for the worker to reconnect and register with the scheduler every hour during inactivity.

I was wondering if this is an issue for somebody else and whether it would be desired to either send a _keep alive_ using the open connection every X secs (simple message to keep the connection active)  or even send the hearbeat over this connection. I believe the first option could be implemented fairly easily in `handle_stream` while the latter is a bit more difficult. In either case I wanted to get some feedback before implementing anything.

(dedicated worker-scheduler connection creation see [here](https://github.com/dask/distributed/blob/0a5b8da4041414e1e621c1b8d613730720c6e684/distributed/worker.py#L575), reconnect if connection is broken see [here](https://github.com/dask/distributed/blob/0a5b8da4041414e1e621c1b8d613730720c6e684/distributed/worker.py#L660))

### PR DESCRIPTION
**Pull request by mrocklin**
This is effectively a heartbeat, but much simpler and less frequent than
our current heartbeats

Fixes #2524

### CODE REVIEW

**Comment by lr4d** [comment]
Getting this error on the scheduler side:
```
2019-08-01 13:30:48,297 ERROR    <lambda>() got an unexpected keyword argument 'worker' (distributed.core)
Traceback (most recent call last):
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/distributed/core.py", line 477, in handle_stream
    handler(**merge(extra, msg))
TypeError: <lambda>() got an unexpected keyword argument 'worker'
```

**Comment by mrocklin** [comment]
Thanks @lr4d .  Handled

Also, what is a good time for the frequency here?  Every minute?  Every ten minutes?  Every hour?

**Comment by lr4d** [comment]
I'd keep it below 5-10 minutes. For HAProxy the treshold for killing a connection on which no data is sent is 60 minutes, but I don't know what this may be for similar tools.

**Comment by lr4d** [comment]
This is appears to be working fine now for our HAProxy setup, I left the cluster alive for 6 hours and no disconnections or error messages took place.
Thanks @mrocklin

**Pull request merged**
