### PR TITLE
Add GPU monitor to dashboard

### PR DESCRIPTION
**Pull request by charlesbluca**
In an attempt to address #4494, this PR adds a time series view of GPU memory and utilization to the dashboard, similar to the System tab:

image

Some things that could be improved:

- I'd like to add a hover tool with the worker name + current value of the metric; this seemingly requires this to be a Bokeh `multi_line` plot, which I tried out but wasn't able to get working just yet.
- Right now, the colors of the lines are generated by iterating through a 256-color Bokeh palette - this caps the number of lines to 256, which could cause problems for cases using more GPUs than this.

A plot like this would be nice in the performance reports, but I don't think this is possible right now as there isn't a way (accessible to the scheduler, at least) to collect logs for the workers outside of the dashboard component itself.

cc @quasiben 

- [ ] Tests added / passed
- [ ] Passes `black distributed` / `flake8 distributed`

### CODE REVIEW

**Comment by charlesbluca** [comment]
Converting this to draft as there's still a lot that should be sorted out.

**Comment by jakirkham** [comment]
cc @jacobtomlinson

**Comment by charlesbluca** [comment]
The failures here are related to the fact that I'm making a column for each worker in the CDS, which isn't Bokeh best practice - instead, I should be opting to use 2-dimensional columns corresponding to the timestamps and metric values for all workers, to be plotted using `bokeh.MultiLine`. However, a CDS formatted this way doesn't support incremental data streaming yet (bokeh/bokeh#11101), so until then this PR is blocked.

**Comment by charlesbluca** [comment]
Closing this as the general consensus from #4668 was that we probably don't want multi-worker time plots like this unless they are more aggregated.

**Pull request closed without merging**
