### PR TITLE
Prevent accidentally starting multiple Workers in the same process

### PR DESCRIPTION
**Pull request by crusaderky**
Supersedes #4837 as discussed in the latest maintainer's meeting

### CODE REVIEW

**Comment by crusaderky** [comment]
CC @fjetter

**Review by fjetter — APPROVED** [review]
LGTM, thanks for fixing this @crusaderky . I have to admit that I'm a bit disappointed that no test breaks :)

**Comment by crusaderky** [comment]
@jrbourbeau ready for merge

**Comment by quasiben** [comment]
This is failing on a known flaky test `test_AllProgress_lost_key`.  Thanks for the work here @crusaderky

**Pull request merged**
