### PR TITLE
Add version option to scheduler and worker CLI

### PR DESCRIPTION
**Pull request by TomAugspurger**
Small quality of life improvement.

@jrbourbeau do I need to manually update docs anywhere, or did you recently have a PR that auto-documents command line options?

### CODE REVIEW

**Comment by jrbourbeau** [comment]
> do I need to manually update docs anywhere

Nope, all the command line options will be automatically documented w.r.t the latest `distributed` release

**Comment by TomAugspurger** [comment]
Great, thanks!

**Comment by TomAugspurger** [comment]
@mrocklin failure is probably unrelated https://ci.appveyor.com/project/daskdev/distributed/builds/25371055#L2137

```
=================================== ERRORS ====================================
2138_________________ ERROR at teardown of test_progress_function _________________
2139Traceback (most recent call last):
2140  File "c:\miniconda35-x64\envs\testenv\lib\site-packages\six.py", line 693, in reraise
2141    raise value
2142  File "c:\miniconda35-x64\envs\testenv\lib\site-packages\_pytest\runner.py", line 340, in _teardown_towards
2143    self._pop_and_teardown()
2144  File "c:\miniconda35-x64\envs\testenv\lib\site-packages\_pytest\runner.py", line 297, in _pop_and_teardown
2145    self._teardown_with_finalization(colitem)
2146  File "c:\miniconda35-x64\envs\testenv\lib\site-packages\_pytest\runner.py", line 315, in _teardown_with_finalization
2147    self._callfinalizers(colitem)
2148  File "c:\miniconda35-x64\envs\testenv\lib\site-packages\_pytest\runner.py", line 312, in _callfinalizers
2149    six.reraise(*exc)
2150  File "c:\miniconda35-x64\envs\testenv\lib\site-packages\six.py", line 693, in reraise
2151    raise value
2152  File "c:\miniconda35-x64\envs\testenv\lib\site-packages\_pytest\runner.py", line 305, in _callfinalizers
2153    fin()
2154  File "c:\miniconda35-x64\envs\testenv\lib\site-packages\_pytest\fixtures.py", line 859, in finish
2155    six.reraise(*e)
2156  File "c:\miniconda35-x64\envs\testenv\lib\site-packages\six.py", line 693, in reraise
2157    raise value
2158  File "c:\miniconda35-x64\envs\testenv\lib\site-packages\_pytest\fixtures.py", line 852, in finish
2159    func()
2160  File "c:\miniconda35-x64\envs\testenv\lib\site-packages\_pytest\fixtures.py", line 803, in _teardown_yield_fixture
2161    next(it)
2162  File "C:\projects\distributed\distributed\utils_test.py", line 549, in cluster_fixture
2163    yield (scheduler, workers)
2164  File "c:\miniconda35-x64\envs\testenv\lib\contextlib.py", line 66, in __exit__
2165    next(self.gen)
2166  File "C:\projects\distributed\distributed\utils_test.py", line 736, in cluster
2167    assert time() < start + 3, ("Workers still around after two seconds", list(ws))
2168AssertionError: ('Workers still around after two seconds', [<Process(Dask cluster test: Scheduler, stopped[SIGTERM] daemon)>])
2169assert 1560888654.4564843 < (1560888651.3991988 + 3)
2170 +  where 1560888654.4564843 = time()
2171
```

**Comment by mrocklin** [comment]
You can probably safely ignore that.  I don't know why that would have failed.

**Comment by jrbourbeau** [comment]
Merged `master` into this branch to resolve the merge conflict

**Comment by jrbourbeau** [comment]
@TomAugspurger mind if I add the same thing to the other CLI commands (e.g. `dask-ssh`)?

**Comment by TomAugspurger** [comment]
Thanks. that would be great @jrbourbeau .

**Comment by TomAugspurger** [comment]
Agreed, thanks.

**Pull request merged**
