### PR TITLE
Add ``dask-expr`` to conda recipe

### PR DESCRIPTION
**Pull request by jrbourbeau**
Closes https://github.com/dask/distributed/issues/8574

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Needs https://github.com/conda-forge/dask-expr-feedstock/pull/33

**Comment by jrbourbeau** [comment]
Here's the corresponding change upstream in the `dask` feedstock https://github.com/conda-forge/dask-feedstock/pull/251

**Comment by jrbourbeau** [comment]
It looks like the needed `dask-core` version isn't available on the `dask` conda channel. @charlesbluca @quasiben do you have bandwidth to look into this further?

**Review by fjetter — APPROVED** [review]

**Comment by charlesbluca** [comment]
Looks like the issue here is that we're trying to pull stable `dask-expr` which transitively pins us to stable `dask-core`, which is in conflict with the pinning of the nightly `dask` package:

```
 - bokeh >=2.4.2,!=3.0.*
 - cytoolz >=0.8.2
 - python >=3.9
 - jinja2 >=2.10.3
 - dask-expr >=1.0,<1.1
 - lz4 >=4.3.2
 - pandas >=1.3
 - numpy >=1.21
 - pyarrow >=7.0
 - distributed 2024.3.1a240315 py_gdf3f57ea_4
 - dask-core >=2024.3.1a.240315,<2024.3.1b

with channels:
 - dask/label/dev

The reported errors are:
- Encountered problems while solving:
-   - package dask-expr-1.0.1-pyhd8ed1ab_0 requires dask-core 2024.3.0, but none of the providers can be installed
```

The two options I see to get around this are either loosening the `dask` pinning in stable `dask-expr` (assuming this is undesired) or publishing `dask-expr` nightlies with a `dask` pinning that's loose enough to use here.

**Comment by charlesbluca** [comment]
With #8601 in this should be good to close - thanks for the help @jrbourbeau!

**Comment by jrbourbeau** [comment]
Closing based on https://github.com/dask/distributed/pull/8575#issuecomment-2034611044

**Pull request closed without merging**
