### PR TITLE
Add text exceptions to the Scheduler

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes https://github.com/dask/distributed/issues/5126

FYI @ian-r-rose @fjetter

### CODE REVIEW

**Review by fjetter — COMMENTED** [review]
Do we need to worry about size? This stores the traceback in plain txt but we usually truncate exception messages. I guess we truncate exceptions for readability but there is no harm in actually submitting the entire traceback, is there?

**Comment by mrocklin** [comment]
Perhaps we should add a `[-10000:]` to the traceback text?

**Comment by fjetter** [comment]
> Perhaps we should add a [-10000:] to the traceback text?

Fine by me but I'm also fine with doing nothing if it is not clear why we're doing it. Whether or not we need to truncate depends on the usage. For instance, logs will need to be truncated since too large message can break certain loggers.
I just wanted to ask in case I was missing anything

**Comment by mrocklin** [comment]
We don't currently truncate the actual traceback, so I don't think that
this will be worse than current state

**Pull request merged**
