### PR TITLE
P2P shuffle can drop partition column before writing to disk

### PR DESCRIPTION
**Pull request by hendrikmakait**
Partially addresses #8530

- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by hendrikmakait** [comment]
Merging this should be coordinated with https://github.com/dask-contrib/dask-expr/pull/899

**Comment by fjetter** [comment]
what's the status on this? the failing tests are due to https://github.com/dask-contrib/dask-expr/pull/899 or is there something else? the mindeps builds seem to have related failures

**Comment by hendrikmakait** [comment]
We had held back on merging because this is a release blocker for `dask-expr`. I'm opening this up for review now.

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx!

**Pull request merged**
