### PR TITLE
Remove special casing of Scikit-Learn BaseEstimator serialization

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes https://github.com/dask/dask/issues/4769

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @TomAugspurger

**Comment by TomAugspurger** [comment]
LGTM. Have you seen the appveyor failure? https://ci.appveyor.com/project/daskdev/distributed/builds/24674420#L1984

```
___________________________ test_nanny_worker_class ___________________________
1985Traceback (most recent call last):
1986  File "C:\projects\distributed\distributed\utils_test.py", line 959, in test_func
1987    coro, timeout=timeout * 2 if timeout else timeout
1988  File "C:\Miniconda35-x64\envs\testenv\lib\contextlib.py", line 66, in __exit__
1989    next(self.gen)
1990  File "C:\projects\distributed\distributed\utils_test.py", line 1541, in clean
1991    del thread_state.on_event_loop_thread
1992  File "C:\Miniconda35-x64\envs\testenv\lib\contextlib.py", line 66, in __exit__
1993    next(self.gen)
1994  File "C:\projects\distributed\distributed\utils_test.py", line 1476, in check_process_leak
1995    assert not mp_context.active_children()
1996AssertionError: assert not [<Process(Dask Worker process (from Nanny), started daemon)>]
1997 +  where [<Process(Dask Worker process (from Nanny), started daemon)>] = <function active_children at 0x000000C78D2B6620>()
1998 +    where <function active_children at 0x000000C78D2B6620> = mp_context.active_children
1999
```

**Comment by mrocklin** [comment]
> LGTM. Have you seen the appveyor failure? https://ci.appveyor.com/project/daskdev/distributed/builds/24674420#L1984

Yes, sort of.  We started getting very picky about processes leaking out from tests.  A lot of these are caught and cleaned up in #2675 .  Regardless I have high confidence that that failure is unrelated to this PR.

**Comment by TomAugspurger** [comment]
Yeah, clearly not related, was just wondering if I should open an issue :)

**Comment by mrocklin** [comment]
Na.

On the plus side, at least that's an error coming from us increasing our standards, rather than dropping our ability to meet those standards :)

**Pull request merged**
