### PR TITLE
Adapt to new Bokeh selection for 1.0

### PR DESCRIPTION
**Pull request by mrocklin**
cc @bryevdv

### CODE REVIEW

**Comment by bryevdv** [comment]
I would recommend a semantic test rather than an eplicit version test, e.g. if `self.ts_source.selected.indices` it not undefined, prefer that

**Comment by mrocklin** [comment]
Sure, done.

Mostly I wanted to ping you so that you were aware of the backwards incompatible change.  Totally reasonable given the version number change, just an FYI as I run into things.

**Comment by bryevdv** [comment]
the "dict" usage was discouraged several releases ago, when `Selection` objects were first added. We don't have a good way to warn about that programmatically, though. That said, for read-only use cases there should be no change, we aren't dropping the compat dicts altogether until 2.0, are you saying you experienced an issue?

**Comment by mrocklin** [comment]
```
  File "/home/mrocklin/workspace/distributed/distributed/bokeh/components.py", line 639, in ts_change
    selected = self.ts_source.selected['1d']['indices']
TypeError: 'Selection' object is not subscriptable
```

**Comment by bryevdv** [comment]
Oh, perhaps they were removed on the Python side. They still exist in BokehJS since there is much specifically JS example code in the wild that uses them.

**Pull request merged**
