### PR TITLE
Stop progress widget on cancel

### PR DESCRIPTION
**Pull request by martindurant**

### CODE REVIEW

**Comment by martindurant** [comment]
A couple of lines in scheduler still appear in the PR from elsewhere - please check whether they are supposed to be there or not.

**Comment by martindurant** [comment]
Hm, my test passes (and it works interactively in the notebook), but the test suite hands in collections.

**Comment by mrocklin** [comment]
Perhaps remove the extra lines in the scheduler and see what happens?

**Comment by mrocklin** [comment]
The collections test additionally serve as a good stress test.  They often fail when the scheduler has something very slightly out of alignment.  The spurious lines in the scheduler code could be just such a misalignment.

**Pull request merged**
