### PR TITLE
Python 3.9

### LINKED ISSUE #4168: Python 3.9 compatibility
Opening this issue to track Python 3.9 compatibility issues.

### PR DESCRIPTION
**Pull request by crusaderky**
Forked from #4234
Fixes #4168

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Woo, thanks for picking this up @crusaderky! FWIW I found this change https://github.com/dask/distributed/pull/4234/commits/236f8af2e6ff2dc409f83dd0270620443943624f resolves the CI issue for the Python 3.9 build on Windows

**Comment by crusaderky** [comment]
Current status:
- pytest_timeout is killing off the whole test suite instead of a single test when something hangs. In a different project, I've experienced pytest_timeout showing other issues with Python 3.9 (it was ignoring the per-function timeout decorators). The package is not covered by CI on 3.9 yet.
- distributed/deploy/tests/test_local.py:test_silent_startup is hanging; did not investigate yet. Cannot reproduce locally.
- travis's extreme slowness is aggravating the whole process. I'm seriously considering shelving this PR, delivering https://github.com/dask/distributed/pull/4218 first, and then coming back here.

**Comment by crusaderky** [comment]
Things look good. I fixed the systematic failures in Windows.
Running stress test tomorrow morning

**Comment by mrocklin** [comment]
Woo!  Are you comfortable enough for this to go out with the release
tomorrow?

**Comment by crusaderky** [comment]
@mrocklin I didn't do any work on dask/dask yet. If you're happy to release them mismatched and the stress test tomorrow morning is green, then it can go in.

**Comment by crusaderky** [comment]
This is... interesting, and unexpected.
I'm getting 0% failure rate on MacOS on 3.9, vs. the 20~30% I was seeing the previous days on 3.7 and 3.8.
I need to run more stress tests to figure out if the Python version actually makes the whole thing rock solid out of the blue, or if today was just a miraculous spell for some reason, or if they changed something in the VMs that would make all python versions stable.

**Comment by crusaderky** [comment]
All versions of Python have become rock solid on MacOS overnight (57/60 successes)

**Comment by mrocklin** [comment]
Great success?

**Comment by crusaderky** [comment]
@mrocklin yes. This is ready to go. However I had a chat with @jrbourbeau and he's of the advice that this shouldn't be merged until the matching PR on dask/dask is ready too (I'm starting it now; should be quick)

**Review by jrbourbeau — APPROVED** [review]
Thanks @crusaderky! It's great to see this go in

**Pull request merged**
