### PR TITLE
Add option to specify a scheduler address for workers to use

### PR DESCRIPTION
**Pull request by etejedor**
This is a a draft PR to follow up on the discussion here: https://github.com/dask/dask-jobqueue/issues/548 . The goal is to provide an option to specify the address that workers should use to contact the scheduler. This is useful when workers can't contact the scheduler on the address it listens on (e.g. because the scheduler is inside a container and that address is private).

The proposed changes are based on @oshadura's [patch](https://github.com/CoffeaTeam/coffea-casa/blob/master/docker/coffea-casa-cc7/distributed/0004-Add-possibility-to-setup-external_adress-for-schedul.patch), with a new option name to avoid a clash with the already existing `external_address`. The chosen name (`address_for_worker`) can of course be discussed (suggestions are welcome).

This solution also modifies the `Scheduler` class to add the new option. Thanks to this modification, the option can be provided when constructing a cluster like this:

```python
cluster = HTCondorCluster(
    scheduler_options={
        'address_for_worker': address
    },
)
```

@guillaumeeb had some ideas on how to implement this without modifying the scheduler. We can discuss here how that would look like - I am not sure how the user would specify the new option when creating the cluster if the scheduler is not modified.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by etejedor** [comment]
> Isn't this what contact_address is for?

Thanks for the feedback. That looks like what we need, but we need it for the scheduler. The docs I could find about that option are:

https://docs.dask.org/en/latest/deploying-cli.html

in particular:

```
--listen-address <listen_address>[¶](https://docs.dask.org/en/latest/deploying-cli.html#cmdoption-dask-worker-listen-address)

    The address to which the worker binds. Example: tcp://0.0.0.0:9000 or tcp://:9000[](https://docs.dask.org/en/latest/deploying-cli.html#cmdoption-dask-worker-contact-address) for IPv4+IPv6

--contact-address <contact_address>

    The address the worker advertises to the scheduler for communication with it and other workers. Example: tcp://127.0.0.1:9000
```

So indeed it seems that, for workers, the address they listen on and they address they advertise to the scheduler can already be decoupled via the two options above. Does the same exist for the scheduler? If so, how can I configure it?

**Comment by etejedor** [comment]
Hi @guillaumeeb @jacobtomlinson do you have any feedback? I'd be happy to do any changes if you find that necessary, but I'd need a bit of guidance.

**Comment by mrocklin** [comment]
In almost all cases I've seen, one can use the `--protocol` keyword to specify the right network protocol.  

However, what I think I'm hearing here is that the scheduler is listening on a protocol that it can't actually specify due to some container issues.  Is that correct?  

Normally in HPC situations I ask folks to look at `ifconfig`, find the network protocol that they like, and then use that when starting the scheduler.

**Comment by guillaumeeb** [comment]
Sorry @etejedor you didn't get any insight here. As this is a bit deep into Distributed general architecture, I was hopping some more core maintainer would have the time to help out.

So at first, I told you I thought you could do that as in @jacobtomlinson PR you already mentionned (https://github.com/dask/distributed/pull/2963), modifying only `SpecCluster`. But digging into this a bit more, I see that would involve also changes in how we handle Scheduler in dask-jobqueue, so I'm not so sure of this anymore:

- I think we actually don't use ProcessInterface for Scheduler there, as we don't submit Scheduler as a batch job (snake biting its own tail ...). 
- Could we provide the `address_for_worker` directly to a SpecCluster object? I think this would be possible, but I'm not sure if this makes sense?

So I think your proposal is good and logical. But this would need some distributed maintainer to validate it for real.

As per the name, I can propose `workers_contact_address`.

**Comment by guillaumeeb** [comment]
To be a bit more clear, I still think we have two options to solve your problem:

- Your proposal, but it involves adding an attribute to `Scheduler`.
- Or only touching `SpecCluster` by adding an argument to its constructor (`scheduler_workers_contact_address`), but this might not be really clear or makes sense. And I might have forgotten something on this part.

**Comment by etejedor** [comment]
> To be a bit more clear, I still think we have two options to solve your problem:
>    Your proposal, but it involves adding an attribute to Scheduler.
>    Or only touching SpecCluster by adding an argument to its constructor (scheduler_workers_contact_address), but this might not be really clear or makes sense. And I might have forgotten something on this part.

Thank you @guillaumeeb for the explanation. So iiuc 1) would be specified via an option inside `scheduler_options` while 2) would be specified as an argument called `scheduler_workers_contact_address` of the `HTCondorCluster` constructor (or any cluster class that inherits from `SpecCluster`) at the same level of `scheduler_options`.

I guess it depends on whether we see this more of a property of the scheduler (in that case 1) would make more sense) or if it's rather a worker configuration option (then 2) would be better).

I don't have a strong preference. Do you think it would be good to ping some core maintainer to get their opinion?

**Comment by guillaumeeb** [comment]
Yes exactly!

And I don't know either, I'd say @jacobtomlinson is the correct person to answer here. We also already have @fjetter, maybe @jrbourbeau?

**Comment by jacobtomlinson** [comment]
Before we go further I want to clear up a few more questions that I have:

- The scheduler container gets an IP which it listens on by default, and the node that it is on also has an IP with ports being proxied into the container. You need the worker to connect via the node IP, but the scheduler is advertising the container IP. Given all of this what happens if you set `host` on the scheduler to be the node IP? I would expect that to provide the correct address to the workers.
- What IP does the client need to connect on? Also the Node IP?
- What addresses do the workers use? Do they have the same issue of having a container IP and node IP?

**Comment by etejedor** [comment]
Thanks for the reply, find my answers below:

>    The scheduler container gets an IP which it listens on by default, and the node that it is on also has an IP with ports being proxied into the container. You need the worker to connect via the node IP, but the scheduler is advertising the container IP. Given all of this what happens if you set host on the scheduler to be the node IP? I would expect that to provide the correct address to the workers.

Setting `scheduler_options:host` to `node_ip:port` unfortunately does not work, because then the scheduler tries to bind to that address and fails. The container has only one network interface, with an address of the private bridge network of Docker. The scheduler runs inside the container and therefore it can only bind to that private address. In other words, the container does not belong to the node network, so its processes can't bind to an address of that network.

>  What IP does the client need to connect on? Also the Node IP?

The client also runs inside the container, so it can freely use the private IP to connect to the scheduler.

>  What addresses do the workers use? Do they have the same issue of having a container IP and node IP?

Workers do run inside containers too on the HTCondor cluster side, hosted by nodes with public addresses. Those containers, differently from the container where the scheduler and client are, run with the host network. Therefore, workers advertise a public address to the scheduler. Anyway, even if workers had to bind to a private address too, that case seems to be covered by the `--listen-address` and `--contact-address` options of the worker (https://docs.dask.org/en/latest/deploying-cli.html). I'm trying to achieve the same decoupling here for the scheduler.

**Comment by jacobtomlinson** [comment]
Yes I see. So if you set the scheduler host to `0.0.0.0` so that it binds to all interfaces it will still report the container's private IP to the workers. So you need an equivalent of `--contact-address` for the scheduler so that the node IP can be passed to the workers.

Having the workers run without network namespacing but the scheduler with it is definitely an unusual setup.

I would be tempted to suggest that instead of `address_for_worker` we standardise on `contact_address` here too given that they are for the same purpose. That way you can set `host` to `0.0.0.0` and `contact_address` to the node IP.

**Comment by etejedor** [comment]
> Having the workers run without network namespacing but the scheduler with it is definitely an unusual setup.

It might or it might not be, since Jupyter platforms for interactive analysis and condor pools are different services that may be managed by different people :) What is definitely not unusual is that Jupyter-based platforms encapsulate their users in containers without host network privileges, and that's why I think this new option can be useful.

> I would be tempted to suggest that instead of address_for_worker we standardise on contact_address here too given that they are for the same purpose. That way you can set host to 0.0.0.0 and contact_address to the node IP.

So iiuc you would be in favour of a new option called `scheduler_options:contact_address` ? This just means changing the name of the option proposed in this PR. And we discard the alternative, i.e. adding an option to the `SpecCluster` constructor. Is this correct?

**Review by jacobtomlinson — COMMENTED** [review]
This seems fine with me. cc @fjetter for visibility.

To merge we need some documentation for this (updating the `Scheduler` docstring would be a minimum).

**Comment by etejedor** [comment]
> To merge we need some documentation for this (updating the Scheduler docstring would be a minimum).

Absolutely, should I just add a paragraph to the class docstring:

https://distributed.dask.org/en/stable/_modules/distributed/scheduler.html#Scheduler

that explains this new option? I don't see any docstring for `__init__` nor a list of the class attributes and their description in the class docstring.

**Comment by etejedor** [comment]
I added a paragraph about `contact_address` to the docstring of `Scheduler`, made @oshadura co-author and changed some formatting according to the suggestion of a pre-commit hook. CI test failures seem unrelated. For me this is good to go, please let me know if there's anything else to do.

**Comment by etejedor** [comment]
@jacobtomlinson do you think this can be merged? Thanks!

**Review by jacobtomlinson — COMMENTED** [review]
We should also make this configurable via `dask.config`. See other `kwargs` that do this. You'll need to update the default YAML with a null value and the schema too.

**Comment by etejedor** [comment]
> We should also make this configurable via dask.config. See other kwargs that do this. You'll need to update the default YAML with a null value and the schema too.

@jacobtomlinson this is done now, thanks for the suggestion. Is there anything else?

**Review by jacobtomlinson — APPROVED** [review]
Sorry for the delay here. Test failures appear unrelated. Let's get this in!

**Pull request merged**
