### PR TITLE
Skip prometheus test when no installed (part 2)

### PR DESCRIPTION
**Pull request by ogrisel**
Sequel to #2533.

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks @ogrisel .  I'll wait for tests to run through and then merge.

**Comment by ogrisel** [comment]
I have added the profiling test failure to:

https://github.com/dask/distributed/issues/966

the other failures are already referenced in #966 I think.

**Comment by mrocklin** [comment]
Yes, the number of intermittent testing failures has increased significantly over the past month.  I'm slowly working on this.   Merging.

**Comment by ogrisel** [comment]
Thanks.

**Pull request merged**
