### PR TITLE
Multi-platform mypy checks

### PR DESCRIPTION
**Pull request by crusaderky**
Add Windows-specific mypy checks to CI.
Reverts #7091

### CODE REVIEW

**Comment by jakirkham** [comment]
How would we get mypy to like these constants?

**Comment by crusaderky** [comment]
> How would we get mypy to like these constants?

As per everything mypy, we don't since mypy does not execute any code; it just searches for very specific explicit, hardcoded tests such as this or `if isinstance(...` or `assert isinstance(...)`

**Review by jrbourbeau — COMMENTED** [review]
Thanks @crusaderky. It's a shame we need to run `mypy` twice, but I suppose we'll have users on Windows running `mypy` in their IDEs so best to support it.

**Comment by jrbourbeau** [comment]
Just merged `main` which should resolve the (unrelated) gpuCI failure

**Review by ian-r-rose — APPROVED** [review]
Thanks @crusaderky, this looks good to me. I agree that the extra check is unfortunate, but this is still cheap compared to a CI run.

**Pull request merged**
