### PR TITLE
Add `dask-expr` to `dask` conda recipe

### LINKED ISSUE #8574: Conda Build CI needs to be updated for dask-expr
Reopen from https://github.com/dask/dask/issues/10979

Conda Build CI has been broken since we started requiring dask-expr: https://github.com/dask/distributed/actions/runs/8249177990/job/22561028749

> ValueError: Must install dask-expr to activate query planning.

### PR DESCRIPTION
**Pull request by charlesbluca**
Closes #8574
Supersedes #8575

- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by rjzamora** [comment]
@charlesbluca - Just checking in: Is this blocked by any legitimate CI failures?

**Comment by charlesbluca** [comment]
Nope, think this is all just flaky CI - the core job impacted here is the conda build which should be unblocked by this

**Comment by quasiben** [comment]
Thanks @charlesbluca @rjzamora . As this changes conda yml we should give @jrbourbeau and/or @fjetter some time to review.  I'll tentatively plan to merge after the release of 2024.4.1 
xref: https://github.com/dask/community/issues/370

**Comment by quasiben** [comment]
With the release done and https://github.com/dask/dask/pull/11014 merged in.  I'll merge this when CI finishes.  Looking green so far...

**Comment by quasiben** [comment]
I think we can ignore the codecov failure here as this PR touches no code.  We suspect this is an issue with [uploaded base vs head](https://docs.codecov.com/docs/unexpected-coverage-changes#how-to-find-the-root-cause).  Merging in

**Pull request merged**
