### PR TITLE
(for discussion) add hooks in wait_for_workers

### PR DESCRIPTION
**Pull request by dchudz**
I work on Coiled's `Cluster`, which is a subclass of `distributed.deploy.Cluster`.

When our users call `client.wait_for_workers`, I'd like to give them information (e.g. via logging) about what's going on (e.g. progress launching EC2 instances), and when something goes wrong (the workers never arrive before timeout) I'd like to give them some information about what went wrong (e.g. details of errors in workers we tried to launch).

This PR is one idea for how we could do that: if `wait_for_workers` calls these new methods on the `Cluster` class, then subclasses can implement manager-specific logic for what to do (which I imagine will mostly be about giving users info, but could involve taking actions).

Thoughts?

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by jacobtomlinson** [comment]
I'm really happy to see some discussion around this topic. Almost all of Dask's cluster managers spawn resources from an external service in some form. Whether the Dask processes are wrapped in VMs, containers, jobs or other processes you often get put in a queue to get your allocation and then there may be some bootstrapping necessary to get a suitable environment to run Dask in before the process can be started.

All of this waiting is not particularly well communicated today. Some cluster managers just hang until they are ready, others block and print some information which tasks are starting. Neither is ideal.

Looking at this PR I'm not sure that `Client` is the right place to handle this though. I would say that anything related to cluster lifecycle and status should be part of the cluster object only.

A common pattern with cluster managers is the following:

```python
from dask_foo import FooCluster
from dask.distributed import Client

cluster = FooCluster(n_workers=3)
client = Client(cluster)
client.wait_for_workers(3)
```

The majority of cluster managers block at instantiation until the scheduler and all three workers are ready, then it will continue to the client. So `wait_for_workers` is redundant and some better feedback there is not much use.

Sometimes you might see something like this:

```python
from dask_foo import FooCluster
from dask.distributed import Client

cluster = FooCluster(n_workers=0)
client = Client(cluster)

cluster.scale(3)
client.wait_for_workers(3)
```

The `FooCluster` will still block while the scheduler is starting up, but then we can asynchronously scale and then wait for the workers before continuing. In that case, I can see these hooks being useful.

Ideally, I would like to see some way we can improve the experience for both cases.

I'm not super familiar with Coiled's cluster manager but am I right that it does not block? The class instantiates almost immediately and the scheduler and workers are created asynchronously? If this is the case I assume you have some way of blocking until things are ready enough to connect a `Client`? It would be nice to see some of these things contributed back here.

I would love to see something like the following:

```python
from dask_foo import FooCluster
from dask.distributed import Client

cluster = FooCluster(n_workers=3)  # Returns immediately and starts things asynchronously. Also has a nice widget that shows cluster startup status in Jupyter for interactive use.

cluster.wait()  # For non-interactive use. Will block until everything is ready and has a nice rich based output to show the state of things.

client = Client(cluster)
```

**Comment by dchudz** [comment]
> I'm not super familiar with Coiled's cluster manager but am I right that it does not block? 

`coiled.Cluster` does block, until the scheduler is ready and some of the workers are also ready (how many is configurable). 

> `cluster.scale(3)`
> `client.wait_for_workers(3)`

Right, my sense is that's the use case I was interested in improving here. Or maybe more like this:

```
from dask_foo import FooCluster
from dask.distributed import Client

cluster = FooCluster(n_workers=3)
client = Client(cluster)

cluster.scale(100)
client.wait_for_workers(100)
```

They created a cluster already, and then want to scale it and wait for workers.

Or maybe this: 

```
from dask_foo import FooCluster
from dask.distributed import Client

cluster = FooCluster(n_workers=100)
client = Client(cluster)
client.wait_for_workers(100)
```

(`FooCluster` doesn't wait for all the workers, but the user wants to wait. Or in Coiled's case, we do offer the option in the Cluster constructor, but maybe the user doesn't know about that, or decide they want to wait after calling `Cluster`.)

But if we should offer something else like `cluster.wait`, that makes sense.

> `cluster.wait()  # For non-interactive use. Will block until everything is ready and has a nice rich based output to show the state of things.`

Looks sensible. I think I was just making suggestions about `client.wait_for_workers` because that's what exists now, so is what our users use now.

Are you thinking `cluster.wait` would be implemented in `distributed.deploy.Cluster`, and give subclasses (like `coiled.Cluster`) ways to customize the behavior?

Are you thinking we'd keep `client.wait_for_workers` (not everyone uses a `Cluster` object, right?), but prefer `cluster.wait` for anyone with a `Cluster` object?

**Comment by jrbourbeau** [comment]
Just wanted to gently bump this thread. @jacobtomlinson do you have any thoughts on @dchudz questions?

**Comment by dchudz** [comment]
> I wonder if we could add something like cluster.wait() that holds the core functionality and then enhance client.wait_for_workers() which could check if the client has a reference to a cluster and if it does call in and grab this info. That would both mean that the cluster is solely in charge of provisioning info, but existing workflows with the client waiting could be improved.

Love that idea.

**Comment by dchudz** [comment]
Question:

I'm thinking `cluster.wait` would have an implementation in `distributed.deploy.Cluster`, but would frequently be overridden by subclasses to implement custom handling.

Does that match your thinking?

**Comment by jacobtomlinson** [comment]
Yeah absolutely.

**Comment by dchudz** [comment]
Opened https://github.com/dask/distributed/issues/6346.

Closing this.

**Pull request closed without merging**
