### PR TITLE
Wrap CUDA initialization warnings in importable functions

### PR DESCRIPTION
**Pull request by charlesbluca**
Because these CUDA initialization warnings are duplicated in Dask-CUDA's [initialization module](https://github.com/rapidsai/dask-cuda/blob/branch-22.06/dask_cuda/initialize.py), @pentschev suggested that we make them importable on Distributed's end and import them in Dask-CUDA to cut down on code duplication.

- [ ] Closes #xxxx
- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by pentschev — APPROVED** [review]
LGTM, thanks @charlesbluca !

**Comment by pentschev** [comment]
@quasiben @jakirkham could one of you take a look/merge?

**Comment by quasiben** [comment]
rerun tests

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks all! 😄

**Pull request merged**
