### PR TITLE
Fix Bokeh allowlist

### LINKED ISSUE #3901: Bokeh renamed whitelist to allowlist
Bokeh renamed their whitelist to allowlist in v2.1.0 (2020-06-15). https://github.com/bokeh/bokeh/pull/10159

```
____ ERROR collecting distributed/dashboard/tests/test_scheduler_bokeh.py _____
ImportError while importing test module 'D:\a\distributed\distributed\distributed\dashboard\tests\test_scheduler_bokeh.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
distributed\dashboard\tests\test_scheduler_bokeh.py:22: in <module>
    from distributed.dashboard.scheduler import applications
distributed\dashboard\scheduler.py:11: in <module>
    from .core import BokehApplication
distributed\dashboard\core.py:7: in <module>
    from bokeh.server.util import create_hosts_whitelist
E   ImportError: cannot import name 'create_hosts_whitelist'
```

### PR DESCRIPTION
**Pull request by nre**
Fixes #3901

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Also being fixed by @mrocklin in https://github.com/dask/distributed/pull/3904.

**Comment by mrocklin** [comment]
Ah!  I need to start reading my github notifications in reverse order :/

**Comment by mrocklin** [comment]
Ah!  I need to start reading my github notifications in reverse order :/  Sorry for the duplication.

**Comment by mrocklin** [comment]
But, the fix in #3904 is a bit more generic because it also supports older versions of Bokeh.  I suggest that we go with that one.  

If you're interested in following up @nre there is another, somewhat more challenging problem in https://github.com/dask/distributed/issues/3905 , which shows up after you fix this issue.

**Pull request closed without merging**
