### PR TITLE
Use CPU count from dask

### PR DESCRIPTION
**Pull request by jrbourbeau**
In https://github.com/dask/dask/pull/5499 the existing `CPU_COUNT` from `distributed.system` was copied to `dask.system`. This is a follow-up PR which imports `CPU_COUNT` from `dask` to avoid duplicate code.

### CODE REVIEW

**Comment by mrocklin** [comment]
I suggest that we wait a release before doing this, just to create some version flexibility (unless we're already breaking for other reasons)

**Comment by jrbourbeau** [comment]
That seems totally reasonable. I just wanted to open a PR with these changes before I forget we moved `CPU_COUNT` over to `dask/dask` : )

**Comment by mrocklin** [comment]
Yup.  Makes sense to me.  Thanks @jrbourbeau !

**Comment by jrbourbeau** [comment]
We've released version `2.7.0` (of `dask` and `distributed`) since this PR was opened. Should we merge this?

**Comment by jrbourbeau** [comment]
Thanks @mrocklin!

**Pull request merged**
