### PR TITLE
Add distributed.comm.ucx.create-cuda-context config

### PR DESCRIPTION
**Pull request by pentschev**
By allowing to explicitly create a CUDA context, we may allow GPU-based workflows to rely on UCX optimally choosing what transports to use without requiring the user to specify which ones to enable.

Relevant changes to make use of this feature are being applied in https://github.com/rapidsai/dask-cuda/pull/792.

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
The Windows/MacOS failing tests shouldn't be relevant to this, since UCX is anyway only supported on Linux. The failing Linux tests should be fixed, as reported in https://github.com/dask/distributed/issues/5527 .

Can we rerun tests here, or are we good as they are now?

**Comment by jakirkham** [comment]
Thanks Peter! 😄

**Comment by pentschev** [comment]
Thanks @jakirkham for the review and merging! 😄

**Pull request merged**
