### PR TITLE
get_ip: handle getting 0.0.0.0 (#2554)

### LINKED ISSUE #2554: Remote peers on 0.0.0.0 instead of 127.0.0.1
In running the tests, I'm getting failures due to expecting 127.0.0.1 but getting back 0.0.0.0:
```pytb
________________________________ test_tcp_repr _________________________________

    def test_func():
        with pristine_loop() as loop:
            if iscoroutinefunction(func):
                cor = func
            else:
                cor = gen.coroutine(func)
            try:
>               loop.run_sync(cor, timeout=timeout)

distributed/utils_test.py:769: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib64/python3.7/site-packages/tornado/ioloop.py:581: in run_sync
    return future_cell[0].result()
/usr/lib64/python3.7/site-packages/tornado/gen.py:1113: in run
    yielded = self.gen.send(value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @gen_test()
    def test_tcp_repr():
        a, b = yield get_tcp_comm_pair()
        assert a.local_address in repr(b)
>       assert b.local_address in repr(a)
E       AssertionError: assert 'tcp://127.0.0.1:39127' in '<TCP local=tcp://127.0.0.1:33746 remote=tcp://0.0.0.0:39127>'
E        +  where 'tcp://127.0.0.1:39127' = <TCP local=tcp://127.0.0.1:39127 remote=tcp://127.0.0.1:33746>.local_address
E        +  and   '<TCP local=tcp://127.0.0.1:33746 remote=tcp://0.0.0.0:39127>' = repr(<TCP local=tcp://127.0.0.1:33746 remote=tcp://0.0.0.0:39127>)

distributed/comm/tests/test_comms.py:1085: AssertionError
```
```pytb
________________________________ test_tls_repr _________________________________

    def test_func():
        with pristine_loop() as loop:
            if iscoroutinefunction(func):
                cor = func
            else:
                cor = gen.coroutine(func)
            try:
>               loop.run_sync(cor, timeout=timeout)

distributed/utils_test.py:769: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib64/python3.7/site-packages/tornado/ioloop.py:581: in run_sync
    return future_cell[0].result()
/usr/lib64/python3.7/site-packages/tornado/gen.py:1113: in run
    yielded = self.gen.send(value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @gen_test()
    def test_tls_repr():
        a, b = yield get_tls_comm_pair()
        assert a.local_address in repr(b)
>       assert b.local_address in repr(a)
E       AssertionError: assert 'tls://127.0.0.1:34149' in '<TLS local=tls://127.0.0.1:51272 remote=tls://0.0.0.0:34149>'
E        +  where 'tls://127.0.0.1:34149' = <TLS local=tls://127.0.0.1:34149 remote=tls://127.0.0.1:51272>.local_address
E        +  and   '<TLS local=tls://127.0.0.1:51272 remote=tls://0.0.0.0:34149>' = repr(<TLS local=tls://127.0.0.1:51272 remote=tls://0.0.0.0:34149>)

distributed/comm/tests/test_comms.py:1093: AssertionError
--------------------------- Captured stderr teardown ---------------------------
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://127.0.0.1:33746 remote=tcp://0.0.0.0:39127>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://127.0.0.1:39127 remote=tcp://127.0.0.1:33746>
```
```pytb
______________________________ test_tcp_adresses _______________________________

    def test_func():
        with pristine_loop() as loop:
            if iscoroutinefunction(func):
                cor = func
            else:
                cor = gen.coroutine(func)
            try:
>               loop.run_sync(cor, timeout=timeout)

distributed/utils_test.py:769: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib64/python3.7/site-packages/tornado/ioloop.py:581: in run_sync
    return future_cell[0].result()
/usr/lib64/python3.7/site-packages/tornado/gen.py:1107: in run
    yielded = self.gen.throw(*exc_info)
distributed/comm/tests/test_comms.py:1116: in test_tcp_adresses
    yield check_addresses(a, b)
/usr/lib64/python3.7/site-packages/tornado/gen.py:1099: in run
    value = future.result()
/usr/lib64/python3.7/site-packages/tornado/gen.py:296: in wrapper
    result = func(*args, **kwargs)
/usr/lib64/python3.7/types.py:277: in wrapped
    coro = func(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

a = <TCP local=tcp://127.0.0.1:49700 remote=tcp://0.0.0.0:34603>
b = <TCP local=tcp://127.0.0.1:34603 remote=tcp://127.0.0.1:49700>

    @gen.coroutine
    def check_addresses(a, b):
>       assert a.peer_address == b.local_address
E       AssertionError: assert 'tcp://0.0.0.0:34603' == 'tcp://127.0.0.1:34603'
E         - tcp://0.0.0.0:34603
E         ?       ^     ^
E         + tcp://127.0.0.1:34603
E         ?       ^^^     ^

distributed/comm/tests/test_comms.py:1107: AssertionError
```
```pytb
______________________________ test_tls_adresses _______________________________

    def test_func():
        with pristine_loop() as loop:
            if iscoroutinefunction(func):
                cor = func
            else:
                cor = gen.coroutine(func)
            try:
>               loop.run_sync(cor, timeout=timeout)

distributed/utils_test.py:769: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib64/python3.7/site-packages/tornado/ioloop.py:581: in run_sync
    return future_cell[0].result()
/usr/lib64/python3.7/site-packages/tornado/gen.py:1107: in run
    yielded = self.gen.throw(*exc_info)
distributed/comm/tests/test_comms.py:1122: in test_tls_adresses
    yield check_addresses(a, b)
/usr/lib64/python3.7/site-packages/tornado/gen.py:1099: in run
    value = future.result()
/usr/lib64/python3.7/site-packages/tornado/gen.py:296: in wrapper
    result = func(*args, **kwargs)
/usr/lib64/python3.7/types.py:277: in wrapped
    coro = func(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

a = <TLS local=tls://127.0.0.1:39508 remote=tls://0.0.0.0:40249>
b = <TLS local=tls://127.0.0.1:40249 remote=tls://127.0.0.1:39508>

    @gen.coroutine
    def check_addresses(a, b):
>       assert a.peer_address == b.local_address
E       AssertionError: assert 'tls://0.0.0.0:40249' == 'tls://127.0.0.1:40249'
E         - tls://0.0.0.0:40249
E         ?       ^     ^
E         + tls://127.0.0.1:40249
E         ?       ^^^     ^

distributed/comm/tests/test_comms.py:1107: AssertionError
```

I also see a failure to _not_ connect in `test_hostport` and `test_server_listen`, which may be because something's listening on all addresses instead of a specific one.

### PR DESCRIPTION
**Pull request by AdamWill**
In Fedora's package build environment, we do some stuff to ensure no network access is possible (this is to ensure the security, policy compliance and reproducibility of builds, and also just so builds don't fail or go slow or run up big networking bills).

In this environment it seems like `get_ip()` returns `"0.0.0.0"`, which is obviously not a concrete host, but `ensure_concrete_host` goes ahead and returns what it gets from `get_ip()` without checking. This ultimately breaks several tests because a server's host is considered to be `"0.0.0.0"`.

So, let's have `get_ip()` use the fallback to `getaddrinfo` if the result of the socket path is `"0.0.0.0"`, but avoid the warning, because pytest seems to consider warnings during test collection as errors and we hit this code during test collection in the affected scenario.

Closes #2554

- [X] Tests added / passed
- [X] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by AdamWill** [comment]
I honestly kinda preferred my other thought here:

```
diff --git a/distributed/utils.py b/distributed/utils.py
index 6fbbf0f2..46c53e20 100644
--- a/distributed/utils.py
+++ b/distributed/utils.py
@@ -176,6 +176,8 @@ def _get_ip(host, port, family):
     try:
         sock.connect((host, port))
         ip = sock.getsockname()[0]
+        if ip == "0.0.0.0":
+            raise OSError("Not a concrete IP, go to fallback")
         return ip
     except OSError as e:
         warnings.warn(
```

which sends `get_ip()` down its `socket.getaddrinfo()`-based fallback path. But the problem with that is that path generates a warning:

        warnings.warn(
            "Couldn't detect a suitable IP address for "
            "reaching %r, defaulting to hostname: %s" % (host, e),
            RuntimeWarning,
        )
        addr_info = socket.getaddrinfo(
            socket.gethostname(), port, family, socket.SOCK_DGRAM, socket.IPPROTO_UDP
        )[0]
        return addr_info[4][0]

and it seems like pytest treats warnings during test collection as errors, so when we run the tests in the build environment with that change, they blow up during collection:

```
__________________ ERROR collecting comm/tests/test_comms.py ___________________
/usr/lib/python3.13/site-packages/toolz/functoolz.py:457: in memof
    return cache[k]
E   KeyError: ('8.8.8.8', 80)

During handling of the above exception, another exception occurred:
../../BUILDROOT/usr/lib/python3.13/site-packages/distributed/utils.py:180: in _get_ip
    raise OSError("Not a concrete IP, go to fallback")
E   OSError: Not a concrete IP, go to fallback

During handling of the above exception, another exception occurred:
/usr/lib/python3.13/site-packages/_pytest/runner.py:341: in from_call
    result: Optional[TResult] = func()
/usr/lib/python3.13/site-packages/_pytest/runner.py:372: in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
/usr/lib/python3.13/site-packages/_pytest/python.py:531: in collect
    self._inject_setup_module_fixture()
/usr/lib/python3.13/site-packages/_pytest/python.py:545: in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
/usr/lib/python3.13/site-packages/_pytest/python.py:310: in obj
    self._obj = obj = self._getobj()
/usr/lib/python3.13/site-packages/_pytest/python.py:528: in _getobj
    return self._importtestmodule()
/usr/lib/python3.13/site-packages/_pytest/python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
/usr/lib/python3.13/site-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
/usr/lib64/python3.13/importlib/__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1387: in _gcd_import
    ???
<frozen importlib._bootstrap>:1360: in _find_and_load
    ???
<frozen importlib._bootstrap>:1331: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:935: in _load_unlocked
    ???
/usr/lib/python3.13/site-packages/_pytest/assertion/rewrite.py:186: in exec_module
    exec(co, module.__dict__)
../../BUILDROOT/usr/lib/python3.13/site-packages/distributed/comm/tests/test_comms.py:43: in <module>
    EXTERNAL_IP4 = get_ip()
../../BUILDROOT/usr/lib/python3.13/site-packages/distributed/utils.py:203: in get_ip
    return _get_ip(host, port, family=socket.AF_INET)
/usr/lib/python3.13/site-packages/toolz/functoolz.py:461: in memof
    cache[k] = result = func(*args, **kwargs)
../../BUILDROOT/usr/lib/python3.13/site-packages/distributed/utils.py:183: in _get_ip
    warnings.warn(
E   RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to hostname: Not a concrete IP, go to fallback
```

and I can't figure out how to tell pytest not to do that :/ So that has problems. OTOH now I'm running the entire test suite with this PR I think it might be causing other failures. sigh.

**Comment by AdamWill** [comment]
argh, yeah, this breaks because `test_comms.py` has `EXTERNAL_IP4 = get_ip()`, so it expects `0.0.0.0` in various places we now return `127.0.0.1` - the opposite of the problem we're trying to fix here. Will have to think of something else.

**Comment by AdamWill** [comment]
The test failures all look like flakes to me, not obviously ones that would be caused by this change.

**Review by jacobtomlinson — APPROVED** [review]
This looks fine to me, I agree that the test failures are unrelated.

Thanks for iterating here @AdamWill!

**Pull request merged**
