### PR TITLE
Add SubgraphCallables to serialization cache

### PR DESCRIPTION
**Pull request by jrbourbeau**
Currently when serializing `SubgraphCallable`s in `dumps_function`, because `SubgraphCallable`s aren't hashable, we can't use them as keys in the `cache_dumps` serialization cache. Instead we end up trigger the `TypeError` here

https://github.com/dask/distributed/blob/2acffc3172ec32e173547ee4c39a01b6c94e74a1/distributed/worker.py#L3288-L3289

and must re-serialize the same `SubgraphCallable` each time it is encountered. 

One solution would be to implement a `SubgraphCallable.__hash__` method, however I don't think we can reliably hash `SubgraphCallable`s as they contain a dask graph which in general can contain non-hashable things. 

This PR proposes we place `SubgraphCallable`s in the serialization cache using their `id` as a key. Having the same `SubgraphCallable` instance occur in many tasks is common when working with dask array and dask dataframe collections. This shouldn't noticeably impact workloads that don't use `SubgraphCallable`s, and will decreasing graph processing time for workloads that do.

<details>
<summary>Example benchmark:</summary>

For example, with the changes in this PR we have:

```python
In [1]: from toolz import valmap
   ...:
   ...: import dask.array as da
   ...: from distributed.worker import dumps_task
   ...:
   ...: # Do some array computation
   ...: x = da.arange(100_000, chunks=100)
   ...: y = da.mean(x) + x
   ...: z = da.cos(y)
   ...:
   ...: # Optimized graph
   ...: dsk_optimized = z.__dask_optimize__(z.dask, keys=z.__dask_keys__())
   ...:
   ...: # Serialize optimized graph
   ...: %timeit valmap(dumps_task, dsk_optimized)
25 ms ± 793 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

and on the current `master` branch the same code snippet gives:

```
3.67 s ± 311 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

</details>

cc @mrocklin if you get a chance to look at this

### CODE REVIEW

**Comment by mrocklin** [comment]
I apologize for the delay in response @jrbourbeau .  Should we concerned about the use of `id` here.  Is it possible for `func` to be gc'ed at some point and lose a handle on that `id` number?

**Comment by jrbourbeau** [comment]
Thanks for taking a look at this, apologies for the delayed response. Good point about `func` getting gc'ed, that situation hadn't occured to me. We'll want to avoid keeping entries in the cache for `SubgraphCallable`s which have been gc'ed as, in theory, a later `SubgraphCallable` could be assigned the same memory location and we'd end up pull the wrong value from the cache. 

A couple of alternatives would be to:

1. Place a reference to the `SubgraphCallable` in cached value which would prevent unwanted garbage collection. So instead of just caching the serialized `SubgraphCallable`, we would cache the tuple `(<serialized-subgraph>, subgraph)`. This would work, but is messy.

2. Use `weakref.finalize` to ensure we remove the `SubgraphCallable` from the cache when it is gc'ed

I have a preference for the second option, so I'll work on that and push up a commit to see what you think

**Comment by jrbourbeau** [comment]
Turns out that one currently can't make weak references to `SubgraphCallable`s as they don't have `"__weakref__"` in their [`"__slots__"` attribute](
https://github.com/dask/dask/blob/5d5b43b4373677ff5fb7cf25eb4bdfb514cf3e76/dask/optimization.py#L956). After exploring what that means for us here (xref https://github.com/dask/distributed/pull/3595/commits/58aa113b7312f6207a98f26611ecdf88846f316f) I think I've changed my mind and prefer option 1.

In the most recent commit we now store a reference to the `SubgraphCallable` object in the cache to prevent the `SubgraphCallable` from being garbage collected prior to eviction from the LRU cache

**Comment by mrocklin** [comment]
> because SubgraphCallables aren't hashable

Alternatively, can we make SubgraphCallables hashable?

**Comment by andrewfulton9** [comment]
I made a [PR](https://github.com/dask/dask/pull/6424) in dask related to this PR that makes `SubgraphCallable` hashable.

**Comment by jrbourbeau** [comment]
Thanks @andrewfulton9! Closing in favor of https://github.com/dask/dask/pull/6424

**Pull request closed without merging**
