### PR TITLE
Remove parse/format functions from utils

### PR DESCRIPTION
**Pull request by mrocklin**
These were moved to dask in https://github.com/dask/dask/pull/4793

### CODE REVIEW

**Comment by TomAugspurger** [comment]
In the next distributed release, do we plan to bump the minimum dask version to something with dask/dask#4793? Else, we'll need to temporarily keep both implementations around.

**Comment by mrocklin** [comment]
I'm more than happy to bump the minimum dask version aggressively, but I'm
also happy waiting on this PR until after the next release (otherwise dev
workflows will probably get more confusing).

**Comment by TomAugspurger** [comment]
+1 for waiting for the next dask release and bumping the minimum version.

**Comment by mrocklin** [comment]
I think that this was done elsewhere.

**Pull request closed without merging**
