### PR TITLE
Set kernel-level TCP timeout

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by mrocklin** [comment]
```
distributed/tests/test_client.py::test_Future_exception_sync Traceback (most recent call last):
  File "/Users/mrocklin/anaconda/lib/python3.5/multiprocessing/forkserver.py", line 178, in main
    _serve_one(s, listener, alive_r, handler)
  File "/Users/mrocklin/anaconda/lib/python3.5/multiprocessing/forkserver.py", line 212, in _serve_one
    code = spawn._main(child_r)
  File "/Users/mrocklin/anaconda/lib/python3.5/multiprocessing/spawn.py", line 115, in _main
    prepare(preparation_data)
  File "/Users/mrocklin/anaconda/lib/python3.5/multiprocessing/spawn.py", line 221, in prepare
    set_start_method(data['start_method'])
  File "/Users/mrocklin/anaconda/lib/python3.5/multiprocessing/context.py", line 231, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

**Comment by mrocklin** [comment]
```
distributed/tests/test_client.py::test_submit <- distributed/utils_test.py distributed.scheduler - INFO -   Scheduler at:            127.0.0.1:50946
distributed.worker - INFO -       Start worker at:            127.0.0.1:50948
distributed.worker - INFO - Waiting to connect to:            127.0.0.1:50946
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    1.29 GB
distributed.worker - INFO -       Local Directory: /var/folders/y9/b466n_bs0qldppk3rc8hdlfm0000gp/T/worker-mai9h9zs
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Start worker at:            127.0.0.1:50950
distributed.worker - INFO - Waiting to connect to:            127.0.0.1:50946
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          2
distributed.worker - INFO -                Memory:                    2.58 GB
distributed.worker - INFO -       Local Directory: /var/folders/y9/b466n_bs0qldppk3rc8hdlfm0000gp/T/worker-ff3g9fp3
distributed.worker - INFO - -------------------------------------------------
FAILED

=================================== FAILURES ===================================
_________________________________ test_submit __________________________________

    def test_func():
        with pristine_loop() as loop:
            with check_active_rpc(loop, active_rpc_timeout):
>               s, workers = loop.run_sync(lambda: start_cluster(ncores, loop,
                                Worker=Worker, scheduler_kwargs=scheduler_kwargs,
                                worker_kwargs=worker_kwargs))

distributed/utils_test.py:437:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../anaconda/lib/python3.5/site-packages/tornado/ioloop.py:457: in run_sync
    return future_cell[0].result()
../../anaconda/lib/python3.5/site-packages/tornado/concurrent.py:237: in result
    raise_exc_info(self._exc_info)
<string>:3: in raise_exc_info
    ???
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:1021: in run
    yielded = self.gen.throw(*exc_info)
distributed/utils_test.py:394: in start_cluster
    yield [w._start() for w in workers]
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:1015: in run
    value = future.result()
../../anaconda/lib/python3.5/site-packages/tornado/concurrent.py:237: in result
    raise_exc_info(self._exc_info)
<string>:3: in raise_exc_info
    ???
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:792: in callback
    result_list.append(f.result())
../../anaconda/lib/python3.5/site-packages/tornado/concurrent.py:237: in result
    raise_exc_info(self._exc_info)
<string>:3: in raise_exc_info
    ???
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:1021: in run
    yielded = self.gen.throw(*exc_info)
distributed/worker.py:257: in _start
    **self.process_health())
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:1015: in run
    value = future.result()
../../anaconda/lib/python3.5/site-packages/tornado/concurrent.py:237: in result
    raise_exc_info(self._exc_info)
<string>:3: in raise_exc_info
    ???
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:1021: in run
    yielded = self.gen.throw(*exc_info)
distributed/core.py:478: in send_recv_from_rpc
    stream = yield self.live_stream()
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:1015: in run
    value = future.result()
../../anaconda/lib/python3.5/site-packages/tornado/concurrent.py:237: in result
    raise_exc_info(self._exc_info)
<string>:3: in raise_exc_info
    ???
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:1021: in run
    yielded = self.gen.throw(*exc_info)
distributed/core.py:460: in live_stream
    stream = yield connect(self.ip, self.port, timeout=self.timeout)
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:1015: in run
    value = future.result()
../../anaconda/lib/python3.5/site-packages/tornado/concurrent.py:237: in result
    raise_exc_info(self._exc_info)
<string>:3: in raise_exc_info
    ???
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:1024: in run
    yielded = self.gen.send(value)
distributed/core.py:318: in connect
    set_tcp_timeout(stream)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

stream = <tornado.iostream.IOStream object at 0x11281aba8>, timeout = 20
nprobes = 5

    def set_tcp_timeout(stream, timeout=20, nprobes=5):
        """
        Set kernel-level TCP transmission timeout on the stream.
        """
        timeout = int(timeout)
        assert timeout >= nprobes + 1, "Timeout too low"

        sock = stream.socket

        if sys.platform.startswith("win"):
            # https://msdn.microsoft.com/en-us/library/windows/desktop/dd877220(v=vs.85).aspx
            nprobes = 10
        idle = max(2, timeout // 4)
        interval = max(1, (timeout - idle) // nprobes)
        idle = timeout - interval * nprobes
        assert idle > 0

        try:
            if sys.platform.startswith("win"):
                sock.ioctl(socket.SIO_KEEPALIVE_VALS, (1, idle * 1000, interval * 1000))
            else:
                sock.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)
                try:
                    TCP_KEEPIDLE = socket.TCP_KEEPIDLE
                    TCP_KEEPINTVL = socket.TCP_KEEPINTVL
                    TCP_KEEPCNT = socket.TCP_KEEPCNT
                except AttributeError:
                    if sys.platform == "darwin":
                        TCP_KEEPIDLE = 0x10  # (named "TCP_KEEPALIVE" in C)
                        TCP_KEEPINTVL = 0x101
                        TCP_KEEPCNT = 0x102
                    else:
                        TCP_KEEPIDLE = None

                if TCP_KEEPIDLE is not None:
>                   sock.setsockopt(socket.SOL_TCP, socket.TCP_KEEPCNT, nprobes)
E                   AttributeError: module 'socket' has no attribute 'TCP_KEEPCNT'
```

**Comment by pitrou** [comment]
> RuntimeError: context has already been set

That's probably not due to this PR. Did you get this error before?

**Comment by pitrou** [comment]
> AttributeError: module 'socket' has no attribute 'TCP_KEEPCNT'

Oh, well, my bad.

**Comment by mrocklin** [comment]
> That's probably not due to this PR. Did you get this error before?

Indeed, this does show up on master.  It's new since the forkserver change.

**Comment by pitrou** [comment]
What does the folliowing print?
```
$ python -c "import distributed, multiprocessing; print(multiprocessing.get_start_method(allow_none=True))"
None
```

**Comment by mrocklin** [comment]
fork

**Comment by pitrou** [comment]
That's weird. Perhaps some grepping will help? `grep start_method /Users/mrocklin/anaconda/lib/python3.5/`?

**Comment by pitrou** [comment]
Also, how about `python -c "import multiprocessing; print(multiprocessing.get_start_method(allow_none=True))"`?

**Comment by mrocklin** [comment]
None

**Comment by mrocklin** [comment]
```
air:distributed mrocklin$ grep -r start_method /Users/mrocklin/anaconda/lib/python3.5/
Binary file /Users/mrocklin/anaconda/lib/python3.5//multiprocessing/__pycache__/context.cpython-35.opt-1.pyc matches
Binary file /Users/mrocklin/anaconda/lib/python3.5//multiprocessing/__pycache__/context.cpython-35.opt-2.pyc matches
Binary file /Users/mrocklin/anaconda/lib/python3.5//multiprocessing/__pycache__/context.cpython-35.pyc matches
Binary file /Users/mrocklin/anaconda/lib/python3.5//multiprocessing/__pycache__/process.cpython-35.opt-1.pyc matches
Binary file /Users/mrocklin/anaconda/lib/python3.5//multiprocessing/__pycache__/process.cpython-35.opt-2.pyc matches
Binary file /Users/mrocklin/anaconda/lib/python3.5//multiprocessing/__pycache__/process.cpython-35.pyc matches
Binary file /Users/mrocklin/anaconda/lib/python3.5//multiprocessing/__pycache__/spawn.cpython-35.opt-1.pyc matches
Binary file /Users/mrocklin/anaconda/lib/python3.5//multiprocessing/__pycache__/spawn.cpython-35.opt-2.pyc matches
Binary file /Users/mrocklin/anaconda/lib/python3.5//multiprocessing/__pycache__/spawn.cpython-35.pyc matches
Binary file /Users/mrocklin/anaconda/lib/python3.5//multiprocessing/__pycache__/synchronize.cpython-35.opt-1.pyc matches
Binary file /Users/mrocklin/anaconda/lib/python3.5//multiprocessing/__pycache__/synchronize.cpython-35.opt-2.pyc matches
Binary file /Users/mrocklin/anaconda/lib/python3.5//multiprocessing/__pycache__/synchronize.cpython-35.pyc matches
/Users/mrocklin/anaconda/lib/python3.5//multiprocessing/context.py:    def get_start_method(self, allow_none=False):
/Users/mrocklin/anaconda/lib/python3.5//multiprocessing/context.py:    def set_start_method(self, method=None):
/Users/mrocklin/anaconda/lib/python3.5//multiprocessing/context.py:    _start_method = None
/Users/mrocklin/anaconda/lib/python3.5//multiprocessing/context.py:    def set_start_method(self, method, force=False):
/Users/mrocklin/anaconda/lib/python3.5//multiprocessing/context.py:    def get_start_method(self, allow_none=False):
/Users/mrocklin/anaconda/lib/python3.5//multiprocessing/context.py:    def get_all_start_methods(self):
/Users/mrocklin/anaconda/lib/python3.5//multiprocessing/context.py:        _start_method = 'fork'
/Users/mrocklin/anaconda/lib/python3.5//multiprocessing/context.py:        _start_method = 'spawn'
/Users/mrocklin/anaconda/lib/python3.5//multiprocessing/context.py:        _start_method = 'forkserver'
/Users/mrocklin/anaconda/lib/python3.5//multiprocessing/context.py:        _start_method = 'spawn'
/Users/mrocklin/anaconda/lib/python3.5//multiprocessing/context.py:def _force_start_method(method):
/Users/mrocklin/anaconda/lib/python3.5//multiprocessing/process.py:            if self._start_method is not None:
/Users/mrocklin/anaconda/lib/python3.5//multiprocessing/process.py:                context._force_start_method(self._start_method)
/Users/mrocklin/anaconda/lib/python3.5//multiprocessing/spawn.py:from . import get_start_method, set_start_method
/Users/mrocklin/anaconda/lib/python3.5//multiprocessing/spawn.py:        start_method=get_start_method(),
/Users/mrocklin/anaconda/lib/python3.5//multiprocessing/spawn.py:    if 'start_method' in data:
/Users/mrocklin/anaconda/lib/python3.5//multiprocessing/spawn.py:        set_start_method(data['start_method'])
/Users/mrocklin/anaconda/lib/python3.5//multiprocessing/synchronize.py:        name = ctx.get_start_method()
Binary file /Users/mrocklin/anaconda/lib/python3.5//site-packages/joblib/test/__pycache__/test_parallel.cpython-35.pyc matches
/Users/mrocklin/anaconda/lib/python3.5//site-packages/joblib/test/test_parallel.py:        start_method = context.get_start_method()
/Users/mrocklin/anaconda/lib/python3.5//site-packages/joblib/test/test_parallel.py:                assert_equal(start_method, 'spawn')
/Users/mrocklin/anaconda/lib/python3.5//site-packages/joblib/test/test_parallel.py:                assert_equal(start_method, 'fork')
/Users/mrocklin/anaconda/lib/python3.5//site-packages/joblib/test/test_parallel.py:            assert_equal(start_method, env_method)
```

**Comment by mrocklin** [comment]
The problem goes away if I don't preload `distributed`

**Comment by pitrou** [comment]
It seems to be something with the latest Dask release. If you use Dask master, it should be ok AFAICT.

**Comment by mrocklin** [comment]
Indeed.  I'm curious, how did you track that down?

**Comment by pitrou** [comment]
I tried to reproduce on a OS X VM. It occurred to me that simply importing `dask` changed the "start method", and I simply checked whether it reproduced with the latest master.

**Comment by mrocklin** [comment]
There are a few OS-X failures, but I don't think that they're related to the changes here.  Unfortunately I don't have any tests handy with long-running GIL-holding operations.

**Comment by pitrou** [comment]
Note that `test_iterator_gather` is flaky on Windows regardless of this patch.

**Comment by pitrou** [comment]
By the way, the issue on Dask 0.12.0 was that it created a ThreadPook at import time.

**Comment by pitrou** [comment]
I've filed https://bugs.python.org/issue28779 for the multiprocessing issue you encountered on OS X. Perhaps we should call `set_forkserver_preload()` only in the test suite.

**Comment by mrocklin** [comment]
Worst case we could always try importing numpy, pandas, tornado, and other expensive-to-import dependencies if they are importable within this process. 

```python
In [1]: %time import pandas, numpy, tornado, dask, tornado, blosc, lz4, snappy, h5py, bokeh, dask.dataframe, dask.array
CPU times: user 816 ms, sys: 256 ms, total: 1.07 s
Wall time: 832 ms

In [2]: %time import distributed
CPU times: user 120 ms, sys: 8 ms, total: 128 ms
Wall time: 124 ms
```

**Comment by pitrou** [comment]
Here the problem was `dask`, not `distributed`. Perhaps we can leave the preload enabled in the next release and wait until users complain.

**Comment by mrocklin** [comment]
So this would only occur if they imported dask, did some dask.dataframe work that created a multiprocessing.Lock, and then imported distributed?

**Comment by pitrou** [comment]
No, the only problematic situation is if Dask (or any dependency) would create a Lock simply by virtue of being imported.

**Comment by mrocklin** [comment]
Is a `threading.Lock` problematic or only instances of `multiprocessing.Lock`?  After quickly looking through the code I don't see `multiprocessing.Lock` called at import time.  I do see `threading.Lock` called at import time.

**Comment by pitrou** [comment]
Many `multiprocessing` resources apparently, including `Lock`, `Queue` and even `ThreadPool`. `threading` resources are ok.

**Comment by mrocklin** [comment]
Perhaps we can identify the resource created at dask/dask import time and remove it.

**Comment by pitrou** [comment]
Hmm, I'm not sure I understand you. This is already solved with dask master.

**Comment by mrocklin** [comment]
Oh, ok never mind then.  It seems like this is solved from our point of view then assuming that we co-release dask/dask and dask/distributed together next time around?

**Comment by pitrou** [comment]
Yes it is. As long as none of our dependencies create multiprocessing resources at import time...

**Comment by pitrou** [comment]
A quick test on a single Linux machine using iptables seems to confirm this PR allows distributed to notice connection loss quite fast.

**Comment by pitrou** [comment]
I've made the timeout value configurable. I'm also not sure what a good default value is. Since distributed will be used mostly in excellent network conditions (e.g. datacenters), I think a short value such as 30s. is okay.

**Comment by pitrou** [comment]
Will merge if no further comments.

**Comment by mrocklin** [comment]
+1 from me

**Pull request merged**
