### PR TITLE
S3 csv

### PR DESCRIPTION
**Pull request by mrocklin**
This copies the read_csv functionality over from HDFS to S3.

This is more-or-less a copy-paste-edit job.  It might be worthwhile looking into how to generalize this in the future.  There was a fair amount of code duplication.

### CODE REVIEW

**Comment by mrocklin** [comment]
@martindurant when you have time if you could give this a quick review that would be appreciated.

**Comment by mrocklin** [comment]
@martindurant are we good to go with this?

**Comment by martindurant** [comment]
All good, +1

**Comment by mrocklin** [comment]
Thanks for the attentive review.  That was very helpful.

**Pull request merged**
