### PR TITLE
Fix implicit string concatenation in Popen args

### PR DESCRIPTION
**Pull request by dhirschfeld**
Also removed the `--scheduler` argument which caused problems for some users

### CODE REVIEW

**Comment by dhirschfeld** [comment]
As per gitter conversation the `--scheduler` argument was causing the below error for me:
```
λ dask-worker --nthreads=1 --nprocs=4 %SCHEDULER%
distributed.nanny - INFO -         Start Nanny at:         
distributed.nanny - INFO -         Start Nanny at:         
distributed.nanny - INFO -         Start Nanny at:         
distributed.nanny - INFO -         Start Nanny at:         
Error: no such option: --scheduler
Error: no such option: --scheduler
Error: no such option: --scheduler
Error: no such option: --scheduler
```

**Comment by mrocklin** [comment]
Oh wow, now I feel dumb :)

**Comment by dhirschfeld** [comment]
:stuck_out_tongue_winking_eye:

**Comment by mrocklin** [comment]
Missing that comma feels silly.  Verified that this works well on my windows box.  Merging on passed tests

**Comment by dhirschfeld** [comment]
It's easy to do and pretty confusing that it works on some platforms and not others. Glad I could contribute - it's a pretty amazing/awesome project :)

**Pull request merged**
