### PR TITLE
Optionally use pickle5

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/dask/distributed/issues/2495

This extends the changes in PR ( https://github.com/dask/distributed/pull/3784 ) to also support using `pickle5` (when available). Depends on PR ( https://github.com/cloudpipe/cloudpickle/pull/370 ), which is in `cloudpickle` version `1.5.0`.

cc @pierreglaser @pitrou

### CODE REVIEW

**Comment by jakirkham** [comment]
Am seeing [this failure (snippet below)]( https://travis-ci.org/github/dask/distributed/jobs/696952581#L1527 ). Think it has something to do with how the `dispatch_table` is being used in cloudpickle. Discussion can be found in thread ( https://github.com/cloudpipe/cloudpickle/pull/368#pullrequestreview-428530129 ).

<details>

```python
__________________________ test_chained_error_message __________________________

c = <Client: not connected>
s = <Scheduler: "tcp://127.0.0.1:46028" processes: 0 cores: 0>
a = <Worker: 'tcp://127.0.0.1:44402', 0, Status.closed, stored: 0, running: 0/1, ready: 0, comm: 0, waiting: 0>
b = <Worker: 'tcp://127.0.0.1:45385', 1, Status.closed, stored: 0, running: 0/2, ready: 0, comm: 0, waiting: 0>

    @gen_cluster(client=True)
    async def test_chained_error_message(c, s, a, b):
        def chained_exception_fn():
            class MyException(Exception):
                def __init__(self, msg):
                    self.msg = msg
    
                def __str__(self):
                    return "MyException(%s)" % self.msg
    
            exception = MyException("Foo")
            inner_exception = MyException("Bar")
    
            try:
                raise inner_exception
            except Exception as e:
                raise exception from e
    
        f = c.submit(chained_exception_fn)
        try:
>           await f

distributed/tests/test_worker.py:406: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Future: cancelled, key: chained_exception_fn-103274397419cf5bcfd188fdd51fd53a>
raiseit = True

    async def _result(self, raiseit=True):
        await self._state.wait()
        if self.status == "error":
            exc = clean_exception(self._state.exception, self._state.traceback)
            if raiseit:
                typ, exc, tb = exc
>               raise exc.with_traceback(tb)

distributed/client.py:235: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   raise exception from e
E   test_worker.test_chained_error_message.<locals>.chained_exception_fn.<locals>.MyException: MyException(Foo)

distributed/tests/test_worker.py:402: MyException

During handling of the above exception, another exception occurred:

    def test_func():
        result = None
        workers = []
        with clean(timeout=active_rpc_timeout, **clean_kwargs) as loop:
    
            async def coro():
                with dask.config.set(config):
                    s = False
                    for i in range(5):
                        try:
                            s, ws = await start_cluster(
                                nthreads,
                                scheduler,
                                loop,
                                security=security,
                                Worker=Worker,
                                scheduler_kwargs=scheduler_kwargs,
                                worker_kwargs=worker_kwargs,
                            )
                        except Exception as e:
                            logger.error(
                                "Failed to start gen_cluster, retrying",
                                exc_info=True,
                            )
                            await asyncio.sleep(1)
                        else:
                            workers[:] = ws
                            args = [s] + workers
                            break
                    if s is False:
                        raise Exception("Could not start cluster")
                    if client:
                        c = await Client(
                            s.address,
                            loop=loop,
                            security=security,
                            asynchronous=True,
                            **client_kwargs,
                        )
                        args = [c] + args
                    try:
                        future = func(*args)
                        if timeout:
                            future = asyncio.wait_for(future, timeout)
                        result = await future
                        if s.validate:
                            s.validate_state()
                    finally:
                        if client and c.status not in ("closing", "closed"):
                            await c._close(fast=s.status == "closed")
                        await end_cluster(s, workers)
                        await asyncio.wait_for(cleanup_global_workers(), 1)
    
                    try:
                        c = await default_client()
                    except ValueError:
                        pass
                    else:
                        await c._close(fast=True)
    
                    def get_unclosed():
                        return [c for c in Comm._instances if not c.closed()] + [
                            c
                            for c in _global_clients.values()
                            if c.status != "closed"
                        ]
    
                    try:
                        start = time()
                        while time() < start + 5:
                            gc.collect()
                            if not get_unclosed():
                                break
                            await asyncio.sleep(0.05)
                        else:
                            if allow_unclosed:
                                print(f"Unclosed Comms: {get_unclosed()}")
                            else:
                                raise RuntimeError("Unclosed Comms", get_unclosed())
                    finally:
                        Comm._instances.clear()
                        _global_clients.clear()
    
                    return result
    
            result = loop.run_sync(
>               coro, timeout=timeout * 2 if timeout else timeout
            )

distributed/utils_test.py:954: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../miniconda/envs/dask-distributed/lib/python3.7/site-packages/tornado/ioloop.py:532: in run_sync
    return future_cell[0].result()
distributed/utils_test.py:912: in coro
    result = await future
../../../miniconda/envs/dask-distributed/lib/python3.7/asyncio/tasks.py:442: in wait_for
    return fut.result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

c = <Client: not connected>
s = <Scheduler: "tcp://127.0.0.1:46028" processes: 0 cores: 0>
a = <Worker: 'tcp://127.0.0.1:44402', 0, Status.closed, stored: 0, running: 0/1, ready: 0, comm: 0, waiting: 0>
b = <Worker: 'tcp://127.0.0.1:45385', 1, Status.closed, stored: 0, running: 0/2, ready: 0, comm: 0, waiting: 0>

    @gen_cluster(client=True)
    async def test_chained_error_message(c, s, a, b):
        def chained_exception_fn():
            class MyException(Exception):
                def __init__(self, msg):
                    self.msg = msg
    
                def __str__(self):
                    return "MyException(%s)" % self.msg
    
            exception = MyException("Foo")
            inner_exception = MyException("Bar")
    
            try:
                raise inner_exception
            except Exception as e:
                raise exception from e
    
        f = c.submit(chained_exception_fn)
        try:
            await f
        except Exception as e:
>           assert e.__cause__ is not None
E           AssertionError: assert None is not None
E            +  where None = MyException('Foo').__cause__

distributed/tests/test_worker.py:408: AssertionError
```

**Comment by jakirkham** [comment]
We now have all tests passing using the development version of `cloudpickle` 😄

**Comment by jakirkham** [comment]
@fjetter, if you have time/interest, it might be worth trying this out. Would need to install `pickle5` and `cloudpickle`, based off of PR ( https://github.com/cloudpipe/cloudpickle/pull/370 ). If you do try this, would be interested in hearing how things go for you 🙂

**Comment by jakirkham** [comment]
cc-ing @jcrist (in case you are interested 😉)

**Comment by quasiben** [comment]
Generally, this looks good.  I spoke briefly with @jakirkham about this and thought I should bring it up here as well.  Do others have issues with bumping cloudpickle version.  Are there dask subprojects that have a pinned cloudpickle version for a particular reason ?

**Comment by mrocklin** [comment]
I'm comfortable bumping the cloudpickle version.  I don't know of anyone
who is pinned.  I feel a little odd bumping it to something that was
released this week, but not entirely against.

**Comment by jakirkham** [comment]
That's a fair concern. We could try to add some conditional logic here to handle an older `cloudpickle`. Alternatively we could just wait on merging this until after today's release ships, which would give us a 2 week gap between the `cloudpickle` release and this change.

**Comment by mrocklin** [comment]
A two week gap sounds good to me.  I suspect that we'll have a good sense
then if things are wonky.

**Comment by jakirkham** [comment]
2.20.0 is now out. So I think we should be good here. Please let me know if we need anything else 🙂

**Comment by mrocklin** [comment]
How confident are we that defaults will pick this up by the next release cycle?

**Comment by jakirkham** [comment]
Sorry pick-up what?

**Comment by mrocklin** [comment]
cloudpickle 1.5

**Comment by jakirkham** [comment]
Sure. I mean that will be a requirement to update `distributed`. So I would think yes.

**Comment by jakirkham** [comment]
cc @jjhelmus (in case you have thoughts on updating `cloudpickle` in `defaults`)

**Comment by jjhelmus** [comment]
I do not foresee any issue updating `cloudpickle` prior to the next release of `distributed` in `defaults`.  We are currently holding off building new packages as we are preparing for a release of Anaconda Individual Edition but once that is out updates should proceed at a normal pace. 

In the future @anaconda-pkg-build is a good handle to ping on these type of issue as it goes to multiple engineers at Anaconda who do packaging.

**Comment by jakirkham** [comment]
> In the future `@anaconda-pkg-build` is a good handle to ping on these type of issue as it goes to multiple engineers at Anaconda who do packaging.

Good tip! Thanks Jonathan. Will keep this in mind for the future 🙂

**Comment by jakirkham** [comment]
Any other questions @mrocklin? 🙂

**Comment by mrocklin** [comment]
1.5 seems to be released.  If we're highly confident that there won't be any issues with this then yes, let's go ahead.  If you think that there is some small chance of issues then let's wait.  I think that you're probably the most educated person to make this call :)

**Pull request merged**
