### PR TITLE
Make workers table sortable

### LINKED ISSUE #8140: Allow workers table in info pages to be sorted
In the info pages we have a table of workers like the following:

Screenshot 2023-08-29 at 7 32 30 AM

It would be convenient to be able to sort by column.  For example, in a case where you have 1000 workers, one of which is still processing a task, it would be nice to be able to click on the Processing column to have that one worker come up to the top. 

These pages are raw HTML written by me, with very little web experience.  I suspect that we could include some very basic JavaScript on these pages and get something that accomplished this easily.

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Closes #8140

ezgif-3-21485f64bc

- Vendor in https://github.com/tofsjonas/sortable to the static directory (which uses the [Unlicense license](https://github.com/tofsjonas/sortable/blob/main/LICENSE) and can be freely distributed) 
- Add sortable to the base template
  - Fixed relative URL templating for favicon too
- Added missing `<thead>` and `<tbody>` sections to the table which are required by sortable
- Added sortable class to the table

cc @mrocklin @jrbourbeau

### CODE REVIEW

**Comment by mrocklin** [comment]
From a UX perspective this looks good to me.  +1 from me if you want to merge @jacobtomlinson 

If you had some great desire to do *even more* work I'd suggest lighter colors on the table (this change makes things feel visually darker).  That's just me being picky though, when really I should feel very grateful.  Thanks @jacobtomlinson !

**Comment by mrocklin** [comment]
Also, playtesting with this caused me to find this other error (unrelated) https://github.com/dask/distributed/issues/8155 so we get an extra bonus :)

**Comment by mrocklin** [comment]
I would normally merge, but I'm unsure of the state of CI here.   I'll defer that to others with more recent experience I think.

**Comment by jacobtomlinson** [comment]
> I'd suggest lighter colors on the table

The styling that has been applied came with the sortable CSS file. If other folks have suggestions about tweaking it I'd be happy to review but I don't intend on putting much more time into this.

I am also unsure of the CI status here, perhaps @hendrikmakait could weigh in?

**Comment by hendrikmakait** [comment]
`test_resources_reset_after_cancelled_task` should be unrelated, so 👍 from the CI side.

**Review by hendrikmakait — APPROVED** [review]
Adding @mrocklin's and my partial 👍 makes this an LGTM!

**Pull request merged**
