### PR TITLE
Add GPU metrics to SystemMonitor

### PR DESCRIPTION
**Pull request by charlesbluca**
This PR adds the GPU metrics available in `WorkerState.metrics` and `WorkerState.extra` to the `SystemMonitor`; coupled with #4657, this should make it easier to generate time series of (GPU) workers in the dashboard / performance report.

- [ ] Closes #xxxx
- [ ] Tests added / passed
- [ ] Passes `black distributed` / `flake8 distributed` / `isort distributed`

### CODE REVIEW

**Comment by charlesbluca** [comment]
Now that #4657 is merged, this PR should be expanded to add static GPU metrics (such as name and memory total) to the results of `scheduler.get_worker_monitor_info()` if `nvml` is available.

**Comment by quasiben** [comment]
Thanks @charlesbluca .  This looks good.  I ran the tests locally and things pass. If CI passes here we can merge in

**Comment by charlesbluca** [comment]
I believe `distributed/tests/test_diskutils.py::test_workspace_concurrency_intense` is flaky, I can run the tests again though if need be.

**Comment by quasiben** [comment]
Yes, I think `test_workspace_concurrency_intense` is unrelated. Merging in.  Thanks again @charlesbluca !

**Pull request merged**
