### PR TITLE
Ensure output chunks in P2P rechunking are distributed homogeneously

### PR DESCRIPTION
**Pull request by fjetter**
This PR includes two changes. One refactoring and one functional change. Separating those into two PRs would be technically possible but would be much more work.

1. The abstraction for `ShuffleSpec` is refactored

- the `output_partitions` property is introduced that allows one to iterate over all the output partition indices. This was chosed to be an iterator to avoid full materialization of the cross product in the P2P rechunking case. I vaguely remember a perf related issue there. I think this introduces a little complexity but not too much
- The new method `pick_worker` does what the name suggests without the previous indirection. The previous code path felt overly complex. The new structure feels much more streamlined and avoids passing around closures.

2. Ensure that the rechunk output partitions are homogeneously distributed

The prior code was using a hash+mod function to assign output partitions to workers. This is mathematically susceptible to heavy skews in the distribution, particularly if the hash function is of poor quality

To convince yourself about this, here is a small sim

```python
import pandas as pd
import hashlib
from collections import defaultdict
nworkers = 50
parts = [(ix, jx, kx) for ix in range(10) for jx in range(10) for kx in range(10)]

def range_sharding():
        sim = defaultdict(int)
        for ix in range(len(parts)):
            i = nworkers * ix // len(parts)
            sim[i] += 1
        return pd.Series(sim).describe()
range_sharding()


def hash_sharding():
    def _hash(obj):
        m = hashlib.sha1()
        m.update(str(obj).encode())
        return int.from_bytes(m.digest(), "big")

    sim = defaultdict(int)
    for part in parts:
        i = _hash(part) % nworkers
        sim[i] += 1
    return pd.Series(sim).describe()
hash_sharding()
```

```python
In [19]: hash_sharding()
Out[19]:
count    50.000000
mean     20.000000
std       4.772369
min      10.000000
25%      17.000000
50%      20.000000
75%      23.000000
max      36.000000
dtype: float64

In [20]: range_sharding()
Out[20]:
count    50.0
mean     20.0
std       0.0
min      20.0
25%      20.0
50%      20.0
75%      20.0
max      20.0
dtype: float64
```

TODO: Test for the output distribution

### CODE REVIEW

**Comment by hendrikmakait** [comment]
(not here): You may want to A/B test this, I vaguely remember some performance issue with range partitioning that led me to consider hash partitioning in the first place.

**Comment by fjetter** [comment]
> You may want to A/B test this

obviously!

mixed results. 

good-ish
image


not good
image
image


> I vaguely remember some performance issue with range partitioning that led me to consider hash partitioning in the first place.

I think this was due to how the mapping was generated but I have to look more closely.
The skew I observed was bad and there was a rather long tail in the computation. I also suspect this to be much worse for large clusters since single workers will then be heavily overloaded while others are not saturated. We're only running on relatively small clusters in the benchmarking suite

**Comment by fjetter** [comment]
I looked more closely into these memory spikes and the results are interesting. Not very concerning but a little.

What is causing the memory to peak is not P2P itself. P2P is humming along *very* nicely and once the entire thing is up and running, the cluster memory is constant at close to zero. However, at the start of the computation it seems that the comm buffers are not flushed as quickly with this PR than they are on main, causing more memory to build up before everything hums along.

Main / hash sharding

image

This PR / range sharding

image

(The actual allocations are what you'd expect and pretty much the same for both runs)


My suspicion is that this is because the workers have to connect to more workers to process a single input shard now and this takes a little more time with a cold connection pool. Particularly if the event loop is blocked, even a little, this can slow down the initial connection attempt significantly due to the handshake.

**Comment by hendrikmakait** [comment]
> not good
> image

This looks like the issue I had in mind.

Thanks for diving deeper into this, so far I never got around to it. What's the current state here, should we do further root-cause analysis to avoid those spikes?

**Comment by fjetter** [comment]
> Thanks for diving deeper into this, so far I never got around to it. What's the current state here, should we do further root-cause analysis to avoid those spikes?

Yes, I'm convinced that this is something we should address. The current hashing is generating very long tails and the imhomogeneous data distributtion after the shuffle can cause downstream processes to behave less than optimal. we should fix this. I think a first pass could be to use a better hash function but ultimately a stable distribution is much better.

Zooming out a little, even if P2P works nicely after this startup, we should understand why we have these spikes in the beginning. I suspect this is some kind of combination of cold connection pools, too big/small buffers or limiters or something else. I suspect that understanding this behavior better will be required anyhow to improve performance while keeping memory stability

**Pull request merged**
