### PR TITLE
Use numpy.nbytes rather than memoryview.nbytes

### PR DESCRIPTION
**Pull request by mrocklin**
This avoids a python 2 issue

### CODE REVIEW

**Comment by pitrou** [comment]
Looks fine to me.

**Comment by mrocklin** [comment]
Running into other issues here that you might be able to help with actually @pitrou.  I like memoryviews, but I'm having trouble creating a very simple memory view with a linear shape and itemsize=1.

I can get to itemsize=1 with `my_numpy_array.view('u1').data`, but I'm not sure how to flatten out a memoryview's shape in a way that doesn't involve a copy on the numpy side.

**Comment by mrocklin** [comment]
I want this:

```python
x = np.ones((10, 10, 10, 10, 10, 10, 10))
x.flatten().view('u1').data
```

But flatten involves a copy.  I have yet to find find API either in numpy or the Python memoryview that lets me do this without a copy.

**Comment by mrocklin** [comment]
Ah, ravel

**Comment by pitrou** [comment]
The cast() method should work (but perhaps not on Python 2):
```
>>> x = np.ones((10, 10, 10, 10, 10, 10, 10))
>>> m = memoryview(x)
>>> m.shape, m.nbytes, m.itemsize
((10, 10, 10, 10, 10, 10, 10), 80000000, 8)
>>> m = m.cast('B')
>>> m.shape, m.nbytes, m.itemsize
((80000000,), 80000000, 1)
```

**Comment by pitrou** [comment]
`array.ravel()` will make a copy if necessary (if the array isn't contiguous), while `memoryview.cast()` will refuse to work on non-contiguous arrays.

**Comment by mrocklin** [comment]
I think we want ravel then.  We're willing to copy.  https://github.com/dask/distributed/pull/833

**Pull request merged**
