### PR TITLE
Add 'local_directory' option to dask-ssh

### PR DESCRIPTION
**Pull request by abduhbm**
This PR enables `--local-directory` option in `dask-ssh` cli to change the default location where workers and scheduler place their files.

### CODE REVIEW

**Comment by abduhbm** [comment]
It is on the SSH machine. `dask-ssh` by default places `dask-worker-space` in the user home directory which can create disk space problems in environments with quota-enabled network home shared by NFS. 

Unknown options can be passed in Click. Please see [Forwarding Unknown Options](http://click.pocoo.org/5/advanced/#forwarding-unknown-options).

**Comment by TomAugspurger** [comment]
> It is on the SSH machine. 

Can you clarify that in the docs?

**Comment by abduhbm** [comment]
I updated the docs for the `--local-directory` option to: 
`Directory to use on all cluster nodes to place workers and scheduler files.
`
> Thoughts on just forwarding all additional arguments through to dask-worker & dask-scheduler?

I think it can be don. I will do another PR for this. 

Thanks @TomAugspurger

**Comment by TomAugspurger** [comment]
Thanks @abduhbm!

**Pull request merged**
