### PR TITLE
S3 loading

### PR DESCRIPTION
**Pull request by martindurant**
Heavily based/copied from the same code in hdfs

No tests possible until we have decided on a place to put appropriate files
for download.

Note: Loader for (set of) http URLs would look identical, replacing 
`s3.Object(bucket, key).get()['Body'].read()`
->
`urllib.request.urlopen(url).read()`
(or the py2 equivalent)

### CODE REVIEW

**Comment by mrocklin** [comment]
The existing S3 tests use the `distributed-test` bucket.  You may have access to this.

**Comment by martindurant** [comment]
I have read access only. It would be the natural place to put test data.

**Comment by mrocklin** [comment]
Are you logged in to the aws console under your continuum-dev account?  console.aws.amazon.com

I'm not very familiar with how to manage permissions on AWS.  Attempts to add you and the group have been unfruitful.  All of the `aws-dev` group has permissions though (perhaps that includes you?)  I imagine that others might have more ability here.

**Comment by martindurant** [comment]
I do have a condinuum-dev account, and I thought this key was from there, but I don't know how to check. I do have write access to blaze-data with it. I'll ask around on Monday to sort it out.

**Comment by martindurant** [comment]
Test fails, issue with read_bytes when lazy=True

**Comment by mrocklin** [comment]
What is the status of this?

**Comment by martindurant** [comment]
@mrocklin : help requested here, I don't know why this isn't working. The futures seem to stay pending.

**Comment by martindurant** [comment]
avro reader requires fastavro: should be hard dependency, or gracefully ignored if not present?

**Comment by mrocklin** [comment]
Gracefully ignored please.  I recommend putting it into travis.ci, not putting it into requirements.txt, and using pytest.importorskip('fastavro') in test files.

**Comment by mrocklin** [comment]
Closing in favor of #162  and #159

**Pull request closed without merging**
