### PR TITLE
Client shutdown cluster properly & suppress tornado errors

### PR DESCRIPTION
**Pull request by bschreck**
Fixes issues #1031 and #1042 

I'm not sure how to test because the LocalCluster.close() method is implemented as coroutine callbacks which are not guaranteed to finish by the end of the Client.shutdown() method. I found two tests in test_client that are supposed to test shutdown but they both don't load the LocalCluster and so don't test to see if it shut down.

### CODE REVIEW

**Comment by mrocklin** [comment]
Hey @bschreck, thanks for working on this.  

I suspect that the `all_fds` flag is required to properly clean up file descriptors in tests quickly enough so that we don't overwhelm the testing machine.  Any suggestions?

**Comment by bschreck** [comment]
Hmm yeah I guess that issue can just go unresolved until a solution that passes the test is figured out. I'll just remove that change for now.

**Comment by mrocklin** [comment]
Sorry, looks like the error is still there.  My analysis with all_fds may not have been accurate.

**Comment by mrocklin** [comment]
This has been merged in https://github.com/dask/distributed/commit/e9357c9d84b9af960eb9413cb2509a606cd12dce

**Pull request closed without merging**
