### PR TITLE
Fixed Long Running Regression Bug

### LINKED ISSUE #5975: Workers with long running tasks are only ones that accept new work
This is almost certainly fallout from the fix for https://github.com/dask/distributed/issues/5332 .

With the latest versions (since 2022.1.0, through 2022.3.0), we're seeing occupancy numbers like `-1531476972.28 us` on workers with long running tasks that have seceded. To the scheduler, this looks very appealing and they are the only workers that get assigned work. As one might imagine, this really inhibits processing speed on a large cluster.

### PR DESCRIPTION
**Pull request by edyounis**
- [X] Closes #5975
- [X] Tests added / passed
- [X] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by wwoods** [comment]
+1 to this PR, as it was needed for our production environment. We currently have to manually apply this patch every time we install dask on a production system.

**Comment by mrocklin** [comment]
cc @crusaderky @fjetter

**Comment by fjetter** [comment]
Closed by https://github.com/dask/distributed/pull/6351

**Pull request closed without merging**
