### PR TITLE
Remove duplication from stealing (was Allow subclasses to control work stealing)

### PR DESCRIPTION
**Pull request by dmcg**
I'd like to be able to exert a bit more control over work stealing - this is a small refactor to give subclasses control over what can be stolen.

See https://dask.discourse.group/t/understanding-work-stealing/335/6

Full disclosure - I haven't worked out how to run the precommit tests!

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Review by gjoseph92 — COMMENTED** [review]
This seems like a reasonable-enough refactor to me. Splitting these things into methods makes them easier to unit-test as well.

@fjetter or @crusaderky might be better ones to look at this though.

**Comment by fjetter** [comment]
Work stealing is currently a hard coded scheduler extension. How would a user set this up and subclass this?

**Comment by fjetter** [comment]
I am a bit concerned in opening this up for custom logic and subclassing. I expect this algorithm to change in the future so maintaining additional public interface comes with a cost. I would like to understand better how this would look like before we're making any decision.
If it all comes down to patching the code, I don't consider it necessary to make this public.

In the discussion on discourse, there was also the question of whether we're simply dealing with a bug or not. There was also the suggestion to ensure follow up tasks are annotated properly, if possible.

**Comment by crusaderky** [comment]
For those who did not read discourse: the use case of the op is that they have workers across different datacentres and a cross-datacentre transfer is very expensive.

I, too, am worried about adding flexibility and potential for user tweaking on such a delicate subsystem. I am also dubious that your change, alone, is going to be effective at solving your issue. There are many other things in place (regular task scheduling and worker retirement, to name two) that will cause you to end up with data in a different datacentre.

**Comment by gjoseph92** [comment]
@fjetter and @crusaderky, agreed with everything you've said. I also don't think we should support users customizing stealing logic. Nor do I think that making this change will even make that any easier (since it's an extension, as mentioned).

As mentioned on discourse, annotating all tasks with restrictions is the best solution.

I just thought this diff itself was a small improvement in readability, even though it wouldn't really help achieve the intended effect (which is why I wouldn't be concerned about the bigger-picture risks if it got merged.) But rereading it, the benefit is small, so it doesn't seem like a change worth making right now.

**Comment by dmcg** [comment]
Thanks for the consideration folks.

In defence of this PR I would say that

1. (I don't believe) that it changes any existing behaviour.
2. It leaves the code in a better state than it was.
3. Given the difficulty of installing a customised WorkStealing it is very unlikely to be abused by anyone who doesn't understand the consequences.
4. Arguably there is a bug in the current work-stealing (@ian-r-rose thought this) that this would facilitate fixing

My organisation is conducting trials to evaluate the viability of cross data-centre operation. We don't expect it to be without issues, but, as with most of distributed, we believe that the benefits of data-proximate computation might outweigh the times where it introduces complications.

**Comment by fjetter** [comment]
> (I don't believe) that it changes any existing behaviour.

It doesn't. That's not what I'm concerned about. As trivial as this may seem but I am concerned about 
A) Not underscoring these methods
B) Signaling that it is fine to overwrite them


> Arguably there is a bug in the current work-stealing (@ian-r-rose thought this) that this would facilitate fixing

Is this documented somewhere?


> My organisation is conducting trials to evaluate the viability of cross data-centre operation. We don't expect it to be without issues, but, as with most of distributed, we believe that the benefits of data-proximate computation might outweigh the times where it introduces complications.

For widespread usage of cross-datacenter clusters you will very likely want to have more sophisticated features than this. You might in-fact be better off disabling work stealing if this is a concern of yours. Generally speaking, what you want to have to support sane cross-datacenter applications is that we track individual bandwidths and latencies much more granularly than we do. You will likely encounter many places where the scheduler makes an awful decision because it underestimates network cost.

**Comment by dmcg** [comment]
Discussion seems to have migrated to https://dask.discourse.group/t/understanding-work-stealing/335/6

**Comment by gjoseph92** [comment]
@dmcg is https://github.com/gjoseph92/dask-worker-pools working for you? Should we close this PR for now?

**Comment by dmcg** [comment]
I've removed all the usefulness leaving behind just the removal of duplication. Feel free to either take it as making things slightly better, or discard as not worth the effort.

**Pull request merged**
