### PR TITLE
Use subprocess for bokeh, kill in application

### LINKED ISSUE #227: Web UI missing components?
When trying out the UI for the first time today I get a figure without two of the components - for example:

image

Using chrome version 49.0.2623.87 (64-bit)

### PR DESCRIPTION
**Pull request by mrocklin**
The bokeh code now kills itself if it's unable to reach the scheduler http server. 

Fixes #227 

cc @nfaggian

### CODE REVIEW

**Comment by nfaggian** [comment]
Push a release?

**Comment by mrocklin** [comment]
Sure, I'll probably in a micro release in a couple of hours.

Before then you can always pip install from git:

    pip install git+https://github.com/dask/distributed.git --upgrade

**Comment by nfaggian** [comment]
Thanks

**Comment by mrocklin** [comment]
Version 1.9.4 publised

**Pull request merged**
