### PR TITLE
Don't inherit from WorkerPlugin class

### PR DESCRIPTION
**Pull request by jsignell**
It seems like WorkerPlugins should not inherit from the WorkerPlugin class, but just use it as a spec. Otherwise I don't think:

https://github.com/dask/distributed/blob/24007c2b81e12d98fb229504f858c8f28b6063ba/distributed/worker.py#L1158-L1162

can work if the user hasn't defined a teardown method.

### CODE REVIEW

**Comment by mrocklin** [comment]
I'm not sure that I understand.  Can you explain why this would fail?

**Comment by jsignell** [comment]
Yeah sorry, if we inherit from the class `WorkerPlugin` then the subclass will have attr `teardown` even if it's not implemented. And it'll try to run `plugin.teardown(self)` you get an error:

```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-486128a0031d> in <module>
----> 1 plugin.teardown()

TypeError: teardown() missing 1 required positional argument: 'worker'
``

But maybe this isn't the solution.

**Comment by jrbourbeau** [comment]
I think in that all the methods are no-ops on the base `WorkerPlugin` class. So there won't be any breakage, just a few extra method calls that don't do anything

**Comment by jsignell** [comment]
You don't get any errors in the worker logs?

**Comment by jsignell** [comment]
Maybe the right thing is to make worker optional in the `WorkerPlugin` class.

**Comment by mrocklin** [comment]
@jsignell maybe the right thing to do here is to provide a failing test case first?  That might help to guide development and conversation.

**Comment by jsignell** [comment]
Oh! I am not thinking about this right at all. Sorry for the noise. I got confused about what self meant in that snippet above (hint - it means worker :facepalm: ).

**Comment by jsignell** [comment]
What I was doing is I kept thinking that `register_worker_plugin` accepted a class rather than an instantiated object. And then I'd have all sorts of errors about self being missing...

**Comment by jsignell** [comment]
Thank you both for engaging with me on this.

**Comment by mrocklin** [comment]
Yeah, no sweat.  Good luck

**Pull request closed without merging**
