### PR TITLE
change cudf groupby import

### PR DESCRIPTION
**Pull request by quasiben**
PR fixes an import statement necessary for (de-)serializing cudf groupby objects

### CODE REVIEW

**Comment by kkraus14** [comment]
> @kkraus14 what do you think about moving this code inside of cudf?

As long as we can make `distributed` an optional dependency then I'm absolutely fine with it.

**Comment by mrocklin** [comment]
The thing for you to be concerned about here is probably import time.

```python
In [1]: import numpy, pandas

In [2]: %time import distributed
CPU times: user 173 ms, sys: 39.5 ms, total: 213 ms
Wall time: 262 ms
```

**Comment by quasiben** [comment]
@mrocklin with https://github.com/rapidsai/cudf/pull/2703 merged we should be good for merging this PR

**Comment by mrocklin** [comment]
Nice.

**Comment by mrocklin** [comment]
Hrm, actually, what happens if I release distributed before the next cudf release (this will almost surely happen).  Should we plan for a bit of buffering with version checks?

**Comment by quasiben** [comment]
Version checks make sense

**Comment by quasiben** [comment]
@mrocklin i think this is ready to go -- rerunning the failed test

**Comment by quasiben** [comment]
currently failing on `distributed/tests/test_client.py::test_sub_submit_priority` which passes for me locally:

```
>               assert False, (thread, call_stacks)
E               AssertionError: (<Thread(Dask-Worker-Threads'-12140-398, started daemon 139961189209856)>, ['  File "/home/travis/miniconda/envs/test-...d/dask/distributed/distributed/worker.py", line 3246, in apply_function
E                 \tresult = function(*args, **kwargs)
E                 ', ...])
E               assert False

```

Merging with master and rerunning

**Comment by quasiben** [comment]
All green now

**Pull request merged**
