### PR TITLE
Move Windows CI to GitHub Actions

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Switching Windows CI from AppVeyor to GitHub Actions to enable multiple parallel jobs and improve performance.

- Switched `appveyor.yml` for `.github/workflows/ci-windows.yaml`
- Removed indirection to multiple one liner batch scripts
- Extracted conda environment from batch script into `continuous_integration/environment.yml`
- Remove JUnit reporting as this was an AppVeyor feature
- Added Python 3.7 as well as 3.6
- Uses bash 🎉

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
While this is in PR the builds are only [showing in my fork](https://github.com/jacobtomlinson/distributed/actions).

**Comment by jacobtomlinson** [comment]
Huzzah!

image

[Link to checks](https://github.com/jacobtomlinson/distributed/commit/4733546edd8b5f0932860f12ecf1f34d61d17e2d/checks?check_suite_id=402302295)

**Comment by TomAugspurger** [comment]
Cool!

Does anyone object to going forward with just GitHub actions for windows CI, or should keep Appveyor for a bit? My preference is for just GitHub actions. cc @jrbourbeau in case this overlaps with anything you're doing for 3.8 support.

**Comment by mrocklin** [comment]
I'm very glad to see this.  Thank you Jacob

**Comment by TomAugspurger** [comment]
Alrighty, merge when you’re ready @jacobtonlinson.

**Comment by mrocklin** [comment]
Woo!

**Pull request merged**
