### PR TITLE
Cosmetic review of story()

### PR DESCRIPTION
**Pull request by crusaderky**
Perform cosmetic tweaks to various methods related to worker and scheduler stories.

This PR has been rescoped since it was opened.

# Original description - obsolete
There was discussion on #6342 about using Worker.story() on non-key arbitrary tags, e.g. "gather-dep".

I find this functionality invaluable.
Example usage:
https://github.com/dask/distributed/blob/ba39915ff754c1683c744f99b6643f9832db0375/distributed/tests/test_worker.py#L1896-L1899

This tests that the task was received from worker rw instead of another worker:
https://github.com/dask/distributed/blob/ba39915ff754c1683c744f99b6643f9832db0375/distributed/tests/test_worker.py#L1952

This PR doesn't change functionality; it merely clarifies in the documentation that this is a legit use.

### CODE REVIEW

**Comment by fjetter** [comment]
The reason why I am opposed to the usage of this is because `Worker.log` is supposed to be a transition log. The _tags_ you are requesting here are not transitions but rather would classify as an event or instruction or similar. We introduced a dedicated log for this and should not encourage "improper" usage of the existing log.

**Comment by crusaderky** [comment]
it's not an event; it's something way more granular that happens in the state machine in response to an event.

For example, it is true that `{"op": "remove-replicas"}` will always trigger a `"remove-replicas"` entry in the log, which makes it somewhat redundant with the event log (although it healps readability a lot, since events are logged in a different log and one would have to match timestamps by hand!). However, then you have two different entries,  `"remove-replica-confirmed"` and  `"remove-replica-rejected"`, which are neither transitions, nor events, nor instructions, but carry valuable information as they tell you *why* there are - or there aren't - transitions immediately afterwards on those keys.

https://github.com/dask/distributed/blob/ba39915ff754c1683c744f99b6643f9832db0375/distributed/worker.py#L1814-L1835

**Comment by pentschev** [comment]
rerun tests

Note: rerunning gpuCI tests since those errors should be fixed by https://github.com/dask/distributed/pull/6434

**Comment by crusaderky** [comment]
I've salvaged this PR by removing all references to arbitrary tags.
Ready for re-review and merge.

**Comment by crusaderky** [comment]
Ready for review and merge again

**Review by fjetter — APPROVED** [review]

**Pull request merged**
