### PR TITLE
Unpin openssl and handle exception

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Instead of pinning the version of openssl this PR catching the broad `ssl.SSLError` and if it contains the new `unexpected eof while reading` message from `1.1.1e` it converts that to a `StreamClosedError` and treats it like that.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
The exception still seems to be being raised in Python 3.6, but I don't fully understand where in the traceback it is being raised from.

Could someone take a look and give me a pointer?

**Comment by mrocklin** [comment]
We need an SSL github team :)

cc @jcrist @mariusvniekerk @quasiben

**Comment by jrbourbeau** [comment]
FYI Travis CI is currently experiencing some issues related to build statuses. The Python 3.6 build is still failing for this PR (https://travis-ci.org/github/dask/distributed/builds/666509937)

**Comment by mrocklin** [comment]
Checking in here.  What should we do with this?

**Comment by jacobtomlinson** [comment]
`1.1.1g` is now available and SHOULD resolve this. It may be sensible to exclude `1.1.1f.

**Pull request closed without merging**
