### PR TITLE
Update client.py

### PR DESCRIPTION
**Pull request by tharris72**
Adding the Returns numpy style documentation to the doc strings. This is for issue #3578.
Testing out the pull request to make sure it works. There are still more doc strings to update.

### CODE REVIEW

**Comment by martindurant** [comment]
Please mark this PR as DRAFT and let us know when you are done.

**Review by jrbourbeau — COMMENTED** [review]
Thanks for the PR @tharris72! Distributed uses numpydoc for docstring formatting. I recommend looking through https://numpydoc.readthedocs.io/en/latest/format.html to make sure that these docstrings conform to numpydoc's style guide. Additionally, we also use `flake8` and `black` for code formatting. Here's the relevant section in the contributing docs for how to install / use `flake8` and `black` https://docs.dask.org/en/latest/develop.html#code-formatting. Let us know if you have any questions

**Comment by mrocklin** [comment]
Thank you for doing this @tharris72 .  Let us know when you are done.  This is great to see.

**Comment by tharris72** [comment]
I hope to work on this some more next week and hopefully I can finish it. I will keep you guys posted.

**Comment by jrbourbeau** [comment]
Sounds good, let us know if you have questions or need any additional input from us 👍

**Comment by jsignell** [comment]
I just came across this @tharris72 and it looks good! You don't need to worry about adding docstrings to the private methods. It looks like this just needs to have main merged in and have flake8 and black run on it.

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by tharris72** [comment]
I ran flake8 and black. The code changes are done but there is an import error 
ImportError: cannot import name 'apply' from 'dask.compatibility' (/home/docs/checkouts/readthedocs.org/user_builds/distributed/envs/4517/lib/python3.7/site-packages/dask/compatibility.py)

I'm guessing something got changed. I'm not sure how to resolve this. I looked in 'compatibility' and there is no apply

**Comment by tharris72** [comment]
> I just came across this @tharris72 and it looks good! You don't need to worry about adding docstrings to the private methods. It looks like this just needs to have main merged in and have flake8 and black run on it.

I ran flake8 and black. The code changes are done but there is an import error
ImportError: cannot import name 'apply' from 'dask.compatibility' (/home/docs/checkouts/readthedocs.org/user_builds/distributed/envs/4517/lib/python3.7/site-packages/dask/compatibility.py)

I'm guessing something got changed. I'm not sure how to resolve this. I looked in 'compatibility' and there is no apply
We can change the status from draft to ready to merge/finished. I'm not sure how to change it.

**Comment by martindurant** [comment]
I think it is `dask.utils.apply`

**Comment by tharris72** [comment]
> I think it is `dask.utils.apply`

You were right. Thanks for the heads up! I fixed the import error.

**Comment by jsignell** [comment]
It looks like there are a few last conflicts. Let me know if you would like me to push to your fork.

**Comment by tharris72** [comment]
> It looks like there are a few last conflicts. Let me know if you would like me to push to your fork.

You can push it and I will try to fix them. 
Thanks for helping!

**Comment by jsignell** [comment]
Ok I just pushed to your branch, so make sure to pull before doing any work.

**Comment by tharris72** [comment]
I believe I merged the changes and I uncommented out a line in the github actions yaml file
(.github/workflows/ssh_debug.yaml). The tests ran and said that 12 tests were cancelled.

> Ok I just pushed to your branch, so make sure to pull before doing any work.

I believe I merged the changes and I uncommented out a line in the github actions yaml file
(.github/workflows/ssh_debug.yaml). The tests ran and said that 12 tests were cancelled but there were no syntax erros.
Does this mean that everything works on my part or do I need to do more changes?
Thanks for the help. I really appreciate it!

**Comment by jsignell** [comment]
It looks like there were some issues with the merge that you did, would you like me to push again? If you look at the diff: https://github.com/dask/distributed/pull/4517/files you'll see that there are a bunch of changes between this branch and main that you didn't intend to include.

**Comment by tharris72** [comment]
> It looks like there were some issues with the merge that you did, would you like me to push again? If you look at the diff: https://github.com/dask/distributed/pull/4517/files you'll see that there are a bunch of changes between this branch and main that you didn't intend to include.

I tried to revert the changes that were not in client.py. Can you check if the only changes I have are in client.py and if so I think the changes are ready to be merged. Thanks for the help!

**Comment by jsignell** [comment]
I cherry-picked your commits onto a fresh branch. https://github.com/dask/distributed/pull/5670

**Comment by tharris72** [comment]
@jsignell Thanks for the help! I appreciate it!

**Pull request closed without merging**
