### PR TITLE
Fixed the 404 error on the Scheduler Dashboard homepage

### PR DESCRIPTION
**Pull request by mikewheel**
See issue #2359

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks for doing this @mikewheel .  I have a naive question, if we're hosting this web server at some other endpoint, will this redirect work properly?  

To make the question concrete, people often host the dashboard behind a proxy using nbserverproxy, so they navigate to something like the following:

    https://my-webserver/proxy/8787/status

In this situation would this redirect still work?   Would `https://my-webserver/proxy/8787` redirect to `https://my-webserver/proxy/8787/status` ?

**Comment by mikewheel** [comment]
You know to be honest I'm not sure. I would assume so, only because the app locations are all specified the same way in the existing code (that is, relative to '/' like '/status' or '/profile'). But I don't know and can only guess.

**Comment by mrocklin** [comment]
OK, well then lets just merge this and see if people continue to have this problem in those situations then. 

Thanks again @mikewheel !

**Comment by mrocklin** [comment]
Also, I notice that this is your first contribution to this repository.  Welcome!

**Pull request merged**
