### PR TITLE
Guard against a bad process ID in the memory monitor

### PR DESCRIPTION
**Pull request by mrocklin**
See https://github.com/dask/distributed/pull/1416#issuecomment-331551505

cc @TomAugspurger

### CODE REVIEW

**Comment by mrocklin** [comment]
@TomAugspurger when you saw these errors what were you doing?  Shutting down the worker?

**Comment by TomAugspurger** [comment]
Nope, this was normal computation. relatively CPU bound, but I think memory should be just fine. Haven't had a chance to narrow it down yet, but if you checkout the `k-means` branch on https://github.com/TomAugspurger/dask-ml/tree/k-means and run

```python

N = 1_000_000
C = N // 8
X, y = make_classification(n_samples=N, chunks=C)
km = KMeans(n_clusters=3)
km.fit(X)
```

You should see it. I just noticed the terminal running `jupyter lab` is printing out errors like

```
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x110bbcf28>, <tornado.concurrent.Future object at 0x114272b00>)
Traceback (most recent call last):
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/distributed/distributed/worker.py", line 2193, in memory_monitor
    k, v, weight = self.data.fast.evict()
AttributeError: 'LRU' object has no attribute 'evict'
```

**Comment by mrocklin** [comment]
That error can be resolved by updating zict

    conda install -c conda-forge zict

**Comment by TomAugspurger** [comment]
Thanks, that seems to have resolved everything.

Do you thing this change is still worthwhile? Will catching that error potentially silence issues that we would rather have raised?

**Comment by mrocklin** [comment]
No strong thoughts either way.

**Comment by TomAugspurger** [comment]
I would say wait until it comes up again, just in case this accidentally catches a meaningful exception.

**Pull request closed without merging**
