### PR TITLE
Add user-defined priorities

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes https://github.com/dask/dask/issues/2860

Or at least it would if more work were put in here.  This is a minimal example.

### CODE REVIEW

**Comment by mrocklin** [comment]
I may not have time to push this forward, however I think that it is now more accessible to others if they want to contribute.  Things we have to do

-  Support a priority= keyword in map, compute, and persist.  This is similar to `resources=` or `retry=` keywords
-  Add documentation

**Comment by pitrou** [comment]
What's the impact of this on shared clusters? I can imagine a user always forcing high priority on his/her tasks in order to be scheduled before everyone else...

**Comment by mrocklin** [comment]
Yeah, we don't currently do any kind of user/client management in Dask.  In practice multi-user clusters are somewhat rare, people tend to set up a different scheduler for each user for isolation.  Most multi-client workloads today are all launched programmatically by the same user with tricks like `get_client()`.

I agree that this is an issue, but it's a big enough and remote enough issue that I don't think we should optimize for it at all these days.

**Comment by mrocklin** [comment]
I've extended this to map, compute, persist.  Removing WIP label

**Comment by mrocklin** [comment]
I agree that that would be useful, presumably we could do that
automatically as well when people gather results.  Short term though I
think I'd prefer to start with this.  Changing already-propagated
priorities is slightly more involved.

**Comment by jakirkham** [comment]
> I agree that that would be useful, presumably we could do that automatically as well when people gather results.

Definitely. There are certainly other use cases that could benefit from this.

> Short term though I think I'd prefer to start with this. Changing already-propagated priorities is slightly more involved.

Ah ok. Should we migrate this part of the discussion into a new issue or perhaps back to issue ( https://github.com/dask/dask/issues/2860 )?

**Comment by mrocklin** [comment]
@pitrou if you have a moment can you take a look at this traceback?

```python
  File "/home/travis/build/dask/distributed/distributed/nanny.py", line 348, in start
    yield self.process.start()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/travis/build/dask/distributed/distributed/process.py", line 36, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/home/travis/build/dask/distributed/distributed/process.py", line 186, in _start
    process.start()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/multiprocessing/popen_fork.py", line 26, in __init__
    self._launch(process_obj)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/multiprocessing/popen_forkserver.py", line 54, in _launch
    f.write(buf.getbuffer())
BrokenPipeError: [Errno 32] Broken pipe
distributed.utils - ERROR - [Errno 32] Broken pipe
```

This happens only on Python 3.6 (not 3.5).  It only happens fairly late in the test suite.  I suspect that we're running out of some resource, I just can't find out what it is.  (I've been futzing with issues like this for most of today).

If it reminds you of anything please let me know.

**Comment by mrocklin** [comment]
@pitrou you may also find the traceback in the failures here interesting.  I've been trying to track these down for the last couple of days and, despite having caught a few issues, haven't managed to identify what is going on here.

This happens consistently.  It happens only on Python 3.6.  It happens only, I think, after running most of our test suite, and then trying to start a new cluster.

```python
Traceback (most recent call last):
  File "/home/travis/build/dask/distributed/distributed/utils.py", line 621, in log_errors
    yield
  File "/home/travis/build/dask/distributed/distributed/utils_test.py", line 447, in run_nanny
    loop.run_sync(lambda: worker._start(0))
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/travis/build/dask/distributed/distributed/nanny.py", line 153, in _start
    response = yield self.instantiate()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/travis/build/dask/distributed/distributed/nanny.py", line 222, in instantiate
    yield self.process.start()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/travis/build/dask/distributed/distributed/nanny.py", line 353, in start
    yield self.process.start()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/travis/build/dask/distributed/distributed/process.py", line 36, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/home/travis/build/dask/distributed/distributed/process.py", line 185, in _start
    process.start()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/multiprocessing/popen_fork.py", line 26, in __init__
    self._launch(process_obj)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/multiprocessing/popen_forkserver.py", line 54, in _launch
    f.write(buf.getbuffer())
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by mrocklin** [comment]
I have temporarily merged in #1723 to see if it makes a difference.  Sadly it does not.

**Pull request merged**
