### PR TITLE
Set `lifetime-stagger` default value to `None`

### LINKED ISSUE #7444: Setting worker lifetime stagger only possible via CLI
**Describe the issue**:
Configuring [worker lifetime stagger](https://docs.dask.org/en/stable/configuration.html#distributed.worker.lifetime.stagger) seems to be only possible via the CLI, as it defaults to `"0 seconds"` [here](https://github.com/dask/distributed/blob/f3556782c5002613d66cae14f95e13f6ec215a59/distributed/cli/dask_worker.py#L193), leading to it never being `None` here: 
https://github.com/dask/distributed/blob/d87cea954aed8d2e9a49fc88fe0bf4aace805f08/distributed/worker.py#L827-L829 which leads to the 

**Minimal Complete Verifiable Example**:

```python
# Workers are started with the lifetime config set through environment variables:
#     DASK_DISTRIBUTED__WORKER__LIFETIME__DURATION="20 minutes"
#     DASK_DISTRIBUTED__WORKER__LIFETIME__STAGGER="10 minutes"

from typing import Tuple

import dask
from dask.distributed import Client
from distributed import get_worker


def get_worker_lifetime_and_stagger() -> Tuple[float, str]:
    return (
        get_worker().lifetime,
        dask.config.get("distributed.worker.lifetime.stagger"),
    )


if __name__ == '__main__':
    client = Client("<URL>")
    lifetimes_and_staggers = client.run(get_worker_lifetime_and_stagger)
    print(lifetimes_and_staggers)  # Returns correct stagger but incorrect lifetime
```

**Environment**:

- Dask version: 2022.12.1
- Python version: 3.8.15
- Operating System: linux-64
- Install method (conda, pip, source): conda

### PR DESCRIPTION
**Pull request by bstadlbauer**
Sets `lifetime-stagger` CLI default to `None` (instead of 0 seconds), to allow overrides through config file or environment variables.

Closes #7444

- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by fjetter** [comment]
Thanks @bstadlbauer . I noticed the same problem is affecting lifetime.restart as well. Could you do the same over there?

I also would appreciate a test. For inspiration see `test_dask_worker.py::test_preload_config` which is setting environment variables and is passing it to the CLI process. The test assertion could then look similar to what you wrote in https://github.com/dask/distributed/issues/7444#issue-1517631590 
See also `test_worker.py::test_lifetime_stagger` as an example how to assert the stagger (e.g. with a client.run)

**Comment by fjetter** [comment]
We're unfortunately struggling with flaky tests frequently. We build a dashboard that helps us to see if a given test is particularly flaky, see https://dask.github.io/distributed/test_report.html and https://dask.github.io/distributed/test_short_report.html for a shorter version

I see four failures on your PR

- test_set_lifetime_stagger_via_env_var seems to be a genuine bug in your test code
- Two unrelated failures in test_semaphore (hopefully fixed byhttps://github.com/dask/distributed/pull/5885
- test_worker_memory which is also known

I assume the commit you just pushed fixes `test_set_lifetime_stagger_via_env_var` in which case we're good to go once CI finishes again

**Comment by bstadlbauer** [comment]
@fjetter Thank you for the quick turnaround here! https://github.com/dask/distributed/pull/7445/commits/4ce53dfdc78b5975da3012b8fd7910626c08fc52 should have fixed the test race condition I introduced, so from my end, things would be ready to merge :-)

**Review by fjetter — APPROVED** [review]
Thank you for fixing this and congrats for your first commit @bstadlbauer!

**Pull request merged**
