### PR TITLE
Add test setup fixture

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR adds a new `initialize_test` fixture which is automatically applied to each test in our test suite. This fixture does a few things:

1. Disable custom preloads in tests, which can interact with tests in unexpected ways
2. Ensures Dask's configuration system is reset for each test
3. Restores default logging levels for each test

I should note that points 2 and 3 above were previously being done in our `clean` content manager (so all tests using `gen_cluster`, `gen_test`, or `cleanup`). This PR just broadens their reach to all tests. 

Closes https://github.com/dask/distributed/issues/5240

cc @mrocklin

### CODE REVIEW

**Comment by jrbourbeau** [comment]
The changes here have caused some tests to start failing. Interestingly if I run `distributed/tests/test_client.py::test_default_get` or `distributed/tests/test_client.py::test_Future_exception_sync_2` individually, they pass. However, if I run the entire `distributed/tests/test_client.py` module, then those two tests fail. This might have uncovered some unsound logic that was previously going unnoticed...

**Comment by jrbourbeau** [comment]
cc @ian-r-rose if you get a chance to take a look at this

**Review by fjetter — APPROVED** [review]
Love it

**Comment by jrbourbeau** [comment]
Thanks for reviewing @fjetter!

**Pull request merged**
