### PR TITLE
Avoid parsing `sys.argv` when starting `jupyter` server

### LINKED ISSUE #7569: dask-scheduler --jupyter fails to start
**Describe the issue**:
I have been using `Scheduler(jupyter=True)` for a while without issue; I just tried the CLI version and it seems to fail.

**Minimal Complete Verifiable Example**:

```
(.venv)  ➜  distributed git:(main) dask-scheduler --jupyter
/Users/brett/distributed/distributed/cli/dask_scheduler.py:140: FutureWarning: dask-scheduler is deprecated and will be removed in a future release; use `dask scheduler` instead
  warnings.warn(
2023-02-21 18:29:56,114 - distributed.scheduler - INFO - -----------------------------------------------
2023-02-21 18:29:56,130 - distributed.http.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
usage: dask-scheduler [-h] [--debug] [--show-config] [--show-config-json] [--generate-config] [-y]
                      [--allow-root] [--no-browser] [--autoreload] [--script] [--no-script]
                      [--log-level ServerApp.log_level] [--config ServerApp.config_file]
                      [--ip ServerApp.ip] [--port ServerApp.port]
                      [--port-retries ServerApp.port_retries] [--sock ServerApp.sock]
                      [--sock-mode ServerApp.sock_mode] [--transport KernelManager.transport]
                      [--keyfile ServerApp.keyfile] [--certfile ServerApp.certfile]
                      [--client-ca ServerApp.client_ca] [--notebook-dir ServerApp.root_dir]
                      [--preferred-dir ServerApp.preferred_dir] [--browser ServerApp.browser]
                      [--pylab ServerApp.pylab] [--gateway-url GatewayClient.url]
                      [extra_args ...]
dask-scheduler: error: argument --jupyter: expected one argument
```

**Anything else we need to know?**:
Adding `sys.argv.remove("--jupyter")` right before `Scheduler()` gets called [here](https://github.com/dask/distributed/blob/main/distributed/cli/dask_scheduler.py#L209) resolves the issue
```
(.venv)  ➜  distributed git:(main) ✗ dask-scheduler --jupyter
/Users/brett/distributed/distributed/cli/dask_scheduler.py:140: FutureWarning: dask-scheduler is deprecated and will be removed in a future release; use `dask scheduler` instead
  warnings.warn(
2023-02-21 18:32:27,072 - distributed.scheduler - INFO - -----------------------------------------------
2023-02-21 18:32:27,081 - distributed.http.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
[I 2023-02-21 18:32:27.752 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-02-21 18:32:27.754 ServerApp] nbclassic | extension was successfully linked.
[I 2023-02-21 18:32:27.861 ServerApp] notebook_shim | extension was successfully linked.
[W 2023-02-21 18:32:27.880 ServerApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 2023-02-21 18:32:27.881 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-02-21 18:32:27.881 LabApp] JupyterLab extension loaded from /Users/brett/distributed/.venv/lib/python3.10/site-packages/jupyterlab
[I 2023-02-21 18:32:27.881 LabApp] JupyterLab application directory is /Users/brett/distributed/.venv/share/jupyter/lab
[I 2023-02-21 18:32:27.883 ServerApp] jupyterlab | extension was successfully loaded.
```
So it seems like something down in the Jupyter initialization stack is getting confused? I also tried on an old Docker image from back when this feature was first released and it seems like it didn't work then either, so I don't think it's anything to do with recent updates in `jupyter-server` etc.

**Environment**:

- Dask version: current main `9e8876dba90e4fac5101a1a3dba0f658b279a243`
- Python version: 3.10

### PR DESCRIPTION
**Pull request by bnaul**
Closes #7569.

`initialize` forwards an `argv` along to `jupyter_core.application.JupyterApp`, if it's not passed then it goes and grabs `sys.argv` which causes the linked issue. So the simplest fix seems to be to explicitly pass no arguments to avoid this behavior. If for some reason we do want to forward along args then we could just pop `--jupyter` from the list, either seems fine to me....?

cc @mrocklin @Carreau

### CODE REVIEW

**Comment by mrocklin** [comment]
This seems fine to me.  I'll merge later this afternoon if there are no further comments.

**Review by jrbourbeau — COMMENTED** [review]
Thanks for tracking this down @bnaul! Would you mind adding a small test? Something similar to 

https://github.com/dask/distributed/blob/650e3f47456091361de3c2672aba26b4b8d0a2b9/distributed/tests/test_jupyter.py#L13-L20

that uses the CLI instead should be sufficient

**Comment by bnaul** [comment]
@jrbourbeau I gave it a shot but wasn't able to easily reproduce the old behavior inside the test environment because of the difference in `sys.argv`; tried `mock.patch` as well but it wouldn't work. If you have a suggested approach for getting that particular part working I can try again but I'm not sure it's worth the trouble 🙃

**Comment by jrbourbeau** [comment]
This should do the trick

```diff
diff --git a/distributed/cli/tests/test_dask_scheduler.py b/distributed/cli/tests/test_dask_scheduler.py
index 1eb2e074..ca08ecfd 100644
--- a/distributed/cli/tests/test_dask_scheduler.py
+++ b/distributed/cli/tests/test_dask_scheduler.py
@@ -612,3 +612,22 @@ def test_single_executable_deprecated(loop):
         stdout, stderr = scheduler.communicate()
         logs = stdout.decode()
         assert "FutureWarning: dask-scheduler is deprecated" in logs
+
+
+@pytest.mark.slow
+def test_jupyter(loop):
+    port = open_port()
+    with popen(
+        [
+            "dask",
+            "scheduler",
+            "--jupyter",
+            "--no-dashboard",
+            "--host",
+            f"127.0.0.1:{port}",
+        ],
+        capture_output=True,
+    ):
+        with Client(f"127.0.0.1:{port}", loop=loop):
+            response = requests.get("http://127.0.0.1:8787/jupyter/api/status")
+            assert response.status_code == 200
```

**Comment by bnaul** [comment]
Thanks @jrbourbeau! I moved this into the `test_jupyter` module since it seemed a little more thematically appropriate.

I did notice that the *failing* version of the test takes 30s to time out, but the passing one finishes in 2s...does that still warrant a `slow` mark?

**Comment by jrbourbeau** [comment]
> I moved this into the test_jupyter module since it seemed a little more thematically appropriate.

Sure! That seems reasonable 

> I did notice that the failing version of the test takes 30s to time out, but the passing one finishes in 2s...does that still warrant a slow mark?

I don't feel strongly either way. We don't really have a strict definition of when the `slow` marker should be applied.

**Review by jrbourbeau — APPROVED** [review]
Thanks for fixing @bnaul

**Pull request merged**
