### PR TITLE
Add GIL metric to dashboard

### PR DESCRIPTION
**Pull request by milesgranger**
Adds a GIL contention metric to the Event Loop
page when `distributed.admin.system-monitor.gil-contention` is enabled and `gilknocker` is installed.

Otherwise, the chart will not show anything GIL
related, not even placeholders.

Part of #7290 

- [ ] Tests added / passed
- [x] Passes `pre-commit run --all-files`

ezgif-2-12d8c56db2

---

When GIL monitoring not enabled it will look like this:
image

### CODE REVIEW

**Comment by mrocklin** [comment]
Very fun!  If it's easy, can I ask for a little bit less horizontal whitespace.  Some is good certainly in order to visually separate the two related sections.  Maybe half of what we have here would be enough though?

**Comment by milesgranger** [comment]
That was easy. Updated the images in the original comment to reflect the updated spacing. Lemme know if you think it ought to have any other changes! :+1:

**Comment by mrocklin** [comment]
Thanks.

Also (sorry to eke out reviews) we maybe want to be aware of the name of the button in the JLab extension.  I suspect that it still says "Event Loop" while maybe it should say something like "Contension".  I suspect that this name is determined by the address of the route in distributed/dashboard/scheduler.py under the `applications` variable

```python
    "/individual-event-loop": individual_doc(EventLoop, 500),
```

So maybe we want to chage this to something like 

```python
    "/individual-contention": individual_doc(EventLoop, 500),
```

Maybe we also want to change the name of the `EventLoop` class as well.

**Review by jacobtomlinson — COMMENTED** [review]
This looks great to me.

> I suspect that this name is determined by the address of the route

@mrocklin is correct it might be good to rename the page to be clearer.

**Review by jacobtomlinson — APPROVED** [review]
Sweet thanks @milesgranger!

Thanks for going to the effort of regenerating the gifs with the new colours too!

**Pull request merged**
