### PR TITLE
Adjust value of zict buffer's `target` to ~inf when `memory_target_fraction` is False

### PR DESCRIPTION
**Pull request by KrishanBhasin**
Helps address #4061 

If `self.memory_target_fraction` is set to False, then `target` becomes `0`, which appears to trigger immediate spill-to-disk.

I believe what we actually want is for target to be ~infinite, so that this measure is not used to trigger spill-to-disk.

When running my code with this code diff, I no longer observe unexpectedly early spill-to-disk.

### CODE REVIEW

**Comment by mrocklin** [comment]
This code block is in a conditional `if self.memory_limit` so I'm not sure that this will have an effect.  I might be reading things wrong though.

**Comment by KrishanBhasin** [comment]
Are you referring to this block?
https://github.com/dask/distributed/blob/0e88c5ba3c2f9ba3e15f19f6ea75d90b8b3693ea/distributed/worker.py#L545-L547

I can't see any other block that it sits in (but its been a long day today so apologies if I'm missing something obvious)

**Comment by mrocklin** [comment]
Yes.  If self.memory_limit is zero then we'll proceed down to the else:
block, where self.data = dict()

**Comment by KrishanBhasin** [comment]
My understanding is that `memory_limit` is the overall limit on the worker, then the `memory_*_fraction` is a multiplier we apply to that value.

My use case is keeping the limit for my workers (e.g. 20GB each), but setting `memory_target_fraction` to False, and using `memory_spill_fraction` to decide when to get my workers to disk.

What I saw was that in this block if `memory_target_fraction` was set to `False`, (but `memory_limit` was a valid memory limit), multiplying them together returned 0


```python
>>> 233434 * False
0
```

Running this code diff with `memory_target_fraction=False`, I am no longer seeing my early spill-to-disk problems

**Comment by KrishanBhasin** [comment]
An MVCE for the problem this fixes is below:

```python
import dask
from distributed import Client

client = Client(threads_per_worker=1, n_workers=4, memory_target_fraction=False)

df = dask.datasets.timeseries(
    start="2000-01-01",
    end="2010-01-31",
    freq="1s",
    partition_freq="1d",
)
df.persist()
```
On `2.30.0`, the `Status` dashboard tab immediately shows spill-to-disk occurring, and the `Worker` tab shows the workers barely breaking 3% memory use.

Using this diff, the memory use ramp up to ~70% as expected, before spill to disk occurs.

**Comment by KrishanBhasin** [comment]
Using `sys.maxsize` feels a bit hacky to me, but it looks like given the way that Zict appears to work, I think this is the best way to implement this.

If I'm reading the below snippet correctly, every time a new key is added, the LRU will call `evict()` as many times as needed to bring the memory use down below `n`. As `n` is a primitive integer, the only 'fix' I can see right now is to make it the maximum possible value so this process is triggered as late/rarely as possible.

https://github.com/dask/zict/blob/3a9ea886583ba9920be8ab8ecec4adde23401a1a/zict/lru.py#L52-L70
```python
def __setitem__(self, key, value):
        if key in self.d:
            del self[key]

        weight = self.weight(key, value)

        if weight <= self.n:
            self.d[key] = value
            self.i += 1
            self.heap[key] = self.i

            self.weights[key] = weight
            self.total_weight += weight
        else:
            for cb in self.on_evict:
                cb(key, value)

        while self.total_weight > self.n:
            self.evict()
```

**Comment by mrocklin** [comment]
I see, so you still want to have spill-to-disk behavior, you just want to rely on the psutil process memory check exclusively.  OK, that makes sense to me.  Merging.

**Comment by KrishanBhasin** [comment]
Thank you!

I have since had a quick thought about using `float("inf")` instead of `sys.maxsize` - if you prefer that (as it guarantees to always be greater than the `memory_limit`, and Zict should handle the `float` instead of an `int` just fine), I can do another quick PR to update this.

**Pull request merged**
