### PR TITLE
Support for latest ipykernel/ipywidgets

### LINKED ISSUE #7688: CI broken: The `ipykernel.comm.Comm` class has been deprecated
CI is broken on Python 3.10 and 3.11.
Many tests fail with the message:

> DeprecationWarning: The `ipykernel.comm.Comm` class has been deprecated. Please use the `comm` module instead.For creating comms, use the function `from comm import create_comm`.

e.g. https://github.com/dask/distributed/actions/runs/4473742414/jobs/7861483350?pr=7686

### PR DESCRIPTION
**Pull request by crusaderky**
- Closes #7688

### CODE REVIEW

**Comment by crusaderky** [comment]
Test failures unrelated

**Review by hendrikmakait — APPROVED** [review]
Thanks, @crusaderky!

**Review by graingert — APPROVED** [review]

**Comment by hendrikmakait** [comment]
Given that we remove `ipywidgets <8.0.5`, it seems like support for `ipywidgets 6` might not be the correct title. Am I missing something here?

**Comment by crusaderky** [comment]
> Given that we remove `ipywidgets <8.0.5`, it seems like support for `ipywidgets 6` might not be the correct title. Am I missing something here?

I must have misread something.

**Pull request merged**
