### PR TITLE
Add HDFS wrapper for pyarrow compat

### PR DESCRIPTION
**Pull request by jcrist**
Add a wrapper for `DaskHDFileSystem` to provide an arrow compatible
interface to our hdfs filesystem. Adds a test using parquet to ensure
compatibility. Depends on https://github.com/dask/dask/pull/2881.

### CODE REVIEW

**Comment by mrocklin** [comment]
Moderate-term I wouldn't mind removing the HDFS code in this repo to somewhere separate.  It might be unwise to add more code here and expect it to survive for a long while.

**Comment by mrocklin** [comment]
This would be more work, but I would be much happier to pull the hdfs code (and testing infrastructure) out of this repository and create a separate `dask-hdfs` package.

**Comment by jcrist** [comment]
I'm hoping this code is quite temporary, and won't last longer than a release or two. Ideally we'd settle on a standard interface that could live in each project and wouldn't require these wrappers.

**Comment by jcrist** [comment]
> This would be more work, but I would be much happier to pull the hdfs code (and testing infrastructure) out of this repository and create a separate dask-hdfs package.

Actually, this wouldn't be too bad to do, and a change like this would be good to get in before the next big release. I'll try and set this up tonight/tomorrow.

**Comment by mrocklin** [comment]
Really my hope was that you would just split things off :)  But, if now isn't a convenient time to do so then yes, throwing it in here for testing purposes seems pragmatic.

**Comment by mrocklin** [comment]
Hooray!

**Comment by mrocklin** [comment]
I will be very glad to see the HDFS code live in its own repository.  Hopefully it will also reduce our testing infrastructure burden.

**Comment by stuckeyr** [comment]
Ah, I was in the middle of testing, but things have gone awry. I checked out dask/dask#2881 and dask/distributed#1554 but must have made a mistake as I now get:
```
NotImplementedError: Using pyarrow with a 'DaskHDFileSystem' filesystem object
```
I might wait till @jcrist has set up the new package...

**Comment by jcrist** [comment]
The dask filesystem and the pyarrow compatibility wrapper are both in https://github.com/dask/hdfs3/pull/144. Closing.

**Pull request closed without merging**
