### PR TITLE
Use dask git tip for mypy

### PR DESCRIPTION
**Pull request by crusaderky**
Fixes mypy failure due to a change in dask since the latest release:

```
distributed/tests/test_client.py:42: error: Module "dask.utils" has no attribute "get_default_shuffle_algorithm"  [attr-defined]
```

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks @crusaderky. This came up in https://github.com/dask/distributed/pull/7513#pullrequestreview-1275680073. Will adding an install directly from GitHub lead any clashes with the local `dask` install people are using?

**Comment by crusaderky** [comment]
> Will adding an install directly from GitHub lead any clashes with the local `dask` install people are using?

If your PR in dask/distributed depends on another PR in dask/dask that hasn't made it into main yet, pre-commit will fail both locally and in CI. This change doesn't make it any better. I typically put a do-not-merge temporary tamper in .pre-commit-config when that's the case.

**Comment by fjetter** [comment]
Does this require me to re-install the hooks every time I execute them? Is there any caching happening?
I don't want to reinstall the hook locally whenever a new commit pops up upstream.

**Comment by crusaderky** [comment]
No, 

> Does this require me to re-install the hooks every time I execute them? Is there any caching happening? I don't want to reinstall the hook locally whenever a new commit pops up upstream.

No, both your local cache and the CI cache[1] will be retained when there's a commit in dask/dask.
[1]https://github.com/pre-commit/action/blob/5f528da5c95691c4cf42ff76a4d10854b62cbb82/action.yml#L15-L18

Note that we already had the problem that the cache won't be invalidated when a new release of dask drops. This PR neither improves nor worsens the issue.

**Comment by crusaderky** [comment]
Any further feedback? Can we merge?

**Review by fjetter — APPROVED** [review]

**Pull request merged**
