### PR TITLE
Fix #618: avoid configuring the root logger

### LINKED ISSUE #618: distributed hijacks the logger
Simply importing the Client will muck with my logging setup - is it using the root logger?

Will try to add a repro in the morning...

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@dhirschfeld, does it fix your issue?

**Comment by dhirschfeld** [comment]
On this branch I still appear to be seeing duplicate logging - e.g.
```
2016-11-10 12:03:51,857 - INFO - MetraMonitor - Downloaded fcast_201611070200_tappt.csv
INFO:TaskRunner:Downloaded fcast_201611070200_tappt.csv
2016-11-10 12:03:51,920 - INFO - MetraMonitor - Downloaded fcast_201611070200_temp_prob.csv
INFO:TaskRunner:Downloaded fcast_201611070200_temp_prob.csv
2016-11-10 12:03:51,873 - INFO - MetraMonitor - Downloaded fcast_201611070200_rh.csv
INFO:TaskRunner:Downloaded fcast_201611070200_rh.csv
```

The messages of the form `INFO:TaskRunner:Downloaded fcast_201611070200_tappt.csv` aren't from my app but from I'm assuming a logger configured in distributed?

**Comment by dhirschfeld** [comment]
Just deleted my comment - I think that's actually a config error on my part...

**Comment by dhirschfeld** [comment]
Ok, have done some testing and this PR doesn't seem to work for me.

I'm still seeing duplicate logs of the form
```
2016-11-10 12:47:37,752 - INFO - GFIMonitor('DataFeeds/MarketCurves') - Downloaded Market_Curve_20161103163604.csv
INFO:TaskRunner:Downloaded Market_Curve_20161103163604.csv
```
where the latter message was sent by (I'm assuming) a logger configured in distributed.

**Comment by pitrou** [comment]
@dhirschfeld, I cannot reproduce your issue with duplicate log lines. Can you produce a simple script reproducing the issue?

**Comment by pitrou** [comment]
Also, which Python version do you use and what are the contents of your `~/.dask/config.yaml` file?

**Comment by pitrou** [comment]
By the way, `INFO:TaskRunner:Downloaded Market_Curve_20161103163604.csv` does not correspond to the logging format configured by Distributed.

**Comment by dhirschfeld** [comment]
Thanks, it must be something wrong with my setup then. I'll look into it some more and see if I can create a repro

**Comment by pitrou** [comment]
You may want to set the `propagate` attribute to False if you added a handler on a non-root logger.

**Comment by dhirschfeld** [comment]
I'll check that also.

For ref, I'm using py35/win64 and my config.yml is:
```
logging: 
  distributed: info
  distributed.executor: warning
  bokeh: critical

compression: auto

# Scheduler options
bandwidth: 100000000    # 100 MB/s estimated worker-worker bandwidth
allowed-failures: 3     # number of retries before a task is considered bad
pdb-on-err: False       # enter debug mode on scheduling error
transition-log-length: 100000 
```

**Comment by dhirschfeld** [comment]
To avoid further conflicts I'm happy for this to be merged as an improvement over master. I haven't gotten to the bottom of my own problem but can open another issue/PR should I find that it is a distributed issue rather than one of my own making :/

**Pull request merged**
