### PR TITLE
Fix flaky test_cancel_fire_and_forget

### PR DESCRIPTION
**Pull request by crusaderky**
https://github.com/dask/distributed/runs/5889416220?check_suite_focus=true

```
    @gen_cluster(client=True)
    async def test_cancel_fire_and_forget(c, s, a, b):
        x = delayed(slowinc)(1, delay=0.05)
        y = delayed(slowinc)(x, delay=0.05)
        z = delayed(slowinc)(y, delay=0.05)
        w = delayed(slowinc)(z, delay=0.05)
        future = c.compute(w)
        fire_and_forget(future)
    
        await asyncio.sleep(0.05)
        await future.cancel(force=True)
        assert future.status == "cancelled"
>       assert not s.tasks
E       AssertionError: assert not {'slowinc-07f21bf6-77d4-46da-84c7-0d0f82e7e1d1': <TaskState 'slowinc-07f21bf6-77d4-46da-84c7-0d0f82e7e1d1' waiting>, 'slowinc-140d6197-d9c9-413b-a31a-5f9f9af99049': <TaskState 'slowinc-140d6197-d9c9-413b-a31a-5f9f9af99049' processing>, 'slowinc-15ba1366-ef7e-4e4c-8ac7-463a65381dca': <TaskState 'slowinc-15ba1366-ef7e-4e4c-8ac7-463a65381dca' waiting>, 'slowinc-571b547f-d6cb-4b88-8c1c-9f28972eee76': <TaskState 'slowinc-571b547f-d6cb-4b88-8c1c-9f28972eee76' waiting>}
E        +  where {'slowinc-07f21bf6-77d4-46da-84c7-0d0f82e7e1d1': <TaskState 'slowinc-07f21bf6-77d4-46da-84c7-0d0f82e7e1d1' waiting>, 'slowinc-140d6197-d9c9-413b-a31a-5f9f9af99049': <TaskState 'slowinc-140d6197-d9c9-413b-a31a-5f9f9af99049' processing>, 'slowinc-15ba1366-ef7e-4e4c-8ac7-463a65381dca': <TaskState 'slowinc-15ba1366-ef7e-4e4c-8ac7-463a65381dca' waiting>, 'slowinc-571b547f-d6cb-4b88-8c1c-9f28972eee76': <TaskState 'slowinc-571b547f-d6cb-4b88-8c1c-9f28972eee76' waiting>} = <Scheduler 'tcp://127.0.0.1:59566', workers: 2, cores: 3, tasks: 4>.tasks
```

### CODE REVIEW

**Comment by mrocklin** [comment]
It looks like I accidentally duplicated your work here: https://github.com/dask/distributed/pull/6131

I'm curious, do you think that the event things are necessary?  What was your thinking there?

I attributed this to the possibility that cancel has the 200ms possible delay if the task hasn't arrived yet.

**Comment by mrocklin** [comment]
Alternatively, should we close?

**Comment by crusaderky** [comment]
The problem is that the current test *hopes*, after 0.05s, to be computing one of the 4 tasks - which take 0.2s in total.
In my experience, I've seen hiccups an order of magnitude longer, particularly on the MacOSX hosts, which systematically cause this test design to flake off. So I still think this should be merged.

**Comment by mrocklin** [comment]
I think that the delay here isn't the 5ms.  It's the delay between `c.compute` (uses the batched comm) and `c.cancel` (uses the connection pool).  If c.cancel actually gets to the scheduler first (very rare) then we retry every 200ms for five retries before giving up.  That, I think, is the heart of the issue here.

The 50ms is, I think, irrelevant.

**Comment by mrocklin** [comment]
The concern I have with the event thing is that it requires a fairly sophisticated reader to puzzle through.  If we can keep the test simpler I think that that will be better for future readers.

**Comment by crusaderky** [comment]
> If c.cancel actually gets to the scheduler first (very rare) then we retry every 200ms for five retries

future.cancel may land on the scheduler:
1. before the tasks themselves have arrived on the scheduler - at which point it will try again after all tasks have been completed (see below). This is because of an internal timeout that doesn't appear anywhere in the test.
2. after the tasks have arrived on the scheduler, but before they've arrived on the worker
3. while the first task is still running
4. after 1 or 2 tasks have been completed, and their completion has already been propagated from worker to scheduler
5. after 1 or 2 tasks have been completed, but the scheduler has yet to be informed about the completion of some or all.
6. after all tasks have been completed, and their completion has already been propagated from worker to scheduler
7. after all tasks have been completed, but the scheduler has yet to be informed about the completion of some or all.

*Most times*, you'll randomly hit use cases 3, 4, or 5. Use cases 1, 2, 6, and 7 will only blip once in a while, and only on very slow CI.

The cancel may land on the *worker* in a similar spread.

In the best case, you'll get flickering coverage - which is currently causing the coverage report to be almost unusable for PRs. 
In the worst case, in one of the use cases above the test will fall over.

I'm not happy about the extra complexity of the event-driven design, either, but it has the giant advantage of being *deterministic*.

**Comment by mrocklin** [comment]
> In the worst case, in one of the use cases above the test will fall over

My guess is that this is no longer the case with the recent fix.  I suspect that the CI Stability issue here has been resolved (I have only about 80% confidence of this)

Because of this, I've stepped away from this conversation.  My apologies.  My sense is that there is now a question/tension between a test being easy-to-read and determinism/coverage.  That is an interesting tension, and something that we should explore, but it's also something that I don't currently have strong thoughts on (although I probably naturally trend a little bit more towards easy-to-read).  

Mostly though I don't care as much about coverage as I do things like stability and CI stability, and so I've kind of moved on to focus on those topics.  

Given that CI-stability is handled (I think) I don't care a ton about this PR, and so am not blocking.  If we were to switch lots of tests to be hard-to-read-but-deterministic then I would definitely want to have a conversation, but I'm hoping that this isn't anyone's focus right now and so this conversation can be delayed until coverage is a more painful issue than stability/CI-stability.  If folks do have a strong desire to spend a lot of time on deterministic tests that improve coverage then we should certainly talk about that before we change lots of tests around.

Summary: if you want to merge this, I'm not blocking.  If this starts a trend then let's talk before we start that trend.

**Pull request merged**
