### PR TITLE
WIP - Add task prefixes to prometheus metrics

### PR DESCRIPTION
**Pull request by mrocklin**
cc @ntabris

### CODE REVIEW

**Comment by ntabris** [comment]
Here's an example graph of the data in Grafana:

image

cc @ian-r-rose

**Comment by mrocklin** [comment]
Context for this:

We like the task stream plot, and we'd like some version of it that could be stored long-term.  The task strream plot is a bit too busy.  We have attempts of this with TaskGroups.  Coiled has systems internally which does this.  Maybe prometheus is better for this though.  This PR samples the task stream and aggregagtes the information.  

This is lossy, which isn't great.  We could also use counters internally and do some sort of diff in grafana.  @ntabris may think about this a bit.

**Review by jacobtomlinson — APPROVED** [review]
Neat!

**Comment by mrocklin** [comment]
This is superceded by #7088 , which gives a much more accurate view.  This PR effectively samples the task stream while the other tracks all results using a bit of added state.

**Comment by hendrikmakait** [comment]
Superseded by #7088

**Pull request closed without merging**
