### PR TITLE
Add routes for solo bokeh figures in dashboard

### PR DESCRIPTION
**Pull request by mrocklin**
This adds new routes for individual plots.

This is to help some JLab extension work.

cc @ian-r-rose

    pip install git+https://github.com/mrocklin/distributed@bokeh-solo-plots

### CODE REVIEW

**Comment by mrocklin** [comment]
@ian-r-rose I've changed the relevant route to `individual-plots.json`

**Comment by mrocklin** [comment]
@mariusvniekerk I'm curious, what is your use case here?

**Comment by mrocklin** [comment]
You might enjoy the JupyterLab extension that @ian-r-rose was working on last week :)

**Comment by ian-r-rose** [comment]
As far as I can tell, the `individual-profile` route doesn't serve any content. Is that a known issue?

**Comment by mrocklin** [comment]
It won't serve content if there are no connected workers who have done
work.  This is definitely an issue, but it's probably orthogonal to this
PR.

**Pull request merged**
