### PR TITLE
Fix #647: clarify usage of add_done_callback()

### LINKED ISSUE #647: future.result() freezes in add_done_callback()
Hi,

below is a simplified example of how calling `future.result()` in `add_done_callback` freezes.

```
c = Client()

def sleep():
    time.sleep(2)
    return 1

def cb(f):
    print(f)
    print('Result should be {}'.format(sleep()))
    print('Result was', f.result())

d = delayed(sleep)()
d.compute() # 1

c.compute(d).result() # 1

f2 = c.compute(d)
f2.add_done_callback(cb)
# <Future: status: finished, type: int, key: finalize-e24717a1ea49f34025d9f69a8d4b9e3e>
# Result should be 1
```

You never get the `f.result()` in `cb`. Execution freezes.

### PR DESCRIPTION
**Pull request by pitrou**
Also add tests for coroutine usage.

### CODE REVIEW

**Comment by mrocklin** [comment]
We might consider changing the API around a bit to call the function in a separate thread, perhaps using a single-threaded `concurrent.futures.ThreadPoolExecutor`

**Comment by pitrou** [comment]
That's a possibility. What is the use case for `add_done_callback`?

**Comment by mrocklin** [comment]
People were asking for it to be there.  Pragmatically I think it's also nice for people who want to run a local function when a future finishes, for example for logging.

**Comment by pitrou** [comment]
I was wondering if people were expecting to pass a coroutine or a regular function but, since the main distributed API is blocking, they are probably expecting to pass a regular blocking function.

**Comment by pitrou** [comment]
Alternative solution in PR #656.

**Comment by pitrou** [comment]
Obsoleted by #656, closing.

**Pull request closed without merging**
