### PR TITLE
Ensure large payload can be serialized and sent over comms

### PR DESCRIPTION
**Pull request by fjetter**
This includes two changes that aim to support the submission of very large graphs

Closes https://github.com/dask/distributed/issues/8257

1. It removes the deprecated msgpack options `max_*_len`. According to https://msgpack-python.readthedocs.io/en/latest/api.html#msgpack.unpackb they are now automatically set to the payload size and are there to protect from malicious behavior. Not setting it ourselves effectively removes any artificial limits from what I understand.
2. It reverts https://github.com/dask/distributed/pull/5854 since in my testing this threshold still causes issues. The only exception I see is a broken pipe here https://github.com/fjetter/distributed/blob/9721a1e83fb6ebb2c486d7226b290d6f7d6e7ec8/distributed/comm/tcp.py#L366 but I haven't tried chasing this down. I was running on python 3.10 so at the very least this version identifier is not sufficient / maybe the cpython bug is not fixed yet. maybe @jakirkham has some insight

### CODE REVIEW

**Review by hendrikmakait — APPROVED** [review]
Thanks, @fjetter! LGTM, assuming there are no surprises on CI.

**Comment by crusaderky** [comment]
The new test `test_large_payload` is flaky

**Comment by hendrikmakait** [comment]
`test_large_payload` takes 9s locally, so I'm not surprised that it would time out on CI. I don't see a good way of testing this behavior without allocating a large payload, so I'd suggest to increase the timeout for this test.

**Comment by hendrikmakait** [comment]
@crusaderky: There's already an issue for those long debug logs: https://github.com/dask/distributed/issues/8465

**Review by hendrikmakait — APPROVED** [review]
Thanks, @fjetter and @crusaderky! CI looks good now.

**Comment by crusaderky** [comment]
FYI the previous test 
```python
await comm.write({"op": "echo", "x": to_serialize(data)})
```
was not reproducing the issue, because it was sending a tiny msgpack blob + a 2 GiB buffer.
I changed it to
```python
await comm.write({"op": "echo", "x": data}))
```
which mocks the current behaviour of `c.submit` and `c.compute`.

- Read: https://github.com/dask/distributed/issues/8510

Regardless of the above "proper" fix suggested above, this PR is useful nonetheless when you have 2 GiB of bufferless data, e.g. caused by an object-string dataframe.

**Comment by jakirkham** [comment]
> 2. It reverts https://github.com/dask/distributed/pull/5854 since in my testing this threshold still causes issues. The only exception I see is a broken pipe here https://github.com/fjetter/distributed/blob/9721a1e83fb6ebb2c486d7226b290d6f7d6e7ec8/distributed/comm/tcp.py#L366 but I haven't tried chasing this down. I was running on python 3.10 so at the very least this version identifier is not sufficient / maybe the cpython bug is not fixed yet. maybe @jakirkham has some insight

It is certainly possible. This Python issue fixed in 3.11.0 sticks out to me: https://bugs.python.org/issue42854

To unpack that, [`SSL_read` uses an `int` size]( https://github.com/openssl/openssl/blob/d597b46f9bdb533761e36fcf1d96ce83f3f6f04d/ssl/ssl_lib.c#L2318C33-L2318C40 ) whereas [`SSL_read_ex` uses `size_t`]( https://github.com/openssl/openssl/blob/d597b46f9bdb533761e36fcf1d96ce83f3f6f04d/ssl/ssl_lib.c#L2340C36-L2340C46 ). The same is true of [`SSL_write`]( https://github.com/openssl/openssl/blob/d597b46f9bdb533761e36fcf1d96ce83f3f6f04d/ssl/ssl_lib.c#L2610 )/[`SSL_write_ex`]( https://github.com/openssl/openssl/blob/d597b46f9bdb533761e36fcf1d96ce83f3f6f04d/ssl/ssl_lib.c#L2632 ). All of these were added in OpenSSL 1.1.1: https://github.com/openssl/openssl/commit/4ee7d3f94590d3766c28eed03b969f338ddf96dc

Python 3.10 requires OpenSSL 1.1.1 with [PEP 644]( https://peps.python.org/pep-0644/ ) and makes use of the newer OpenSSL APIs allowing more throughput: https://github.com/python/cpython/pull/25468

However they had a bug (same one mentioned above) where they weren't consistently using `size_t` all the way through. Looks like they fixed that in Python 3.11: https://github.com/python/cpython/issues/87020

It looks like GH issue ( https://github.com/python/cpython/issues/87020 ) covers the full history of these changes. Note one use made the same observation about Python 3.10 Florian: https://github.com/python/cpython/issues/87020#issuecomment-1093897686

So maybe we can just bump the minimum Python version to 3.11

**Comment by fjetter** [comment]
Thank you @jakirkham for your detailed response.

> Maybe it is worth asking what Python version exactly (with patch version, which OS and from where) is being used? Also does it build with OpenSSL or a different SSL library? Also which SSL library version?

I think I'm having a hard time answering all of those questions. On my machine, I'm using conda and these are the relevant packages installed
```
python                    3.10.13         h2469fbe_1_cpython    conda-forge
python_abi                3.10                    4_cp310    conda-forge
openssl                   3.2.1                h0d3ecfb_0    conda-forge
pyopenssl                 23.3.0             pyhd8ed1ab_0    conda-forge
```

**Pull request merged**
