### PR TITLE
Remove some old deprecated code

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Review by sjperkins — COMMENTED** [review]
These deprecations seem straightforward to me. It looks like test cases fail due to leaked semaphores on Windows py3.8 and a leaked thread on MacOS py3.8. Do you think this is a matter for concern?

**Comment by mrocklin** [comment]
Definitely a concern.  Our CI system needs love.  I'm working on these issues separately in other PRs.  I don't think that they're related to these changes.

**Review by sjperkins — APPROVED** [review]

**Comment by mrocklin** [comment]
https://github.com/dask/distributed/pull/6146 for the Thread leak.  I'll probably leave the semaphore stuff for @fjetter (he's owned that feature historically)

**Comment by fjetter** [comment]
I think the leaked semaphores are not `distributed.Semaphore`s but multiprocessing Semaphores, aren't they?

**Comment by mrocklin** [comment]
See https://github.com/dask/distributed/runs/6048484364?check_suite_focus=true

The semaphore code in Dask comes up an increasing fraction of the time.  This part of the codebase has tests that I don't understand well enough to operate in.  As a result I'm not able to clean them up the way I am with the other parts of the codebase.

**Pull request merged**
