### PR TITLE
Use bokeh column for /system instead of custom css

### PR DESCRIPTION
**Pull request by jsignell**
Closes: #2710
image

Please weigh in if you think the columns should stacked in a single column rather than in a grid.

### CODE REVIEW

**Comment by mrocklin** [comment]
The dashboard is often used in an orientation where it takes up half of the screen.  In this setting a stacked column is nice.  But when it's run full-screen this can be a bit much.  About a year ago @dsludwig tried using CSS Grid to make things switch around based on aspect ratio I think.

**Comment by jsignell** [comment]
Ah, thanks for the context. If switching between column and grid based on screen size is still desirable then I don't think this can be solved from the bokeh side. Personally I think that always stacked or always grid will be less brittle.

**Comment by mrocklin** [comment]
Between the two, always stacked seems better to me for time series.  This way you can easily compare between the different plots.  Also we tend not to need too much precision in the y-axis in order to make decisions.

**Comment by jsignell** [comment]
It is surprising to me how much I prefer the bokeh stacking - which aligns the axes - to the flex stacking that we had before. 

image

**Comment by mrocklin** [comment]
> It is surprising to me how much I prefer the bokeh stacking - which aligns the axes - to the flex stacking that we had before.

I'm entirely happy to defer the question of using this solution or the other to you.

**Comment by jsignell** [comment]
Ok I think this is the better approach.

**Comment by jsignell** [comment]
This is ready to merge.

**Comment by mrocklin** [comment]
Thanks @jsignell !

**Pull request merged**
