### PR TITLE
Add linux CI for GitHub Actions

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Adding a GitHub Actions linux CI as a result of the Travis openssl debugging we've been doing in #3588 

Curious to see if I can reproduce the same issues on GitHub Actions with openssl `1.1.1e`.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
The errors here appear to be related to IPv6.

**Comment by mrocklin** [comment]
What is the status here?  Is this still live or should it be closed?

**Comment by jacobtomlinson** [comment]
I would be keen generally to try and unify CI on Windows/Linux/Mac and GitHub actions would be a good way to do it.

This PR may not be the best implementation of that. There is no reason why the same CI script can't be used an all operating systems.

If this is still desirable I'm happy to pick it up again.

**Comment by jacobtomlinson** [comment]
Closing in favour of #4218

**Pull request closed without merging**
