### PR TITLE
Add `ForwardOutput` worker plugin to forward `stdout` and `stderr` to client.

### LINKED ISSUE #7202: Plugin to pipe stdout/stderr to a log event
Folks sometimes want stdout and stderr sent to the client.  This is maybe pretty easy with ...

1. Teeing off sys.stdout/stderr as in https://stackoverflow.com/questions/616645/how-to-duplicate-sys-stdout-to-a-log-file
2. Dropping the results into the `print` log event
3. All withing a WorkerPlugin

Maybe something like this for stdout?

```python
class Tee(object):
    def __init__(self, worker):
        self.stdout = sys.stdout
        self.worker = worker
        sys.stdout = self
    def close(self):
        sys.stdout = self.stdout
    def write(self, data):
        self.worker.log_event("print", data)
        self.stdout.write(data)
    def flush(self):
        self.file.flush()

class StdOut(WorkerPlugin):
    def start(self, worker):
        self.tee = Tee(worker)

    def close(self):
        self.tee.close()
```

### PR DESCRIPTION
**Pull request by hendrikmakait**
This PR adds a `ForwardOutput` worker plugin that forwards all output from `stdout` and `stderr` on all workers to all clients using the internals implemented for `distributed.worker.print`. This plugin is not intended for chatty workloads and may put significant load on the scheduler.

Note that this plugin is related to #7276 but takes a slightly different route as it tries to avoid adding additional client methods that start to bloat the client interface. This comes at the cost of forwarding to **all** clients. This is the same behavior that we already have with `distributed.print()`. Unless somebody is particularly interested in using this plugin in a multi-client environment, I would leave this as is until we have added client plugins that allow adding functionality on the client without the need for dedicated methods. 

* Closes #7202

- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by hendrikmakait** [comment]
I just realized that this does _not_ capture any `logging.StreamHandler` that has been initialized before the plugin was installed.

**Comment by hendrikmakait** [comment]
> I just realized that this does _not_ capture any `logging.StreamHandler` that has been initialized before the plugin was installed.

Fixed by monkey-patching instead of replacing the stream objects.

**Comment by fjetter** [comment]
FWIW I don't really care about the logging stream handlers. We can forward logging on different channels. If it works like this, I'm OK with it though

**Review by fjetter — APPROVED** [review]

**Comment by hendrikmakait** [comment]
The issue I encountered with `logging.StreamHandlers` generalized to any object that stores a reference to objects `sys.std{out|err}` reference before we replace them, so this might occur in a few other places that follow the same pattern. It wasn't much effort to tweak since all the heavy-lifting of forwarding the logs had been implemented, it merely became a small exercise in monkey-patching instance methods in the right spot.

**Pull request merged**
